### ISSUE TITLE
Touch exports models to make sure their updated_at field is changed

### ISSUE THREAD

**Issue by edpaget** [zooniverse/Panoptes#1006]
Make sure the updated_at field is set the time of the most recent export when a new one is requested so the Front-End accurately indicates when the last request happened.

**Comment by camallen** [comment]
@marten feel like having a go at this one as well?

**Comment by marten** [comment]
Yeah, will do.

**Comment by camallen** [comment]
Thanks

**Comment by marten** [comment]
Can't find any models that seem to represent the actual exports themselves, @edpaget which models did you want the timestamps touched on?

**Comment by edpaget** [comment]
Medium models with "project_classifications_export" or "project_subjects_export" type.

**Comment by marten** [comment]
@edpaget Could you double-check after deployment whether #1015 fixed it?

**Comment by edpaget** [comment]
Will do

**Comment by camallen** [comment]
@edpaget - can you confirm this was fixed by #1015?

**Comment by edpaget** [comment]
Sorry just check its not changing as far as I can tell. I just made a subjects export and the line in the front end still says 3 days ago.

**Comment by marten** [comment]
That's weird, I expected https://github.com/zooniverse/Panoptes/blob/master/app/controllers/api/v1/projects_controller.rb#L65-L70 to touch the timestamp in both of the if/else branches. (And then the actual execution of the job later on also updates the medium object attributes).

**Comment by edpaget** [comment]
I think if the media is already created that if/else branch doesn't do anything since none of the attributes should change.

**Comment by marten** [comment]
Hmm, right. Will fix then.
