### ISSUE TITLE
Can't edit workflow description

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes#1017]
![screen shot 2015-06-25 at 10 49 22](https://cloud.githubusercontent.com/assets/6217406/8351810/e4091920-1b27-11e5-9d4e-421acf7841d7.png)

**Comment by camallen** [comment]
The prod api nodes dont' have the latest code, i need to optimize a migration then i'll get this deployed.

**Comment by edpaget** [comment]
@aliburchard @camallen is this setup now?

**Comment by camallen** [comment]
@edpaget deploy is happening now, @aliburchard can you try and add the workflow description again?

**Comment by aliburchard** [comment]
Working!
