### ISSUE TITLE
Error 500 hitting project_preferences route

### ISSUE THREAD

**Issue by chrissnyder** [zooniverse/Panoptes#1020]
Nor sure how important this is or not. Got a 500 hitting the project_preferences route when attempting to include project resources. I ran it through the client so it had proper headers and such.

Raw URL of the query: URL:https://panoptes.zooniverse.org/api/project_preferences?user_id=104&include=project

**Comment by edpaget** [comment]
There's something wrong with including the project and loading the translations. Can you work around for now by not doing the include and I'll try to get it fixed ASAP

**Comment by chrissnyder** [comment]
Yea, no worries, just wanted to put it on record.

**Comment by marten** [comment]
@chrissnyder Do you know if this is still an issue? I can't manage to reproduce it so far.

**Comment by marten** [comment]
Going by the [error in Honeybadger](https://app.honeybadger.io/projects/40595/faults/13753303#notice-summary) I'd say this was probably solved by 6323f50d

`
