### ISSUE TITLE
Editing live workflows - some edits should be allowed

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes#1021]
From #984

There are a few things on the workflow editor that should be allowed even if the project is live:

  - Help text (provided the workflow number still increases from A.a to A.b)
  - Associated subject sets
  - Retirement limit

Changing the help text alone won't disrupt a workflow enough to make the project unworkable. I suppose it's theoretically possible someone could add something verboten to the help text of an approved project, which is a different concern.

I can add new subjects to a subject set while a project is live, so unless I've missed a restriction on the format of additional subjects in an existing subject set, I think I should also be able to associate a new subject set, or deactivate an old one, while the workflow is live. If I discover that my project is about to run out of subjects I'd like to be able to upload and activate a different set even if the whole Zooniverse team is e.g. asleep.

Changing the retirement limit also won't affect the functioning of the project except to extend or truncate its lifetime. I could go either way on whether this should require approval or not.

**Comment by aliburchard** [comment]
I agree with being able to edit these three things.

Two thoughts:
1) I think it's good to be able to change associated subject sets in addition to adding subjects to an existing subject set (think of adding additional "seasons" in Snapshot Serengeti).
2) How does extending the retirement limit affect subjects that have already been retired when the limit was shorter? Will we un-retire subjects? Warn the researchers that they've already retired subjects with fewer votes?

**Comment by camallen** [comment]
@edpaget just throwing this out there, it looks like postgres 9.5 will allow us to update parts of json fields, https://wiki.postgresql.org/wiki/What's_new_in_PostgreSQL_9.5#jsonb_set_function. Pretty sure this is exactly what we want to use to update parts of a workflow in this issue but doesn't look like it'll be available any time soon.

**Comment by edpaget** [comment]
I was looking at this and it doesn't look like the API is actually rejecting any changes to Workflows once a project is 'live'. It's only preventing new workflows from beind created. I think I this is a front-end only issue.

**Comment by camallen** [comment]
@edpaget so what if a user manages to modify their workflow tasks via the api after we've approved a launch. We wouldn't be able to track this change and downgrade the project status and we may still be advertising this project on our sites to volunteers and thus perhaps wasting volunteer effort. 

I agree that if the user changes stuff via the API manually we should not be help accountable but if we're then advertising this to users and drawing effort from them, we should make sure that effort is not potentially wasted.

I still think we should put a check on this to allow a subset of workflow property changes and any others should downgrade the launch approved setting.

**Comment by edpaget** [comment]
Yup I'm working toward something that will allow us to selectively change workflows. I was just saying that right now the Front-End is the only thing preventing changes to workflows. We're not doing anything on the back-end.

**Comment by camallen** [comment]
Solid - sounds good.
