### ISSUE TITLE
Duplicate user zooniverse_id

### ISSUE THREAD

**Issue by parrish** [zooniverse/Panoptes#1027]
I found this when I was reviewing things from the Ouroboros side.

Some of the id's are from duplicate/deleted users, or from nearly identical records 

zooniverse_id | count
----- | -----
1025 | 2
115818 | 2
1231718 | 2
1248842 | 2
1276473 | 2
1315964 | 2
1360717 | 2
1391611 | 2
1426357 | 2
1456050 | 2
1460880 | 2
1518287 | 2
1598703 | 2
163171 | 2
1645120 | 2
1670968 | 2
1728590 | 2
1743021 | 2
1749392 | 2
1760425 | 2
1761957 | 2
1767800 | 2
1772665 | 2
1777646 | 2
1781498 | 2
1860940 | 2
1868986 | 2
1877364 | 2
1892085 | 2
1907911 | 2
1911330 | 2
1915361 | 2
1919491 | 2
1926316 | 2
1927350 | 2
1937794 | 2
1938898 | 2
1951678 | 2
1954550 | 2
1967214 | 2
222152 | 2
234900 | 2
316034 | 2
328994 | 2
37827 | 2
420431 | 2
50638 | 2
5309 | 2
59339 | 2
640813 | 2
642714 | 2
843140 | 2
849936 | 2
878282 | 2

**Comment by camallen** [comment]
Which db was this in? Panoptes prod?

**Comment by parrish** [comment]
Production

**Comment by camallen** [comment]
Thanks - these look like deleted users that we then re-imported, will clean them up.

**Comment by edpaget** [comment]
I have cleaned all these up.
