### ISSUE TITLE
Clean up factory girl association build / create chains

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#1031]
See #1030 `spec/factories/classifications.rb`

I guess this is really an argument where we should use factory_girl specifically mocking and stubbing vs persisting data to the DB. However if/when we do persist data we need to ensure that only the required factory associations we need for the test are built and we don't fire off costly persistence operations.

**Comment by marten** [comment]
Good idea but I think this needs to be boyscouted rather than something we'll do as a concrete issue.
