### ISSUE TITLE
Need to better weight user searching and match inside name

### ISSUE THREAD

**Issue by edpaget** [zooniverse/Panoptes#1034]
From zooniverse/Panoptes-Front-End#859, I think this is a three part thing:

+ [ ] Need to search using '%fragment%' to match inside a displayname (
   + this was the whole reason for doing the trigram index don't know why I didn't do it.
   + Why meg can't find Darren. 
+ [ ] Exact matches need to be matched first 
   + When I type in 'zookeeper' the user 'zookeeper' should be matched first
+ [ ] It should maybe search both display_names and logins

**Comment by mschwamb** [comment]
@edpaget  Is this live? - I could add my summer student's new username to a private project. The search couldn't find it a few minutes ago

**Comment by edpaget** [comment]
Yes this should be live. Were you able or unable to add the student?

**Comment by mschwamb** [comment]
Sorry  about that. I **couldn't** add my student. Nothing came up when we typed the new username she created.

**Comment by edpaget** [comment]
What's the the username?

**Comment by mschwamb** [comment]
don't remember but trying to zookeeper doesn't work either

**Comment by mschwamb** [comment]
Here's what I get when I try to add you @edpaget to a collection
![screen shot 2015-07-08 at 9 17 40 pm](https://cloud.githubusercontent.com/assets/753325/8571050/f3abbae2-25b6-11e5-99a1-8b48d6d5152a.png)

**Comment by edpaget** [comment]
Searching for both Meg Schwamb and Zookeeper work fine for me:

![screenshot from 2015-07-08 08 18 04](https://cloud.githubusercontent.com/assets/108177/8571063/0b283316-254a-11e5-91b1-e9530fb5872a.png)
![screenshot from 2015-07-08 08 18 40](https://cloud.githubusercontent.com/assets/108177/8571062/0b251852-254a-11e5-841b-f8c924c79692.png)

**Comment by mschwamb** [comment]
So what am I doing wrong/different I'm using Firefox but I don't imagine that would cause this
![screen shot 2015-07-08 at 9 20 19 pm](https://cloud.githubusercontent.com/assets/753325/8571096/395aaecc-25b7-11e5-97cc-fdd3b8162bca.png)

**Comment by edpaget** [comment]
edpaget and Ed Paget also both find me. 

You should be able to select the user from the search drop down that appears rather than just typing in the user name. We have to find the user ID before adding a collaborator so you can't type in the name then hit submit.

**Comment by mschwamb** [comment]
right - nothing is coming in the search

**Comment by camallen** [comment]
it's working for me in firefox, @mschwamb try clearing your cache perhaps.

**Comment by edpaget** [comment]
Are there any errors in your console (command + shift + k)? Or in the Network tab in the the developer tools (command  + shift + q)? Do you get different behaviour in Chrome or Safari? Any extensions installed in Firefox?

**Comment by mschwamb** [comment]
I did get a bunch of errors when I pulled up the console, but then the search came up successful when I did a refresh of the browser with the console open. That might have cleared the cache. 

Same issue happened on my student's computer but also might have had a cache issue. Thanks for the help. I'll see if it repeats when I clear the cache on my student's computer tomorrow.

**Comment by chrissnyder** [comment]
Sounds like it's worth us checking if we are doing cache busting correctly
as there looks to be a lot of issues that are being solved with just
clearing cache.

**Comment by edpaget** [comment]
I think it's an issue with the CF distribution getting new content out to an edge near Meg.

**Comment by chrissnyder** [comment]
Ah that's fair. Not much we can do in that case.

**Comment by CKrawczyk** [comment]
On a related note, the search bar does not find my account when I search for my login name (cmk24) but it does find my display name (Coleman Krawczyk).  Is this intended, or should both work?

![screen shot 2015-07-08 at 4 21 57 pm](https://cloud.githubusercontent.com/assets/6557526/8574225/83f197b8-258d-11e5-9675-02337e24dab4.png)

![screen shot 2015-07-08 at 4 22 12 pm](https://cloud.githubusercontent.com/assets/6557526/8574230/8a1b9918-258d-11e5-9327-32bfc76021c0.png)

**Comment by edpaget** [comment]
Both should work, but I think it might an issue with having a short name and the type of indexing we use.
