### ISSUE TITLE
Can create a collection with a name length of 0

### ISSUE THREAD

**Issue by chrissnyder** [zooniverse/Panoptes#1036]
Related to https://github.com/zooniverse/Panoptes-Front-End/issues/832

Given the only way we offer to reference collection is by name, seems to make sense to require a name. I can enforce it on the front-end, but would be great if the API threw an error too.

**Comment by edpaget** [comment]
I think the front end should just show the subject set id if there's not name. I can think of automated processes where it may not make sense to want to worry about naming a subject set.

**Comment by camallen** [comment]
@chrissnyder did you mean display_name? 

Collection display_names are uniq for owners so there will only be 1 blank collection display_name per owner. A this is used for filtering i think we should enforce a display_name on the collection.

**Comment by chrissnyder** [comment]
Yes, I mean display_name. I've enforced it in the front-end, because the only way users can add subjects to a collection from a project is by filtering by display_name. Ed's point about automated routines is well taken, so I don't know where that leaves us from an API perspective.

**Comment by edpaget** [comment]
Yeah I was actually thinking this was about Subject Sets, we should definitely enforce something for collections.
