### ISSUE TITLE
Project Cateogries

### ISSUE THREAD

**Issue by edpaget** [zooniverse/Panoptes#1042]
How do we want project categories to behave? Should there be a restricted list of categories they fit in? Some sort of free-form tag system? A hybrid?

I'd like to start adding search to the projects page, so @DarrenMcRoy @chrislintott @brian-c @aliburchard, @camallen and anyone else let me know your thoughts.

**Comment by DarrenMcRoy** [comment]
I'd like to have a series of tabs across the top of the projects page: ACTIVE / PAUSED / BETA / RETIRED. It would automatically display ACTIVE, of course, but you could tab over to the others.

Within those tabs, projects could then be tagged by subject matter (color-coded? just tagged?) and thus could be sorted by subject matter... and also hopefully by several other categories, as mentioned in https://github.com/zooniverse/Panoptes-Front-End/issues/701 (also discussed in https://github.com/zooniverse/Panoptes-Front-End/issues/680)

How does that sound?

**Comment by edpaget** [comment]
Cool do the Paused/Retired bits actually need to be on the main page or could they be somewhere else?

**Comment by edpaget** [comment]
Could paused just be shown with a flag on the project card?

**Comment by DarrenMcRoy** [comment]
I'd say let's have them there. Paused projects are popular for educational purposes, and retired projects are good for having clear sources for their completed data sets.

There's no fear of anyone getting confused if they literally have to click  "RETIRED" to see any retired projects. :-)

**Comment by DarrenMcRoy** [comment]
I would also be cool with paused being a flag.

**Comment by brian-c** [comment]
If the eventual goal is more community management, I think tags are the way to go. otherwise you're going to have people fighting over what categories exist, what happens to projects when their category is deleted, why can't my project be in two categories, etc.
