### ISSUE TITLE
Avoid duplicating subjects on upload

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes#1047]
@edpaget @camallen - any suggestions for this project builder? What's the best way to finish uploading the subject set without creating duplicates? We have no way of downloading a list of uploaded subjects. 

"When I upload new subject sets, will the system remove duplicate files? Due to the partial upload (my subject set uncropped_TC20150625 stopped at 600 files when I hit the 10,000 subject limit), I’m not sure which files were unable to upload. So once the limit is raised or lifted, I’ll add more but don’t want to put up duplicates if that will screw things up.

Assuming the subjects are uploaded in the order they appear on the manifest (?) I suppose we can scroll to the last subject viewable via the uploader and assume that everything before that subject in the manifest was uploaded correctly? @brian-c is there any way to report a csv of all subjects successfully uploaded (in addition to being able to view them individually)?

**Comment by camallen** [comment]
There is an export subject data now in the project builder.
![screen shot 2015-07-02 at 10 01 52](https://cloud.githubusercontent.com/assets/295329/8473417/7182566c-20a1-11e5-8b06-fe142661773f.png)

We don't check for duplicates when uploading subjects, looks like those 600 files will be in the system, ther rest that failed won't, https://github.com/zooniverse/Panoptes-Front-End/issues/316. I think Brian is working on a better system to check before attempting the upload but it's not there yet.

The subject exporter should give the information you need to figure out what's uploaded to find the set of data that needs to be imported without duplicates.
