### ISSUE TITLE
NULL zooniverse_id's

### ISSUE THREAD

**Issue by parrish** [zooniverse/Panoptes#1048]
Some new users are being created without zooniverse_id's.  It looks like it's failing on a short password validation, creating the user, then failing to reach the after_create callback to set the zooniverse id.

**Comment by camallen** [comment]
Are they being created from ourobors?

**Comment by parrish** [comment]
Nope

**Comment by parrish** [comment]
Also, it looks like the password validation I mentioned is bogus (it was just the validation failing when the user was fetched from the db and didn't have the attribute set)

**Comment by parrish** [comment]
Shouldn't this be fixed by #1049?

**Comment by edpaget** [comment]
I think you're right.

**Comment by parrish** [comment]
Just checked and there is one user without a zooniverse id.  Not sure if that happened before or after the PR was deployed though (it was about the same time).  I'll fix the user and see if it happens again
