### ISSUE TITLE
Should password reset request route return error?

### ISSUE THREAD

**Issue by chrissnyder** [zooniverse/Panoptes#1051]
- Related to https://github.com/zooniverse/Panoptes-Front-End/issues/905 and https://github.com/zooniverse/Panoptes-Front-End/issues/616
- Could the password reset request route never return an error? We can squelch errors on the front end, but returning errors in this case confirm if an email exists, which isn't great.

**Comment by camallen** [comment]
Yeah - we should probably do replicate devise does and create a inavalid user with the correct error messages.

**Comment by marten** [comment]
What kind of error messages would you like to return @camallen? I read it like the proposal was to never return an error, and always pretend everything was ok and a reset mail was sent?

I'm happy to take this btw.

(If you're really serious you'll still have timing attacks to worry about (not finding a record and thus not enqueuing a mail takes less time, which is detectable). I think that's probably overkill for our application though.)

**Comment by camallen** [comment]
Just replicate the behaviour as if it was a html form submission as per [here](https://github.com/plataformatec/devise/blob/master/app/controllers/devise/passwords_controller.rb#L12) and [here](https://github.com/plataformatec/devise/blob/1a0192201b317d3f1bac88f5c5b4926d527b1b39/lib/devise/models/recoverable.rb#L126).

**Comment by marten** [comment]
Will do. We would still need to turn on Devise paranoid mode to handle @chrissnyder second point?

**Comment by camallen** [comment]
@marten can you add in the paranoid mode as well?

**Comment by camallen** [comment]
@chrissnyder so you'll get 200's now for almost everything even when there is no associated email in the db (it just won't send reset instructions). It will return 422 if there is no supplied email address so if you just ensure that form can only be submitted via a valid email format string it should cover our bases.

**Comment by chrissnyder** [comment]
Looks perfect, thanks!
