### ISSUE TITLE
Missing links for /subject_sets/id

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/Panoptes#1054]
I've just tried to retrieve the members of a `subject_set` via `/subject_sets/id/set_member_subjects`. The [Apiary docs](http://docs.panoptes.apiary.io/#reference/subject-set/subjectset/retrieve-a-single-subject-set) reckon the link should exist, but after talking to @brian-c it looks like it doesn't...

The `subjects` link didn't work either.

**Comment by edpaget** [comment]
@rogerhutchings that's not how the API works at the moment. Use `/set_member_subjects?subject_set_id={id}`.

**Comment by edpaget** [comment]
Additionally the likes are contained in the response (I'm not seeing the part of the API docs that give those). So if you're using @brian-c's API client you'll be able to do (given a subject_set). `subjectSet.get 'set_member_subjects'`.

**Comment by rogerhutchings** [comment]
Weird, I thought the sample response on the "Retrieve a single SubjectSet" entry implied `set_member_subjects` was linked to `subject_set`, or am I reading it wrong...?

![screen shot 2015-07-01 at 16 59 59](https://cloud.githubusercontent.com/assets/2725841/8459092/b93ebcd2-2012-11e5-8fc3-ac4a52b463f7.png)

**Comment by rogerhutchings** [comment]
Ugh, think I read it wrong

**Comment by edpaget** [comment]
Yeah whenever we update to conform with the newest JSON API spec version, it'll look more like that. For now following links in the response is the best way to go.
