### ISSUE TITLE
Need a property for custom projects

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/Panoptes#1067]
I was talking to @camallen about this just now for AnnoTate - we need to be able to set a property on projects that determines whether a project has a custom front end or not. This should enable some extra features on Panoptes Front End, e.g. 

- disabling the classification interface and rerouting people if they try to access it
- setting up links back to the custom project url

etc.

**Comment by chrissnyder** [comment]
Isn't this just the redirect property?

**Comment by rogerhutchings** [comment]
...what redirect property?

**Comment by chrissnyder** [comment]
The one set on all zooniverse projects on Panoptes at the moment. Just a text key thats a URL.

Only settable by admins, and no, I don't think it's exposed on the front end, or in the docs anywhere.

**Comment by rogerhutchings** [comment]
Okay... is it solely for Panoptes Front End to indicate a redirect? And if so, wouldn't a more generic approach (e.g. a boolean) that enables additional features be a more flexible approach, as there's stuff like Talk that will need to behave slightly differently?

**Comment by camallen** [comment]
@chrissnyder yep you're right, I just tested the behaviour on an existing migrated project and it's what we want. https://www.zooniverse.org/#/projects/zooniverse/cell-slider/talk
