### ISSUE TITLE
Adding subject's public AWS link in the subject metadata dumps

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes#1070]
A future request  to have the subject's public AWS link in the subject metadata dumps. 

I use this feature alot with Planet Four. I download a subset of the images from Planet Four for summer students or myself to do analysis on or in this case download set to upload into a project builder. It would be nice to be able to do the same on Planet Four: Terrains or any other project  built with the project builder. Especially if you're not the person in the collaboration who created the images or uploaded them you can go to the project builder get your subject csv and wget what you need

**Comment by aliburchard** [comment]
I think this would be really useful for a lot of projects.

**Comment by edpaget** [comment]
Eh you can get this information really easily if you you're already using wget and the csv file. I don't see a reason to include it. 

```bash
wget -qO - --header="Accept: application/vnd.api+json; version=1" https://panoptes.zooniverse.org/api/subjects/{subject_id}
```

**Comment by edpaget** [comment]
A full example using [jshon](http://kmkeen.com/jshon/2011-08-12-11-11-46-590.html)

```bash
wget -qO - --header="Accept: application/vnd.api+json; version=1" https://panoptes.zooniverse.org/api/subjects/{subject_id} | \
jshon -e subjects -e 0 -e locations -e 0 -e "image/png" -u | \
wget -q0 img.png -q -i
```

**Comment by aliburchard** [comment]
I think that's actually a bit of an obstacle. As a researcher, I know how to download the csvs, and I can figure out how to script wget over a list of urls in the csv, but I have no idea how to do that if the url isn't provided in the csv. 

I think this should be in the Subject Export so that collaborators on a project can easily view and download subjects (because right now I can't even figure out how to url hack to view a given subject ID).

**Comment by mschwamb** [comment]
Currently I don't know how to get the url for one image from what you wrote. I think your code snippet is downloading a csv list of ids as pngs. 

I'll admit, I could eventually  figure it out from what you just wrote, but  I'm not sure all science teams will. Nor figure out how to get that information from the api documentation.  

The other reason, I think it should be added is if I have 30,000 subjects, do you really want me querying the api over the web 30,000 times for that info? I'd  only have to do it once, but it seems like it would be faster if the database query spat it out when making the csv file

**Comment by edpaget** [comment]
Yes I absolutely would prefer people use the API that's why we wrote it. It allows a much richer representation of our resources than a CSV does, and means we're spending time working on other problems not creating data dumps. 

If you substitute a subject id for {subject_id} in my snippet and the project has png images, it'll download the image for it.

**Comment by edpaget** [comment]
Also don't project creators already have all the images considering they had to upload them?

**Comment by aliburchard** [comment]
not necessarily. A project could be collaboratively created by several people across continents (as with wildebeest watch and whales), so chances are only one member of the project team has the images.

**Comment by mschwamb** [comment]
Depends who in the collaboration uploaded the images/created the subjects. For Planet Four: Terrains I'm the owner but someone else cut them up. And in all my projects that's pretty much been the case.  Takes me way less time to get the data off of AWS then to email collaborator have them convert from zooniverse id to their system and then send me the images or light curves. Actually for Planet Hunters the zooniverse versions are the only remaining versions of the data, what was uploaded and the deleted or on someone's computer not involved in the project anymore.

If you all want research teams to use the api for that info that's fine by me, not sure if @aliburchard agrees.  I'd recommend that the folks who made the help documents for the project builder then in the future also  create a document/brief tutorial with examples for typical things like your code snippet a research team might use. 

The api documentation I can read, but I can't easily and quickly parse. Spending more time and playing with your code snippet @edpaget  I figured out how to get what I need so I'll make a script that does that every time I upload the subjects csv into my local mysql table. Also I've never heard of jshon before, which looks very handful for future api queries.

**Comment by aliburchard** [comment]
@edpaget I think you're overestimating the coding prowess of most of our project builders. Zooniverse astrophysicists are not normal -- 90% of the people who have approached me about building projects have never even worked in the command line, so asking them to interact with API seems like a pretty big deal. Asking them to learn how to use wget or curl if they want to download subjects seems reasonable.

Our goal with this platform is to enable research teams who don't have big data or programming expertise to be able to run a successful citizen science project. That includes being able to work with the data coming out of the project. 

Yes, teams are going to have to develop some coding skills to pre-process or analyze the data from these projects, but I think we can make this most useful by figuring out 1) which things are hard for most (non-developer) researchers, 2) which of those things are easy-ish for us to do, 3) which of those things are hard for us to do, 4) *do* the things that are easy, and 5) *document/provide some guidance* on how to do the things that are hard.

If adding the image url to the subject data dump is a straightforward query that will take us not very much time but save (eventually hundreds of) individual research projects hours upon hours learning how to talk to the API (while they are just now learning how to write unix commands to create file manifests), then I think we should do this.  In contrast, if it's days of work, and doesn't generalize well, then I think we should write up very clear instructions for people to do these sorts of things.

**Comment by mschwamb** [comment]
Some of us like to be called astronomers :-). But in agreement with @aliburchard  in general planetary scientists, physicists, and astronomers/astrophysicsits tend to be more coding savy and wanting access to the raw data. 

I do want this url location information for when I test my weighting code, so extracting the url location for me is something I need right now. Running on all roughly 8000 subjects with the speed to Taiwan, querying the api for each subject individually in total will take 4.4 hours to complete with the code I wrote. Now, I only need to do this once in a long while, but if this was in the csv. If it doesn't slow down the creation of the download, it would probably be faster than what I'm doing.

**Comment by chrislintott** [comment]
@edpaget, I agree with @aliburchard here. Including the URL in the CSV dump is the easiest thing to do for our researchers, so we should do that.
