### ISSUE TITLE
Include subjects in the Kafka classification JSONs

### ISSUE THREAD

**Issue by marten** [zooniverse/Panoptes#1072]
For the SWAP integration with Kafka the worker needs to have access to the metadata of the subjects of the classification. It needs that to check if a subject is a training subject. To avoid dealing with caching  and making API calls to fetch the metadata, it's easiest if we post the subject JSON along with the classification straight into Kafka.

**Comment by camallen** [comment]
I'm wondering if we should package the known state of the project / workflows / subject into the classification to avoid merging and workflow versioning lookups here. 

@ggdhines what do you currently lookup for the aggregation engine / is there any other information that you would need here?

**Comment by ggdhines** [comment]
not sure that I follow completely but the only metadata I use is subject metadata which gets inserted into the aggregation results (as requested by the scientists). Metadata about whether  a subject is active might make the process more efficient.

**Comment by camallen** [comment]
I'm wondering what information (if any) you need to make the aggregation engine work, i.e. do you lookup the subject data, the workflow information as it was at the time of classificaiton, etc. So instead of having a disparate set of data to make decisions about classifications, we may be able to package it up into a self contained data unit that can be fed into disparate services.

That said if you just need the classification data we're probably just better off with different data topics (streams) in kafka.

**Comment by ggdhines** [comment]
I start with the current workflow version which I use to then get the current workflow structure. I then use the version to filter the classifications and the structure to parse the JSON annotations for each classifications

**Comment by camallen** [comment]
Do you lookup any subject data?

**Comment by ggdhines** [comment]
I would like to look up image size - to help remove markings with errors in them

**Comment by camallen** [comment]
@marten i think this is a good idea generally. We may end up with slightly different data representation requirements that i'd prefer to have published in different topics but for the meantime i think both your and Greg's use cases can be solved by packing a classification event with it's required processing data.

**Comment by marten** [comment]
And it fits with the Restpack `can_include` stuff, it's just that with Kafka the client can't specify per request what it needs included.
