### ISSUE TITLE
Compressing the csv data dumps for subjects and classifications

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes#1077]
Future request - I'm noticing it's already starting to take minutes for the classification database for P4T to download. Also one of my collaborators mentioned that he uses safari and it automatically tries to load the csv when he clicks the link from his email since it's uncompressed  - eventually it might be better if these were compressed

**Comment by vrooje** [comment]
+1

Would take up considerably less space on Amazon too.

**Comment by aliburchard** [comment]
+1

**Comment by mschwamb** [comment]
@camallen this says this is closed, but I keep getting data dumps unzipped. Did this get reverted somewhere? I'm not on this repo, so I can't reopen.

**Comment by marten** [comment]
That's weird, I'm seeing the same thing.

**Comment by marten** [comment]
They're gzipped on S3 though, but when you download, you download the unzipped data. Must be some feature of S3 that we'll want to disable to save on bandwidth.

**Comment by mschwamb** [comment]
Might want to trying tar.gz - that's how the Planet Four data dumps come, and those to download as compress files. I believe @parrish set up that for us.

**Comment by astopy** [comment]
This is probably related to #1694.

**Comment by marten** [comment]
I've had a look, and the data flying over the internet is zipped, but after that your browser unzips it for you (on the fly, before writing to disk). This is because of the way we set up the headers. Is that acceptable or would you prefer to always receive a tar.gz which you'd have to unpack manually?

**Comment by mschwamb** [comment]
I might not be representative of your target audience, but I personally like it compressed. I presume that would be faster in terms of download speed?

**Comment by marten** [comment]
No, you're already downloading compressed data, it's just that right now your browser unzips it before writing to your downloads folder.

**Comment by mschwamb** [comment]
if it's the same then fine by me, it just looked uncompressed. thanks for looking into it @marten
