### ISSUE TITLE
subjects seen more than once

### ISSUE THREAD

**Issue by ggdhines** [zooniverse/Panoptes#1086]
@camallen can you double check that classifications for subjects that a user can has already seen will contain a flag?

**Comment by camallen** [comment]
@ggdhines can you check that avatar project on staging we did the other day. You should see extra annotations in there for already seen (`seen_before` i think).

**Comment by ggdhines** [comment]
I'm not seeing any such flag.

**Comment by camallen** [comment]
Seems the front end isn't submitting the required metadata, https://github.com/zooniverse/Panoptes-Front-End/issues/368

**Comment by camallen** [comment]
@ggdhines close this if you don't need it as per the front-end discussion.

**Comment by camallen** [comment]
Linked to https://github.com/zooniverse/Panoptes-Front-End/issues/368#issuecomment-125189891

We can update the metadata flags on any user classifications that have already seen that subject.
