### ISSUE TITLE
60 logged in volunteers since July 5 saw the same subject, but it is supposed to be retired after 20 classifications

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes#1087]
We sent out a newsletter to the Planet Four volunteer list about Terrains and I noticed that pretty much Talk was empty. There were very few new posts.  I originally though this was a problem with Talk posting again. 

Then I looked at the subjects, just yesterday alone 61 people all except 1 who wasn't logged in, saw the same subject and are posting on it. It's supposed to retire at 20 and all the correct live settings as far as I can tell are active and @camallen  uploaded our dataset so I don't think it's a data upload issue. We did have the subject set being used while new subjects were being added but I don't presume that would cause this issue. 

I don't think I should publish the csv file here - check out subject 483978 and 483873

I'm also confused even if these subjects are not retiring and why if I have 8000 subjects in the subject set that  these show so frequently even if it wasn't retiring? Is this a bug on the backend?

**Comment by mschwamb** [comment]
So from the csv export I just got, it says for both of these subjects that "retired is false under the subject metadata - I don't know how to get the api to return my back the status of the subject looking into the documentation now, but it looks like these subjects are very much alive and not retiring

**Comment by mschwamb** [comment]
Sorry posting this again in the wrong ticket -  Looks like 484085 has over 200 classifications since launch. Other numbers I'm quoting are just from yesterday's classifications

**Comment by mschwamb** [comment]
@aliburchard and @vrooje are your projects exhibiting the same behavior?

**Comment by mschwamb** [comment]
I've finally got some scripts to process the csv classification file - In case there was strangeness from launch I'm calculating these numbers as of July 1st. forward 

122 subjects with more than 25 classifications since July 1st - None of these subjects appear to be retired according to the classification csv subject metadata - Retirement rate was set at 20. 

subject id number of classifications
483676	58
483683	81
483687	62
483690	104
483695	62
483699	35
483700	43
483704	136
483707	39
483713	27
483717	105
483722	35
483731	44
483736	63
483740	26
483741	44
483743	42
483747	30
483749	26
483751	69
483752	54
483754	159
483762	43
483770	33
483771	189
483776	180
483779	31
483784	53
483792	84
483793	177
483796	72
483799	59
483800	39
483804	60
483805	81
483807	76
483809	56
483813	32
483814	95
483815	88
483816	27
483822	63
483827	42
483832	50
483836	302
483840	67
483846	37
483852	79
483853	43
483858	199
483868	49
483870	110
483873	277
483880	80
483889	73
483893	131
483894	62
483897	35
483909	88
483913	41
483917	30
483920	96
483922	112
483941	61
483943	271
483945	26
483947	57
483949	27
483950	42
483954	107
483964	38
483968	86
483969	90
483976	58
483978	257
483981	170
483982	28
483984	112
483986	236
483987	68
483989	29
483991	104
483992	42
483997	89
484003	31
484005	36
484006	89
484010	54
484015	207
484016	50
484023	197
484033	48
484047	147
484049	73
484052	67
484057	27
484063	56
484064	76
484066	221
484068	67
484080	27
484082	209
484085	144
484086	46
484094	44
484095	143
484099	113
484101	37
484102	97
484105	48
484107	67
484138	50
484140	63
484142	65
484145	35
484147	54
484149	27
484154	28
484156	202
484162	63
484165	82
484169	32

2547 subjects have at least 1 classification since July 1st

**Comment by camallen** [comment]
@mschwamb - i'm looking into it, thanks for the details.

**Comment by mschwamb** [comment]
Cool - thanks @camallen - took a quick look at a few individual cases - most people are logged in only a few non-logged in entries contributing to these

**Comment by camallen** [comment]
@mschwamb - yep this was a bug in our event ordering. I've got a fix via #1088 but I want to run it by the team first. We'll replay your classifications events to update the counts and retire those subjects out of the system.

**Comment by aliburchard** [comment]
@mschwamb haven't had a chance to check this in the WW data, but sounds like it's platform-wide. Good catch!

**Comment by mschwamb** [comment]
Thanks @camallen for working on this. Was this also exacerbated by #1033 since our subjects were uploaded in order? When this fix is in, should the system be stressed a bit again to make sure this is working correctly. I can see if there's another excuse to have a newsletter that could direct people to Terrains.
