### ISSUE TITLE
Project Pages should handle languages properly

### ISSUE THREAD

**Issue by edpaget** [zooniverse/Panoptes#1091]
Currently they're locked to just looking at the 'en' pages since the project builder similarly locks the project language. It should use the same selection strategy as the workflow_content and project_content models.

**Comment by camallen** [comment]
@edpaget I assume that this means reverting [this](https://github.com/zooniverse/Panoptes/commit/bcd7ce317da52b65e0ace08254405a0f13dcfa2c) and looking to add in functionality from [translatable](https://github.com/zooniverse/Panoptes/blob/c34f86525678397420bf886ddf80fcfeff58ac95/app/models/concerns/translatable.rb)?

**Comment by edpaget** [comment]
Nothing translatable does will help with this unfortunately. We need to figure out how to order pages by language preference and then only select the most complete set of pages that matches the user's language preference.

**Comment by eatyourgreens** [comment]
Tutorials and Field Guides have a language flag, hardcoded to `en` too. Does this also apply to those resources?

I've started a list of localised Panoptes resources in zooniverse/pandora#6, for the translations UI.

**Comment by camallen** [comment]
Looks like field guides will return all languages (though we can setup filtering) and tutorials are hard coded to en at the moment, https://github.com/zooniverse/Panoptes/search?utf8=%E2%9C%93&q=params%5B%3Alanguage%5D+%3D+%22en%22&type=
