### ISSUE TITLE
Documentation update needed: user.display_name is now user.login

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes#1094]
I've not used my API code recently and am trying to get it running again. The login part of my script breaks, giving me a 401 ```You need to sign in or sign up before continuing.```. 
I send a valid username and password and get what looks like a valid CSRF token in reply. But when I try to use the token I get the above message. Thoughts?

Also, I'm still using this as the host API:
https://panoptes-staging.zooniverse.org/api/
What is the host for the live Panoptes?

**Comment by mkosmala** [comment]
And I'm trying to do sign-in here:
https://panoptes-staging.zooniverse.org/users/sign_in

**Comment by chrissnyder** [comment]
Pretty sure this is because you are likely sending a `user.display_name` rather than a `user.login` field. That's the only change from the login side that I can think that was made recently.

**Comment by mkosmala** [comment]
Thanks, @chrissnyder! That's exactly it. Docs need updating.

**Comment by mkosmala** [comment]
Oh, and where do I access the live Panoptes? Want to create a project on it...

**Comment by chrissnyder** [comment]
That's one for @edpaget or @camallen. Not sure of our strategy there.

**Comment by edpaget** [comment]
It's at panoptes.zooniverse.org. It may move to zooniverse.org/api in the near future.

**Comment by mkosmala** [comment]
Thanks, @edpaget. Now I'm getting a new error: a 422 with no message. This happens in the following stage of authentication. So I successfully send a username and password and get a token string. Then I successfully use that string to get a devise session. But when I try to get a bearer token using the devise session at ```panoptes.zooniverse.org/oauth/token```, I get the 422 error. 

The same exact code runs fine on panoptes-staging.zooniverse.org.

Thoughts?

**Comment by edpaget** [comment]
They don't share OAuth applications, so I'll need to create new OAuth application for you on the backend. I'll send you details via email.

**Comment by mkosmala** [comment]
@edpaget Still having trouble logging in to Panoptes. Sent email reply to yours with the application ID. @camallen might have thoughts, too?

**Comment by camallen** [comment]
@mkosmala I don't think we've documented the auth workflow yet, feel free to provide a PR if you want.
