### ISSUE TITLE
Allow API Clients to get tokens via ClientCredentials workflow

### ISSUE THREAD

**Issue by edpaget** [zooniverse/Panoptes#1095]
See [Doorkeeper Docs](https://github.com/doorkeeper-gem/doorkeeper/wiki/Client-Credentials-flow).

**Comment by edpaget** [comment]
The thing with this is that is should issue a token to act as the OAuth Application's owning user instead of just a generic token, which wouldn't be able to do anything.

**Comment by camallen** [comment]
@edpaget what's the use case for this auth worklow?

**Comment by marten** [comment]
I think this is something I might need for the retirement agent. That will probably act on multiple projects, and should (ideally) have a limited set of authorizations (possibly just the API call to retire a subject).

**Comment by edpaget** [comment]
@camallen anyone doing the same thing as Margret. We're already telling them to use a workflow that we're only supposed to support for the Front-End client anyway.

**Comment by camallen** [comment]
Wouldn't the [resource owner credentials workflow](https://github.com/doorkeeper-gem/doorkeeper/wiki/Using-Resource-Owner-Password-Credentials-flow) be a better fit for this?

**Comment by edpaget** [comment]
I don't think so. You wouldn't necessarily want to store your master credentials everywhere. It would be useful for testing, but Client Credentials are definitley a better fit for people building services that interact with the API.
