### ISSUE TITLE
Manage OAuth applications through the API

### ISSUE THREAD

**Issue by edpaget** [zooniverse/Panoptes#1096]
I don't think there's any reason, why the OAuth tokens couldn't be managed through the API instead of though the Doorkeeper endpoints.

**Comment by edpaget** [comment]
What I'm going to do with this is to associate OAuth application ownership with projects, so project Owners/Collaborators will be able to generate OAuth apps for their projects and then use those credentials to only interact the project they're scoped too.

**Comment by zwolf** [comment]
This is implemented.
