### ISSUE TITLE
Retiring subjects via API

### ISSUE THREAD

**Issue by marten** [zooniverse/Panoptes#1098]
I'm figuring out how to retire subjects by API call. The logical place for that seems to be using the `SetMemberSubjectController` (as per @edpaget's comments in #519). 

But to use that API (and for things like `SubjectWorkflowCount#retire!`), the API caller needs the id of the join model (why does a join table even have it's own ids?), which has been hidden since #519.

How do we see this fitting in the API?

/cc @camallen @edpaget

**Comment by camallen** [comment]
@marten the `set_member_subjects (sms)` controller already has a route to retire subjects for a workflow (though it's not documented). Checkout `rake routes` and look for the `retired_workflows` and `update_links`. This will mark the sms as retired but not remove it from any queues, etc. We'd need to override the `update_links` controller action (see other controllers) to yield a block that does the required actions.

Not sure i follow on the id of the join model, i assume you're talking about the `SetMemberSubject` which is a resource in it's own right (hence the Id) and is not realy hidden but obfuscated from subject calls.

**Comment by marten** [comment]
Yes, that would be technically possible, but it's a very low-level API and it would mean retirement agents would have to have a lot of knowledge about how subjects are divided into sets.

This is because we don't retire an sms as a result of a classification, at least not directly. After a classification, we retire the subject for that workflow, for all the sets the subject is part of that are referenced by the workflow. (taken care of in [ClassificationCountWorker](https://github.com/zooniverse/Panoptes/blob/master/app/workers/classification_count_worker.rb#L6))

Basically the issue is that because a `Subject` has a many-to-many relation with `SubjectSet`, and a workflow has a many-to-many relation with `SubjectSet`, a workflow can have multiple references to the same subject. The current API exposes the underlying database, but in this case that doesn't fit well with the tell don't ask principle. Personally I think it would be cleaner to make an API call to Panoptes telling it "this subject is done for this workflow, make it retired somehow" which fits less well in the REST/resources structure we have now, and therefore I can't find a "good" place to put it in the API.

Let me know if this is clear, we could do a quick hangout if not.

**Comment by camallen** [comment]
Yeah that makes sense. So how about a retire action on the `workflows` controller, perhaps `/api/worfklows/:id/retire_subject` with the params `subject_id: X` and it will figure out the SMS id's and do the retirement across subject_sets for that worklow. Is this what you want?

**Comment by marten** [comment]
Yeah. I'll add that then.
