### ISSUE TITLE
Error on entering 'science case': "Error: Validation failed: Url key has already been taken"

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes#1100]
I have a project (#347) on the deployed Panoptes. When I go to the 'science case' tab in the Project Builder, I get the error ```Error: Validation failed: Url key has already been taken```. The same error also shows up for 'results', 'FAQ', and 'education' pages.

**Comment by mkosmala** [comment]
Okay, really weird. I'm having the same trouble on staging in projects where I've already got content for these pages. When I try to view the project as if I'm a user, there is no content on any of these pages.

**Comment by mkosmala** [comment]
Update: it looks like I only have this problem for the projects I created via the API today. @camallen @edpaget: Is this due to the authentication fiddling we did? If so, can it be fixed? I need to work on these projects ASAP.

**Comment by edpaget** [comment]
No it's due to me giving up on figuring out translations for those pages (for now) and hard-coding to the project builder. Can you change your script to [create projects](https://github.com/mkosmala/PanoptesScripts/blob/master/panoptesPythonAPI.py#L337) with a 'primary_language' of 'en', and I'll update your existing projects to be the same. 

I'll have a better fix for this soon, but since we don't have any translation tools I punted supporting them until later.

**Comment by edpaget** [comment]
Everything should be updated on the backend. This is the issue for fixing the problem: https://github.com/zooniverse/Panoptes/issues/1091

**Comment by mkosmala** [comment]
@edpaget I was creating projects with 'primary_language' of 'en-us'. Should I switch that to be 'en' instead?

**Comment by edpaget** [comment]
Yes until that #1091 issue is fixed.

**Comment by mkosmala** [comment]
Hey @edpaget, the fix seems to have forced me to have the tabs. I don't actually want to have tabs for 'result' and 'education' right now. 

Also, and I don't know if this is related or not (seems likely), the link I added from the project builder to have a custom tab doesn't show up -- maybe because I am already using all the pre-defined tabs?

**Comment by edpaget** [comment]
Can you link me to your Project?

**Comment by mkosmala** [comment]
Editing (I made you a collaborator temporarily in case it's helpful):
https://www.zooniverse.org/#/lab/347

Viewing:
https://www.zooniverse.org/#/projects/kosmala/season-spotter-questions

**Comment by edpaget** [comment]
I don't see any URL links added to your project. I put in a fix to hide tabs when they don't have any content.

**Comment by mkosmala** [comment]
@edpaget Indeed. But there was yesterday. Hrm. I'll keep a lookout for any other disappearing links. Seems to work now fine.

**Comment by mkosmala** [comment]
@edpaget Weird! It happened again. I made it its own issue: https://github.com/zooniverse/Panoptes-Front-End/issues/1088
