### ISSUE TITLE
Installation troubles on OSX

### ISSUE THREAD

**Issue by chrissnyder** [zooniverse/Panoptes#1101]
Attempting a fresh install of Panoptes on OSX, running into problems getting setup

Steps: 

1. Did install steps 1-3
2. Installed Docker 1.6.2, as per Ed's instructions.
3. Ran `docker-compose up` and it seems to work fine.
4. Attempted to run `frake db:create db:migrate` and consistently get variations of the following: `Cannot start container a96dcba4bbce24acebd81b421ecbc5df37981077fb66a3498dd9e95976d5f4d7: [8] System error: exec: "\"rake\"": executable file not found in $PATH`

Haven't had any luck troubleshoot. Anyone run into something similar?

**Comment by chrissnyder** [comment]
Couple more things I learned:

- I hadn't properly cleared out my first install of Docker 1.7.0. After I nuked everything and reinstalled 1.6.2, I was able to create the db.
- Still wasn't able to run `frails runner db/fig_dev_seed_data/fig_dev_seed_data.rb`. However I could run the command directly in the docker container, which got me up and running. Not sure what caused frails to break.

Up and running now though, so that's something.

**Comment by camallen** [comment]
@chrissnyder did you explicitly enable frake via https://github.com/edpaget/fig_rake#monkey-patching?
> You still need to explicity enable Fig Rake after including it in Rake or Rails by setting the environment variable FIG_RAKE.

**Comment by edpaget** [comment]
He shouldn't need to since using `frails` or `frake` will run using docker-compose. I've opened an issue https://github.com/edpaget/fig_rake/issues/1 to add bundle exec to the fig_rake commands.

**Comment by camallen** [comment]
closing as it seems more related to fig_rake gem, re-open if needed.
