### ISSUE TITLE
Classification data output: drawing tool indexing

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes#1118]
In the classification data output, the drawing tools are numerically indexed if we have more than one of the same type per task. But I have no way of knowing which tool (for which I provided only a name) goes with which index. I *assume* they're indexed in the same order they appear in my project, but I don't know for certain. 

I am happy to have numerical indexes, but I need a lookup table to be sure I am matching the right classification to the right tool. Otherwise, the classification data will need to provide the tool name. 

@ggdhines This will apply to your aggregated data, too, I'm sure.

**Comment by mschwamb** [comment]
I think eventually #1045 might we what you want which should index with the task id

**Comment by aliburchard** [comment]
@mkosmala my drawing tools are labeled in the raw classification output. There is a numerical index (e.g. "tool": 2) but also a label (e.g. "tool_label":"To the left") reported. The "tool_label" appears after the list of values and details for each tool.

**Comment by mkosmala** [comment]
@aliburchard Hmm. I don't have a "tool_label". But my classifications are from a few weeks ago. 

...pulling a new set of classifications...

Aha! You're right. All set then.
