### ISSUE TITLE
subject upload limit

### ISSUE THREAD

**Issue by AdrianEvans** [zooniverse/Panoptes#1124]
I have only 2828 subject uploaded but I get the upload limit notification when trying to upload more - this is likely cause due to me having previously uploaded and then deleted subject sets - so I may have 10000 uploads in total rather than 10000 active subjects.

Following that, if I deleted all my current subjects then I wouldn't be able to add any more and my project would have none. This leads me to think that it isn't the intention to have the limit be on the total number of subjects uploaded but rather on the number of currently active subjects.

**Comment by camallen** [comment]
Linked to https://github.com/zooniverse/Panoptes/issues/1037. 

This is a know issue that we understand will cause problems. What was the reasoning as to why you were just uploading and removing subjects instead of reusing them? Just trying to figure out user behaviour, not an accusation. 

@aliburchard can you PM @AdrianEvans to figure out a new custom limit.

**Comment by AdrianEvans** [comment]
I didn't realise the limit - I see it is in the policy document but adding a comment on the subject upload page would be good. 

The reason was that I'd left 6000 uploading over night and then my computer went to sleep and as the site doesn't check for duplicates, and it isn't a very simple process to manually do that check I decided to change my upload strategy and start again. This time being very aware of what was and wasn't uploaded. Essentially it's because I'm an idiot.

**Comment by camallen** [comment]
@AdrianEvans - thanks for the feedback. I agree that providing guidance and maybe hard limits on the uploader tool would help here. 

Some liks, please comment on the open ticket, as your the person we want to hear from about this. 
https://github.com/zooniverse/Panoptes-Front-End/issues/461
https://github.com/zooniverse/Panoptes-Front-End/issues/861
https://github.com/zooniverse/Panoptes-Front-End/issues/316

You can use the subject csv exporter (on your builder project page down the bottom) to get a list of subjects that exist. 

Also see the discussion started here (again thoughts appreciated), #1120

I'm going to close this ticket as we've got this discussion already started in a few places, reopen if needed.
