### ISSUE TITLE
Login errors

### ISSUE THREAD

**Issue by trouille** [zooniverse/Panoptes#1126]
We have some volunteers (new volunteers) that have the same issue occurring.
They create an account and can't log in with that account information. So they figure something is wrong with their password and change the password, but still can not log in.

Two of the people @JulieAnnKU spoke with gave her their usernames:
micbailey
julipaz1331

**Comment by edpaget** [comment]
Logging into the main zooniverse.org website?

**Comment by JulieAnnKU** [comment]
To zooniverse.org and any of the projects, so logging in in general.

On Wed, Jul 15, 2015 at 2:13 PM, Edward Paget <notifications@github.com>
wrote:

> Logging into the main zooniverse.org website?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zooniverse/Panoptes/issues/1126#issuecomment-121718227>
> .
>



-- 
Julie A Feldt
Citizen Science Education Coordinator
Adler Planetarium
1300 S Lake Shore Dr
Chicago, IL 60605
Office: (312) 542-2200

**Comment by edpaget** [comment]
As far as I can tell we don't have any users registered with those names. When did they try to to sign up? And di they do it through zooniverse.org? Or one of the project sites?

**Comment by JulieAnnKU** [comment]
So julipaz1331 signed up on zooniverse.org yesterday around 10am and it
said that their was already a username and email address (I was present for
that one). I asked her to try to create the account with the same user name
and then when it said that was taken I asked her to do it with a different
user name and it said that her email was already in use by another account.
But we could not get her logged in with the user name it said already
existed. She had never heard of Zooniverse before yesterday so she didn't
have an account before then, plus we tried to reset the password and even
after resetting her password it still didn't work, there was "Error 0"
under the login each time we tried.

On Wed, Jul 15, 2015 at 2:25 PM, Edward Paget <notifications@github.com>
wrote:

> As far as I can tell we don't have any users registered with those names.
> When did they try to to sign up? And di they do it through zooniverse.org?
> Or one of the project sites?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zooniverse/Panoptes/issues/1126#issuecomment-121720565>
> .
>



-- 
Julie A Feldt
Citizen Science Education Coordinator
Adler Planetarium
1300 S Lake Shore Dr
Chicago, IL 60605
Office: (312) 542-2200

**Comment by edpaget** [comment]
Can you send me the email, use `ed@zooniverse.org` so it doesn't show up in the public issues.

**Comment by JulieAnnKU** [comment]
I did not get the email addresses :(

On Wed, Jul 15, 2015 at 2:40 PM, Edward Paget <notifications@github.com>
wrote:

> Can you send me the email, use ed@zooniverse.org so it doesn't show up in
> the public issues.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zooniverse/Panoptes/issues/1126#issuecomment-121723549>
> .
>



-- 
Julie A Feldt
Citizen Science Education Coordinator
Adler Planetarium
1300 S Lake Shore Dr
Chicago, IL 60605
Office: (312) 542-2200

**Comment by edpaget** [comment]
Really sorry then. I don't think there's anything we can do. It sounds like they may have signed for an older Zooniverse project without knowing it was one (easy to do back in the day). There are a few things they can try:

* Using the [Password Reset](https://www.zooniverse.org/#/reset-password) with their emails. They should get a link to reset their password if we have an account with their email address( which it sounds like we do). Once they've reset their passwords, they can login without knowing their user name by using their email in the User name field of the [sign in form](https://www.zooniverse.org/#/account/sign-in).
* Register for a new account by using a '+' in their email address. Most email providers will you do something like `ed+github@zoonivese.org` and have the email delivered to `ed@zooniverse.org`. 
* Register with a different email address. They're easy to signup for.
