### ISSUE TITLE
Non-logged in volunteer see same subject 20 minutes after first seeing it

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes#1127]
Not sure if this is addressed with the fix for classification counts to actually retire subjects

 thought although it's not explicitly tracking the same way as logged in volunteers that this shouldn't happen in that time span. I've got 8,000 subjects live there should be plenty to classify - is this possible  bug in the backend?

On Terrains - 

not-logged-in-070e1feaaa5e7c8fd4d31c8e074d216ba4d6fb7e saw subject  484218 at 2015-07-04 11:07:56 and then again at 2015-07-04 11:26:23  This session has done 100 classifications up to July 8th. Also there was no flag in the database that this was a duplicate (perhaps that isn't possible with the way non-logged in users are tracked). 

To be this seems a little short to be seeing a duplicate - this was before a P4 newsletter

**Comment by mschwamb** [comment]
possibly related to #1128 - will try to look for more recent examples

**Comment by edpaget** [comment]
It could totally happen within that time span. I don't think this is something we can really fix since non-logged in users aren't tracked what so ever.

**Comment by mschwamb** [comment]
I thought everyone got 100 subject queues even non-logged in?

**Comment by edpaget** [comment]
Nope there is a single 100 subject queues that all non-logged in users pull from. It's shuffled after each selection to make it as random as possible, but a user could definitely get reserved a subject from it.

**Comment by mschwamb** [comment]
and they don't ever see the already classified tag? or they do and then next image is back to being a new image?

**Comment by edpaget** [comment]
They should unless they close their browser. Some state is tracked by the front-end.
