### ISSUE TITLE
repeat classifications for logged-in users when still other data to clasify 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes#1128]
I noticed this in the Terrains classifications checking on duplicates and seeing what filtering if any I need to do to the classifications

Brainiak97 saw subject 483700 at 2015-06-29 19:59:10 and then submits again at 2015-06-29 19:59:59
The volunteer does roughly 8 classifications in between and classifies the image again

**Comment by mschwamb** [comment]
possibly related to #1127  - will try to look for more recent examples

**Comment by mschwamb** [comment]
notice same thing for nathalieg69 on subject 484066 2015-07-01 03:55:37 and 2015-07-01 04:05:37 - thought I'd bring it up if this isn't directly related to the subject retirement issue from last week - still looking for more recent examples

**Comment by mschwamb** [comment]
Yeah got a very recent one subject 487143 2015-07-12 23:43:49 and 2015-07-12 23:45:07 - this is after is live for correctly accounting for the subjects - now subject has seen almost 50% of the live subjects if that matters

**Comment by mschwamb** [comment]
@aliburchard and @vrooje you getting the same behavior on your projects

**Comment by aliburchard** [comment]
@mschwamb I haven't dived too deep into raw classifications because I can't easily parse the file in R, but I do know that whales has been having the same subject retirement issues (and need to check to make sure they're fixed now...).

**Comment by vrooje** [comment]
I haven't found any rapid-succession duplicates yet, but I've found plenty of duplicates and I'll report more details in #1069.

**Comment by vrooje** [comment]
scratch that, looking at the whole file I do have some of those.

**Comment by mschwamb** [comment]
closing this since it's open #1069
