### ISSUE TITLE
enable duplication of workflow

### ISSUE THREAD

**Issue by AdrianEvans** [zooniverse/Panoptes#1129]
Just an idea this morning for an enhancement -
A 'duplicate workflow button next to the delete workflow button would be a great way of helping us develop workflows - It's too much of a pain to recreate a detailed workflow from scratch but then again if I want to modify a workflow it would be great to have the option to redact it if the new idea is bunk.

Also - an 'are you sure you want to delete this workflow' prompt following a press of the delete button would put me at ease a little.

**Comment by camallen** [comment]
This is already supported in panoptes but not linked up to the front end client. Docs [here](http://docs.panoptes.apiary.io/#reference/projects/project-create-links/add-a-link) via update project links, if it's a workflow it'll create a copy of it and link the copy to the project.

Front-end ticket already exists too, https://github.com/zooniverse/Panoptes-Front-End/issues/841.
