### ISSUE TITLE
Project URLs

### ISSUE THREAD

**Issue by AdrianEvans** [zooniverse/Panoptes#1130]
What are the options for using a specific URL?

Pre-panoptes projects mostly have their own URLs - I've purchased [fossilfinder.org](http://preview.fossilfinder.org) with the plan to be able to brand our project with that. Perhaps just a notes box is needed to go along with the submission button for going into beta or public.

currently I just have a redirect going from [preview.fossilfinder.org](http://preview.fossilfinder.org)

**Comment by edpaget** [comment]
At some point we will support custom urls for projects.
