### ISSUE TITLE
Uploading subjects barfs on manifest text containing umlauts

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes#1140]
I'm uploading a subject that has in its manifest the field "Location name" for which the value is "Marktplatz Tübingen, Germany". 

I get an Error 500 back, "We're sorry, but something went wrong"

Am I really limited to the 128-ASCII table?!

(Also, poor error response...)

**Comment by edpaget** [comment]
No we should support the full utf-8 character set. I do have an error in our logger about malformed utf-8 error values.

**Comment by edpaget** [comment]
You're using Python 2.7 right? I know it has some weird hangups about utf characters and strings. I'll see if I can find some documentation about it.

**Comment by mkosmala** [comment]
Oh, hmm... okay, I'll look into it, too.

**Comment by edpaget** [comment]
There's this page which is the main one https://docs.python.org/2/howto/unicode.html

**Comment by mkosmala** [comment]
The JSON looks okay when I print it:
```
Tried to pass data:
    {
        "subjects": {
            "locations": [
                "image/jpeg"
            ],
            "metadata": {
             "Filename": "cam3397_20150213_090946.jpg",
                           "Webcam": "3397",
                           "Location Name": "Marktplatz Tübingen, Germany",
                           "Latitute": "48.52126",
                           "Longitude": "9.05311"
            },
            "links": {
                "project": "348"
            }
        }
    }
```
But I'll check out that page. (...started reading...) Oh, right. I remember reading about this once. Okay, let's see if I can properly encode everything. -sigh-

**Comment by mkosmala** [comment]
(PS, uploading has been great so far. I've been uploading a group of about 10,000 images. It had been chunking along quickly for 5254 images until it hit my mis-encoded umlaut.)

**Comment by mkosmala** [comment]
Argh! I want to gauge my eyes out. Why is this so hard? (I can't figure out what encoding I'm reading in, so can't convert it to anything. It's not utf-8 or latin-1 or ...)

**Comment by edpaget** [comment]
Yeah it's hard because computers are terribad.

**Comment by edpaget** [comment]
Is there anyway your script would work in Python 3? That has default unicode support. Are you on windows? It uses a different weird encoding system.

**Comment by mkosmala** [comment]
It's a Windows encoding. I'm pretty sure of it. I think I need to just figure out how to convert my text file to another encoding... may be the easiest?

**Comment by mkosmala** [comment]
@edpaget I've made some progress. I can actually properly encode/decode my file now. (That only took 3 hours).

But I'm still having trouble passing the data to the Panoptes API. What format does Panoptes expect the payload to be in? This doesn't seem to work, for example:
```
Tried to pass data:
    {
        "subjects": {
            "locations": [
                "image/jpeg"
            ],
            "metadata": {
             "Filename": "cam3397_20150213_090946.jpg",
                           "Webcam": "3397",
                           "Location Name": ""Marktplatz T&#252;bingen",
                           "Latitute": " Germany"",
                           "Longitude": "48.52126"
            },
            "links": {
                "project": "348"
            }
        }
    }
```

**Comment by mkosmala** [comment]
OMG. That only took 5 hours to figure out. 
-bangs-head-on-table-  
-passes out-

**Comment by camallen** [comment]
@mkosmala it'd be nice if you outline the solution here for future users.

**Comment by mkosmala** [comment]
Hmmm... Okay, @camallen 
Step 1: Read the webpage @edpaget referenced above. 
Step 2: Also read this webpage: https://pythonhosted.org/kitchen/unicode-frustrations.html
Step 3: Realize that in Python, 'decode' means to go from ascii to unicode, and 'encode' means to go from unicode to ascii. Which seems backwards, but there you have it.
Step 4: Realize that there is no reliable way to know what @#$! codec your text file is in.
Step 4.5: Realize that you're on a Windows machine and so your codec is probably some weird thing that no unix-based machine can hope to read. And files may have BOMs at the beginning. And all sorts of craziness. Decide to abandon Windows.
Step 5: Borrow husband's Mac, transfer file, and replace all the messed-up-looking characters with the correct ones using find-replace-all. Importantly: save as UTF-8. Transfer file directly to remote linux machine where the images are.
Step 6: Find this little piece of magic: top answer of http://stackoverflow.com/questions/904041/reading-a-utf8-csv-file-with-python . 
Step 7: ~~Steal~~ Borrow code from awesome StackOverflow answer to finally read file in successfully.
Step 8: Become desolate because code still crashes.
Step 9: Eat chocolate. Rally.
Step 10: Figure out that this ```unicode(str(project_id))``` is a functional way to turn an integer into unicode. 
Step 11: Figure out how to properly encode metadata text as ascii using XML encodings for non-128-ascii characters: ```strvalues = values.encode('ascii','xmlcharrefreplace')```
Step 12: Watch code run successfully. Yawn. Go to bed because it's past midnight and you have to nurse the baby when he wakes up at 6:30am. (YMMV)

**Comment by camallen** [comment]
Thanks - I especially like Step 9!
