### ISSUE TITLE
Subjects not being randomized. Thought a fix for this was in but seeing 13 subjects in a row  from same number range of subjects

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes#1141]
I thought https://github.com/zooniverse/Panoptes/pull/1133 would fix this but it's still happening. I thought when I login in that my queue of subjects to do would be reset 

I noticed the images on Planet Four: Terrains changed look and everyone else is commenting on the different features so we're all collectively seeing the same thing. They are all from the same larger CTX image we divided out. We've got 8000 subjects made from a many larger full frame CTX images  and most are unseen and they were uploaded in order grouped by parent image id in the original manifest, we didn't randomize. 

I made a collection - of 13 of the 14 in a row images I saw - except for 1 they all come from the same CTX image - Only 1262 of the 8437 images in the subject set are from that CTX image most of my subjects still need classifications, so I shouldn't be getting 10 or more classifications in a row from the same subset group.

You can check the collection here  to see except for the first one they are all from Dorsa Argentea    

https://www.zooniverse.org/#/collections/mschwamb/planet-four-terrains-examples?page=1

**Comment by mschwamb** [comment]
Maybe the patch isn't live or it takes a long while for a classifier's queue to reset. I thought I'd mention it since I'm not sure

**Comment by marten** [comment]
The patch is deployed to staging, but not to production yet. Should go out today, but since it's going to be my first production deployment, I want to make sure there's someone else awake in case of problems.

**Comment by mschwamb** [comment]
Okay. Thanks for the clarification @marten . That's why the issue on randomizing was closed, but I'm see what I'm seeing. I make another ticket if it's still showing this way after your change is made live.

**Comment by marten** [comment]
And thank you for testing that our fixes actually work!
