### ISSUE TITLE
API retrieved project retired_subjects_count giving wrong value?

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes#1142]
Not sure if I'm doing this correctly - the retired subject count returned by the api doesn't match what actually exists in the data

I have 521 subjects that have more than 20 classifications and could be retired out of  8436

I'm getting retired_subjects_count:3903 when I call the api

wget -qO - --header="Accept: application/vnd.api+json; version=1"  https://panoptes.zooniverse.org/api/projects/17  |  jshon -e projects -e 0  -e retired_subjects_count

3903

And in the annotations  csv all the retired states are false. 

Is it just retired_subjects count means something different than I think it does?

**Comment by camallen** [comment]
@mschwamb that larger number seems to have been a remnant of the prev subject sets. I've reset the retired count on that worklow so it should match what you are expecting. For reference the project level `retired_subjects_count` will summate all your workflows, so you can use the workflow end point to get more specific details.

**Comment by mschwamb** [comment]
@camallen  Thanks. I'll try and figure out how to access that part with the api. 
~Meg
