### ISSUE TITLE
Subject that has enough classifications made since Tuesday is not retired

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes#1143]
I might be wrong on this since I'm having a hard time finding in the documentation of how to get this from the api so I'm relying on the annotations csv dump for the subject status

subject 483915 has had 20 classifications since '2015-07-14-00:00:00' and 21 since '2015-07-13-00:00:00' So the fix @camallen  made for subjects not retiring should be working 

I presume that when the annotations csv file is made it puts in the current subject data so when it says retired:false for all the annotations associated with  483915 it means panoptes thinks its still not retired. 

Am I going wrong somewhere or is something still up with retiring classifications?

**Comment by camallen** [comment]
@mschwamb that subject is retired, check the subject manifest dump for more information. There is a bug in the classifications dump that will be fixed by PR #1145.

**Comment by mschwamb** [comment]
Thanks @camallen  and sorry for not checking the subjects csv  when I checked the annotations csv

**Comment by camallen** [comment]
All good - found the classification dump bug.
