### ISSUE TITLE
Scientist Names instead of usernames on research page

### ISSUE THREAD

**Issue by AdrianEvans** [zooniverse/Panoptes#1144]
The style would look better if instead of just using the usernames of the team the api pulled the real name from the database and used that.
Also it isn't clear how these are sorted - perhaps by status, owner, collaborator etc, but perhaps with owner and then alpha by surname

**Comment by camallen** [comment]
@AdrianEvans this is not a backend api issue, please report this in the front end client repo https://github.com/zooniverse/Panoptes-Front-End
