### ISSUE TITLE
Shouldn't retired in workflow in the csv data dump only list one number once the subject is retired if project has only one workflow? Workflow id is repeating multiple times

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes#1148]
I checked the subjects data dump this morning and I noticed that when a subject is retired, the workflow id repeats to varying number of repeats

example subject 483915 for P4T has [16,16,16,16,16,16,16,16,16,16,16,16,16] listed in retired_in_workflow column - Why is it repeating?  From the classification count it was 32 classifications listed, so I'm not sure what the 13 repeats of the 1 workflow means.  Should it just list workflow 16 once?

**Comment by camallen** [comment]
@mschwamb - this just means that the retirement counter fired X number of times. We're modifying the way we track retirement at the moment so this will change soon.
