### ISSUE TITLE
Connection timing out when uploading to AWS

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes#1154]
Advice wanted here. I've been doing my uploads mostly in the evenings (Eastern time) from 9pm to 2am. I've uploaded tens of thousands of images and only timed out once. Right now (2pm Eastern) I've just hit 4 time-outs in a row -- and I've only uploaded a few hundred images. Is this likely a time-of-day thing? Or something else? Any ideas?

**Comment by edpaget** [comment]
You can check AWS status at: http://status.aws.amazon.com/. Otherwise you just need to catch errors and retry. Errors are just something that will happen with services that handle the scale S3 does.

**Comment by mkosmala** [comment]
Yeah... I was just being lazy about error handling, since I'd been so lucky about them...
