### ISSUE TITLE
Redirect URIs from oauth access_token flow incorrect

### ISSUE THREAD

**Issue by chrissnyder** [zooniverse/Panoptes#1156]
Given a link like

`https://panoptes.zooniverse.org/oauth/authorize?response_type=token&client_id=XXXX&redirect_uri=http://localhost:3434/#/classify`

Panoptes will return you to

`http://localhost:3434/#/access_token=XXXXX&token_type=bearer&expires_in=7200`

**Comment by edpaget** [comment]
Not a bug Panoptes will only allow applications to redirect to their whitelisted URLs.

**Comment by camallen** [comment]
Ah - got it. Is there a way to add extra params to the redirect?

**Comment by edpaget** [comment]
Yeah you can whitelist multiple URLs. You can't edit applications at the moment though.
