### ISSUE TITLE
Oauth access_token flow result in 422 CORS error

### ISSUE THREAD

**Issue by chrissnyder** [zooniverse/Panoptes#1157]
When given a token like

`http://localhost:3434/#/classify?access_token=c9beaa256f9fb8ce7841ac92c9a1011efdf2...&token_type=bearer&expires_in=7200`

Subsequent requests to get the session result in a 422 No Access-Control-Allow-Origin header present. Request sent is below:

```
OPTIONS to https://panoptes.zooniverse.org/me

Headers:
Accept:*/*
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8
Access-Control-Request-Headers:accept, authorization
Access-Control-Request-Method:GET
Cache-Control:no-cache
Connection:keep-alive
Host:panoptes.zooniverse.org
Origin:http://localhost:3434
Pragma:no-cache
Referer:http://localhost:3434/
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.134 Safari/537.36
```

**Comment by camallen** [comment]
Non-api routes have CORS domain restrictions on them [here](https://github.com/zooniverse/Panoptes/blob/c8eeaf130b5c809cc1bbcb95fc32e6d28c09f692/config/environments/production.rb#L93), currently *.zoonivese.org only on production. For reference custom first party front ends will have to be whitelisted here.

Also did you mean to hit `/api/me` instead?

**Comment by chrissnyder** [comment]
Is that true even for separate doorkeeper applications?

I did mean to hit `/api/me` instead, my bad. That returns a 404 rather than a 422.

**Comment by edpaget** [comment]
It's api/users/me

**Comment by edpaget** [comment]
Whoops that was wrong. You need to specify the accept header:

"Accept: application/vnd.api+json; version=1"

**Comment by camallen** [comment]
CORS headers are what you seen in the links above. 

`/api` routes are open for all. For OAuth routes, we should probably do what @edpaget is talking about [here](https://github.com/zooniverse/Panoptes/issues/1096) and wrapping them in api end points or open up CORS where needed.

**Comment by edpaget** [comment]
Yeah this is just about the Accept header, which wasn't set in the example request.

**Comment by chrissnyder** [comment]
Ah ha, worked like a charm.

Yea, I worry I'm getting slightly ahead of myself here. Happy to wait until this settles down a bit.

**Comment by edpaget** [comment]
the `/api/` routes should be all good to go. I don't think you need to wait on it.
