### ISSUE TITLE
Subject creation reverses the locations array that was posted.

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/Panoptes#1159]
If I post `locations: [ 'image/png', 'image/jpeg', 'text/plain' ]` for a new subject, the locations array that comes back has this order `[text, jpeg, png]` so the wrong files get assigned to each location by the uploader.

**Comment by edpaget** [comment]
Your uploaders should look at the content type returns instead of relying on the order. 

You should get a response like: 

```
[
  { "image/png": url...},
  { "image/jpeg": url...},
  { "text/plain": url...}
]
```

So you can iterate through the array match the returned keys.

**Comment by eatyourgreens** [comment]
I looked at that, but wasn't sure how the uploader should handle the case where the response has more than one file of a given type

```
[
  { "image/jpeg": url...},
  { "image/jpeg": url...},
  { "text/plain": url...}
]
```
ie. which local jpeg to assign to each jpeg in the returned locations.

**Comment by camallen** [comment]
Does it matter what order the same mime type files are uploaded in? if it does then i think we should just add an `order(:id)` to the `subject.locations` relation.

**Comment by eatyourgreens** [comment]
This was me being dumb and not understanding the upload client. @edpaget is spot on, order isn't important and the client should map by MIME type, rather than relying on the locations array index, to match up local files with S3 URLs.

I'm writing a fix for the subject uploader and I'll put in a PR for PFE too.

**Comment by camallen** [comment]
We should respect the order of the incoming mime type arrays from the front end and just return the relation ordered by the created id. 

https://github.com/zooniverse/Panoptes-Front-End/issues/1152#issuecomment-123755810
