### ISSUE TITLE
Add Rank Order to Projects

### ISSUE THREAD

**Issue by edpaget** [zooniverse/Panoptes#1161]
So we can can control the order they appear on the page.

**Comment by camallen** [comment]
this looks useful, https://github.com/swanandp/acts_as_list

**Comment by marten** [comment]
We replaced that with https://github.com/mixonic/ranked-model at RoQua earlier this year. Main difference is that with ActsAsList you get `Project.pluck(:rank) == [1,2,3,4,5]`, which means to move a single record, you have to update many rows. RankedModel distributes them across a large range like `[-40000, -20000, 0, 20000, 40000]`, so usually there is a number available between two models to insert it at the correct position.

**Comment by camallen** [comment]
neat.

**Comment by edpaget** [comment]
:+1: thanks @marten
