### ISSUE TITLE
Batches of images are shown to users in ID order instead of randomly

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes#1163]
When Panoptes grabs a bunch of images to show to a user, the images within this batch get shown in ID order. It would be better if they were shown randomly. But this is a low-priority issue.

**Comment by chrissnyder** [comment]
This can be done on the front-end as well by just randomly selecting from within the subject array Panoptes returns.

**Comment by camallen** [comment]
Pretty sure this is the serializer using the natural sort order coming out of the DB. If so we could look at the workflow selection strategy and add a sort order to the serializer. Note some workflow selection strategies need to be in order (priority).

**Comment by mschwamb** [comment]
I'm getting the same thing, but I think it's still not selecting randomly from the list of available subjects to classify. 

My subjects are subimages for larger CTX  full frame images. Which we divide up and are listed in order of image they came from, so the subimages associated with a given CTX image are clustered in the manifest file. I just did 10 classifications and they are all from the same CTX image. I'm not sure if that's means that #1033 isn't fixed. Even if I had an ordered list I would think in 10 classifications it would give me a cutout from a different CTX image to look at

**Comment by mschwamb** [comment]
People on Terrains are still seeing groupings of the same set of rows from the manifest file. Is the current solution for now that for the next data upload I should randomize the order of the subjects in the manifest so they're not grouped?

**Comment by camallen** [comment]
There was a bug in the subject queues that was fixed by #1242. I'll be rebuilding the queues today so this should not be a problem after i've deployed the fixes and cleared the existing queue sets.

**Comment by mschwamb** [comment]
oh okay. thanks @camallen for the explanation

**Comment by vrooje** [comment]
Just noting [yshish has also noticed this](https://www.zooniverse.org/#/talk/18/115?comment=4558) and said it would be useful for the subjects to not be served in order. Does a front-end issue exist for this yet?I didn't see one but I may have searched for the wrong thing.

**Comment by camallen** [comment]
This should have been fixed by #1297.
