### ISSUE TITLE
Handle invalid relations on resource create / update

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#1165]
Gracefully handle missing resource relations and proivde better error messaging instead of 500'ing.

E.g. when creating a subject set with the `workflow: 1` key instead of `workflows: [1]` it 500's due to the missing association [here](https://github.com/zooniverse/Panoptes/blob/31316cab492cf2d5775f13b7e43bc6f790b38d54/lib/json_api_controller/relation_manager.rb#L48).

**Comment by edpaget** [comment]
We just need to be stricter in the validating the json requests.
