### ISSUE TITLE
One hour is too short for holding classification dumps

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes#1177]
I requested classifications from the Project Builder, but they didn't arrive within ten minutes, and I had a lot of other things to do. I came back to my email an hour and a half later -- 61 minutes after the email had arrived -- and was unable to get my classifications. So now I'm re-requesting them, which is a waste of processing on the Panoptes side and a pain in the neck for me. Can we up that holding time to, say, 6 hours? Or 24?

**Comment by camallen** [comment]
Can't you just use the latest dump link next to the request data button?

**Comment by mkosmala** [comment]
Oh, yes. Yes, I can. Sorry, I hadn't noticed the link. (Or rather, I had noticed it before I made the first request, clicked it, and got an error. So I didn't know what it was for.) So Panoptes stores the results of the latest request for a long time (forever?). Great solution. 

Might want to mention that in the email that is automatically generated. "Has it been more than an hour? You can get your classification by going to your project, blah, blah, blah."

**Comment by vrooje** [comment]
I don't know the reason for making the link expire in an hour (except possibly that for the Nepal project, which may have been the first time this was implemented, I was getting new files every hour). But I think it would be great to add directions to get the file from the project builder interface.
