### ISSUE TITLE
Redirects go via preview

### ISSUE THREAD

**Issue by astopy** [zooniverse/Panoptes#1185]
The redirect in #1183 redirects via preview:

$ curl -v https://panoptes.zooniverse.org/unsubscribe
[...]
< HTTP/1.1 302 Found
< Cache-Control: no-cache
< Content-Type: text/html; charset=utf-8
< Date: Fri, 24 Jul 2015 09:27:00 GMT
< Location: http://preview.zooniverse.org/panoptes/#/unsubscribe

**Comment by camallen** [comment]
This is vestigal from a while back, I'm fixing now. They did end up at the correct spot due to a redirect on http://preview.zooniverse.org/panoptes/

**Comment by camallen** [comment]
Fixed.
