### ISSUE TITLE
Workflow-specific media links

### ISSUE THREAD

**Issue by brian-c** [zooniverse/Panoptes#1186]
Users'll be able to upload a whole bunch of images for the survey task (feature filtering icons, species catalog images) and I'd like to keep them separate from project's media.

And "a whole bunch" is about 150 for Gorongosa (50 species, 2 or 3 images each, plus ~30 filterable feature icons). It'd be nice to be able to grab all the resources with one request if possible.

**Comment by camallen** [comment]
Any way these could be constructed into a sprite image?
