### ISSUE TITLE
Track Requests for Beta

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes#1190]
Now that the project builder is live, and the policy page states that builders can submit their projects for review by hitting the "Apply for Beta" button, we need a way to see when projects have requested review (e.g. https://www.zooniverse.org/#/talk/18/1239?page=1&scrollToLastComment=true)

Ultimately I think we'll want some sort of automatic checks for basic completeness, as well as a plan for community-based review, but for now, I think we need some sort of alert system for Zooniverse team members who can authorize a project for beta testing. For example, an automated email that goes out to the team when a project has requested beta testing?

Thoughts, @camallen @edpaget @chrissnyder @mrniaboc @DarrenMcRoy ?

**Comment by chrissnyder** [comment]
You already can. Make sure you check "Admin Mode", then goto `https://www.zooniverse.org/#/projects?beta_requested=true`

**Comment by chrissnyder** [comment]
That said, a more thorough system to sheperd these proejcts these their lifecycles is needed.

**Comment by DarrenMcRoy** [comment]
We need some type of alert when a new project is submitted for beta, at least, right?

**Comment by chrissnyder** [comment]
I don't think it's that important right now. Occasionally checking manually does the job just fine when there's only a handful of projects at that stage. When we actually have more projects coming through the system, then we are going to need something better than an email anyway.

**Comment by camallen** [comment]
@chrissnyder FYI - admin mode won't "survive" a page reload. It's something that needs some work possibly with local storage backing.

So that using the URL above ends up sending this `https://panoptes.zooniverse.org/api/projects?include=owners,avatar&launch_approved=true&beta_requested=true` which will return and empty set.

**Comment by chrissnyder** [comment]
Sorry, copy-pasting the URL should be fine then. The page will react to query param changes.

**Comment by camallen** [comment]
hmm - still got `https://panoptes.zooniverse.org/api/projects?include=owners,avatar&launch_approved=true&beta_requested=true` when copying and pasting. 

The `launch_approved=true` & `beta_requested=true` would not meet any projects that are requesting beta.

**Comment by chrissnyder** [comment]
Even if you click Admin Mode first? I get `https://panoptes.zooniverse.org/api/projects?admin=true&include=owners,avatar&beta_requested=true` which is correct

**Comment by camallen** [comment]
yep - will PM you to try and replicate what you're doing.

**Comment by aliburchard** [comment]
@chrissnyder who's checking this? Are they checking every day? Every two days? Once a week? I agree an email isn't going to cut it once we're getting 10 (or 100) beta requests every day, but if it's easy to set up, it would remove the onus from one of you guys to have to remember to check for this every day. Just one less thing to have to remember to remember to do.

**Comment by mrniaboc** [comment]
...and who's making the final decisions on whether a project is legit or
not just now?
