### ISSUE TITLE
Should we allow subjects to be deleted via the API

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#1193]
Seems any collaborator / project owner can delete subjects via the API. Since subjects can be re-used across the zooniverse should we still allow this?

**Comment by mkosmala** [comment]
Yes, especially for testing. To get my projects up and running, I create the project and then add three images to each workflow. I don't care about these images; they're just for testing. When I'm ready to do a beta or launch, I delete these dummy images via the API and load my real images in.

**Comment by mkosmala** [comment]
(But can be tricky, as you note. So I would vote for a solution that makes deleting subjects relatively easy -- but perhaps subject to some constraints.)

**Comment by brian-c** [comment]
Yes, but not if they've been classified in a live project?

Maybe that check could happen automatically when they're removed from a subject set. I don't think the user should have to know the difference between deleting a resource and deleting the only link to it.

**Comment by camallen** [comment]
So a classification in any project could be a proxy to being commented in talk / collected. Can anyone think of a way to comment / collect a subject without classifying it somehow first?

So removal from a subject set just removes the link between `subject_set` and `subject`, it doesn't actually delete any subject (these just get orphaned from the site now for reference in any collections / talk, etc). 

This functionality is really why i wanted to start this discussion as we don't provide an interface to delete subjects except via the API which may cause problems if more advanced users decide to issue `DELETE /subjects/id` without understanding the consequences. @mkosmala did you actually delete the subject resources via the delete described above or just the `subject_set`?

**Comment by mkosmala** [comment]
I can't think of a way to comment or collect a subject via the front-end without first classifying it. 

And, all my "deletes" were through the front-end. I've both clicked the little trash can icon to delete images one at a time and deleted entire subject sets full of subjects. I haven't looked to see what this did on the back-end -- if I understand you, @camallen, I really just removed links between the subjects and subject_sets when I did these things. 

I have not issued any ```DELETE```s via the back-end. (Seems a bit scary to do that... I would probably consult with you guys to see what the consequences would be if I were to try it that way.)

But a follow-up question: if my subjects are just getting orphaned when I trash-can them (or delete entire subject sets) and they aren't really being deleted, do they still count toward my subject quota?

**Comment by camallen** [comment]
> I have not issued any DELETEs via the back-end. (Seems a bit scary to do that... I would probably consult with you guys to see what the consequences would be if I were to try it that way.)

Yep - that's why i'm wondering if we should allow this end point at all.

>But a follow-up question: if my subjects are just getting orphaned when I trash-can them (or delete entire subject sets) and they aren't really being deleted, do they still count toward my subject quota?

Yep - we've solved this mostly by increasing subject limits on request.

**Comment by mkosmala** [comment]
>> But a follow-up question: if my subjects are just getting orphaned when I trash-can them (or delete entire subject sets) and they aren't really being deleted, do they still count toward my subject quota?

> Yep - we've solved this mostly by increasing subject limits on request.

Oh.... wow. Okay. So.... I kinda sorta "deleted" about 30,000 subjects. They are subjects that absolutely positively can be removed forever and ever. (They had "masks" and we decided right before launch that we didn't want to use masks.) Oughtn't there be a way to do permanently delete subjects?

**Comment by parrish** [comment]
> Can anyone think of a way to comment / collect a subject without classifying it somehow first?

Some users do this by changing the URL.

During the soft delete, we could check to see if the subject

- is included in multiple subject sets
- has any classifications
- has any comments
- has been collected

If those are false, we could perform a hard delete.

**Comment by camallen** [comment]
@parrish thanks. so really we're talking about a subject reaper worker that could cleanup every so often.

**Comment by parrish** [comment]
Or even just an asynchronous worker to run the checks and perform the sort/hard delete

**Comment by aliburchard** [comment]
Just going to echo the need for real "hard" deletes - @mkosmala's use case isn't going to be unique.

**Comment by chrislintott** [comment]
Human subjects use cases or copyright limitations might also require ‘hard’ deletes.

C
