### ISSUE TITLE
reserved key words to task ids

### ISSUE THREAD

**Issue by ggdhines** [zooniverse/Panoptes#1201]
so people are able to set whatever task id string they want. In the JSON output, I use "param" and "  instructions" (note the two spaces at the start) as special reserved keywords. If the users made a task with either of those ids, the aggregated output would be messed up. Would it be possible to add something that checks to make sure that those are ids aren't used? Are task ids even allowed to have spaces at the start? If not, then I'll just change "param" to " param" and everything will be good.

**Comment by camallen** [comment]
@ggdhines - I just tried on my project and i looks like i can set the task's main text to "  param". I think this is a front end issue but maybe swayed on adding reserved words restrictions to the API if needed. Can you give an example of how the aggregated output would be messed up?

**Comment by ggdhines** [comment]
sorry I meant the task id (not the text) being set to "param" - in which case some data would be overwritten - I specifically set "param":something which would overwrite any existing data. Probably a front end issue

**Comment by camallen** [comment]
Ok - not sure i'm following, where is this value being set? Close this if you think it's a front end issue.

**Comment by ggdhines** [comment]
nm - my bad, misunderstood what was going on.
