### ISSUE TITLE
High skew in number of subject classifications

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes#1202]
Perhaps this is by design, but there is high skew in the distribution of classifications in my subjects over this first week in Season Spotter. In particular, subjects with small ID numbers have been seen many more times than subjects with large ID numbers. It doesn't seem very random. (And it's bad news because my subjects are largely grouped by site, so it means people are seeing the same site over and over again instead of a diversity of sites.) 

Here is the distribution of one of my projects:
```
number of classifications, number of images with that number of classifications
25	1
21	3
20	2
19	3
18	9
17	10
16	20
15	28
14	22
13	28
12	41
11	54
10	59
9	58
8	78
7	84
6	109
5	147
4	201
3	274
2	377
1	415
0	14758
```
So you can see that the ~10,000 classifications on this project are distributed over only ~2,000 subjects. Seems weird.

**Comment by camallen** [comment]
It's a vestige of the way we create queues to serve subjects and should have changed behaviour via some recent commits. There was also the problem of sorted ids in #1133 that probably explains why your seeing low ids with more classifications, they came out first.

For reference, we create a queue for the non-logged in user and then copy that as a starting point for a user when they start classifying on a project. So you're probably seeing a vestige of the same low id subejcts coming out of peoples queues. 

As of yesterday we've deployed some changes that will dequeue a subject whenever it's requested (and not just retired) so you should get a more random spread of the subjects all queues now but especially the non-logged in queue.

**Comment by mkosmala** [comment]
Got it. Thanks!
