### ISSUE TITLE
Handle missing language content in project serializer

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#1212]
[Here](https://github.com/zooniverse/Panoptes/blob/dc255329cd19f3ebdfaf6771f8dc4b4540e91efc/app/serializers/project_serializer.rb#L66) and might be related to #1091 

I get an error on staging using the apiary docs http://docs.panoptes.apiary.io/#reference/projects/project-collection/list-all-projects?console=1, originally reported [here](https://www.zooniverse.org/#/talk/17/1403?page=1&comment=3031).

**Comment by edpaget** [comment]
It should always at least return the primary_language content for a project from [here](https://github.com/zooniverse/Panoptes/blob/master/app/models/concerns/translatable.rb#L22), and a project shouldn't valid unless it has some sort of content. Are we sure this is the issue?

**Comment by camallen** [comment]
Maybe not, might be a problematic project. I didn't debug properly just had a quick look at the code.

**Comment by edpaget** [comment]
It looks like there are ~500 projects on staging that are invalid.

**Comment by edpaget** [comment]
I'm fine with just deleting them.

**Comment by camallen** [comment]
old weather and retina's are two that we need to keep in the meantime, otherwise yeah - it's staging...

**Comment by chrissnyder** [comment]
Would it be useful to have a short description on how to setup an application on production somewhere? Happy to put this together myself. I think people are just following the Ouroboros model of dev/production, when it doesn't make sense here because we can label the project as private while in development.

**Comment by camallen** [comment]
@chrissnyder I think this is a vestige of us having staging ready before prod. We should encourage everyone to build on prod now. Not sure if i know anyone building on staging anymore.

So the real problem here is the invalid projects are linked to deactivated user accounts. We are including 'deleted' (think deactivated) resources in our api responses instead of excluding them. All of these seem to be from front end testing on staging and it's something that should be fixed by adding scopes on our controller controled_resources scope to only find active resources.

Closing this, will open a new issue and submit a PR.
