### ISSUE TITLE
Request: ability to "backup" a project

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes#1225]
Continued from / related to https://github.com/zooniverse/Panoptes-Front-End/issues/1273

It would be great to have a way to export / import a text representation of a project and its workflows and subject sets (ignoring the actual subjects). That way people could "save" their project to their own computers.

Alternatively -- or in addition -- it would be nice to have a project versioning system so that people could (A) try alternative approaches in creating their projects; and (B) revert to an earlier draft of the project in case something went terribly wrong (e.g. a collaborator deleted all the workflows by mistake). 

Discussion warranted, as the former puts more responsibility on the end-user, but should be fairly easy to implement. The latter is more complicated and puts the responsibility for "backing-up" on Zooniverse, but is more sophisticated and perhaps more user-friendly.

**Comment by chrislintott** [comment]
I wonder if the system @aliburchard and @brian-c have cooked up for Serengeti-style projects could help here - a csv file containing Workflow data.

**Comment by brian-c** [comment]
It should be easy to import/export data (it's all JSON anyway), but nearly impossible to debug errors if someone changes the file manually (and they will).

**Comment by vrooje** [comment]
What's the status of this?

We've been working on some customized aggregations using zooniverse/aggregation as a starting point, and right now that code queries Panoptes directly to get workflows. It would be much better to just read them from an exported workflow csv, but I don't think we have access to one.

**Comment by edpaget** [comment]
@vrooje I'll add it to the future plans. 

Are you actually manipulating stuff from the workflow? Or just want to save a request against Panoptes?

**Comment by vrooje** [comment]
I just want to save it - no need to change anything.
>
>

**Comment by marten** [comment]
While I think this is a good idea in principle, I can see how this might be better dealt as an API client feature, without needing special backend support for it. Closing it here, if anyone wants this feel free to work on it in the scope of panoptes-python-client or similar.
