### ISSUE TITLE
Individual User Authentication

### ISSUE THREAD

**Issue by bruggsy** [zooniverse/Panoptes#1226]
User here, I'd like to manipulate and subjects my project via API but there's no documentation for the oauth workflow. Wondering if this is possible but just not documented yet.

**Comment by edpaget** [comment]
Yes it possible. I haven't setup a method for individual users to generate API Keys since I'm still working out the exact way that will work. If you'd like to mess around through, feel free to drop me an email at ed@zooniverse.org and I'll generate keys for you, and send you instructions.

**Comment by edpaget** [comment]
Waiting on this https://github.com/zooniverse/Panoptes/issues/1096
