### ISSUE TITLE
Search has difficulty with short user names

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes#1230]
As @edpaget discovered, short user names like mine (DZM) don't work with the search algorithm. Opening an issue to work on that.

**Comment by camallen** [comment]
this will need to use use a different index type for the search function

**Comment by camallen** [comment]
New solution seems to be missing users too, e.g. `@astopy` will have to revert or try a different kind of text indexing.

**Comment by DarrenMcRoy** [comment]
This still takes about 7-10 seconds to find my username, for the record...

**Comment by camallen** [comment]
It's a trade off between speed and completeness, i.e. i can have a search return super quick that doens't find you. Also looks like the front end is firing off a lot of queries. maybe it could do better on timing events and stress the server less.

**Comment by DarrenMcRoy** [comment]
Any chance we could add some time of note that it's "still searching..." so that it doesn't look like it's just hanging?
