### ISSUE TITLE
Add CSRF route

### ISSUE THREAD

**Issue by astopy** [zooniverse/Panoptes#1236]
For zooniverse/Panoptes-Front-End#1312

Currently the front end has to scrape the HTML on arbitrary pages to get a CSRF token. Ideally it should be able to just fetch one from, say, /csrf as plain text.

**Comment by camallen** [comment]
I'm going to modify the `/users/sign_in` route to return the csrf heades for json requests to avoid scaping the html. https://github.com/zooniverse/Panoptes/blob/master/app/controllers/sessions_controller.rb#L7

**Comment by astopy** [comment]
It’ll also need to not redirect if the user is already signed in.

**Comment by camallen** [comment]
Pretty sure that scuppers my plan...will look into another end point.

**Comment by camallen** [comment]
PR in - if you get the `/users/sign_in` via json it won't redirect and will have the csrf tokens as headers in the response.

**Comment by brian-c** [comment]
Sorry, can we get `X-CSRF-Token` added to `Access-Control-Expose-Headers`?

**Comment by camallen** [comment]
Should be fixed now.
![image](https://cloud.githubusercontent.com/assets/295329/9132835/5bd2a13c-3cee-11e5-9594-6f627f5b4316.png)
