### ISSUE TITLE
Subject queue operations should maintain the existing order

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#1241]
`Subject.enqueue_update` and `dequeue_update` [here](https://github.com/zooniverse/Panoptes/blob/520453d62b926e9e6fff11330520d42a4e744d3f/app/models/subject_queue.rb#L92) should maintain order of the queue as it was.

Postgresql int array union and diff sorts the queue after manipulation (http://www.postgresql.org/docs/9.1/static/intarray.html)
![screen_shot_2015-07-16_at_14 22 02_360](https://cloud.githubusercontent.com/assets/295329/9109821/9e8e933c-3c30-11e5-8a5e-8bdf7ff7503a.png)

![image](https://cloud.githubusercontent.com/assets/295329/9109944/9bf0ecf0-3c31-11e5-8a77-cb4bae78568c.png)

**Comment by edpaget** [comment]
Geeze, good catch.
