### ISSUE TITLE
retroactively associate not-logged-in classifications with userid after a user logs in

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes#1248]
Based on looking at a sample of project classification exports, it seems fairly common that a user classifies on a project for up to 10 or so classifications before logging in and continuing (based on IP addresses). Right now we don't explicitly associate the not-logged-in classifications with the user, even though we can theoretically tell that it's the same IP and browser session. 

I think we should do that -- if a user logs in we should retroactively add the user id+name to the not-logged-in classifications for that same session in the DB. This would be very helpful for more accurate user weighting during the aggregation stage (and doing it in small pieces as needed would prevent a heavy-processing step every time an aggregation is performed).

If we also added a flag like user_info_added_retroactively=1 it might help us with splits/experiments, and external researchers would probably use that too.

(hope this is appropriate here... wasn't sure whether to post it here or PFE.)

**Comment by camallen** [comment]
@vrooje - yep this is the right place. 

I'm not sure we should do this as different use cases may want to treat these differently. I.e. we record a canonical version of the classifications and then it's up to the interpretter to use the data how they want. I agree you can most likely ID users with a combination of user agents and IP but maybe not always especially with NAT'd private networks (sharing the public IP), also maybe public terminals that volunteers share (musuems, etc). These situations may present different volunteers as the same after someone logs in.

**Comment by vrooje** [comment]
I was chatting about this with @willettk yesterday, and we generally agreed that it would be better to be able to associate not-logged-in classifications with a later-logged-in user if there is very good evidence they were from the same person. I completely agree the IP wouldn't be enough to make this unique on its own... but I'd think a browser session and an IP would do much better, and even better would be IP + browser-session + timed-session, where timed-session is designed to *not* include e.g. the classifications from person A on a public terminal who forgot to close their browser before person B came along an hour (or whatever) later and classified on the same project.

As far as I can tell there isn't enough information to do this after the fact, as the browser session isn't stored. (At least, it isn't exported with the classifications in the GZ Bars project). So I suppose one option is to store the browser session itself, so that researchers who want to can reconstruct this.

The reason I'm arguing to have this done on-the-fly is that I'm hoping it's not computationally expensive to do it in small batches, and doing so avoids having to re-calculate it every time an aggregation is performed. If there was also a flag indicating that this user_id/name was retroactively associated, it would still be possible to extract the canonical version.

One thing I don't know for sure is just *how* much better this might make the user weighting. The reason this occurred to me at all is that yesterday I was spot-checking classification exports from Ouroboros sorted by IP address, and after looking at only the first ~100 classifications in a couple of project files I noticed this not-logged-in-then-logged-in pattern several times. Extrapolating that to typical user behavior is uncertain, but suggestive.

Also tagging @chrislintott @trouille @mkosmala @aliburchard @ggdhines @mschwamb as people who've reduced classification data and may want to weigh in. If I'm the only one who thinks this would be useful it's probably not worth it (though adding the browser session info may still be).

**Comment by camallen** [comment]
@vrooje just an aside the classification metadata from panoptes includes started / finished at and the user agent (this depends on the client sending this information but PFE does). Combing that with user_name / user_ip should give you a proxy to browser session.

**Comment by mkosmala** [comment]
@vrooje For Snapshot Serengeti, we didn't get as far as needing to do user weightings, though I thought about it quite a bit. I think what you suggest would be useful, but not sure that it should be done on-the-fly or if it makes more sense to have it as a post-processing step. (Though if the latter, it would be nice to have a universal script that would work on all data sets.)

@camallen Any reason for NOT including some sort of session ID (hash?) to make gluing not-used-in classifications to their logged-in owner nice and easy (in post-processing), as Brooke suggests?

**Comment by camallen** [comment]
@mkosmala - we're going to add one from the client and it's on our todo list, https://github.com/zooniverse/Panoptes/issues/866#issuecomment-129914564

**Comment by vrooje** [comment]
Cool, so project owners will have less ambiguity to deal with if they want to associate the sessions with users themselves. Thanks :+1:
