### ISSUE TITLE
Build a tool to explode JSON columns to many CSV columns

### ISSUE THREAD

**Issue by marten** [zooniverse/Panoptes#1259]
We want to have a tool that takes a CSV file with JSON-serialized columns (e.g. classification csvs) and just explodes the JSON structure. I think the way to do that is to flatten the JSON to just key-value pairs and then gather the unique set of keys across all rows, and turn that into columns. Not all rows might have the same set of keys, so the table will probably turn out to be somewhat sparse.

Some examples: 

```
{"foo": "a", "bar": "b"}

foo | bar
a   | b


{"foo": ["a", "b", "c"]}
{"foo": ["a", "c"]}

foo_0 | foo_1 | foo_2
a     | b     | c   
a     | c     |


{"foo": {"bar": "a", "baz": "b"}}

foo_bar | foo_baz
a       | 
```

Arrays of hashes are annoying, but could be done like this:

```
{"foo": [{"a": 1, "b": 2}, {"a": 0}]}
{"foo": [{"a": 0}, {"a": 1, "b": 4}]}

foo_0_a | foo_0_b | foo_1_a | foo_1_b
1       | 2       | 0       | 
0       |         | 1       | 4
```

We probably want this written in Python, and we envision this a stop-gap measure that people just run on their own if they prefer it over parsing JSON and using the actual data structures. It's okay if it's just a command line script we have to help them get running with a README, it needn't have any GUI.

**Comment by astopy** [comment]
Possibly useful links:

https://github.com/onyxfish/csvkit <https://github.com/onyxfish/csvkit>
https://github.com/evidens/json2csv <https://github.com/evidens/json2csv>
https://github.com/korczis/json2csv <https://github.com/korczis/json2csv>

**Comment by edpaget** [comment]
I wrote something similar here: https://github.com/edpaget/jcvd, but it had the advantage of all the json objects being regular instead of possibly having different structures.

**Comment by marten** [comment]
I have a really really early version of a Python package up at: https://github.com/zooniverse/panoptes-dump-reader. Ideally, I'd like it if people could just pip install it, and have a library that can load our CSVs in a sane manner if they happen to want a Pandas dataframe anyways, as well as some command line tools to convert and spit out a new CSV if they don't use Python. 

Both the pushing a pip package and bundling executables with it I've never done before, but I'm sure there are tutorials somewhere :)

**Comment by CKrawczyk** [comment]
@marten here is a useful tutorial I have used to make python packages that install via pip: https://packaging.python.org/en/latest/distributing.html

**Comment by camallen** [comment]
@marten this is nice and for a first push just getting users to clone the repo and use the scripts to get a csv file will work. 

Pinging @vrooje and @mschwamb for thoughts on how useful this is.

**Comment by vrooje** [comment]
If there's good documentation in the repo (including linking to the Python download/install page for those starting from scratch) and it does the flattening mentioned above, I think that would be very useful.

**Comment by marten** [comment]
Let's close this issue and use the other repo for discussion if something comes up.
