### ISSUE TITLE
Increasing the project data dump link access time in email from an hour to 12 or 24 hours

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes#1274]
It took over 30 minutes to create the csv file for Planet Four: Terrains. With the link only being active for an hour in email, especially as the time becomes longer to generate, I think it would help if the data link in email was open for more than hour. 

If it 1.5 hours to get the email link, the email link becomes useless because you have to be there within in an hour of receiving it to use the link in the email.  Is there any reason that access timeframe can't be extended? That would make it easier tor request a data dump and then download it at the researcher's convenience

**Comment by marten** [comment]
I'm pretty sure the hour timer only starts at the time the email is actually sent, so only once the dump is complete and ready. That said, the timeout seems to be a parameter in the code so increasing it for the dumps shouldn't be hard. Let me look at this tomorrow.

**Comment by mschwamb** [comment]
Cool. That would be great. Thanks @marten
