### ISSUE TITLE
Searching for users with just @ rack timeout

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#1296]
Getting rack timeout errors on https://panoptes.zooniverse.org/api/users?search=@&page_size=10

We should probably only look for users with a character after the @ symbol.

**Comment by edpaget** [comment]
I think this the same problem as #1230, we need to switch from trigram searches to using the normal full-text search methods.

**Comment by camallen** [comment]
I was thinking about just not running the search if the params are empty.

**Comment by edpaget** [comment]
Aren't the params non-empty though? A display name could have an '@' in it.

**Comment by camallen** [comment]
yeah sorry, i meant empty like matching just the at mention string /^@$/.

**Comment by camallen** [comment]
but this is really just a workaround to not run a long query.

**Comment by edpaget** [comment]
Ah yeah, I think we can update the index type and be set. The search point searches both logins and display_names so it should search @ in case the user was looking for someone with the display_name '@'.

**Comment by camallen** [comment]
just out of interest if I wanted to mention them it'd be @@?

**Comment by edpaget** [comment]
No you mention with the login name, which can't have a '@'.
