### ISSUE TITLE
what happens if you increase the classifiation count required for retirement on a live project?

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes#1301]
I wanted to ask before broaching the P4 science team. I'm not doing any weighting yet, but I think we might want more than 20 classifications per subject. If I bring the project back to development and increase the classification count  to 30 and the make the site back to live will that un-retire subjects that are already retired that had 20 classifications? 

Thanks.

**Comment by edpaget** [comment]
As it's currently written raising the limit will not unretire subjects.

**Comment by mschwamb** [comment]
So I'd had to use the api to unretire subjects after that step?

It seems like should be a way to do this with the project builder  because there may be times once you've got a much larger sample classified that you find you need more classifications. Should open a separate ticket for that discussion on the front end side?

**Comment by mschwamb** [comment]
PS - thanks @edpaget for the info

**Comment by aliburchard** [comment]
+1 - This has come up a few times in projects I'm working on.  We try to
overshoot in beta testing to come up with sensible limits, but needs can
change, especially if aggregation algorithms change.


On Monday, August 24, 2015, Meg Schwamb <notifications@github.com> wrote:

> So I'd had to use the api to unretire subjects after that step?
>
> It seems like should be a way to do this with the project builder because
> there may be times once you've got a much larger sample classified that you
> find you need more classifications. Should open a separate ticket for that
> discussion on the front end side?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zooniverse/Panoptes/issues/1301#issuecomment-134119421>
> .
>


-- 
Sent from my moderately intelligent phone.

**Comment by marten** [comment]
Does anyone actually depend on the current behaviour, or could we just always retrofit the retirement limit?

**Comment by edpaget** [comment]
We could allow changes to the retirement limit to unretire subjects.

**Comment by camallen** [comment]
agreed, no one depends on the way it currently works. I think we'd have to add some copy / warnings to the front end page stating something about "may result in subjects being un-retired / retired."

**Comment by mschwamb** [comment]
That would be great if it's possible to do.

**Comment by marten** [comment]
This hasn't been done, but we've made solution much more complicated now that Caesar is in the mix. I don't think we'll get to this anytime soon.
