### ISSUE TITLE
Mention syntax fails when usernames have periods

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes#1303]
User names are allowed to have periods, but the mention syntax in Talk fails to grab them.

Example with user am.zooni: https://www.zooniverse.org/#/talk/17/2275?comment=4700

**Comment by aweiksnar** [comment]
@DarrenMcRoy I'm moving this to https://github.com/zooniverse/Panoptes-Front-End/issues/1459
