### ISSUE TITLE
Divorce project-card description and landing-page text

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes#1304]
Currently, the text that you put for your project-page card is automatically the same thing that shows up as your landing-page text.

I don't love this... from a content perspective, these are two very different message cases: what you'd want to show in a list of projects, and what you'd want to say when someone arrived at your project.

Checked with @aliburchard and @vrooje and they wholeheartedly agreed. Probably lower-priority, but we seem to all think it'd be good to have these be two different fields in the project builder.

**Comment by camallen** [comment]
closing this now - feel free to reopen if people think it's important.

**Comment by vrooje** [comment]
I still think it's a good idea to do this, but not top priority, no.
