### ISSUE TITLE
Missing project preferences

### ISSUE THREAD

**Issue by parrish** [zooniverse/Panoptes#1313]
It looks like some project preferences are currently missing on the [email preferences page](https://www.zooniverse.org/#/settings/email).

This was [pointed out here](https://www.zooniverse.org/#/talk/14/114?comment=5091).  After looking into it, I realized that I'm also missing a preference for worms as well (though others may also be missing).

Is this possibly just an incomplete migration?

**Comment by camallen** [comment]
@edpaget where did we get to with the migration?

**Comment by camallen** [comment]
I think this is finished, @edpaget ?

**Comment by edpaget** [comment]
Yes
