### ISSUE TITLE
Paging is unstable for subjects in collections

### ISSUE THREAD

**Issue by edpaget** [zooniverse/Panoptes#1314]
It doesn't look like collections are being properly paged through and results are repeating over pages. 

Ref: https://github.com/zooniverse/Panoptes-Front-End/issues/1356#issuecomment-136069668

**Comment by mschwamb** [comment]
This would also be causing people to see duplicates from other collections in? I've got a new report that more than volunteer is seeing images from an older collection showing in a new collection where they didn't add those subjects in

**Comment by edpaget** [comment]
No that sounds like a different issue with something on the frontend
