### ISSUE TITLE
Panoptes hosed?

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes#1316]
Loading time for Panoptes-based projects, including the Season Spotter ones, is extremely slow. They just stall. Perhaps related to the AnnoTate launch?

**Comment by mkosmala** [comment]
Load time is on the order of 5-10 minutes for the Season Spotter projects and Wildebeest Watch.

**Comment by DarrenMcRoy** [comment]
We're aware and all hands are working on it.
