### ISSUE TITLE
Handle subject sets with very few subjects

### ISSUE THREAD

**Issue by edpaget** [zooniverse/Panoptes#1320]
Projects like AnnoTate which uses lots of subject sets with only a few subject put a ton of strain on the servers since they queue subjects constantly. We should think about handling queue sizes differently.

**Comment by camallen** [comment]
So i've been thinking we should remove the heavy data processing work from the api nodes and run these different sidekiq queues on different ec2 nodes with more cpu nodes.

**Comment by camallen** [comment]
this should have been taken care of with the queue rebuild work and the data selectors.
