### ISSUE TITLE
Some emails still not mirgrated

### ISSUE THREAD

**Issue by mrniaboc** [zooniverse/Panoptes#1326]
It looks like some of the projects still only have partial migration of emails etc. For example, Plankton Portal only has ~4,000 entries in the users table in Panopted DB, but there are more like 8,000 in the old Zoo Home DB. 

Is there any news on when all vales will be completely migrated, so we can stop using Zoo Home DB all together?

**Comment by edpaget** [comment]
Dup of #1313 I've been too busy dealing with Tate stuff to look into this since getting back.
