### ISSUE TITLE
Better login errors

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes#1342]
@marten @camallen this is the same issue that I mentioned in an email chain, just wanted to pop up here.

The gorongosa folks are having trouble logging in; they've sent this screenshot, which doesn't have any console information, but might be a starting point.

**Comment by edpaget** [comment]
@aliburchard  looks like you forgot the screen shot?

**Comment by camallen** [comment]
@edpaget check slack - it had some personal details in it.

**Comment by edpaget** [comment]
The login error was just non-intuitive I'm going to work on improving that page.
