### ISSUE TITLE
add ability for a walkthrough/training set for users new to projects

### ISSUE THREAD

**Issue by AdrianEvans** [zooniverse/Panoptes#1348]
This is something that can be found on almost all of the non-panoptes projects - at the start you're guided through an example classification. Can this type of thing be added to this system?

Huge amount of feedback since our launch of people wanting this type of help (the help files can only do so much it seems).

**Comment by camallen** [comment]
@brian-c are we thinking about adding this to the UI?

**Comment by camallen** [comment]
@AdrianEvans this is being worked on in #1414 and https://github.com/zooniverse/Panoptes-Front-End/pull/1712. Please re-open if this doesn't come online soon.
