### ISSUE TITLE
Batch creating accounts for user groups 

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes#1349]
Talked to @camallen about this a couple days ago. I'm speaking at an event in about 2 weeks, and the organizers want all of the attendees (students and teachers) to sign into wildcam gorongosa and make some classifications (we'll then query the classification data for those IDs).

The trick is that there are 200 attendees, and the organizers need to provide the attendees with pre-made accounts. Is there any way we can batch create a set of usernames (and passwords?) for this situation?

I realize that this is a recurring problem that we should solve long-term, but am also hoping there is a short term solution we can use for this event so that we don't have to create 200 accounts via the GUI.

@camallen @edpaget @marten @astopy any thoughts?

**Comment by edpaget** [comment]
Yes we should make an interface for doing this.

**Comment by camallen** [comment]
@edpaget you thinking that we support this in the front end just creating user accounts normally in a loop and storing logins, emails, etc? Or are you proposing we provide something in panoptes api for this?

**Comment by aliburchard** [comment]
@edpaget or @camallen the immediate use case is for a group that wants to generate 200 logins and hand them out next week. Would it be possible for us to do a one-off generation of names (say hhmi001, hhmi002, etc) for next week? (And then use that process to drive the longer term solution?)

**Comment by edpaget** [comment]
@aliburchard yeah we can do a one time thing (I've done it several times for kelly). I'm not sure the best way to handle doing this overall yet.

**Comment by aliburchard** [comment]
@edpaget thanks!! Okay, so they've asked for 250 logins (HHMI001 thru HHMI250). If all the passwords can be the same, they've requested a specific password (I'll pass it through slack). Could we get this done by Thursday Sept 24 so they can mail out the addresses on Friday?

**Comment by edpaget** [comment]
Yes slack me the password I'll create them later today.

**Comment by camallen** [comment]
@aliburchard did this get sorted?

**Comment by edpaget** [comment]
Yes, but the more the issue of of being able to create users more generally.

**Comment by chrislintott** [comment]
I think we shouldn’t be offering this as a front end option - at least until enough people need it that it becomes a pain. Doing it easily on the API is a good idea though.

**Comment by bruggsy** [comment]
Has this been implemented? I'd like to be able to create individual users via the API if possible.

**Comment by camallen** [comment]
Nope, it'd be closed if it was. You can create users via the api, `POST https://www.zooniverse.org/api/users` with a payload similar to what you see on the signup / register forms https://www.zooniverse.org/accounts/register

**Comment by bruggsy** [comment]
Of course, just wanted to know what's been enabled. Posting my questions to #546 since it's more relevant.
