### ISSUE TITLE
Limit number of draw tasks

### ISSUE THREAD

**Issue by rjsmethurst** [zooniverse/Panoptes#1356]
From analysing the data from the bar project which asks users to draw a line for the length and line for the width of the bar in a galaxy image we've realised there's nothing to stop people from drawing as many lines as they want. Could we put something into the Build Project tools that let's you select which drawing tool and limits how many a user can draw?

**Comment by camallen** [comment]
@rjsmethurst this is a front end question, mind trying over there? https://github.com/zooniverse/Panoptes-Front-End/

**Comment by camallen** [comment]
closing this in here. @rjsmethurst please file an issue in the front end repo.
