### ISSUE TITLE
Database architecture

### ISSUE THREAD

**Issue by parrish** [zooniverse/Panoptes#1359]
I just want to throw this out there to get some feedback.

Since Panoptes' database now contains the Zooniverse users table, all services in the Zooniverse depend on that database being accessible.

Rather than allowing performance regressions in subject selection (or other bugs) to take down the entire Zooniverse, it seems like it would probably be a good idea to split that table off from Panoptes' database.

[postgres_fdw](http://www.postgresql.org/docs/9.4/static/postgres-fdw.html) makes this separation very seamless.

Thoughts?

**Comment by edpaget** [comment]
I think this would be good idea.

**Comment by astopy** [comment]
Surprisingly that extension is actually supported by RDS, so I don’t see any reason why we can’t do that.

Another option might be to use read replicas, but postgres_fdw is probably better anyway.

**Comment by parrish** [comment]
postgres_fdw has been used by talk for a while now.

The big caveat is that you need to set `use_remote_estimate 'true'` when you create the local server to enable the query planner on the foreign server.  Also, you do need to be slightly careful about how you query the foreign table.  99% of the time it's good, by you may need to map to `user_id` and join records from that on occasion.

**Comment by chrislintott** [comment]
It feels like this would help with Stargazing-scale projects where the login traffic has a profile very different from that of classification.
