### ISSUE TITLE
Slow index routes on large tables

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#136]
RestPack uses Kaminari for pagination which counts all the rows of a table to determine the number of pages. It's a known issue of slow counts in PostgreSQL and Kaminari. I think we'll have to look at using an estimated count and submitting a PR for kaminari.

```
Started GET "/api/classifications" for 127.0.0.1 at 2014-08-05 11:31:38 +0100
Processing by Api::V1::ClassificationsController#index as JSON_API
  Classification Load (0.5ms)  SELECT  "classifications".* FROM "classifications"  LIMIT 20 OFFSET 0
   (24957.0ms)  SELECT COUNT(*) FROM "classifications"
Completed 200 OK in 25003ms (Views: 3.3ms | ActiveRecord: 24959.7ms)


Started GET "/api/classifications" for 127.0.0.1 at 2014-08-05 11:32:12 +0100
Processing by Api::V1::ClassificationsController#index as JSON_API
  Classification Load (0.7ms)  SELECT  "classifications".* FROM "classifications"  LIMIT 20 OFFSET 0
   (1362.8ms)  SELECT COUNT(*) FROM "classifications"
Completed 200 OK in 1372ms (Views: 2.7ms | ActiveRecord: 1363.5ms)


Started GET "/api/classifications" for 127.0.0.1 at 2014-08-05 11:41:00 +0100
Processing by Api::V1::ClassificationsController#index as JSON_API
  Classification Load (0.4ms)  SELECT  "classifications".* FROM "classifications"  LIMIT 20 OFFSET 0
   (1226.8ms)  SELECT COUNT(*) FROM "classifications"
Completed 200 OK in 1245ms (Views: 12.6ms | ActiveRecord: 1227.1ms)
```

**Comment by edpaget** [comment]
This is already a problem with only 250,000 some odd subjects in production. Doing `GET http://panoptes.zooniverse.org/api/subjects/` fairly consistently times out for me.

**Comment by camallen** [comment]
I was looking into this on Monday before getting sidetracked. Using rails logs and curl scripts it looked like the DB fetch times weren't the main problem (~1.1 secs) the views reported a small amount of time as well. I was pretty sure these were including count quereis so it might not be a paging related issue. Overall the first page was rendering in about 35s on my dev machine which is definately a problem.

I was about to benchmark the actual code around the controller index action to find out if it was the serializer that was causing problems (perhaps N+1 type queries there) but got sidetracked. This is on my list to tackle after the easter break but feel free to have a look if you want.

**Comment by marten** [comment]
@camallen if this is still an issue (I don't really see these pop up in NewRelic in practice) then please reopen. Spring cleaning issues right now.

**Comment by camallen** [comment]
just adding this for reference, seems kaminari allows a page without a count scope now which is a neat way around this. https://github.com/kaminari/kaminari#paginating-without-issuing-select-count-query
