### ISSUE TITLE
counters miscounting

### ISSUE THREAD

**Issue by ggdhines** [zooniverse/Panoptes#1363]
As discussed on Slack with @camallen  and @marten, there are subjects that are being retired before they have the necessary number of classifications. For wildebeest, the threshold is 15 classifications but there are several subjects that are being retired before they reach that. For example, for workflow 6 (and 6 for project_id of wildebeest), subject 493554 has 9 classifications according to SELECT workflow_id from classifications where project_id=6 and subject_ids = ARRAY[493554]. 
![panoptes_production_readonly_____panoptes_____sql_query_and_1__marten_marten-zoobook____zoo_nero__zsh_](https://cloud.githubusercontent.com/assets/6626461/9850428/71f468e6-5aea-11e5-84aa-73e286e43980.png)

The above is the result from Marten doing a different search for that same subject and finding 17 classifications.

**Comment by camallen** [comment]
@marten did you find 15 or 9?

**Comment by marten** [comment]
This subject has a single `set_member_subject`.

The `subject_workflow_counts` table has a counter saying 17 classifications.

Looking at the classifications table I find 9 rows referencing this subject in the `subject_ids` array.

**Comment by marten** [comment]
Something else that catches my eye:

The last classification made was created_at `2015-08-26 18:50:08` and updated_at `2015-08-26 20:24:32`.
The counter was updated and retired_at: `2015-08-26 19:18:47.230958`

For one, this was before the Tate/Wildcam performance issues. But there was still quite the (queue-related I presume) delay between receiving the classification and performing the count worker?

**Comment by mkosmala** [comment]
Are you sure it's the counters miscounting and not classifications being misplaced?

**Comment by marten** [comment]
Pretty sure. We found a way in which the retirement counter might be incremented multiple times for a single classification. And the timestamps of retirement match the timestamps of the last classification we have in the DB well enough; up to 30 minutes delay can be explained by queue delay much better than that we had 2 classifications spread across days and then suddenly 8 lost classifications within 30 minutes.

**Comment by mkosmala** [comment]
Well that's reassuring, at least. Good that we're not losing classifications!

**Comment by AdrianEvans** [comment]
I'm noticing this issue with fossilfinder - retirement age set at 10 - some retiring at 1, others at 14 (the vast majority are at 10 though) - I can understand the overcount but I don't understand what would cause subjects to be retired early.

**Comment by camallen** [comment]
@AdrianEvans we're possibly counting the same classification multiple times, so you may see 1 classification but we're counting that possibly over the retirement threshold.

**Comment by camallen** [comment]
we should probably recount for all launched projects like we did for GZ bars.

**Comment by camallen** [comment]
this should be fixed but we may need to recount for certain projects
