### ISSUE TITLE
User metadata

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes#1365]
Do we not get IP addresses for (logged in) users? (I'm okay with this -- just wanted to make sure I'm not overlooking it.)

And how do I interpret UTC_offset? For example, I have "25200" as a UTC_offset value. What does that mean?

**Comment by camallen** [comment]
You get an obfuscated hash of the user ip for both logged and not logged in, see [here](https://github.com/zooniverse/Panoptes/blob/master/lib/formatter/csv/classification.rb).

UTC offset should be the client time zone utc offset in seconds. It's not reliable but could give you a proxy to where the client is in the world based on their clock settings. See [here](https://github.com/zooniverse/Panoptes-Front-End/issues/468) and [here](https://github.com/zooniverse/Panoptes-Front-End/pull/584/files) for details.
