### ISSUE TITLE
is there an easy way to determine all of the workflows associated with a project?

### ISSUE THREAD

**Issue by ggdhines** [zooniverse/Panoptes#1367]
via either the api or the postgres db

Greg

**Comment by edpaget** [comment]
Yup `/api/workflows?project_id=1` via the API, or `SELECT w.* FROM workflows w INNER JOIN projects p on p.id = w.project_id WHERE p.id = 1`

**Comment by marten** [comment]
Or just SELECT * FROM workflows WHERE project_id = 1

**Comment by ggdhines** [comment]
sweet - thanks
