### ISSUE TITLE
disable counter retirement for live projects with custom retirement

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#1368]
Linked to https://github.com/zooniverse/Ancient-Lives/issues/18#issuecomment-140395139

Projects like annotate and the ancient lives rebuild will use custom retirement instead of the counter based ones. We should support counters on these live projects but provide a mechanism to disable the retirement from happening via these raw counters.

@ggdhines - re annotate is there any reason to have both custom retirement via aggregation engine and a counter retirement set to a higher number? I.e. retire from aggregation if conditions X otherwise retire from counts if they reach 15?

**Comment by ggdhines** [comment]
@camallen  - maybe as a sanity check (in case somehow a case is missed) - so maybe for beta testing. But for production use, I think we would want to rely entirely on the custom retirement

**Comment by camallen** [comment]
Sounds good - i'll add a config to disable retirement then.
