### ISSUE TITLE
Subject Create route is super Slow

### ISSUE THREAD

**Issue by edpaget** [zooniverse/Panoptes#1383]
Ping @saschaishikawa for more information, but he was trying to create subjects for the whaling project and brought down to the API each time.

**Comment by camallen** [comment]
@rogerhutchings did this on staging firing off promises as fast as he could and it just swamped the server. the solution is to rate limit per user req's server / client side.

**Comment by edpaget** [comment]
We did to one every .5second and it still swamped. Does it need to be slower?

**Comment by marten** [comment]
We really want a batch api. But some profiling to see if there's any
hotspots would also be good to do.

**Comment by edpaget** [comment]
It should already work with batch requests.

**Comment by chrissnyder** [comment]
I think there's a couple things wrong with this:

1. The fact that there exists a condition in which a user of the API can effectively DDOS us. This is more than a little terrifying. And we've already done it twice to ourselves should indicate that others are likely to cause the same problem.

2. Depending upon clients to rate-limit themselves is asking for trouble, unless we limit the subject creation routes to admins and build an internal service that we all use with built-in rate limiting, and reject any requests not using that service.

3. Documentation. Had no idea you can batch create these. Educating the group (and most importantly newcomers) on how to properly consume the API is pretty critical so we don't continually shoot ourselves in the foot.

**Comment by camallen** [comment]
Ok I think i've found the culprit on this, since #1357 moved to check limits via indexed counts on each subject upload (to avoid counter update contention) it's a problem when using the a user with large upload counts (e.g. zooniverse user) vs normal users. It should only be a problem for when uploading as a the zooniverse user till we get a fix in.

I think it's best to revert this change and figure out a way of updating this count out of band but still provide the limiting function we need. Alternative approaches appreciated..

```
#Normal user
pry(main)> Subject.unscoped.where(upload_user_id: 6).explain
  Subject Load (1477.0ms)  SELECT "subjects".* FROM "subjects" WHERE "subjects"."upload_user_id" = $1  [["upload_user_id", 6]]
=> EXPLAIN for: SELECT "subjects".* FROM "subjects" WHERE "subjects"."upload_user_id" = $1 [["upload_user_id", 6]]
                                               QUERY PLAN
--------------------------------------------------------------------------------------------------------
 Index Scan using index_subjects_on_upload_user_id on subjects  (cost=0.42..2368.36 rows=911 width=803)
   Index Cond: (upload_user_id = 6)
(2 rows)

#Zoo user
pry(main)> Subject.unscoped.where(upload_user_id: 1).explain
  Subject Load (33522.5ms)  SELECT "subjects".* FROM "subjects" WHERE "subjects"."upload_user_id" = $1  [["upload_user_id", 1]]
=> EXPLAIN for: SELECT "subjects".* FROM "subjects" WHERE "subjects"."upload_user_id" = $1 [["upload_user_id", 1]]
                            QUERY PLAN
-------------------------------------------------------------------
 Seq Scan on subjects  (cost=0.00..52140.60 rows=508290 width=803)
   Filter: (upload_user_id = 1)
(2 rows)
```

**Comment by chrissnyder** [comment]
Use a Redis counter, rather than scanning the table? Maybe have a worker that ensures the count is correct occasionally?

**Comment by camallen** [comment]
Actually - looks like this is the counter cache on set_member_subject -> subject_set. Looks like we should reopen #1347 or come up with our own redis / delayed counter solution. 

![image](https://cloud.githubusercontent.com/assets/295329/10159991/03259656-6693-11e5-989b-09d422cb569f.png)

**Comment by marten** [comment]
Just a single call per transaction though? Why would there be so much contention/deadlocking around a subject set row?

**Comment by camallen** [comment]
concurrent updates to the same set.

**Comment by marten** [comment]
Yes, but why are there many concurrent updates? There's only a few people that can update any given set. Are we DOSing ourselves by sending all images as individual requests?

**Comment by camallen** [comment]
We don't currently rate limit so if someone writes their own script to upload data and hammers the create subjects end point for the same subject set then this contention occurs. This was the reason why i removed the user -> subjects counter too. 

For reference, the [PFE code](https://github.com/zooniverse/Panoptes-Front-End/blob/eec606e276bce3897b4bfd17137e0d9f7df4bc23/app/partials/subject-uploader.cjsx#L58).

**Comment by camallen** [comment]
actually - i'm not sure why the subject set is updating. The counter cache is only for the set_member_subject..which should not be getting called on this end point.

**Comment by edpaget** [comment]
The script the scribe people have been using adds the subjects to the subject set by doing:

```json
{
    "subjects": [
        "...": "...",
        "links": {
            "subject_set": "10
        }
   ]
}

So the set_member_subject is being creating here and counter would be updated.

**Comment by edpaget** [comment]
<img width="1489" alt="screen shot 2015-09-29 at 9 42 21 am" src="https://cloud.githubusercontent.com/assets/108177/10167502/6bde7118-668e-11e5-9f20-896a4ea09e03.png">

From when this crashed us last week. Are we missing an index or something?

**Comment by camallen** [comment]
Good one, I missed the `subject -> subject_set` relation that would create the sms. Don't think we're missing an index this is just where these counters don't perform well without atomic updates.

**Comment by marten** [comment]
```
[12] pry(main)> SetMemberSubject.where(subject_set_id: ss.id).explain
  SetMemberSubject Load (326.1ms)  SELECT "set_member_subjects".* FROM "set_member_subjects" WHERE "set_member_subjects"."subject_set_id" = $1  [["subject_set_id", 3]]
=> EXPLAIN for: SELECT "set_member_subjects".* FROM "set_member_subjects" WHERE "set_member_subjects"."subject_set_id" = $1 [["subject_set_id", 3]]
                                                    QUERY PLAN
------------------------------------------------------------------------------------------------------------------
 Bitmap Heap Scan on set_member_subjects  (cost=2483.42..11704.87 rows=132516 width=48)
   Recheck Cond: (subject_set_id = 3)
   ->  Bitmap Index Scan on index_set_member_subjects_on_subject_set_id  (cost=0.00..2450.30 rows=132516 width=0)
         Index Cond: (subject_set_id = 3)
```

**Comment by camallen** [comment]
@marten suggested removing the counter and use rescheduling rate limited workers to update the subject set counters on each subject create. 

For reference for the scribe people, http://docs.panoptes.apiary.io/#reference/subject-set/subjectset this is the optimized route to bulk import subjects into a subject set.

**Comment by edpaget** [comment]
That sounds fine to me.

**Comment by edpaget** [comment]
You working on it or do you want to assign this to me?

**Comment by edpaget** [comment]
Hope that works!
