### ISSUE TITLE
priority workflow ordering not being respected

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#1386]
Subject queue updates are sorting the sms id array in asc order and losing any priority ordering from the input. 

We should respect this workflow's priority ordering when when retrieving from the queue (ignoring any internal queue order from PG array ops) [here](https://github.com/zooniverse/Panoptes/blob/f4c3e7eb4d4cea32f2b0397198b5d940ed5cdb96/lib/subject_selector.rb#L27) and when random we should suffle the ids to mitigate the pg array sort order op.

**Comment by eatyourgreens** [comment]
Bumping this one as I've run into it while generating subjects for the Wellcome Library project. Subjects for project 396, workflow 215 seem to be coming back in the order that the SMS links were created, not the order set by the priority field.

**Comment by camallen** [comment]
@eatyourgreens how pressing is this issue?

**Comment by eatyourgreens** [comment]
@camallen Fairly urgent. Wellcome would like to start beta testing next week.
