### ISSUE TITLE
Add a workflow "overall_tasks" field

### ISSUE THREAD

**Issue by brian-c** [zooniverse/Panoptes#1391]
We need a field for out-of-normal-flow workflow tasks (I've been calling them `overall_tasks`, I'm not crazy about the name) like Snapshot Serengeti's "Fire/Nothing here" checkboxes.

It's just an array of tasks. Tasks are formatted the same as the `tasks` field values.

Example here: https://github.com/zooniverse/Panoptes-Front-End/blob/d6c371535a894d47240f724d85e9474d3f1a40a4/app/classifier/mock-data.coffee#L11-L27

**Comment by edpaget** [comment]
Why can't this just be a task with an answer that ends the workflow?

**Comment by brian-c** [comment]
I think this is mostly to reproduce the Serengeti interface as closely as possible.

**Comment by aliburchard** [comment]
how about "persistent task" for a name? (Since it persists across all other tasks within a workflow?) 

I don't have a good use case for this task outside of a snapshot serengeti style filtering task though.

**Comment by edpaget** [comment]
I'm just confused why the survey task can't just auto-generate a button that behaves this way, without needing back-end support? Or have a blank option in the list survey list?

**Comment by chrislintott** [comment]
It’s mostly an elegance point - but it would be most useful for ‘and’ classifications.

e.g. If we wanted to use Galaxy Zoo to record galaxy morphology and note any asteroids that appeared, but didn’t want the main galaxy related task to include anything about asteroids we could have a ‘Asteroids?’ checkbox.

**Comment by vrooje** [comment]
This will also be very useful for humanitarian projects or any kind of project that has potentially disturbing images in it.

**Comment by edpaget** [comment]
So this field just needs to be a string field with a key for one of the tasks? I'll add it in that case.

**Comment by brian-c** [comment]
An array of objects won't work?

**Comment by edpaget** [comment]
So it's a whole separate set of tasks?

**Comment by brian-c** [comment]
Yeah, a task will either be a normal-flow task or in the special persistent list. They won't mix.

**Comment by alexbfree** [comment]
+1 to this, v useful for serengeti

**Comment by camallen** [comment]
@brian-c what's the status on this, are you doing this client side or still need api support?

**Comment by brian-c** [comment]
On hold for now, might be replaced by the combo task.

**Comment by camallen** [comment]
I'm closing for now, @brian-c re-open if/when you need api support for this.

**Comment by alexbfree** [comment]
@brian-c what is the combo task? is there anything you can link me to to find out about that?

**Comment by eatyourgreens** [comment]
@alexbfree have a look at zooniverse/Panoptes-Front-End/pull/2137 for the combo task.

**Comment by alexbfree** [comment]
Thanks Jim
