### ISSUE TITLE
Some users say Ouroboros projects' classification counts aren't updating

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes#1394]
From one user:

["None of my new non-panoptes classifications are being added to my stats or ribbon, but GZ Bars is being correctly incremented. It doesn't matter how many additional classifications I do, the total is always static."](https://www.zooniverse.org/talk/14/515/?comment=17911)

From another:

["Non of my recent classifications from GZ or SpaceWarps are showing up in my stats/ribbon."](https://www.zooniverse.org/talk/14/515/?comment=17931)

(However, mine are indeed updating, and another user added a counter: ["mine are updating (P4 & Whales) using Windows and Firefox."](https://www.zooniverse.org/talk/14/515/?comment=17927) )

Any thoughts on this? Will add if there are more reports.

**Comment by camallen** [comment]
@DarrenMcRoy can you reproduce or do your counts work?

**Comment by edpaget** [comment]
The user whose complaint is linked is definitely not having her counts increased. It works for me though, so I don't know where the failure is happening.

**Comment by camallen** [comment]
FYI, I'm working on this @DarrenMcRoy

**Comment by camallen** [comment]
@DarrenMcRoy can you chase up with the reporters and find out if the problem is still occurring?

**Comment by DarrenMcRoy** [comment]
I've posted a question in the thread. Thanks for your attention to this! :-)

**Comment by DarrenMcRoy** [comment]
Looks like this is fixed. Thanks!
