### ISSUE TITLE
Way to have classification counts and user participation counts to start when the project launches and not during beta and building

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes#1398]
I'm building a new project and we're adding in images to check the background and play with the subject presentation (since it's a combination of several images we're uploading as one). Currently when we click we can see the classification counts going up on the project front page, but this isn't going to be reflective of the actual project stats when we launch. On custom projects I've been involved in the classification database was typically zeroed out right before launch. Is there a way to mark prelaunch classifications and not count them towards the project status counters ?

**Comment by camallen** [comment]
I think https://github.com/zooniverse/Panoptes-Front-End/pull/1673 will solve this issue in the future. We currently count all classifications, pretty sure these counts will disappear as noise after launching.

**Comment by mschwamb** [comment]
It won't fix the whole issue because it won't record the annotations. We're also testing our design tree and subject design with the team and looking at the data afterwards. We'll be iterating a bunch of times arguing over image contrast and scaling between the different components. I agree eventually it will be noise, but when you add in the beta test it will take some time to become noise. 

Feel free to label as won't fix and close if you disagree.  thought it would be a back end issue and didn't look at the front end.  Looks like it something that others want the same feature  #273

**Comment by camallen** [comment]
Is it really just that you are thinking about old projects launching from scratch where we hid the beta classification work / counts and "started" with a clean slate (after lots of internal iteration)?

Happy to leave this open as a discussion. In my opinion Panoptes doesn't use this paradigm as a project evolves over time and hopefully reaches launch status. Where is the distinction to what classifications we count, perhaps only live state classifications?

**Comment by mschwamb** [comment]
well, yes, but it's not really an old way. I'm finding that bit stayed the same with the project builder, it's just that there's no telecon with the developer it's happening in the meeting with the science team and one of us is opening the project builder website. 

 At least for my two project builder projects Terrains and the one  I'm currently building that has been my experience.  The research team for my new project is debtating over whether we should have one image bigger with the reference stars smaller  whether we need four color contrast levels or just the grey scale image and then a inverted black --> white image. So the only difference I'm finding is the iteration is the same or a bit more, because we can do it quickly and make the entire team test it and check the result.

Also I still find the best way to get help examples is to run through 100s of images in the interface to find the examples. The ticket you pointed to does solve those clicks racking up since it won't record those.

I agree the paradigm has changed.  For me it would only be live state classifications after Zoonvierse approval or if it never gets zooniverse approval than just when it's live. Could make it an option for the project owner? You can zero the counter for launch or whatever you deem to be 'launch'.

**Comment by chrislintott** [comment]
I agree with Meg that we should reset counters (or be able to) before launch. 

For now we could do it by hand.

Chris

**Comment by camallen** [comment]
Currently we update the count with the results of a query not an increment and the proposed resetting and then incrementing a counter won't work properly with the database technology we use since it doesn't do atomic updates, we could switch the transaction isolation level but there may be scaling side effects. 

We could add a project setting to signal different counting strategies and possibly add in a date time field to not count before as well to give you a reset mechanism. How much do we want this feature?

**Comment by mschwamb** [comment]
The counters were an easy way for the Planet Four PI who doesn't deal with the database to report numbers to NASA or in talks. One could download the csv , so maybe not a great reason but it was really quick to look at the counters and quote the value  in a blog post or in a grant report . 

Maybe the scarier option to suggest but in some ways simpler (not sure maybe it's much harder), could the classifications database be reset/cleared like was done for old way for builds? Before a launch after the beta test and final construction  if a project owner wanted the database cleared, then it's reset and then the counters would be correct. Maybe that could be done manually and on request for now?

**Comment by aliburchard** [comment]
I agree we want counters to restart for an official launch. This is part of a bigger question of how we frame the build process - I think builders really want this "creation" stage, where they iteratively test and build (and evaluate test classifications), and then a "launch" stage where they clear the slate and are more formally in a live, public, finalized, data collection mode.

**Comment by camallen** [comment]
How about a project setting to switch between:
 1. count all classifications - the default.
 2. only count live classifications.

We could also but an embargo date time field to reset counters, i.e. don't count any before date X that would apply to both options above. I think point 2 would mostly take care of this though.

**Comment by mschwamb** [comment]
That sounds good to me.

**Comment by aliburchard** [comment]
I'm not sold on points 1 and 2 as a solution - it's trivial right now to switch between 'live' and 'development', and I put projects into live for the beta test, so those classifications would still be counted. The *real* milestone I think is a "public launch". 

I think that only works if there is also a reset button (i.e. I don't think point 2 takes care of the need to reset).

**Comment by mschwamb** [comment]
@aliburchard make option 2 launch - 'from the date/time you get Zooniverse approval'?

**Comment by aliburchard** [comment]
I think I'd be okay with that.

**Comment by camallen** [comment]
so just to clarify, if we use the launch_approved datetime setting as the reset point to count from then any changes to a live launched project will **drop** counts. Does the front end still force a user to "un-live" a project to make workflow changes? If so and if you actually do make real task changes then this will be a problem and classifications that come in between zoo team re-launching a project will not be counted too!

We really need an actual launch_date / classification_count_from field that gets set for reference and is used to ensure the counts are correct. We can do it, just need the dev time and figuring out how pressing this feature really is.

**Comment by aliburchard** [comment]
So that's a problem - the front end still forces the un-living of projects to make minor changes. Also, even when that is fixed, there will occasionally need to be changes made to a real live project that shouldn't reset the clock. (As we do on our custom projects.)

I do think it's important (but not wildly urgent) that we provide a way for projects to start the counter fresh when they a real, proper, zooniverse approved launch (with all the press, fanfare, and home-page fame).

However, for the reasons above, I don't think this can just be a query that automatically discards classifications. I think, as was discussed in https://github.com/zooniverse/Panoptes-Front-End/issues/273, that this needs to be a conscious decision made on the part of the project owner. Right now, the "launch requested" button doesn't actually launch the project, it just sends a request to Zooniverse to launch the project. Maybe alongside that "launch now" button, we could have an option to reset classifications on launch? The project owner would only select that option when they really launch the first time.

**Comment by marten** [comment]
Would there be a reason to ever have a period after launch where we're not counting? As in count between 2015-01-01 and 2015-02-04, then don't count until 2015-02-08 and then start counting again until 2015-04-27, and count again from 2015-06-01? 

Or can we assume that just "only count everything since 2015-03-02" is always sufficient?

- Marten

**Comment by aliburchard** [comment]
I think we can assume that we count everything after that initial launch. So if we tie the "real launch event" to a date, and count everything after that date, we're good.

**Comment by marten** [comment]
Cool. I'll get crackin

- Marten

**Comment by vrooje** [comment]
What about periods of inactivity in projects? If we're thinking there will eventually be Panoptes projects where we temporarily put up a message of "your clicks aren't helping science right now, so you could do X or Y instead, but schools etc go ahead and classify", would we want to count those classifications?

For reference, GZ1 had something like 2 million classifications from the date of the GZ2 launch to the day the GZ1 classification interface was actually shut down.

**Comment by aliburchard** [comment]
hmmmmmm...I think I'd still want to count those classifications...

**Comment by camallen** [comment]
I agree with Ali but we could unlive the project too, then they wont count.

**Comment by chrislintott** [comment]
I’m happy with them being counted for now if it makes life simpler

**Comment by camallen** [comment]
This has been implemented, we need to set the project launch date and run a worker to make it happen.
