### ISSUE TITLE
project_preferences tutorial_completed_at field 

### ISSUE THREAD

**Issue by brian-c** [zooniverse/Panoptes#1401]
Could we add a `tutorial_completed_at` field?

I'd like to store it as a date so we can tell the user if a tutorial has changed since they last went finished it.

Defaults to `null`.

**Comment by edpaget** [comment]
Can this be stored in the user's project_preferences?

**Comment by edpaget** [comment]
In the preferences hash?

**Comment by brian-c** [comment]
Sure, looks like I can't write arbitrary stuff there though: Error: found unpermitted parameter: tutorial_completed_at

**Comment by camallen** [comment]
We should move the preferences controller to use json schema and allow writes to the preferences json object.

**Comment by rogerhutchings** [comment]
I was hoping to write arbitrary data here too, in my case for reusing annotation grids with Old Weather
