### ISSUE TITLE
project status text field for display on the landing page.

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#1403]
Should we add a field to project contents to provide better user messaging for when a project is out of data / not active for classifications?

@mrniaboc @alexbfree ?

**Comment by mrniaboc** [comment]
Yes!

**Comment by vrooje** [comment]
+1

**Comment by alexbfree** [comment]
+1

**Comment by simoneduca** [comment]
yep, +1

**Comment by camallen** [comment]
still not enough

**Comment by aliburchard** [comment]
+100!

**Comment by camallen** [comment]
happy for pull requests on this one @aliburchard

**Comment by DarrenMcRoy** [comment]
Oh, well, yes, absolutely. Both as part of the card on the Projects page and on the landing page.

**Comment by zwolf** [comment]
This is implemented, at least on the API end.
