### ISSUE TITLE
Help with orientation to aggregation code

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes#1409]
As luck would have it, I need to do some serious aggregation stuff over the next couple weeks -- exactly when @ggdhines is gone. He set up the "aggregation" button on the project builder, but I never get any results back if I push it. So I'm diving into the https://github.com/zooniverse/aggregation/ code. There's a lot there, though, and not much top-level documentation. I'm *assuming* the code I want to look at is in the engine/ subdirectory. But I'm getting a bit lost as to the top-level code (web_api.py? job_runner.py?).

I'm sure this code is all set to pull directly from Panoptes and create the directories and files that would be sent if the aggregation button were working. I'd like to modify a copy of it run the aggregation as stand-alone code, where I download all the classifications for a project (via the project builder) and then run aggregation on my machine using those classifications. But I'm having trouble figuring out what files do what. 

Is anyone other than Greg familiar with these files? @edpaget maybe?

**Comment by edpaget** [comment]
Greg is on vacation for the next couple weeks. I am only familiar with the api and job running code I setup.

**Comment by camallen** [comment]
@mkosmala the web_api.py and job_runner.py is to link the aggregation engine to the panoptes API (and not surprisingly run the jobs). Looks like something is up with the aggregation engine not reporting errors, i'll have a look asap. 

We wanted to get this feature out asap but realized it will have bugs (unfortunately Greg is away). I'm not sure where @ggdhines got to with csv exports being an input for the aggregation engine, though it was discussed at length to do this. Also this code is setup to run on our systems with access to internal databases (postgres and cassandra) so i'm not sure how useful it will be. That said i'd start [here](https://github.com/zooniverse/aggregation/blob/46b90becbd5a7b26704835b4c7f59463bca5fecb/engine/aggregation_api.py#L196) and see if you can't shoehorn the csv data as an input and remove the dependency on postgres / cassandra.

**Comment by mkosmala** [comment]
@camallen Thanks. Yeah, looks like the main guts are in aggregation_api.py. I'm starting there. Thanks again.
