### ISSUE TITLE
Expert roles

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#1411]
I've got some stuck classification workers in the backend. Seems the collaborator role is allowed to submit expert classifications [here](https://github.com/zooniverse/Panoptes-Front-End/blob/7b519a06fd9aa798eda853142e27ff76323e0230/app/classifier/index.cjsx#L205) but the api only allows owner and expert roles specifically. 

@aliburchard, should collaborators be experts as well?

**Comment by brian-c** [comment]
Setting gold_standard is actually limited to experts just below that line: https://github.com/zooniverse/Panoptes-Front-End/blob/7b519a06fd9aa798eda853142e27ff76323e0230/app/classifier/index.cjsx#L209-L220

**Comment by camallen** [comment]
@brian-c thanks. Then i'll have to dig into why the collaborator roles are being set in gold standard mode. Any chance gold standard data was submitted without the export / owner role for testing on prod?

**Comment by aliburchard** [comment]
a bit late, but @camallen I'm fine with limiting gold_standard to just experts, as collaborators aren't necessarily experts (and they can be labeled as both if they are)

**Comment by camallen** [comment]
right - this is probably a bug then.
