### ISSUE TITLE
Please don't change project URLs without letting project teams know!

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes#1416]
Sometime recently the # has been dropped from the project URLs so that, e.g. 
https://www.zooniverse.org/#/projects/kosmala/season-spotter-questions/classify/
is now
https://www.zooniverse.org/projects/kosmala/season-spotter-questions/classify/

This breaks all the links I have from outside websites and social media (including our landing page)!

Tagging @khufkens who will also be affected...

**Comment by edpaget** [comment]
This changed over a month ago. It was being automatically redirected, but the redirect must have been broken yesterday.

**Comment by astopy** [comment]
Closing this since it's covered by zooniverse/Panoptes-Front-End#1716
