### ISSUE TITLE
Default retirement rules show as {} in workflow export

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes#1417]
In one of my projects, I've set workflows to retire at a count of 5. In the "retirement" column of the workflows export, the value is ```{"options":{"count":5},"criteria":"classification_count"}```

In my other project, I left the workflows at their default value (retire at a count of 15). The "retirement" column for these workflows is just ```{}```. 

Earlier versions of workflows in my first project also have ```{}``` listed for the "retirement" column, so my guess is that when the retirement rules haven't been changed from their default, nothing ends up in the workflows export.

**Comment by camallen** [comment]
we should export the defaults.

**Comment by aliburchard** [comment]
yes please!
