### ISSUE TITLE
Allow admins to update user resources

### ISSUE THREAD

**Issue by chrissnyder** [zooniverse/Panoptes#1419]
Specifically any of https://github.com/zooniverse/Panoptes/blob/master/app/controllers/api/v1/users_controller.rb#L12-L14

**Comment by edpaget** [comment]
You should be able to.

**Comment by chrissnyder** [comment]
Will double-check what I was doing. Was getting 422 like:

`{"errors":[{"message":"found unpermitted parameter: private_profile"}]}`

With a payload of 

`{"admin":"true","users":{"private_profile":false}}`

**Comment by edpaget** [comment]
On production? It looks like those changes haven't been deployed.

**Comment by edpaget** [comment]
See https://github.com/zooniverse/Panoptes/pull/1413

**Comment by chrissnyder** [comment]
Yea on production. I see cam's commit now, thanks.
