### ISSUE TITLE
Project stats data for owner / review

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#142]
Provide an API end point for project stats to enable a project owner / admin to review the state of a project. 

This will be a combination of Google Analytics and internal project state; Classification count, classifying users, subject counts (including state), user activity (talk?), etc.

**Comment by mkosmala** [comment]
Would *love* this.

**Comment by vrooje** [comment]
Also want to be able to get retirement limits for a better estimate of project completeness.

**Comment by marten** [comment]
Closing this: a stats-page for PFE is incoming any day now thanks to @CKrawczyk. Backend support for this is in zoo-event-stats. We've also since started serializing default retirement limits, which was what vrooje was talking about above.
