### ISSUE TITLE
Subject data dump broken for Planet Four: Terrains due to bad subject set?

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes#1420]
Not sure where this goes, I thought this might be more a backend data issue so it should go here. Please let me know if I should report this somewhere else.

I'm concerned about the subject set I was able to upload yesterday. I started getting index error and postgres errors coming through. So I'm not sure if the database is okay for that subject set. See https://github.com/zooniverse/Panoptes-Front-End/issues/1738

I did try to get a subject csv dump today, but I never got an email.  I'm not sure if the issues uploading subjects have caused a problem with the subjects data dump or if I've requested twice in a 24 hour period. I can't tell from the project builder. Could someone check on Monday for Planet Four Terains?

 if I can get a subject set csv dump in between then and now, I'll close the ticket.

**Comment by mschwamb** [comment]
I should note, I was using the project builder to upload. I wasn't doing anything that should be unsupported.

**Comment by mschwamb** [comment]
Still says 'CSV format. Processing your request.' So I think some error is being thrown. If the subject set is broken beyond repair, you can remove it  and I'll wait until I get to Oxford to upload data. I made a separate subject set for this, so it's not the one live on P4: Terrains. It's subject set 2384 'p4_terrains_manifest2'

**Comment by camallen** [comment]
I've just recreated your export, looks like you were still rate limited, I'll look into relaxing the time windows on this.
