### ISSUE TITLE
Rename to ZooniverseAPI

### ISSUE THREAD

**Issue by edpaget** [zooniverse/Panoptes#1429]
@chrissnyder and I were talking about it this today, but we really think Panoptes and Panoptes-Front-End, should be renamed to ZooniverseAPI and zooniverse.org respectively. 

I think this move would help our #hashtag #brand because it would mean when people are talking about this new thing at conferences they can say, "We have a new API and website, zooniverse.org, for building your own Zooniverse projects", instead of, "We have this new thing, Panoptes, which is ...".

**Comment by edpaget** [comment]
Also it would get rid of calling things 'Panoptes Projects' they would just be 'Zooniverse Projects', and it would remove the weird Foucault association I get every time I say the name (not sure if that's a problem for other people).

**Comment by chrissnyder** [comment]
:+1: on pretty much everything here

**Comment by vrooje** [comment]
:+1:

**Comment by camallen** [comment]
I assume you're talking about these repository names?

**Comment by astopy** [comment]
I agree. Frankly I was surprised we kept the “panoptes” name when we went live. I always thought of it as just an internal codename for development.

**Comment by aliburchard** [comment]
:+1:

**Comment by chrissnyder** [comment]
@camallen Repo names, references in code, and more generally how we talk about the platform.

**Comment by camallen** [comment]
got it

**Comment by marten** [comment]
Seems like @astopy [is using "panoptes" in AWS](https://github.com/zooniverse/infrastructure/pull/34/files#r42141124) as a more broad term for "the api and related services"? Might be useful to think about what we call the collective group of apps (ie panoptes+nero+aggregation+$thing).
