### ISSUE TITLE
Can't log in to PFE locally -- No 'Access-Control-Allow-Origin' and 404 errors

### ISSUE THREAD

**Issue by srallen** [zooniverse/Panoptes#1437]
I'm seeing errors with sign in while running PFE locally today:

`XMLHttpRequest cannot load https://www.zooniverse.org/oauth/token. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3735' is therefore not allowed access. The response had HTTP status code 404.`

`XMLHttpRequest cannot load https://www.zooniverse.org/users/sign_in/?now=1444836078740. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3735' is therefore not allowed access. The response had HTTP status code 404.`

I see the same when using `0.0.0.0` or `127.0.0.1` too.

**Comment by camallen** [comment]
yeah we don't allow access to prod from localhost. you can use the staging server or run a local one.

**Comment by srallen** [comment]
Yeah, ok, maybe something weird is going on locally for me. The other day it was authenticating with staging correctly and now with the latest PFE pulled down its trying to authenticate with production. Gonna close since this clearly isn't a back end issue --- what it's doing is correct.
