### ISSUE TITLE
Project collections

### ISSUE THREAD

**Issue by parrish** [zooniverse/Panoptes#1448]
To allow collections to be filtered by project
- [x] Add a field to collections that contains the project_ids of subjects contained by the collection.
- [x] Update the field when a subject is added to or removed from the collection.

To allow subjects to have a project context in collections
- [ ] Add a field to collections_subjects that contains the id of the project the subject was collected from.
- [ ] Use the project_id context here to update the collection's advertised project_ids. This will sync the data as it comes in /out.

To allow subjects to know what collections they belong to
- [x] Expose an API resource for collections_subjects
  - [x] Allow filtering by subject_id
  - [x] Allow sorting by created_at

**Comment by camallen** [comment]
@parrish just looking at the code
> To allow subjects to know what collections they belong to

This should already be in the api via [here](https://github.com/zooniverse/Panoptes/blob/7bd47e0197f38f10a6262b67ccfd5abfc39d397d/app/serializers/collection_serializer.rb#L4) and look like `/collections?subject_id=1`. So we just need to add a sort field in the collection serializer and supporting index. You happy to mark the last checkbox as done?

**Comment by parrish** [comment]
We could use that.  Must've missed the intent of the abstraction before.

Do you foresee any issues with performance filtering across the join like that?

**Comment by camallen** [comment]
Should be ok since it'll be hitting the join table. We've got a compound index on collection_subjects (collection_id, subject_id) but we'd probably need another on just the subject id to support this query. I'll have a look at the query explains.

**Comment by camallen** [comment]
@parrish in light of https://github.com/zooniverse/Panoptes-Front-End/pull/1939 we just need the final project tracking context of subjects in collections right? I assume the last point i solved..

**Comment by parrish** [comment]
Yep, updated!

**Comment by MvGulik** [comment]
The "_Update the field when a subject is added to or removed from the collection._" item is checked, but to me it seems to be not working.

... Considering its probably a Panoptes internal process, I leave it at that.

**Comment by camallen** [comment]
@MvGulik - can you provide some examples where ti's not tracking the project context if they param is set?

**Comment by MvGulik** [comment]
Related to Panoptes returned Json data ... "collections":"links"."projects":[<some project-id>]

This project-id list seems only be set(*checked*) when a new collection is created.
After that, the content of that projects-list never changes.
As in, no change when:
-- Adding a subject from a other project to a collection.
-- Deleting all subjects related to the current stored/used project-id from a collection.
-- Emptying out the collection.

**Comment by camallen** [comment]
Right, I get it. Yep that is the current behaviour. The plan was to allow each collected subject to retain it's project context, `Add a field to collections_subjects that contains the id of the project the subject was collected from.`...but we haven't implemented that yet.

What should we implement @MvGulik ? Track each subject's project context where it was collected? If we do that then we can add each uniq project context to the collection (for collection level filtering) and then allow project level filtering within the collection (if this is useful).

**Comment by MvGulik** [comment]
Filtering collections based on project seem very useful ... to me at least, but that more fueled by my general dislike of the fact that all Zooniverse Panoptes collections are all tossed into one big heap.
(*which kinda translates to an encyclopedia ... without a proper, or any, index. :( *)

Unrelated: Personally I'm not sure, if supporting subjects from different projects in a single collection, is actually a good thing. (*but that's probably opening a other can of code-worms.*)

**Comment by MvGulik** [comment]
> The plan was to allow each collected subject to retain it's project context, `Add a field to collections_subjects that contains the id of the project the subject was collected from`....but we haven't implemented that yet.

Aha. It took some time for that one to sink in.

>Track each subject's project context where it was collected?

As far as I can see, that seems to be the only way, yes. (*So yes*)

The alternative, to use a lookup list linking subject-id's to related projects, ... is probably not in line with Panoptes overall design (*of which I know little to nothing*).

As "[Idées noires](http://www.franquin.com/in/index_in.php)" fan, the "_subject's project context where it was collected_" is a bit disconcerting to me (*as you can pick any subject from the general Zooniverse Subjects heap*). But other than it being a nuisance to some if someone would actually do that, I can't see any critical downsides to that.
