### ISSUE TITLE
Extra quotations around everything in json format in the subject metadata in the csv dump

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes#1449]
I'm trying to parse the subject data csv in python so I can figure out what's in the site and what needs to be uploaded after some issues with my upload. I haven't parsed the files in a while but I'm having a problem using the python json package to parse the data. It looks like extra quotes have been added around everything

example:

The csv file has "{""filename"":""D13_032401_0920_XN_88S266W_0000.png""}"

but when I put that in the json to load it I get errors unless I remove one set of the double quotes:

Is this a bug or is this something I have to change when reading in the csv. It would help I think if research teams didn't have to change the format to use the python json package

>>> x=json.loads("{""filename"":""D13_032401_0920_XN_88S266W_0000.png""}")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 326, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 360, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 376, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 1 column 1 (char 1)

removing one set of the double quotes and having the outside by single quotes works. 
>>> x=json.loads('{"filename":"D13_032401_0920_XN_88S266W_0000.png"}')

Am I doing something wrong or has the data format of the output changed? Any help would be much appreciate.

**Comment by marten** [comment]
How are you parsing the Csv files themselves? Any csv field that has a comma in it needs to get quotes around the value, so that it's clear which commas terminate columns and which are part of the value. If a value then has quotes in and of themselves, the quotes in turn need to be doubled up to indicate which are the quotes wrapping the value.

A good csv parsing library should take care of all that for you, but splitting lines manually on commas won't. Hence the question: can you paste how you're parsing the csv file itself?

- Marten

**Comment by mschwamb** [comment]
import numpy as np
from numpy import genfromtxt
import json

subject_set_id=genfromtxt('subjects.csv', delimiter= ',', dtype=np.str, skip_header=1, usecols=3)
metadata=genfromtxt('subjects.csv', delimiter= ',', dtype=np.str, skip_header=1, usecols=4)
print subject_set_id[0], metadata[0]

w=(subject_set_id == '2384')

print subject_set_id[w]
#metadata=metadata[w]

for x in metadata:
        x=x[1:-1]
        print x
        uploaded=json.loads(x)
        print uploaded['filename']



code fails at json.loads() I get the quotes around the value, it's the double quotes around filename and the value for it in the json string that the python json parser doesn't like.

**Comment by marten** [comment]
I'll have a look in the morning. 

- Marten

**Comment by marten** [comment]
Looks like the issue is genfromtxt is not an actual CSV parser, it just splits on comma's, and doesn't recognize the need to do anything with string quotes.

You could use pandas:

```python
import pandas

# load up the csv
dataframe = pandas.read_csv("subjects.csv")

# limit to just rows for desired subject set
filtered = dataframe[dataframe["subject_set_id"] == 2384]

# convert metadata column into actual parsed json dicts
filtered["metadata"] = map(lambda x: json.loads(x), filtered["metadata"])

for x in filtered.values:
  print x[4]["filename"]
```

**Comment by mschwamb** [comment]
Thanks.
