### ISSUE TITLE
Don't allow projects with broken workflows to apply for review

### ISSUE THREAD

**Issue by mrniaboc** [zooniverse/Panoptes#1450]
We get a lot of people pushing the 'Apply for Review' button and when we go to look at their projects they aren't even delivering any images.

Perhaps we could also have some text appear that lets them know why they are not being allowed to push the button?

**Comment by aliburchard** [comment]
YES!! (not sure how easy this is to implement - but it sounds like a great start for the list of "health checks" we should run whenever someone applies for beta.)

**Comment by chrissnyder** [comment]
I agree with the sentiment, but not the solution. Personally, I think it's far too easy to click that button, which results in a lot of noise. I'd be for removing both review/full launch buttons from there, and creating a dedicated page with a much more extensive form for somebody to fill out before it enters the system. At that point, we can more clearly message who the review process is for, why it isn't for everyone, and generally weed out people who don't put any effort in. All without having to do anything from an API level.

**Comment by aliburchard** [comment]
I love the idea of a more formal application for beta review process (though I do also want to automate a series of "health" checks that are run upon and/or prior to beta application). I'm a big fan of the application form that projects used to submit for open Zooniverse calls -- I think it does a really good job of forcing researchers to think really critically about 1) whether they really need people to do this, 2) what information they want out a project, and 3) how they go from images into final data -- all of which are critical for making a good Zooniverse project.
