### ISSUE TITLE
Removing the play button that triggers an automatic flicker between multiple images

### ISSUE THREAD

**Issue by ezzjcw** [zooniverse/Panoptes#1452]
As discussed at yesterday's Zoominar in Oxford, I am requesting the option (checkbox) in the project builder to disable the play button for workflows in which volunteers are presented with and classify multiple images, so that they are just left with the circles for selecting each image manually. I admit that we have not yet consulted any of the Panoptes code here in Nottingham, so if anybody out there is able to expedite our request by at least pointing us in the right direction I'd be incredibly grateful! Cheers, Jess.

UPDATE: We have found the code, which are lines 62-76 here: https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/components/subject-viewer.cjsx. We have had another thought too. If it possible, it's probably preferable all round that, instead of a check box, the code searches for a column called "RemovePlay" (or something like that) in the Manifest file and bypasses the call of the play button if that column exists and the value is Y for any particular subject and there is some 'else' code that calls the play button otherwise. This might stop it affecting other projects, if you can help me with that and think it's a better option?

**Comment by marten** [comment]
I must admit that my first thought on that was "but those circles are tiny!"

Also think that maybe we need to make autoplay configurable, default to false, or perhaps the play/pause state should be sticky across subjects for a given user, rather than remove the button altogether.

- Marten

**Comment by ezzjcw** [comment]
Yes, I like your suggestions. We'd be interested in playing around with the pace of the autoplay too, if that could be configurable. Any other suggestions?! (See my update above too.)

**Comment by vrooje** [comment]
I'm confused: is this based on the assumption that subjects with multiple images will autoplay upon load? All the subjects in my projects have 2 images and they don't auto-play, so the play button is an extra for me. Is it not that way for others for some reason?

**Comment by ezzjcw** [comment]
My apologies for not being clearer, Brooke. You're absolutely right that autoplay is the wrong word to use because the user has to hit the play button first before they flick. 

Whilst I am extremely wary to ask for too much, and to confuse you even further, is there the possibility for control of the play button to be read from the Manifest file? I hesitate to ask but for some time we have been hoping to control: 1) the number of times the images flick (at the moment it is set at 3, which is fine as a default); 2) whether the button appears at all (so that it is entirely controlled by the small circles underneath, or the arrow keys on the keyboard, so that the user can stay focused on the screen); and 3) the flicking starts automatically on the page load and the user can only control it with a pause/play button.

**Comment by vrooje** [comment]
In general I think it would be interesting to play with the way the multi-image subjects are presented (e.g. making the circles more obviously connected to switching subjects, related to @marten's comment above), and we've certainly talked about some of this before (e.g. zooniverse/Panoptes-Front-End#405). Just going based on the amount of coffee the Zooniverse developers drink, however, I suspect there isn't much developer time to do this anytime soon. 

However, if you have need of this imminently for a project, and you're up for forking the code and trying out some of the changes, you could do it on a custom fork or submit a PR...

**Comment by camallen** [comment]
> 1. the number of times the images flick (at the moment it is set at 3, which is fine as a default)
2. whether the button appears at all (so that it is entirely controlled by the small circles underneath, or the arrow keys on the keyboard, so that the user can stay focused on the screen)
3. the flicking starts automatically on the page load and the user can only control it with a pause/play button.

Most of these settings would be better supported at the API level with a workflow configuration option rather than a metadata hack per subject. That is pretty easy to get in but it'd take more work getting the front end working based on these configs combined with sensible defaults.

**Comment by chrislintott** [comment]
Agreed on making this a workflow option for now.

**Comment by aliburchard** [comment]
While these different options will be nice to have eventually, this seems like a pretty low priority for front-end at the moment (given the long list of front end to-dos).

**Comment by camallen** [comment]
I'm closing this as the api now has a workflow configuration object, that the UI can store state in to modify behaviour. 

@ezzjcw you should probably open a ticket in the UI repo (https://github.com/zooniverse/Panoptes-Front-End) referencing this issue but as Ali say's it's pretty low priority for us.
