### ISSUE TITLE
Incorrect URL on apiary documentation

### ISSUE THREAD

**Issue by bruggsy** [zooniverse/Panoptes#1460]
Was using the documentation to create user groups via the API, kept getting 404 errors. Turns out the URL in the doc is 'api/groups' instead of 'api/user_groups', at least I assume because I got a real response for the latter.

**Comment by camallen** [comment]
Linked to https://github.com/zooniverse/Panoptes/commit/da8579bc0edac797c9a6ca79d2cea480c091a7dd, will get a fix in for the docs soon. @bruggsy feel free to submit PR's for the api docs when you discover mistakes.
