### ISSUE TITLE
Users with NULL email

### ISSUE THREAD

**Issue by parrish** [zooniverse/Panoptes#1470]
id:
1351050
1346916
1346529
1341967
1339109
1338316
1338281
1254840
1253836

**Comment by camallen** [comment]
these all seem to be created by ouroboros and should have been fixed by this PR, https://github.com/zooniverse/Ouroboros/commit/1f26407df40e8949de69bedb27f3c6d771613f0b.

I'll add some dummy data into these.

**Comment by parrish** [comment]
Cool, thanks!

**Comment by camallen** [comment]
Done.
