### ISSUE TITLE
SpaceWarps test site not showing correct Task

### ISSUE THREAD

**Issue by aprajita** [zooniverse/Panoptes#1477]
Hi there
Not sure if this is the best place for this query, but I am making a second demo of the SpaceWarps site on the Panoptes project builder and I've run into something strange with the first workflow I generated.

The way the SW classification is set up is that the first question is a drawing task (I deleted the original question). However, when I go to the classification web page it doesn't show my question but that the question is undefined and it doesn't show my drawing task.

Have I missed a step in defining or saving the workflow?
https://www.zooniverse.org/lab/1434/workflow/960/

I've attached screengrabs of the workflow definition and the classification page that doesn't show the workflow task.
Thanks, Aprajita.

![panopteserr2](https://cloud.githubusercontent.com/assets/1917970/11090085/dc9bfc28-8866-11e5-8f6d-840044023c35.png)

![panopteserr](https://cloud.githubusercontent.com/assets/1917970/11090047/9463966e-8866-11e5-851c-a46ebe817de0.png)

**Comment by camallen** [comment]
@aprajita it looks like the workflow changes haven't saved correctly. Any chance we could debug in person?

**Comment by aprajita** [comment]
Sure, thanks @camallen 
I can come down anytime between now and 3pm - let me know what's convenient & which office you are in. thanks.

**Comment by camallen** [comment]
Submitting changes to tasks was 401 as the Token had expired, without getting a new one before expiration. Strange as they user details still showed up on a new page load so not sure what was happening here since my sign out / sign in fixed it.
