### ISSUE TITLE
Projects need a FieldGuide resource

### ISSUE THREAD

**Issue by brian-c** [zooniverse/Panoptes#1502]
Very very similar to the Tutorial resource.

It'll contain an list of `items` (probably a JSON blob?), each with a `title` string, a `content` string, and an `icon` image source string that'll refer to a Media resource, so it needs `attached_images` too.

**Comment by camallen** [comment]
i'll get working on this tomorrow.

**Comment by camallen** [comment]
Do the items need to be ordered? Or would it make sense to have the project have many tutorial resources that have an order property?

**Comment by brian-c** [comment]
Yes, some ability to define the order is required.
