### ISSUE TITLE
Add "finished_at" to workflows and set it when retiring last subject

### ISSUE THREAD

**Issue by marten** [zooniverse/Panoptes#1506]
Currently we set them to `active: false`. Deactivating means they get hidden from view which focuses users on whatever workflows are still left to do. However, it also means we lose the information about which workflows should be visible whenever everything is completely done.

I think we should therefore set a flag that marks them as done, and add support in PFE to help focus users on workflows that still need effort, as well as adding some messaging for finished workflows ("We have enough data for this workflow, but if you still want to work on it, more data never goes amiss").

Thoughts? /cc @vrooje @camallen

**Comment by camallen** [comment]
This is exactly what happened to GZ Bars. 

PFE only selects active workflows on the project load so i think the user focus is ok in most cases. When all workflows are retired is when it gets messy. I agree we should still mark worfklows as "finished" when they have completed their data. 

Project level signalling was something @mrniaboc and I spoke about a while back and providing a project level "thanks we're finished data classification stage, now for some actual researcher work!" [ala here](https://github.com/zooniverse/Panoptes/issues/1403)

**Comment by camallen** [comment]
@marten pretty sure this is finished..?

**Comment by marten** [comment]
Yup, just forgot a separate issue existed and thus didn't tag it in the PR.
