### ISSUE TITLE
Panoptes-dump-reader

### ISSUE THREAD

**Issue by JessMead** [zooniverse/Panoptes#1510]
Hello,
I have downloaded my data exports from the zooniverse project builder website and can see that within the .CSV files there are columns where all of my data is presented. However, in this format it's not very "usable" for the kind of data analysis I want to do. I'd like to separate out the data in these single columns into multiple columns. I found this: https://github.com/zooniverse/panoptes-dump-reader on this website which sounds like it does exactly what I need it to do- " a converter that will attempt to turn the JSON structures in our dumps into (lots of) columns in CSV".
My issue is, that as someone who has never used Python before, I am struggling to get the package to work. I have done a lot of reading to try and figure it all out and also asked my IT support guy to take a quick look at it with no luck. 
I downloaded Python 3.5 onto my computer and then downloaded the Panoptes-dump-reader zip file and saved it in the Python folder on my computer. Then I opened Python and typed in "pip install zooniverse-dump" which is the first step in those instructions online and it says "SyntaxError: invalid syntax". I tried it a few times and also downloaded python 2.7.10 in case it worked on that version instead. 
Since trying that I have done a lots more research of the possible issues and tried various other things still to no avail (though I did get slightly further than in my first attempt!). The pip.exe files are in the scripts folder within my Python folder but for some reason it isn't working- I am worried I've missed a step when trying to set up Python from scratch in Windows 7. If possible what I would like either:
1. More detailed step by step instructions of how to run this package- starting with installing and setting up Python to ensure the package will work.
or
2. The name of other programs that would handle the JSON columns in the data exports better than excel.
I am no IT expert (as you can almost definitely tell!) but I have manged to build quite a nice project via the zooniverse project builder (which is much more user friendly those of us that aren't familiar with coding) and it seems a shame to fall at the last hurdle- not being able to get the data I need displayed in a usable way.
I am sorry if I am being a bit slow but I'd really appreciate any help you can give me.
Thanks for your time,
Jess Mead
PROJECT # 592
The Community Seagrass Initaitive - Seagrass Explorer

**Comment by marten** [comment]
It's quite possible you're the first person to use this on Windows. I don't think that piece of code has seen much usage yet. I'll have a look on a Windows machine over here.

That said, we're working on converting the normal exports into a format that doesn't use JSON as much. Some questions will still need it for some parts of the answer (a drawing task has a list of coordinates which is probably better left as a single column), but for the kinds of things you'd want to do in Excel it should work much better out of the box. This is probably a couple of weeks away though.

**Comment by JessMead** [comment]
Hi Marten,
Thanks for the information. The two week wait is completely fine as the project I've made isn't even live yet- I was just making sure that I could do something with the data once I had some. If the new format would mean having the answers to each question in separate columns except for the drawing tasks (because that could potentially be lots of columns!) then that would be ideal.
Look forward to seeing the new and improved data exports.
Thanks again,
Jess

[Jessica-Mead]

**Comment by marten** [comment]
For now this won't have priority, our efforts are shifting towards making sure the exports are useful and easy to work with out of the box, rather than supplying additional libraries to work with them.
