### ISSUE TITLE
Not all my collections showing in search for collections for menu to add a subject to a collection

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes#1513]
I think this is an api issue, so posting here. When I try and add to collections it's not listing my entire list of collections. New collections aren't showing on the list. 

The menu to add subjects to a collection is displaying the recent ones that I added. 

Maybe it's related to the lag time from being in Taiwan, but then I'd expect not see any search results. 
![screen shot 2015-11-26 at 7 30 16 am](https://cloud.githubusercontent.com/assets/753325/11413483/7745e932-9424-11e5-8f59-9a49dcc7530a.png)

![screen shot 2015-11-26 at 7 29 49 am](https://cloud.githubusercontent.com/assets/753325/11413501/90a9d262-9424-11e5-8d6b-e5ac42340095.png)

![screen shot 2015-11-26 at 7 29 55 am](https://cloud.githubusercontent.com/assets/753325/11413506/95b8bc6e-9424-11e5-95cf-090db857d0cc.png)

**Comment by mschwamb** [comment]
Random Mars and Mars are missing from the list. I made those out testing out that collections had be fixed a few days ago.

**Comment by camallen** [comment]
@mschwamb can you please add me as a collab on the problematic collections? I'll need access to them to debug.

**Comment by mschwamb** [comment]
https://www.zooniverse.org/collections/mschwamb/random-mars/collaborators/

https://www.zooniverse.org/collections/mschwamb/mars/

You should be a collaborator on both now

**Comment by camallen** [comment]
both show up for me when i search for them, try "mars" in the search box. I think what's happening here is a default page size of 10 on first load and you've got more than 10 so they don't show. Best to use the search filter to shrink the resulting set size so you see more relevant collections.

**Comment by mschwamb** [comment]
Thanks for checking on this.

People aren't going to remember their collection names in the classification interface,  I think. I couldn't tell you the name of my four collections.  I think the classification menu should show them so they don't have to try and remember, especially the person is active on many projection. The very advanced volunteers could have many collections for a few projects. When you scroll to the end could't that trigger the next set of 10 to show?

I think what changed for me since I don't have 10 collections is that now the favorite collections are nowshowing up on that list which wasn't a few weeks, so at least one thing that could mitigate for typical volunteers don't have to try remember since you can add an image to favorite with the heart button.

**Comment by camallen** [comment]
Ok this is a UI issue, we need to filter the fav's out of the collection list and maybe increase the page_size on the load request.

**Comment by mschwamb** [comment]
yeah I think that would be helpful. I can put in a ticket there, though the search changed recently to include the favorites recently so is that an api/backend change ?

**Comment by camallen** [comment]
The api supports search by fav tag (t/f) so it's just a matter of modifying the query params for the collection search [here](https://github.com/zooniverse/Panoptes-Front-End/blob/0bb3ac57aaa5438e9795fd776c731dcc487e44a0/app/components/collection-search.cjsx#L17).

**Comment by mschwamb** [comment]
okay. I'll link to this ticket in the front end. thanks @camallen
