### ISSUE TITLE
Incorrect project classifiers count

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#1514]
The `events_controller` api is incorrectly updating the project classifier count on all activity messages. It should only count them when the `user_project_preference` is created for the first time and thus indicating a new user for a project.

For reference, the `events_controller` is used to link legacy project activity counts to the new zooniverse api, this is the way we keep counters in sync between legacy projects and older api's.

**Comment by camallen** [comment]
Inspired by [this blog](https://medium.com/@kentcdodds/first-timers-only-78281ea47455#.f0qsx03r0) post, I've made a start on fixing this issue and written specs that can verify a solution (TDD) on this [here](https://github.com/camallen/Panoptes/commit/93f41ed318f6226b8dad7dbca4a7058690ffc4e7). 

If anyone wants to help fix this it'd be a great chance to get a PR into the panoptes api, just take my specs as a template. 

See the [How to contribute](https://github.com/zooniverse/Panoptes#contributing) section of the readme for best practices on submitting a PR.

**Comment by camallen** [comment]
@zooniverse/developers does any non-api contributor want to try their hand at this? This is an ideal way to get exposure to the API code.

**Comment by marten** [comment]
@amyrebecca Here's that issue Cam mentioned yesterday.
