### ISSUE TITLE
save data for replay when redis errors on classification save

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#1516]
Similar to when redis is unavailable we 500 on saving classifications and may lose user data if the client doesn't catch this and attempt a resubmit.

Should we rescue and push to a queue (SQS?) on failures like these?

**Comment by marten** [comment]
If we can rescue it, we can write the job args to a normal Postgresql table, and have a Sidekiq cron job that tries writing it to Sidekiq every so often (like 10 mins).

**Comment by camallen** [comment]
specific classification Redis errors to rescue on are `Redis::CommandError` & `Redis::CannotConnectError`. 

I like the idea of serializing the classification data,  we'd just recreate the controller create action via a sidetiq job. On error, push the classification object with the action type into the table. Then at an interval load each one, persist it to the db then queue via the lifecycle actions.

**Comment by marten** [comment]
Oh, I was thinking more like a wrapper around `Job.enqueue` that falls back to AR.

**Comment by camallen** [comment]
looks like i've misinterpreted what happened when redis was unavailable, looks like the classification data was saved [here](https://github.com/zooniverse/Panoptes/blob/409e0f3d8d81e9d72e658f25bfcd33a49664a796/lib/json_api_controller/creatable_resource.rb#L17) but they wouldn't have been queued for lifecycle events. 

Your wrapper around the job enqueue is what we need here.

**Comment by camallen** [comment]
closing in favour of #1517
