### ISSUE TITLE
Policy/documentation for custom (automated) uploads

### ISSUE THREAD

**Issue by astopy** [zooniverse/Panoptes#1519]
Following a brief discussion in Slack yesterday I wanted to open this issue for us to decide what our "official" process is for non-project builder uploads, and to get some documentation/guidance for developers published somewhere detailing that process.

This has already come up a few times, when people have asked me whether we can provide AWS credentials for people to upload their files (with manual steps by us required after that to actually import those images as subjects into Panoptes). This isn't exactly ideal; requiring this kind of manual processing by the Zooniverse team is exactly what Panoptes was supposed to solve in the first place.

I'm proposing that our policy should be the following:
1. [The API](http://docs.panoptes.apiary.io/#reference/subjects/subject-collection/create-a-subject) is the **only** supported way of uploading images to the Zooniverse AWS/S3 account (this obviously includes the project builder, which is essentially just an official GUI for the API). AWS credentials will not be given to non-Zooniverse team members.
2. Third parties who can't (or won't) use the API/project builder are free to host their images elsewhere and just upload the metadata to us. They could just create their own AWS account and put them on S3, or make other hosting arrangements.

This came up as a question for Glitch Zoo, which will need to upload nightly batches of images, and it will be relevant for disaster relief (and probably other projects) too. The original suggestion for Glitch Zoo was they would script an upload to our S3 account, and we'd set something up at our end to process those uploads. Instead they should script something to talk to Panoptes and then they can manage their uploads without any involvement from us.

@zooniverse/developers @zooniverse/team-zooniverse Any thoughts or objections?

**Comment by marten** [comment]
Completely agree.

**Comment by camallen** [comment]
agree, also there is nothing stopping us adding external uploads to the project builder. I started a branch to do just this a while back but never got around to finishing it.

**Comment by rogerhutchings** [comment]
Agree - it would also give me an incentive to package up the various subject upload scripts I wrote for AnnoTate if people want examples of how to script their own uploads

**Comment by srallen** [comment]
I think all of us have probably written a script to upload a batch of subjects, so a single preferred solution would be useful. There's also the [panoptes subject uploader](https://github.com/zooniverse/panoptes-subject-uploader) that could be updated and used?

**Comment by camallen** [comment]
@srallen yes! Perhaps it's something we can iterate over next week?

**Comment by srallen** [comment]
There are a couple of open PRs that I believe fix the authentication problem. Let's definitely review it next week. :+1:
