### ISSUE TITLE
Retired images being served when plenty of unretired images remain

### ISSUE THREAD

**Issue by tedcheese** [zooniverse/Panoptes#1531]
@camallen, @aliburchard 

A few users have brought up that they are seeing retired cropped images (workflow 9) in Whales as Individuals -- https://www.zooniverse.org/projects/tedcheese/whales-as-individuals/ 

See talk, from Dec 2 onward: https://www.zooniverse.org/projects/tedcheese/whales-as-individuals/talk/27/668?comment=40079&page=1

According to a subject export yesterday, the 'combined cascadia training set' this workflow applies to still has 2743 remain un-retired images out of 7388 total images.

I'll add screenshots from volunteers when possible.

Thanks ~ Ted

**Comment by tedcheese** [comment]
Here's a couple screen shots from volunteer (and moderator) elisabethb. She sent a bunch more, largely more of the same, and said, "I clicked on ten images (more or less) and all of the uncropped images were 'already seen/retired'."

![retired1](https://cloud.githubusercontent.com/assets/7146233/11574011/12d08e68-99be-11e5-94ef-cf933429ecf0.jpg)
![already seen1](https://cloud.githubusercontent.com/assets/7146233/11574014/186517ae-99be-11e5-8b6d-fd4657343ad3.jpg)

**Comment by camallen** [comment]
Hi @tedcheese, most likely the users are power users that have seen all the images. If they have seen it we won't show it to them again and they may have only not seen retired subjects. Can you get some user names / ids and i'll check.

**Comment by yshish** [comment]
@camallen I'm sorry I have to disagree with you. I didn't classify that much (less than 200) but I am one of those experiencing the issue while classifying uncropped images.

**Comment by tedcheese** [comment]
@camallen, apologies, this is workflow 84, not workflow 9. I was thinking exactly what you've said, but as of 12/2 there were still 114 images in workflow 84 that had no classifications. Users are: yshish -- but as we see from the above comment this is not the case there, elisabethb and Anitavdk.

Could it be that there's a problem with some of the subject sets? There are still > 1800 unretired images

**Comment by camallen** [comment]
I'll have a look tomorrow.

**Comment by camallen** [comment]
@tedcheese @yshish - yep there was a problem. The workflow was marked as finished as it's retired counts were off from an earlier bug with early retirements (multiple counting on incoming classifications). I've reset the counts and un-finished your workflow so data should be flowing properly again.

**Comment by yshish** [comment]
Thanks, @camallen I've just tried it and received an uncropped image to classify with no retired flag.

**Comment by camallen** [comment]
@yshish good news! Note: the issue may really be happening for power users though.

**Comment by tedcheese** [comment]
@camallen we've seen this issue now once again, with workflow [9], where there are a few unretired images yet I and others are only getting retired images served up for https://www.zooniverse.org/projects/tedcheese/whales-as-individuals/classify. I'd **really** like to complete the classification of workflow [9], since they are almost done. The suggestion above that power users have classified all images might apply to a few but I myself am only getting retired images and certainly I haven't classified all. Thanks

**Comment by aliburchard** [comment]
could this be an issue where peoples' queues are built before the images are retired, but by the time they get to an individual image, it may have already been retired?

**Comment by camallen** [comment]
same issue as here but for workflow 9 this time. https://github.com/zooniverse/Panoptes/issues/1531#issuecomment-162008097 we'll get it fixed soon.

**Comment by aliburchard** [comment]
@tedcheese looks like it's the same issue as was happening on workflow 84 above, but is now happening on workflow 9. We* should be able to get this sorted today. 

*We = our wonderful backend devs @camallen or maybe @marten -- I'm just trying to understand what's going on!

**Comment by tedcheese** [comment]
yay thanks for being on it!

**Comment by marten** [comment]
I'll pick this up tomorrow.

**Comment by marten** [comment]
@tedcheese I've reset the counts on workflow 9, could you double check that it's resolved?

**Comment by tedcheese** [comment]
Brilliant, looks good, thank you :)
