### ISSUE TITLE
Request for a metadata file describing fields in data exports

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes#1532]
Just like the title says -- new folks don't know how to read the data exports. A file explaining the different fields would be super helpful. (Maybe such a thing already exists, but I don't know where?)

**Comment by camallen** [comment]
Would resolution of the csv exploded dump export fix this issue for you? https://github.com/zooniverse/Panoptes/issues/1510#issuecomment-159312145

**Comment by mkosmala** [comment]
Not exactly. My colleague wants to understand exactly what things like 'workflow_version', 'created_at', 'started_at', and 'finished_at' mean. These latter two will be new columns in the exploded dump export. But we'll still need to know what exactly they mean! The explanation doesn't need to be long. Something like "finished_at is the time (in UTC) that a user clicked the 'Done' button" is perfect. As users of the data, we just don't want to be guessing what the columns mean from the very short column headers.

**Comment by camallen** [comment]
Any chance you want to write this up for your colleague and contribute back?

**Comment by mkosmala** [comment]
Hmmm... well, I'm not *entirely* sure I know the exact meaning of each column. For example, is 'created_at' the same as 'finished_at'? If not, what's the difference? And I don't know exactly how the 'workflow_version' gets incremented. When is the minor number incremented and when is it the major number? Maybe the way to get the best documentation is for me to have a first-round crack at it, attach questions, and have you guys flesh out the details?

**Comment by camallen** [comment]
Sounds like a plan. For starters, created_at is set on first db persistence, updated_at any db persistence after that (caveat being through the model layer and not direct sql). 

Finished at is recorded browser side (as are all metadata timestamps). Workflow version is the combination of the workflow model version (major) and the workflow_contents model (text and minor versions), so updating the wording bumps the minor but changing tasks, etc the major.

**Comment by mkosmala** [comment]
Where's a good place to upload a draft?

**Comment by camallen** [comment]
why not start a wiki doc on the repo, https://github.com/zooniverse/Panoptes/wiki?

**Comment by mkosmala** [comment]
Do you think that's a good place? Seems to me like all the Panoptes docs are really low-level and geared towards developer-types. I tried adding my file to https://github.com/zooniverse/Data-digging, which I think might make more sense, as it's more project-creator end-user oriented. (But I did a pull request, which is maybe overboard. Is there an easier way to add to a GitHub repo when the merge won't affect any other files?)

**Comment by camallen** [comment]
@mkosmala not so easy to edit that file together without a lot of back and forth. Any chance we could put it google docs or something and edit it together then put the finished version back to the above repo?

**Comment by mkosmala** [comment]
For sure. Don't know why I didn't think of that in the first place...
https://docs.google.com/document/d/1YMk6cx1pXBX5Y2PPL3cr08HkLTiNU8ldn0BaKeNRRms/edit

**Comment by camallen** [comment]
I started adding comments and working through this and seems there is outdated information. Did the export formats change or am i just confused?

**Comment by aliburchard** [comment]
Ha, I just started working on this yesterday too, combining this with what Meg wrote up. Was going to check export formats and also ping you for answers to things I didn't know -- maybe we can touch base on it after lunch or something.

**Comment by camallen** [comment]
for sure.

**Comment by chrislintott** [comment]
@aliburchard Can this be closed now?

**Comment by aliburchard** [comment]
Yes - currently docs on raw data are here: https://aliburchard.github.io/ProjectBuilderDocumentation, though I'd like to get them online and formatted somewhere more sensible. Aggregated docs are https://github.com/zooniverse/aggregation/wiki/Understanding-Aggregation-Results.
