### ISSUE TITLE
It's too hard to set up panoptes

### ISSUE THREAD

**Issue by marten** [zooniverse/Panoptes#1538]
Keeping some notes about @amyrebecca's struggles while setting up Panoptes for actual dev work instead of just docker. 

If you want to `bundle install` locally so you can run the test suite outside of Docker (easier debugging and way faster):
- mysql gem needs mysql installed locally
- can we remove zoohome connections so we can remove mysql2?
- you need postgres locally, needs to be in the readme

**Comment by amyrebecca** [comment]
Here are the additional steps I needed to follow:

1. `brew install ruby` to go from system ruby to ruby v2.2.x
1. `brew install mysql`
1. `brew install postgres`
1. `docker-machine ps` to get ip address
1. edit `config/database.yml` to change hostname
1. `gem install bundler`
1. `bundle install`
1. `rake db:setup RAILS_ENV=test`

now you can run tests with bin/rspec and, for example, a given rb file like

`bin/rspec spec/controllers/api/events_controller_spec.rb`

**Comment by amyrebecca** [comment]
Marten advises that the mysql dependency is or will soon be removed.

**Comment by marten** [comment]
mysql is gone now as per #1542

**Comment by camallen** [comment]
@alexbfree based on your work last week, can you get some doc updates ready for close this?

**Comment by zwolf** [comment]
I've created a wiki page to detail the process (minus the eternal libv8 struggle) necessary to get at least as far as running specs locally:

https://github.com/zooniverse/Panoptes/wiki/Contributing-to-Panoptes

It also uses docker for the Postgres server, which seems best given the main instructions. Feel free to add/edit or recommend changes.

**Comment by camallen** [comment]
@zwolf good stuff thanks, i think we should close this for now and maybe let new folk re-open / comment if it's still too hard.
