### ISSUE TITLE
Issues with project search

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes#1546]
To see these issues, please visit http://preview.zooniverse.org/panoptes-front-end/miniztm/?env=production#/projects , which uses the project search service for the search box on the right. This reveals a couple of issues, you will see both if you start typing `"Snapshot Serengeti"`.

### First issue: Non-public projects(?) being included
If you type `"snapsh"` you can see a project called "Snapshots at Sea" listed. I do not have access to this project so it should not be listed in search.

### Second issue: No results with first few characters
We get no results back for 1,2,3 and 4 length search strings. This produces strange behaviour in the autocomplete, where somebody might be confused by the apparent absence of results - it's not obvious that you have to keep typing the first 5 characters.

**Comment by astopy** [comment]
First issue only seems to happen if you have admin mode turned on.

**Comment by CKrawczyk** [comment]
I am seeing "Snapshots at Sea" and I don't have admin access at all.

**Comment by eatyourgreens** [comment]
Same here, and I'm not logged in at all.

**Comment by camallen** [comment]
snapshots at sea is a public project, https://www.zooniverse.org/projects/tedcheese/snapshots-at-sea, we can add more restrictive search filters to only find launch_approved, etc flagged projects.

search is something we can work on, see for some details https://github.com/zooniverse/Panoptes/issues/1230

**Comment by camallen** [comment]
closed by #1547
