### ISSUE TITLE
Longer sessions before forced logout

### ISSUE THREAD

**Issue by VVH** [zooniverse/Panoptes#1550]
A number of volunteers on transcription projects have asked whether we can increase the session time. See https://www.zooniverse.org/projects/zooniverse/shakespeares-world/talk/194/20869?comment=42965 for further discussion. 

Possible solutions: 

1. A session timer showing at the top of the page
2. A longer session (4 hours?)
3. no forced log out

**Comment by camallen** [comment]
The annotate/sw client should just set a timeout to refresh the token like the PFE client does [here](https://github.com/zooniverse/Panoptes-Front-End/blob/0f1823110594a9373dcf4082e88de970ab04f8f8/app/api/auth.coffee#L56).

**Comment by camallen** [comment]
Also we can extend the length the tokens are valid for but that increases the window that security breaches could be valid for.

**Comment by VVH** [comment]
Thanks @camallen

**Comment by camallen** [comment]
oauth implicit grant and @rogerhutchings work on the client will fix this. closing as no change in the api is needed.
