### ISSUE TITLE
Can't find existing user when adding collaborators

### ISSUE THREAD

**Issue by VVH** [zooniverse/Panoptes#1554]
Think this is a backend issue. Trying to add user jenmunroe as an expert and researcher to Shakespeare's World. There is a jmunroe but apparently that's not the right person. @camallen I know you've sorted out a few of these before and can maybe help again?

**Comment by camallen** [comment]
Got an idea on this @VVH hopefully get a solution soon. If you need this collab hooked up in the backend let me know.

**Comment by camallen** [comment]
we need to be more restrictive when searching for usernames and not do fuzzy matching in postgres. When adding collaborators we should only search on login names and match these exactly.

**Comment by mschwamb** [comment]
I have a possibly related issue I can't write a private message to  [CThomas](https://www.zooniverse.org/users/CThomas). The search doesn't come up with their username. Is this the same issue?

**Comment by camallen** [comment]
@mschwamb if the search box returns a list that has entries but none match then this is the problem. It'll be fixed by #1565 when that gets deployed.

**Comment by mschwamb** [comment]
yep that was the behavior. thanks @camallen

**Comment by camallen** [comment]
@VVH @mschwamb for reference, this is now deployed and working.
