### ISSUE TITLE
Need to be able to see which files have been uploaded to subject sets

### ISSUE THREAD

**Issue by tedcheese** [zooniverse/Panoptes#1559]
I'm trying to upload large image collections to subject sets. Problem is, uploads sometimes fail and when they do, I have no tools to know where to start again. Issues:

* I understand that zooniverse is not 'aware' of duplicate files, so I need to avoid uploading the same file twice. This means I need to:
* (1) eliminate duplicates on some of my subject sets since for sure there were some duplicates uploaded and,
* (2) know exactly which file was uploaded last to know where to start again. This is very difficult because:
* a) the display of filenames in the subject list in each subject set is not sorted, and
* b) the subject set export does not come out up-to-date

The consequence of all this is that when I have problems uploading to a subject set (like I have for example with https://www.zooniverse.org/lab/14/subject-set/2882, which for some reason topped out at 2800 subjects and would not load more), I then have to wait until the next day to pick up again. Given the scale of the project, uploading images is proving to be a significant time suck.

Apologies for confounding multiple issues but it's all under the pursuit of successful subject uploading.

:) Ted

**Comment by camallen** [comment]
Hi @tedcheese - firstly what was the problem with subject uploads? Did you network connection time out or something else? 

We do really recommend keeping uploads sets pretty small for this reason. It's easier to track smaller failed batch sizes (especially if they are to uniq subject sets). How big were your upload batches? 
> We strongly recommend uploading subjects in batches of 500 - 1,000 at a time.

You should be able to use the subject set export to resolve the state of your subjects in the system. When you state the export is out of date, i assume this is because you can only request 1 per day? We'll have to look at relaxing these export limits so you can get an up to date view of your project.

**Comment by tedcheese** [comment]
Thanks @camallen. I uploaded subjects in batches of ~200 to 800, but with multiple uploads to each subject set. I will make separate subject sets for each UL going forward.

Yes it seems that network issues contributed to the problem, since in the course of the few days of uploading I used several connections and when I had better connectivity I had less problems. But there were some odd ones along the way, for example subject-set/2882 as referred to above topped out at 2800, after which I got:

<img width="301" alt="screen shot 2015-12-19 at 6 47 19 pm" src="https://cloud.githubusercontent.com/assets/7146233/11930015/b9452040-a794-11e5-858a-d4c15619179e.png">
<img width="304" alt="screen shot 2015-12-19 at 6 56 45 pm" src="https://cloud.githubusercontent.com/assets/7146233/11930016/b9623cb6-a794-11e5-8283-6b5add6d8feb.png">

Yes, tried to use the subject set export to resolve but the 1/day limit meant I couldn't see the up-to-date file list.

Cheers,
Ted

**Comment by camallen** [comment]
So have you got this sorted from a recent export? We can look at relaxing limits for these to be more than 1 per day. 

Not much we can do with failed connectivity on the client as the client may not be able to cleanup properly (it does currently try to cleanup failed subject uploads as it goes). What kind of connection were you on?

**Comment by tedcheese** [comment]
Yes, just got a new report.There are 300 duplicates in the 2882 subject set. @aliburchard and @camallen will it cause an issue if I hard delete the entire subject set and upload anew?

**Comment by camallen** [comment]
As long as the subject set was never active for classifications. Also It'll affect your quota but we can bump that in light of this.

**Comment by tedcheese** [comment]
It tells me 'unauthorized' when I try to delete subject set 2882 I suppose because it was turned on as active, briefly, so there were some classifications. But so be it, no problem, I can upload to new subject sets the images that were in it and the ones missed in the process

**Comment by camallen** [comment]
Unauthorised sounds like you are logged out, can you try explicitly logging in and logging out again?

**Comment by tedcheese** [comment]
okay, didn't have to log out / log in, for whatever reason it let me delete the subject set this time. Thanks!
