### ISSUE TITLE
Upload issues creating new subject set

### ISSUE THREAD

**Issue by tedcheese** [zooniverse/Panoptes#1562]
I seem to be getting an error repeatedly at the same point, when I get to the 671st image uploaded to subject set 2892:

https://www.zooniverse.org/lab/14/subject-set/2892

I have run into this, oddly enough, repeatedly whether I upload 800 images at a time, or 600 in 100 image batches then another 100 etc etc.

<img width="317" alt="screen shot 2015-12-28 at 4 53 47 pm" src="https://cloud.githubusercontent.com/assets/7146233/12027977/8b5bdd86-ad84-11e5-99d6-f1d1cf81507b.png">

**Comment by camallen** [comment]
Strange, it's not subject limits (checked). I'm pretty sure this is related to local network issues but if it's always the 671st image upload then something funky could be up. 

@tedcheese any chance you can send a screenshot of the browser console / network tab when this error is happening?That XMLHttpRequest error isn't very helpful but does indicate an error.

**Comment by tedcheese** [comment]
Hmmm well it has allowed me to upload the rest of the set. Sorry, should have grabbed that browser console screenshot; will do so next time. This is the second time this issue has occurred, difference was that this time I had very good local network connectivity.

I've completed the upload and activated these new subject sets. Would you approve the project so that it's publicly visible again?

Happy new year :)

**Comment by camallen** [comment]
done re project approval. can you try and get more info the next time this happens?

I'm going to close this for now but feel free to re-open with more info.

**Comment by tedcheese** [comment]
yes definitely will find out what I can next time. Thanks
