### ISSUE TITLE
Can I please get the subject ids in this collecton

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes#1563]
Can I please get the subjects in this collection: https://www.zooniverse.org/collections/planetaryscience/chois-comet-hunters-objects-of-interest ?

Ideally to add to the todo list would be a feature in the project builder to do this query so I don't have to ask for it. I don't actually know how to get the id for it since only the ascii name is released publicly, so I don't know how to access it through the api since the api document requires the numerical id from what I could gather.  If there's a way to get that information on my how do let me know.  Thanks!

**Comment by camallen** [comment]
@mschwamb you can get the collection id and subject ids via the API

Search for the collection via something like, `https://zooniverse.org/api/collections?owner=planetaryscience&search=CHOIs`

OR if you know the URL extract it's ID from it's URL `https://zooniverse.org/api/collections?slug=planetaryscience/chois-comet-hunters-objects-of-interest`

Or if you know the collection id:
`https://zooniverse.org/api/collections/4064`

The api call result should have the subject ids listed as an array of subjects.

**Comment by mschwamb** [comment]
Thanks. I found the one for the id but not with the slug. Thanks.
