### ISSUE TITLE
workflows are not auto finishing

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#1571]
Workflow counts show the project is finished but the `finished_at` flag is not being set, most likely due to the transaction block [here](https://github.com/zooniverse/Panoptes/blob/4db3fca4e7fb9ab644826437c7ffc057fe36d241/app/workers/retirement_worker.rb#L11).

**Comment by camallen** [comment]
or the workflow hasn't reloaded and the sum count is off.

**Comment by camallen** [comment]
linked to #1745

**Comment by mschwamb** [comment]
This happened with Planet Four: Terrains again recently. I didn't remember what flag got set on the image for a retired image, and had to ask volunteers on Talk if there were starting to see an orange banner. I think better messaging would be helpful.
