### ISSUE TITLE
retirement counters dont' take into account unlinked data

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#1572]
as happened on snapshots as sea, the workflow finished and finished counts matched the subjects count but then the owner unlinked all the active sets and added new ones. This left the retired counts much larger and counting old data that wasn't currently active compared to an arbitrary number of currently linked active subjects.

**Comment by marten** [comment]
Maybe we could count active subjects, and retire/finish a workflow when that number hits 0, instead of when #retired > #total

**Comment by camallen** [comment]
i was thinking about not using a counter at all and running a query on active linked subjects / SWC's to see if any aren't retired.

**Comment by marten** [comment]
Yeah we could just do that in a rate-limited worker.

**Comment by camallen** [comment]
as long as we always use this in a worker, else you count down solution looks neat.
