### ISSUE TITLE
no already seen banners or flags coming up for classifiers on Comet Hunters

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes#1591]
Might be important for stargazing - At least one user is done with the images we have on the site, and says he's getting duplicates. It appears to be that he's not getting the banners when the data for him is complete. 

https://www.zooniverse.org/projects/mschwamb/comet-hunters/talk/211/19110?comment=55111

**Comment by camallen** [comment]
Looks like the user seens are in place and they have exhausted all the data. Are you sure they aren't seeing the banner saying reitred / already seen? Be good to track this down, as it looks like the api is returning the correct data. 

We did have a few issues over thu / fri that may have slowed the creating of the user seens tracking ids that may have led to them not seeing the banner, but i can be sure as the data has all caught up now.

@mschwamb can you find out if they are getting the banner? They may be logged out too which may cause it.

**Comment by mschwamb** [comment]
Is it both users that seen all then available data because there are 7000 subjects live. WEBs_in_space is claiming duplicates as well and see less than half the data. I can confirm because there are two talk posts in places like [this](https://www.zooniverse.org/projects/mschwamb/comet-hunters/talk/210/27107?page=1&scrollToLastComment=true)

**Comment by mschwamb** [comment]
I've also posted and waiting for a reply about the orange banner.

**Comment by camallen** [comment]
No only CThomas. WEBs_in_space has only seen 1528 subjects so should not be getting duplicates but it could have been the issue I described above (i.e. we didn't have the tracked subject ids in the db). Make sure they have refreshed the page or logged out / in again, to ensure they have a real session since if the user is unknow we just keep showing the latest non-logged in queue data.

**Comment by mschwamb** [comment]
@camallen got a reply - CThomas doesn't see any flags or notifications. So the front end appears to not be showing banners on the images when duplicates are being shown when you've completed all the data. I was clear and asked about any orange banners. He said he's seen nothing. So I don't think he's just missing or not understanding the banner, I think its not there.

**Comment by mschwamb** [comment]
@camallen also let me know if you want me to bring this up on the front end ?

**Comment by camallen** [comment]
Assuming this was related to https://github.com/zooniverse/Panoptes-Front-End/issues/2170, closing.
