### ISSUE TITLE
Move Cellect notifications to own workers

### ISSUE THREAD

**Issue by marten** [zooniverse/Panoptes#1592]
That way they can keep retrying until Cellect gets back up, while the rest of the callbacks and postprocessing happens just fine on the Panoptes side. This involves pushing seen-subjects and retirements.

**Comment by camallen** [comment]
Good idea, agree that the main workers should not be blocking on cellect. We can have a low retry limit on them too if cellect is down / busy. panoptes can just move on as the next time cellect loads it'll get the fresh data. 

I made a retire cellect worker yesterday that we can use from the retirement worker.
