### ISSUE TITLE
Can't see own classifications for a project via API when i am a tester on that project

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes#1605]
My user ID is 209
The project ID for Pulsar hunters is 764, and workflow 1224
For this project, I am a tester. I am also a general PFE admin but I have admin mode switched off.

When I type `zooAPI.type("classifications").get({"project_id":764}).then(log);` in the JS console, I get no classifications returned.

Similarly when I hit a URL such as `https://panoptes.zooniverse.org/api/classifications?project_id=764` I get zero records returned.

@camallen had a look with me, we confirmed the records were definitely in the DB, it's a scope issue affecting API queries.

**Comment by camallen** [comment]
This seems to be the classification `scope_for` method not returning data unless you're a collab / owner for the index show routes. It should really be returning the classifications that the user has contributed to the specified project.

**Comment by camallen** [comment]
closed by #1732
