### ISSUE TITLE
fix removal from queues on retire

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#1624]
Figure out a way to not update all the queues at once. Alternatively we could just leave them in there and allow them to drain naturally or we could remove from the serialized response on selection similar to how we do the current seen context.

Any thoughts on this one appreciated.

**Comment by camallen** [comment]
Check if the subject is in the queue still before issuing a dequeue. https://github.com/zooniverse/Panoptes/pull/1625#issuecomment-171463494

**Comment by parrish** [comment]
> Alternatively we could just leave them in there and allow them to drain naturally or we could remove from the serialized response on selection similar to how we do the current seen context.

I think both is a good option.  Just do a quick ruby `.select(&:active?)`.  I guess that could put you in the position of having to refill the queue mid-request though.

**Comment by camallen** [comment]
- [ ] Move to ruby land queue updates that touch the updated_at timestamp (track old queue updates)
- [ ] Avoid retire dequeue contention, just leave them in the queue and remove them when serializing or serialize with the finished context (current).
- [ ] Look at flushing / ignoring stale queue data (older than 1 day?)

**Comment by marten** [comment]
That last point, do you mean deleting queues that have not been read from for a day? That sounds like a plan.

**Comment by camallen** [comment]
I wasn't going to delete them per se but maybe just empty them. Might be an idea to remove them altogether. 

Linking #1661 & #1640 here for ref.

**Comment by camallen** [comment]
this work was done in #1676 and #1682
