### ISSUE TITLE
Cannot upload subjects through the project builder - Getting 500 server errors when trying to upload subjects

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes#1636]
I didn't have this issue Friday night, but today I am. Tried creating a new subject set. I'm below my limit for uploading subjects supposedly. I tried making a new subject set. That didn't work either. This was for Planet Four: Terrains. It says Error: 500 Internal Server Error on the upload screen

But I also tested this on a separate project builder project (id = 264) and I get the same issue. Not sure if the console helps. I saw this on the console TypeError: this.state.successfulCreates is undefined

**Comment by mschwamb** [comment]
I should note this is happening while I'm on my work wired internet

**Comment by mschwamb** [comment]
Looks like it gets through 1-2 images and then just dies with the 500 error.

**Comment by marten** [comment]
Seems like one of our web servers was misbehaving. I've restarted it and I can upload a bunch of images just fine now.

**Comment by mschwamb** [comment]
Yeah that seems to have fixed it. Thanks. Though I get other errors as I upload batches of 25 subjects at different intervals, but I can get stuff uploaded. Will open tickets for the other errors when I understand how I'm getting them.
