### ISSUE TITLE
classification exports: any way to have subject ID passed differently?

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes#1637]
In the classification export files, is there any chance of getting the subject data JSON to be like:
`{"subject_id":1234567, "retired":{[stuff]}, "owner_given_data1":"value1"...}`
instead of
`{"1234567":{"retired":{[stuff]}, "owner_given_data1":"value1"...}}`
if possible? This structure makes it more difficult (and also slower in the otherwise-very-fast framework I'm using to analyse classifications, pandas in python) to extract subject data out of the classifications, because I first have to extract the top-level key from the dict before I can access any of the data in it, and thus far the only way I've found to get to the data is to use a for loop, which is slow in python.

As an alternative I'm open to hearing about ways I can do this more quickly in pandas... but I thought I'd throw this out there. Are others having this issue too? @mkosmala @aliburchard @mschwamb @khufkens et al? I know we shouldn't change the export structure lightly, but I think it's worth discussing...

**Comment by mkosmala** [comment]
I haven't been writing code that needs speed (yet), and am all for making the data structure easier to use. Seems like ```"subject_id":1234567``` is more canonical JSON anyway. I can't think of a reason the current implementation would be more generally useful. I might have to tweak a couple scripts to accept the new format, but am happy to do so.

**Comment by khufkens** [comment]
I'm not processing bulk data yet so this is doesn't apply to me. However, a
strict JSON implementation would be favoured.

Cheers,
K

On 19 January 2016 at 17:26, Margaret Kosmala <notifications@github.com>
wrote:

> I haven't been writing code that needs speed (yet), and am all for making
> the data structure easier to use. Seems like "subject_id":1234567 is more
> canonical JSON anyway. I can't think of a reason the current implementation
> would be more generally useful. I might have to tweak a couple scripts to
> accept the new format, but am happy to do so.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zooniverse/Panoptes/issues/1637#issuecomment-172906707>
> .
>



-- 
Dr. Koen Hufkens

Harvard University
Department of Organismic & Evolutionary Biology
Richardson Lab <http://www.oeb.harvard.edu/faculty/richardson/>

@koen_hufkens - www.khufkens.com
Find the Rhythm of Tropical Trees - www.junglerhythms.org

**Comment by aliburchard** [comment]
I still haven't fully tackled the JSON obstacle, so haven't really had to deal with this yet, but would be in favor of a consistent structure.

**Comment by camallen** [comment]
The current format is valid JSON for reference 1 big object vs an array of individual objects. We can modify the exports to be an array of objects instead of the current subject id attribute data value, code [here](https://github.com/zooniverse/Panoptes/blob/b81d2dbfa423d4c9020717ff879e435ec3e29be5/lib/formatter/csv/classification.rb#L46) for ref.

Just for reference, projects may have multiple subjects per classification, I am pretty sure we only have 1 project that uses this all the others are 1 subject per classification. 

Brooke how will changing to an array of unique JSON objects be easier/faster than 1 object with each subject subject identified by the attribute key? I assume you'll still have to loop over the array? That said we can probably be smarter about the formatting (i.e. switch between array / object based on subject data).

**Comment by camallen** [comment]
Will this problem be solved by moving to a straight csv format as per #1553?

**Comment by khufkens** [comment]
csv flat files would work even better for me. In R JSON still is a jungle.

On 20 January 2016 at 11:20, Campbell Allen <notifications@github.com>
wrote:

> Will this problem be solved by moving to a straight csv format as per
> #1553 <https://github.com/zooniverse/Panoptes/pull/1553>?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zooniverse/Panoptes/issues/1637#issuecomment-173160886>
> .
>



-- 
Dr. Koen Hufkens

Harvard University
Department of Organismic & Evolutionary Biology
Richardson Lab <http://www.oeb.harvard.edu/faculty/richardson/>

@koen_hufkens - www.khufkens.com
Find the Rhythm of Tropical Trees - www.junglerhythms.org

**Comment by aliburchard** [comment]
Indeed, R doesn't have viable JSON support (even though technically you can read it in, it's pretty pointless to do). #1553 would certainly solve the issue -- but what's the timeline for implementing that?

**Comment by camallen** [comment]
@aliburchard have you checked this one out? https://cran.r-project.org/web/packages/jsonlite/index.html. Looks like it was released late last year, 2015-11-28.

**Comment by vrooje** [comment]
I think a flattened csv would definitely solve all of this - I was assuming the timeline for that was long enough for an interim solution (if it's quick) to be useful!

You're right that I still currently have to use a for loop to parse things from all the JSONs:
`classifications['meta_json'] = [json.loads(q) for q in classifications.metadata]`

but while those aren't exactly fast, the direct method that I can then use to extract individual columns as needed:
`classifications['started_at_str']  = [q['started_at']  for q in classifications.meta_json]`

is much faster than what I have to do to extract subject data, e.g.:
`classifications['subject_json'] = [json.loads(q) for q in classifications.subject_data]`
`# stringifying the key appears necessary but then adds all these extra characters`
`classifications['subject_id'] = [str(q.keys()).replace("dict_keys(['", "").replace("'])", '') for q in classifications.subject_json]`
`# separate gold-standard from regular subjects`
`classifications['subject_type'] = [get_subject_type(q) for q in classifications['subject_id subject_json'.split()].iterrows()]`

The last line is a bit different because you have to iterate through a pandas dataframe differently if you're operating on multiple columns at a time, which is needed if I have to pass the subject ID separately from the JSON; even if I can work around that I have to write a function to deal with it and all of this is much slower (in addition to being a third loop that wasn't needed with the metadata JSON extraction). 

Of course, I am perfectly willing to admit that I was writing this all fairly quickly in the pre-Stargazing buildup, so there is probably a more efficient way! But the difference in structure between the subject data and the other JSONs in the export really stood out for me.

**Comment by astopy** [comment]
I'm not sure I understand why you're turning the dict into a string. Wouldn't parsing these just be a case of doing something like:

```
# row = (a list from csv.reader.next())
subject_dict = json.loads(row[-1])
for subject_id, subject_data in subject_dict.items():
   ...
```

Or am I missing something? 

Also, as a side note if you're not already using [ujson](https://pypi.python.org/pypi/ujson) you'll probably get a big speed boost from switching to that.

**Comment by aliburchard** [comment]
@camallen yeah -  the issue is that all R-JSON packages (including the one above) convert the JSON to R objects (lists, arrays, etc) instead of actually maintaining the JSON itself. And since our JSON blobs are pretty complex, that turns into lists embedded in lists embedded in lists in R, which is just really hard to work with.

**Comment by vrooje** [comment]
@astopy I've been using pandas.read_csv() to read the classification exports, which reads the json columns as strings that I then parse via json.loads. For the end goal of my script pandas is *much* faster than other methods I've tried - actually the whole of weighting and aggregating takes about the same amount of time as parsing the various columns with these loops. I will definitely look into ujson! Thanks.

The more I think about it the more I'm certain there's a way to streamline this process - so perhaps this is more theoretical than I'd previously thought, and just comes down to a question of why the subject data is exported in a different way than the other data...

**Comment by mschwamb** [comment]
I just spoke to the Comet Hunters PI and he sends the output from the Talk output (which is in json) through an online json to csv converter and then looks at it excel. He took a look at the csv from the classifications and couldn't understand it because of the json format, and so I do think having a flattened csv would be better option for many science teams. Currently it is now my job will be to parse the classification data dump into flattened csv format.
