### ISSUE TITLE
Workflows should auto-unfinish

### ISSUE THREAD

**Issue by marten** [zooniverse/Panoptes#1639]
* Adding subjects to a subject_set should trigger a check on all associated workflows.
* Adding subject_sets to a workflow should trigger a check on that workflow.
* Checking that workflow should basically do: `if workflow.retired?; workflow.finished_at ||= Time.zone.now; else; workflow.finished_at = nil; end`

Labelling this as a bug because we're basically forgetting to invalidate caches here.

**Comment by camallen** [comment]
linked to #1384
