### ISSUE TITLE
Fetching owned projects gets a 500

### ISSUE THREAD

**Issue by brian-c** [zooniverse/Panoptes#1646]
GET `/projects?current_user_roles=owner` gives me a 500.

`/projects?current_user_roles=collaborator` returns all the right projects, and `/projects?current_user_roles=owner,collaborator` is right too.

Sorta oddly, `/projects?current_user_roles=owner,temporary_workaround` actually returns just the owned projects, so I've got this as a temporary workaround (no rush).

**Comment by camallen** [comment]
I'm able to reproduce, looking into a fix.
