### ISSUE TITLE
Projects do not return sorted

### ISSUE THREAD

**Issue by brian-c** [zooniverse/Panoptes#1647]
I expected `/projects?sort=display_name` to sort by display_name, but no dice. I coulda sworn I've done this before, do I have the syntax wrong?

Browser console one-liner: `zooAPI.type('projects').get({sort: 'display_name'}).then(ps => ps.map(p => p.display_name)).then(log)`

**Comment by camallen** [comment]
we have to activate the sort fields in the api serializers, e.g. [here](https://github.com/zooniverse/Panoptes/blob/dacb4af7250534fa7d4d6b2af103ce4c0d4c2bcc/app/serializers/project_serializer.rb#L23).

Do you want just `display_name` or other fields as well?

**Comment by brian-c** [comment]
Just `display_name`'d be great, thanks!

**Comment by amyrebecca** [comment]
This is actually in the PR that revamps the project page, it was one of the
things that we worked on at mini ztm. you probably saw it working this way
in our preview builds.

On Tue, Feb 2, 2016 at 1:11 PM, Brian Carstensen <notifications@github.com>
wrote:

> Just display_name'd be great, thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zooniverse/Panoptes/issues/1647#issuecomment-178764645>
> .
>



-- 

SPACE IS FREAKING AWESOME
