### ISSUE TITLE
Aggregation export does not appear to be working

### ISSUE THREAD

**Issue by tedcheese** [zooniverse/Panoptes#1657]
In the last two days I've thrice requested an aggregation export from Snapshots at Sea https://www.zooniverse.org/lab/14/data-exports

I've received no email notification, and when I download the aggregation, the results are from 12 January when I last did so :(

**Comment by aliburchard** [comment]
@ggdhines can we get a manual aggregation export? (And also fix this so it works?) but we need to put results up from this workflow before moving onto the next one. Thanks!

**Comment by ggdhines** [comment]
I've sent Ted the results from manually running the code. We need a way to notify people when there has been an error with their run. That said, I've checked rollbar (where I can see errors) and don't see anything in the last couple of days.

**Comment by ggdhines** [comment]
Figured out why the error message was not showing up for me. See commit d283b60.
