### ISSUE TITLE
Noticed II'm getting finished images on Fossil Finders but there's no message saying data is complete

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes#1661]
If I'm logged in and seeing finished images, shouldn't the site be putting up the gone through all the data message for the logged in user? 

<img width="1099" alt="screen shot 2016-02-10 at 8 38 57 pm" src="https://cloud.githubusercontent.com/assets/753325/12947477/911e7808-d036-11e5-9223-ee902a728774.png">

**Comment by camallen** [comment]
Looks like the non-logged in queue is getting stuck with retired data, I'm looking into it. @mschwamb was this the first time you've classified on this project or first time back in a while?

**Comment by mschwamb** [comment]
@camallen Looks like I've never gotten through a full classification on this project.  I was logged in, in case that matters.

**Comment by camallen** [comment]
Seems your queue was created a while back and had old data sitting in it. In the meantime that data was processed...

**Comment by mschwamb** [comment]
Right, I've visited a while ago and came back to check it out. Shouldn't the queue reload upon coming to the project site?

**Comment by camallen** [comment]
If there is data in the queue it just uses that. Reloading the page a few times would empty your queue, it'll only refill when you've supplied a classification, I'll be looking into some queue rebuild work in #1624. I'll take into account tracking stale queue data somehow and look at flushing / ignoring it.

**Comment by mschwamb** [comment]
@camallen Especially from newsletters, you'll get people who haven't classified in a long while, so I think this would come up in that scenario. Thanks for looking into it.

**Comment by camallen** [comment]
@mschwamb  FYI - #1676 was deployed today. I'm now working on ignoring stale queue data in #1682. I think the current deploy will help with the "already seen" but probably won't help the "finished" issue.

**Comment by mschwamb** [comment]
Thanks for the update @camallen. I can confirm that I'm seeing the same finished flag on images when I go to Fossil Finders.

**Comment by camallen** [comment]
thanks @mschwamb - looks like you've Identified a bug in the selector, see https://github.com/zooniverse/Panoptes/pull/1688

**Comment by mschwamb** [comment]
@camallen I can confirm I no longer say the retired flag
