### ISSUE TITLE
Updating OAuth apps fails with a 422 error

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/Panoptes#1664]
Updating the details of an app (`redirect_uri` in this case) POSTs to `https://panoptes.zooniverse.org/oauth/applications/{app_id}` which returns `422 Unprocessable Entity`

Here's the form data, if it helps (minus the authenticity token)
```
utf8:✓
_method:put
application[name]:Diagnosis London
application[redirect_uri]:http://localhost:3333/
https://preview.zooniverse.org/wellcome/
application[default_scope][]:user
application[default_scope][]:project
application[default_scope][]:group
application[default_scope][]:collection
application[default_scope][]:classification
application[default_scope][]:subject
application[default_scope][]:medium
commit:Submit
```

**Comment by camallen** [comment]
Looks like Doorkeeper requires secure redirects now, https://github.com/doorkeeper-gem/doorkeeper/blob/master/spec/validators/redirect_uri_validator_spec.rb. Will fix manually and look into some better form handling for this.

**Comment by eatyourgreens** [comment]
Looks like Gorongosa and Shakespeare's World have `http:` redirects too.

**Comment by camallen** [comment]
yeah - they were created before this change in the lib we use came in.

**Comment by eatyourgreens** [comment]
Ok, so we need to upgrade Wildcam and Shakespeare to `https`, including any content they load, then fix the redirect URIs.

**Comment by astopy** [comment]
I was planning to do this soon for our custom panoptes projects anyway, so I’ll move that to the top of my list.
