### ISSUE TITLE
Feature request: Adding annotation image size

### ISSUE THREAD

**Issue by khufkens** [zooniverse/Panoptes#1670]
Would it be possible to put the image size of the image on which the annotations were made into the classification metadata somewhere?

The currrent python notation for coordinates is python / matlab style (image coordinates 0/0 start top left). However, the raster library in R uses standard Cartesian coordinates (0/0 bottom left). This can be a huge source of confusion - or error if one does not plot the data to visually check annotations!

Having the dimensions of the original image would allow for flipping the axis and plotting the annotations within R, without querying the image size first (overhead).

**Comment by camallen** [comment]
@brian-c didn't we have this info coming into the classification a while back?

**Comment by brian-c** [comment]
Wow, yep, but it looks like it got totally screwed up at some point. I'll look into this.

<img width="326" alt="screen shot 2016-02-15 at 11 25 01 am" src="https://cloud.githubusercontent.com/assets/464389/13055766/d037109c-d3d6-11e5-9ba6-0b4f18c97e85.png">

**Comment by camallen** [comment]
great, thanks

**Comment by khufkens** [comment]
Thanks, it would be really helpful to have it in there in some accessible way.
