### ISSUE TITLE
Adding X-Frame-Options headers to permitted URLs in Doorkeeper

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/Panoptes#1673]
Canthe Panoptes OAuth sign in pages have `X-Frame-Options` headers set to `ALLOW-FROM` for authorised URLs?

Use case: I'm working on an OAuth module for [panoptes-javascript-client](https://github.com/zooniverse/panoptes-javascript-client) which refreshes the bearer token via an iFrame before it expires. The benefit is that it doesn't require subsequent page redirects once a user has initially authenticated, so no lost state / interrupted work.

Due to the Same Origin Policy, however, the content of the iFrame can't actually be loaded unless it's permitted via the X-Frame-Options. That means that I can't get the access token and other credentials passed back via the iFrame's URL.

I've checked with @marten and he doesn't think it's too mad, and it would make authentication in custom projects a lot more slick.

**Comment by camallen** [comment]
We've done similar things in the past, check [here](https://github.com/zooniverse/Panoptes/blob/9678d8a3ccb3d607340add6af9361993698cca0f/config/cors_config.yml.hudson#L4). We need to update the prod configs and the .hudson config for panoptes dev versions.

**Comment by camallen** [comment]
@rogerhutchings have you tried this in a popup instead of an i-frame?

**Comment by rogerhutchings** [comment]
No - I figured a hidden iFrame would be less disruptive for users than a popup that suddenly appears / disappears every time you need to refresh a token. Also, I can imagine people getting freaked out by this kind of non-standard behaviour as well ("Have I been hacked?")

**Comment by camallen** [comment]
What if the original auth window was a popup based one? Pretty sure this exists for other oauth setups.

**Comment by eatyourgreens** [comment]
Pretty much every browser now blocks popups unless they're initiated by a user action, so people would have to click on a button or something to refresh their token, I think.

**Comment by camallen** [comment]
thanks @eatyourgreens good call.

**Comment by eatyourgreens** [comment]
Can we expire the token based on when it was last used, rather than when it was issued, or is that a security issue?

I'm thinking of sites like my bank, which displays a message saying "You've been inactive for x minutes. You'll be automatically logged out unless you click this button to continue."

**Comment by camallen** [comment]
we could but we'd have to implement that, default implementation from the lib we're using is expires_in and created_at so not tracking the last use access.

**Comment by eatyourgreens** [comment]
No problem, maybe we just show a dialog in a div that says "Hey, you've been on our site for 2 hours, time for a break?" :)

**Comment by camallen** [comment]
we're going to try the x-frame-options header for whitelisted sites..this should allow the access_token to be renewed without interrupting the user after the time period.

**Comment by rogerhutchings** [comment]
You don't actually get passed back `created_at` as part of the query params, I've been faking it with `Date.now()` but it's probably not very accurate

**Comment by camallen** [comment]
Closing this as it wasn't needed for the solution. Freel free to re-open if we need it again.

**Comment by brian-c** [comment]
Sorry, what's the solution? I don't think zooniverse/panoptes-javascript-client#24 will work without having access to the iframe across domains.

**Comment by camallen** [comment]
If the user has a valid panoptes session then the redirect works fine, if not then it errors with a SAME_ORIGIN error due to the X-FRAME-OPTIONS response value. @rogerhutchings is double checking browsers and on prod env.

**Comment by camallen** [comment]
@rogerhutchings can you confirm what you found with this today?

**Comment by rogerhutchings** [comment]
Yup - having SAMEORIGIN set doesn't stop this from working, as a successful redirect _doesn't actually render anything_ - it just bumps you back to the original domain, which of course has permission to run in an iFrame, hence no errors.

 If we get an `X-Frame-Options` error, that's interpreted as not having a session, so we ignore it and accept that the user isn't logged in.
