### ISSUE TITLE
User getting annoyed by many "already seen" and "finished" banners

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes#1677]
This is really just a follow on to #1640, but it seems like it is not an occasional problem, at least for some users, but rather a common one.
https://www.zooniverse.org/projects/kosmala/season-spotter-questions/talk/62/39930

**Comment by camallen** [comment]
It's high on our list @mkosmala see #1676

**Comment by mkosmala** [comment]
Super!

**Comment by camallen** [comment]
closing this in favour of #1640
