### ISSUE TITLE
Subject from other project showing on Shakespeare's World Talk

### ISSUE THREAD

**Issue by VVH** [zooniverse/Panoptes#1680]
This subject has popped up a while ago (mid-December) and seems to be from another project entirely. Maybe it's because the subject name is the same as something in our subject set? The metadata fields otherwise have nothing in common with our subject metadata. I wonder if this something we need to look into though. If subjects have the same name in different projects, can the API accidentally serve subjects from another project?

https://www.zooniverse.org/projects/zooniverse/shakespeares-world/talk/192/21111

**Comment by mschwamb** [comment]
@VVH The thread from this is on the front end. It was fixed and then cropped up again when I saw your posts on Planet Four: Terrains Talk  https://github.com/zooniverse/Panoptes-Front-End/issues/2210

**Comment by camallen** [comment]
@parrish can you have a look at this, might have been related to this https://github.com/zooniverse/Panoptes-Front-End/issues/2210 but i'm not sure how.

**Comment by marten** [comment]
Note: On the Panoptes side this is definitely just in Planet Four's sets.

**Comment by parrish** [comment]
We previously had an issue with the front end routing breaking some of the app.  I'm pretty sure this is just a side-effect from before that was fixed -- the comment was created in December.
