### ISSUE TITLE
mime type/content-disposition for data exports

### ISSUE THREAD

**Issue by astopy** [zooniverse/Panoptes#1694]
Safari (and presumably other browsers) displays data export files inline by default rather than saving them. We should set the appropriate metadata on S3 to stop it doing that. Also may as well set a more useful filename while we're doing that.

Since we're already using signed URLs we can just set the headers in the GET request. See the request parameters section here: http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectGET.html We'll just want to set content-disposition to something like `Content-Disposition: attachment; filename=projectname-classifications.csv`

**Comment by mschwamb** [comment]
a more intuitive filename would be great

**Comment by camallen** [comment]
agree with this completely.
