### ISSUE TITLE
Urgent: Empty workflows throwing errors

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes#1701]
I am "pausing" all but one workflow in Season Spotter Questions for a volunteer recruitment campaign we are launching on Monday. We need to run a single workflow ("2-1_SimpleDoubleDeciduousSpring"). If I unlink all subject sets from the non-target workflows and then try to classify images, I get errors stating that the workflow has no attached subject sets. If I hook up subject sets that have zero subjects to all non-target workflows, I get errors saying "Error: No data available for selection." I need to be able to have inactive workflows. This was a problem many many months ago when we launched Season Spotter, but I thought it had been resolved. How do we make this work without deleting the workflows (which I'll need again after the campaign)? @camallen @aliburchard

**Comment by camallen** [comment]
@mkosmala Those error messages are expected. There is no need to unlink the subject sets, instead you have to set each workflow to `active=false' via the api [here](https://github.com/zooniverse/Panoptes/blob/59c2e6b640c98e15bd6f609d1136872e0bbd22c5/app/schemas/workflow_update_schema.rb#L21). PM @aliburchard or myself if you need more help. Non active workflows will not be available via the homepage / classify interface.
