### ISSUE TITLE
If-Match header error when updating Workflow

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes#1702]
This might just be a documentation issue, but I'm following the Apiary instructions to update a workflow to turn "active" to false. When I PUT to Panoptes, I get the error `Request requires If-Match header to be present`. I don't know what this means. 

Python code here:

    wfcontents = get_workflow_contents(wfid,token)
    # wfcontents looks good

    # substitue false for true in "active"
    wfcontents.replace("\"active\": true","\"active\": false")

    head = {'Content-Type':'application/json',
            'Accept':'application/vnd.api+json; version=1',
            'Authorization':'Bearer '+token}

    response = requests.put(hostapi+'workflows/'+str(wfid),
                             headers=head,data=wfcontents)

**Comment by camallen** [comment]
You need to provide the etag of the original request as per [here](http://docs.panoptes.apiary.io/#introduction/headers). This etag specifies the content / version of the resource and is used to stop stale updates from happening.

**Comment by mkosmala** [comment]
I'm confused. What is the 'original request'? Where do I find the etag that I need?

**Comment by camallen** [comment]
The ETAG is a response header from a GET on the requested workflow.  I.e. get the resource, save the etag, modify the resource, PUT new copy -> server checks etag hasn't changed (not stale update) and voila, updates!

**Comment by mkosmala** [comment]
Got it.
