### ISSUE TITLE
abiity to select a subject set to become live next if the current ones live are finished

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes#1707]
A feature request - Right now you can have more than one subject set live at the same time, but you can't specify any priority. Since there are no priorities in how frequently a given subject set would show, it would be nice to be able to finish up a subject set and have the panoptes automatically switch to another subject set. 

Here's the use case I'm thinking of: projects where you need to complete the data for a region of interest and need that complete that for a paper you need. If you put in the new data so the site doesn't shut down, then it will take longer for those final subjects in the subject set you want to completed to get classifications.

I'm in the situation for Planet Four: Terrains now. We're thinking of writing a paper with the current data in, but we need 7000 classifications to finish that subset set, it would be nice to upload the new data and have the site switch rather than having to keep checking if the all out of data message is on the site to switch

I would see this is a separate check box (go to next)  in the front end in the work flow editor

**Comment by camallen** [comment]
This is a good idea, basically a staging area for data sets to go "live" once the workflow finishes.

**Comment by aliburchard** [comment]
I love this idea!! On the front end it would need some checkboxes (@brian-c I assume this is pretty straightforward), but @camallen what would this need on the back end?

**Comment by camallen** [comment]
A subejct_set_id queue on the workflow that has next in line set ids to activate. Then some login around finishing the workflow to activate the next data (if it exists) until all is exhausted, then mark as finished.

**Comment by marten** [comment]
Isn't this what a grouped workflow does?

**Comment by camallen** [comment]
not quiet. Grouping allow specific selection from subject_sets. This would basically "refill" the active sets of data from a defined list client side.

**Comment by marten** [comment]
I'm working on something that would solve this issue. We've got a new subject selector that can prioritise between live sets. It would basically mean that we'd select from set A with 99% probability, from B with 0.9% probability, and from C with 0.009% probability. 

While this doesn't fully guarantee *all* effort goes into set A first, it's probably good enough. It also means that it's per user: a power user can have classified all of set A, and therefore pull from B (mostly) automatically, even before all of A is retired.

Reason for this probability based approach is that we're using the same code for gold standard sets, to give people a high chance of hitting gold standard images with some feedback.

**Comment by mschwamb** [comment]
One thing to note is that quantity of classifications the volunteer has done and quality are two different things. The most of my top classifiers on all my past and on-going projects, don't tend to be the best classifiers. I have a few exceptions, but for example the top classifier on Old Planet Hunters marked everything as transit but shouldn't have.  

So I'm not sure it's the best idea to do trigger showing of the next data set  if a single user or two have completed all the available data. Maybe if there's a majority of people not seeing data then having the site switch to a backup dataset would be more useful?

**Comment by camallen** [comment]
@mschwamb this would only activate the new subject set for a user that has finished the previous ones. It would not be activated for all users.

**Comment by mschwamb** [comment]
@camallen right, I get that. I'm wondering if it's not helpful to have those 2 most frequent classifiers now able to classify the next dataset when they're not actually helping the assessment. Whereas if they have to wait until there are many more classifiers (some who are doing the task correct), than more of the new subject set gets useful assessments. Most of the top classifiers in terms of numbers are not necessarily doing the task correctly. Because like on Planet Hunters and Planet Four, the person who has classified the most is not actually engaging in the task correctly so by letting this person continue to classify onto the next set, I've effectively lost a classification and if the next person that finishes than they may be the same and now I've lost two classifications. Whereas if you release the next subject set when there are more people who are in need of subjects, then there is a bit more balance/distribution of effort in the dataset.

**Comment by mschwamb** [comment]
Maybe it turns out to be exactly equivalent with this method to having twice the data live in terms of distribution of effort and my slight worry is unfounded, but I'm not sure.

**Comment by camallen** [comment]
I can see the concern, I'm not sure how you want us to mitigate power users like this though (current vs new systems)?

**Comment by mschwamb** [comment]
The only thing would be that I wouldn't automatically  activate a new subject set if only one or a small handful of classifiers are in need of it so that at least there's a balance in the subject set between regular classifiers and power users.

**Comment by camallen** [comment]
@mschwamb i'm pretty sure what @marten is working on will only use the current linked data sets. It will still be up to the owner to set the "live" set of data.
