### ISSUE TITLE
Planet Four: Terrains says its out of data, but it's not (it's close but there are subjects in need of clicks)

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes#1709]
Planet Four: Terrains currently say it's out of data, but the subject data dump has subjects that are live and not retired yet
some examples:

1510488
1510597
1510640
1515833
1515840
1515847
1515850

also 1510718  has only 16 classifications and we retire at 20, and I haven't classified it, so my account (mschwamb) should be able to classify that one. Instead I'm only seeing retired images and can not get these subjects to their full 20 clicks to retire.

**Comment by mschwamb** [comment]
@camallen I presume this is a backend issue? Please let me know if it belongs on the front end. Thanks.

**Comment by camallen** [comment]
Yep - most likely some out of sync counters, i'm investigating.

**Comment by camallen** [comment]
Should be all fixed. I've also reset the counters based on project launch date. This was caused by some count problems we had when first launched. There is some scheduled work on this topic too.

**Comment by mschwamb** [comment]
Thanks @camallen for the rapid response and for sorting the issue
