### ISSUE TITLE
Allow all users to fetch their classifications for a subject.

### ISSUE THREAD

**Issue by csalexwilliams** [zooniverse/Panoptes#1713]
This issue is in reference to the following API call:
http://docs.panoptes.apiary.io/#reference/classification/classification-collection/list-all-classifications

The use-case for this issue is driven by a key feature in Ancient Lives, which is temporarily available here: https://preview.zooniverse.org/ancientlives/. The exact use-case is a user returning to an image of a papyrus fragment to continue / update their transcription.

In the current implementation, only users in administrative roles for a project (e.g., collaborator) can fetch classifications via the API. If a user is logged in, the user should have the privilege of fetching the data that they have contributed for the subject.

The API's response is empty for a user that has no administrative affiliation with the project. The response should, however, be populated with their past classifications.

A secondary issue is returning *only* the most recent classification, but that is another matter. I have front-end code that identifies the most recent classification currently, but future projects may benefit from the ease of retrieving the most recent.

Spoke with @camallen about this earlier today.

**Comment by camallen** [comment]
thanks for catching this @csalexwilliams - i'll get working on this soon.
