### ISSUE TITLE
having a whitelist of vetted project owners and scientists for subject upload?

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes#1716]
I asked for my subject limit to be raised again today so I could upload the next set of Planet Four: Terrains images. I've had my limit already upped 2 or 3 times in less than a year because I'm the main person uploading for P4: Terrains, and I had to upload the first batch of  Comet Hunters for launch. 

Out of a conversation with @camallen, the idea came about of instead of always having to get approval for certain trusted project owners and scientists, should there be a white list that if  the account was approved then it could upload without restrictions on the amount of subjects. 

If there is a white list, maybe it would be worth having some thresholds to trigger sending an email to the Zooniverse team list if someone on the white list uploads an anomalous amount that someone can check their account wasn't hacked and uploading porn or something else that shouldn't be uploaded.

Thoughts @chrislintott & @aliburchard

**Comment by srallen** [comment]
:+1: This came up with regard to Gravity Spy since they have a nightly batched upload.
