### ISSUE TITLE
allowing search on displayname

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes#1719]
one of the moderators was trying to message me on pantopes and  couldn't find me because they were trying to search for 'meg' and my username is mschwamb and my display name is 'Meg Schwamb' - The search used to allow the ability to search on display name. Is there a specific reason this changed? If it's too much on the backend, could there instead be a check box to mention if you're searching by username or display name?

**Comment by aliburchard** [comment]
Searching for users is known to be buggy, but I'm not actually sure what's in the works in terms of fixes. (It could be that searching by display name got lost while trying to fix other search functionality?) But agreed that this is important...

**Comment by camallen** [comment]
we removed this a while back since it was buggy and tying up resources. @mschwamb any reason why the mod didn't just ask for your username / look it up on talk, etc? I mean it's in the url of the project too...

**Comment by mschwamb** [comment]
most people use the redirect http://terrains.planetfour.org so I wouldn't expect them to realize my username is in there. He would have to find a conversation I'm in. Not that hard, though he had an open conversation so he messaged me in that.

**Comment by camallen** [comment]
@mschwamb I'm not going to fix this currently as I think better internal communication would have alleviated this. 

If you feel strongly about this / it is affecting a lot of people we should re-open.

**Comment by mschwamb** [comment]
Originally put this in the wrong thread... (sorry) I don't have a strong preference, but I do think if you're not going to have that search then the research pages need to be fixed to show username and display name. The research page only shows my display name https://www.zooniverse.org/projects/mschwamb/planet-four-terrains/research to help make it easier for volunteers to message researchers

**Comment by camallen** [comment]
@mschwamb can you move this the context where you're talking about login / display names.

**Comment by mschwamb** [comment]
yep. I'll add that to the front end
