### ISSUE TITLE
Having 'folders' for grouping related subject sets

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes#1720]
I'm not sure how feasible this is, but it would be nice and save on navigation on the project builder if I could group related subject sets into a folder and then the folders show up on the navigation bar of the project builder. That I could group subject sets as Season 1 or wildebeest images. It wouldn't need to be recorded in the classification data, but it would save on the list of subject sets that show on the navigator. 

Like I have 5 or 6 subject sets for the first batch of data for Planet Four: Terrains and 1 or 2 for the new round of images. Now I won't need to ever go back on the subject sets for the first batch of data, so hiding them in a folder would make it easier for me to access the new sets rather than searching through the list of 8 subject sets on the navigation bar.

**Comment by camallen** [comment]
We could add a grouping code to the subject set and then have the UI present that group differently. 
I'm not sure we're going to implement this though instead we could just change the lab builder page to handle the large set of data.

**Comment by mschwamb** [comment]
Yeah, I saw it more for organization as a project ages. Like I have 5 subject sets from the first upload, they're completed, so I don't ever need to look at them in the workflow again, so being able to hide them in a folder would be nice so that I can easily separate out what's new versus old data very easily.

**Comment by alexbfree** [comment]
It occurs to me that this would also be a way to have the concept of "seasons" (as in Serengeti) or "named datasets" (e.g. Decals in GZ) in Panoptes/PFE. You could create a folder for a collection of subject sets called "Season 10" or "XYZtelescope images" or whatever... you could represent that in the UI with some sort of progress bar or finite list of groups... then you could be free to add new subject sets to that folder/season/group as classification progresses, without having to name new subject sets cleverly or start again....
