### ISSUE TITLE
Adjust the name for the csv dumps so they open on macs (and likely other computers)

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes#1723]
I think somehow the csv dumps when they get more intelligible fillenames now have quotes. When I try and click on it for example to open a few classifications from a test project I get this 

<img width="572" alt="screen shot 2016-03-13 at 8 08 49 pm" src="https://cloud.githubusercontent.com/assets/753325/13728556/a44183dc-e957-11e5-9869-c3e95e2846f7.png">

if I do an ls, I get this:

/Users/mschwamb/Downloads/'europa-zoo-test-classifications.csv'

You can see the quotes visible. Can they please be removed.

**Comment by camallen** [comment]
Seems to be just safari in my testing, I'll get a fix ready for this.
