### ISSUE TITLE
subjects with classification counts less than retirement limit retired

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes#1724]
I have subjects like the following 

487678
487941
488038
487736
487917
488026
487911
488059
488026
487911

that have classifications below the retirement limit by a significant number of clicks but are retired from workflow 16. Is this a bug in retirement or does unchecking a subject set retire all it's subjects and you cannot classify them again if you re-check in the workflow editor? If it's the latter, that wasn't clear in the documentation. 

Is it possible to get these subjects that are retired but less than 20 classifications reset to unretired in subject_set 73?

**Comment by camallen** [comment]
most likely a bug which we know happened and it was fixed but there are data problems like this around. I've "un-retired" those subjects (there are 2 dups there by the way), is it just these ones?

Also for reference, the retired information is set on the worklfow retirement counts and it's per workflow only not subject set. Have you changed the retirement counts for the workflow at all?

**Comment by mschwamb** [comment]
Thanks. I was manually copying and apparently hit the same subject.  There's more should I give you a list?  It's about 500 subjects.

**Comment by camallen** [comment]
No need. I'll look it up. I'll work on the premise that retirement was always 20 for that workflow.

**Comment by mschwamb** [comment]
yep it's 20 clicks until retirement  for that workflow. It's been that way since launch. We never changed it. 

 It appears there's only 1 subject in  the other subsets previous uploaded  didn't hit retirement from my check. It's mainly subject set  73  that's impacted . Looks like I misremembered from early it's about 250 subjects, but some have only 6 classifications. 

486757 is the new subject set i just uploaded . Thanks for fixing this.

**Comment by camallen** [comment]
Done - un-retired the incorrect ones (240 of them).

**Comment by mschwamb** [comment]
thanks very much
