### ISSUE TITLE
Mini-course resource for projects

### ISSUE THREAD

**Issue by srallen** [zooniverse/Panoptes#1726]
We are porting the Planet Hunters style mini-course into PFE for Gravity Spy. The mini-course will be identical to the tutorial on the back end, but will have minor differences from the tutorial on the front-end. We also want projects to be able to have both tutorials and mini-courses, which is why this is separate from a tutorial resource, too. Could we add support for projects? Mini-courses will have a `media` string which will be an id of an `attached_image` and `content` string which will be markdown (like #1425).

Just for fyi, in the future we may give researchers the ability to set the interval of many classifications for the mini-course slides to pop up, but this will be determined after a/b testing if it is added at all. For now, we will be hard-coding in the front end the frequency (like the sign-in prompt).

**Comment by camallen** [comment]
yeah - we can add another resource for this. 

Can you specify the resource data types you'll need? Tutorial looks like [this](https://github.com/zooniverse/Panoptes/blob/03b096db6c33be6535a1c87d4552642ec1bf3839/db/structure.sql#L947). I assume that will do for you?

**Comment by srallen** [comment]
Yes, it'll be identical to the tutorial, so that will do. Thanks.

**Comment by camallen** [comment]
what's the timeline on this?

**Comment by srallen** [comment]
Would the end of this month work? There's going to be some a/b testing with it that we'll need to get in place April or May. The project is targeting a June launch. I working on and can get most of the front end for it done this week.

**Comment by camallen** [comment]
Will aim for that. If you can stub the data as is from the api then it should be a drop in replacement.

**Comment by srallen** [comment]
@camallen, @eatyourgreens brought up a good question in the custom projects stand up today about whether or not tutorials or mini-courses should belong to workflows rather than one per project. I think I'll need to follow up with the Gravity Spy team about this since one of the plans is also to have multiple workflows based on difficulty for the volunteer and it may make sense to have separate tutorial or mini-course for them.

**Comment by camallen** [comment]
@brian-c and I talked about this...i preferred per workflow but we were told to implement them per project in the interim. @srallen find out if we need per workflow..

**Comment by srallen** [comment]
@camallen I'm going to find out asap.

**Comment by srallen** [comment]
@camallen, I checked in with @trouille and it sounds like we'll need tutorials to linked to workflows for Gravity Spy and the Notes for Nature rebuild (I'll open a separate issue for that). Gravity Spy will only have one mini-course, but for future proofing, mini-courses should also be linked to workflows.

**Comment by marten** [comment]
@srallen If it's going to be just the same as a tutorial, wouldn't we be better off adding a "kind" field to the tutorial resource so that you can distinguish between two kinds of tutorial in the frontend?

**Comment by srallen** [comment]
@marten Yeah I was thinking about this, but at the time tutorials belonged to project and had only one, it made sense to have a separate resource for mini-courses to be able to support both and allow some divergence. However, if tutorials will change to belong to workflow and to allow many per project, then yeah, it can just be a "kind" field on the tutorial.

**Comment by marten** [comment]
Tutorials are now assignable per-workflow in the API (have-many, so you can share tutorials across workflows). Tutorials also have a `kind` field where you can store an identifier to distinguish between normal tutorial and the "mini-course".
