### ISSUE TITLE
Allow for empty workflow tasks

### ISSUE THREAD

**Issue by brian-c** [zooniverse/Panoptes#1728]
Currently, tasks cannot be set to `{}`. Desired behavior is to be able to start with an empty tasks list (zooniverse/Panoptes-Front-End#934).

**Comment by camallen** [comment]
was there any reason we didn't allow this?

**Comment by brian-c** [comment]
Not that I'm aware of. Probably seemed reasonable at the time that a workflow would never have zero tasks.
