### ISSUE TITLE
allow data export filtered by workflow

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/Panoptes#1729]
noting this here to collect input, start conversation...

data export by workflow feature request per Notes from Nature conversion to Panoptes:

currently within Project Builder, Data Exports there are the classification, subject, workflow and workflow contents exports, which create related CSV files with the entire project's data, and we’d like to generate the CSV with only a chosen workflow’s data (filtered on the back-end before the CSV is created).

the impetus behind this is that there’ll be multiple institutions working within NfN, each creating there own subject sets and related workflow, and it would be preferred that when they go to export data they can export their specific workflow (i.e. institution’s) data, as opposed to the the entire project’s data, which could be quite large.

currently it looks like there’s a post call made from PFE to the API with the data export type that triggers the CSV generation. i’m sure i’m horribly over-simplifying and embarrassing myself here, but i’m hoping we can add a workflow id param to the API post call, that the API can then filter the data by and then generate the CSV, but i’m sure it’s far from that simple.

**Comment by camallen** [comment]
There is nothing to stop us generating reports for a specific workflow. I guess we'd have to think about how to present data exports / requests per workflow in the lab pages. I know @marten is working on data exports but not sure where we're at. 

@mcbouslog what's a realistic time line on requiring this? I assume it's not needed for project launch?

**Comment by mcbouslog** [comment]
@camallen - we're hoping to open the project to the various science teams/institutions May 1st, could that be a realistic timeline? Full launch goal is June 1st. Though not needed by dates noted, would be nice to show if possible, but I'm admittedly ignorant when it comes to gauging what's a reasonable timeline for this. 

Might be nice project for/if Adler hires a new back-end dev sooner than later? Though again I'm not sure this would be a good intro project to API and could be more pressing needs.

**Comment by camallen** [comment]
I think the 1st of May will be too ambitious (holidays and travel to the US). When will a science team actually start using the data, that will be a more realistic time frame. In my experience this is much later than after project launch. 

@marten thoughts on this / new dev project work?

**Comment by marten** [comment]
It'll need a bunch of front-end work too, might not be the best thing for a new team member to have to deal with multiple codebases immediately. I'm not opposed to doing this, and I think it makes more sense in general than lumping everything together. However I don't think it'll have a high priority for a while since it can be worked around by filtering the full export on the workflow column after downloading.

**Comment by marten** [comment]
In any case, if we're going to do this, I would suggest we just decide that this is not going to be "a filter", but rather that we stop generating project classification exports, and always generate them per workflow.

Keep in mind that nothing is set up to do permissions per workflow, so all those NfN institutions will have access to all of the project anyways. Yesterday the thought of overarching "organizations" that bundle projects came up, might have been a good fit here (but timing wise it's too late for that).

**Comment by camallen** [comment]
@zwolf is this fixed?

**Comment by zwolf** [comment]
Yeah, this is in production.
