### ISSUE TITLE
Link tutorials to workflows

### ISSUE THREAD

**Issue by srallen** [zooniverse/Panoptes#1730]
Related to #1726, Gravity Spy will have a couple workflows: one for beginners to the project and one for advanced classifiers. The different workflows should have separate tutorials. In the future, Notes for Nature will also need tutorials linked to workflows.

**Comment by brian-c** [comment]
@chrislintott, want to weigh in on this? The reason we attached tutorials directly to projects was that if two workflows need significantly different tutorials, they should be in separate projects. No longer the case perhaps?

**Comment by trouille** [comment]
@brian-c Gravity Spy workflows will differ in that the 'beginner level' workflow will ask volunteers to choose between two glitch classes (and the subject set associated with the workflow will be identified via machine learning to likely be of those two glitch classes) while the 'advanced level' workflow will ask volunteers to choose between ~8 glitch classes (using the survey tool). The workflows definitely fall under the same umbrella project (gravity spy), but the tutorial for beginners will need different wording than that for the advanced workflow. 

Notes from Nature: different workflows will have slightly different fields that volunteers fill out (and different associated subject sets). Reflecting the current differences in workflow from one collection to another in the existing Notes from Nature site. 

I can imagine future use cases for different workflows having different tutorials.

**Comment by vrooje** [comment]
+1 for me on this - it would be good to have this flexibility if possible for some projects.

**Comment by marten** [comment]
@brian-c what's our migration path on this? If we remove the resources from projects it'll be a breaking change to the API. Do we want to maintain support for tutorials which aren't linked to a workflow specifically, or should we just deprecate that?

**Comment by brian-c** [comment]
@marten Can we update existing projects to move their tutorials from the project to each of the workflows at the same time we update the front end to look for them there? The front end can be ready early next week.

**Comment by marten** [comment]
We can do that.
