### ISSUE TITLE
Aug 8, 2015 incomplete classifications

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes#1737]
This problem is probably the symptom of a long-solved problem. But I have 58 incomplete classifications for Season Spotter in the data dump file. Specifically, the first question ("Do you have a clear view?") is answered affirmatively and then no other answers are recorded. Since all questions are marked required, this type of classification shouldn't exist in the database. All 58 incomplete classifications were done on Aug 8, 2015. I'm mainly posting here because these incomplete classifications are messing up my processing scripts. Maybe they should be removed? Marked as invalid? Something? Not too many other projects were live then, but any that were may have incomplete classifications from this date, too.

**Comment by camallen** [comment]
What workflow version were they submitted for? Any chance these were submitted via scripts and not the interface (classification metadata should show some information on this). I don't think we have incomplete support from the front end app.

**Comment by mkosmala** [comment]
This problem crosses four workflows. And the project was live by this time, so it's the most up-to-date version of each workflow. They definitely came in through the front end -- they represent the classifications of 7 different users, including 3 not-logged-in ones. What's odd is that there are plenty of good classifications in and around these incomplete ones, and they were brief in time (between midnight and 10:15 UTC on 8/8/15), which makes me think someone deployed a fix that did something wonky and then fixed the wonkiness within the day.

**Comment by mkosmala** [comment]
(Hey, related, but I won't open another issue right now: is there no longer a classification ID, as there was in Ouroboros? I realize that I should be able to concat some of the fields (user_id,metadata) to get a unique value. But it was nice when there was a single short-ish value that indexed a classification. Basically, I want to spit out the "IDs" of the incomplete classifications as my script runs.)

**Comment by vrooje** [comment]
+1 to the above - I don't always need a unique classification ID, but when I do I prefer a pre-existing column.

(I've run into issues before when e.g. a browser submits classifications so close together that created_at is the same for a given user so I can't create a unique id without actually including the classification details in the id, and perhaps not even then...)

**Comment by camallen** [comment]
@mkosmala where are these incomplete classificaitons coming from, the dumps? From [here](https://github.com/zooniverse/Panoptes/blob/95671795f2790da789c16a35b4bb8fa1f677f637/app/workers/classifications_dump_worker.rb#L36) there should only be completed classifications. We may be talking across each other here as in the api we have the notion of "incomplete" classifications that allow a user to save a partial and pick it up later. I think you're talking about not fully answered questions instead. 

Yes we have internal primary key ids we can add to the dumps. Is this required right now? @marten is working on full csv dumps with another system.

**Comment by aliburchard** [comment]
Absolutely +1 to having primary keys for each classification. Since I suspect we'll maintain the current json exports for teams that already are set up for working iwht them, we probably want to add pkeys to those at some point (in addition to adding them into the csv exports).

**Comment by mkosmala** [comment]
@camallen I assume it's the dump. It's the thing I get when I "request new classification export" from the Project Builder. 

(Also, more processing shows that the problem occurs in all 7 of my workflows for the Season Spotter Questions project; I have 95 total incomplete classifications out of 113,142 total classifications.)

**Comment by mkosmala** [comment]
I'll split off the primary key request into a new issue. For me, it's not urgent, but would be nice.

**Comment by marten** [comment]
It's definitely not incomplete classifications in the way @camallen was thinking, there aren't any in the DB for this project at all. If this issue only occurs on that day last day, that makes me wonder if it was perhaps just a temporary bug in the frontend that allowed people to submit classifications without going through the entire workflow.

**Comment by mkosmala** [comment]
@marten Yeah. That's what I think. It's really just 12 hours during which these occurred. And in the same time frame there are good classifications. So these got in there through some now-solved bug. The question is what to do with them now? They're useless to me. And I don't want them contributing to retirement...
