### ISSUE TITLE
Request for unique classification ID in classification dumps

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes#1739]
Split from #1737 
It would be nice to have a unique classification ID in the classification dumps. I realize that I should be able to concat some of the fields (user_id,metadata) to get a unique value. But it was nice when there was a single short-ish value that indexed a classification in Ouroboros.
@vrooje is +1 for this. She can't always guarantee a unique ID by concatting existing fields.
@aliburchard is +1 for this, too.

**Comment by camallen** [comment]
sounds like a good idea.
