### ISSUE TITLE
create sensible names for aggregated data export

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes#1740]
Because you guys are awesome, the raw data dumps and talk data now have logical names (project name + dump type). Can we do the same for the aggregated data dump please?

**Comment by chrislintott** [comment]
Maybe including the name of the routine that generated it?

Chris

**Comment by aliburchard** [comment]
or even just ProjectName_Date?

**Comment by camallen** [comment]
closing - aggregated data is now available via caesar.
