### ISSUE TITLE
Give Comet Hunters Zooniverse approved status again

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes#1746]
We had to upload new data to Comet Hunters. I've made the subject set live now, and switched the site back into Live mode from Development. When someone has a chance can you switch the flag for the project to Zooniverse approved again? Thanks.

**Comment by eatyourgreens** [comment]
Hi Meg, I've just flipped it to approved again.

**Comment by mschwamb** [comment]
Thanks @eatyourgreens!
