### ISSUE TITLE
Data aggregation not functioning

### ISSUE THREAD

**Issue by tedcheese** [zooniverse/Panoptes#1750]
@ggdhines I requested a new aggregation export from Whales as Individuals two days ago, then again yesterday, with no apparent result. When I download data, result is an aggregation from January.

Thx ~ Ted

**Comment by ggdhines** [comment]
hi Ted, is your project id 11? I don't know how to easily get the a project name from an id but I know that an aggregation run for project 11 caused an error a couple of days ago. That error has been fixed. I didn't receive an error yesterday but I there was stuff going on with rectangle aggregation that only got fixed today. Apologies - need to get a better notification system set up.
That said, new builds aren't working right now - for some reason config files aren't being copied over correctly from AWS (amazon web services). I notified the admin person at Zooniverse but that might not be get fixed until Monday. Will keep you updated.

**Comment by tedcheese** [comment]
Hi Greg. Thanks, yes, project 11. So as far as getting the aggregation data, sometime Monday or so?

**Comment by ggdhines** [comment]
Hopeful that the config file issue can be quickly fixed - in which case definitely Monday.

**Comment by aliburchard** [comment]
quick q: Is the config file issue affecting all projects? Or just projects with rectangle aggregations?

**Comment by ggdhines** [comment]
@aliburchard was unfortunately affecting everything but is now fixed. @tedcheese give it a go. I'm heading out for the head but will check tonight or tomorrow for any issues.

**Comment by tedcheese** [comment]
... requested again a five hours ago with no result... how long should it take?

**Comment by tedcheese** [comment]
@ggdhines Any update on this?

**Comment by ggdhines** [comment]
Hi @tedcheese - things are looking good but there are some clusters that aren't being included in the final output. They seem to be missing some data fields (those fields get calculated for every cluster so trying to understand why these clusters are different). Once that's done, I'll run the code and email you the results.
