### ISSUE TITLE
Optimize panoptes user group fetching. Affects education-api.

### ISSUE THREAD

**Issue by simoneduca** [zooniverse/Panoptes#1757]
@marten not sure you had a look at this already, but there you go.

**Comment by camallen** [comment]
can someone fill in some details? 

is this optimizing user_group searchers (attribute filtering) or is get `/ap/user_gorups/1` slow?

**Comment by simoneduca** [comment]
I think it's the latter, but I leave Marten to clarify.

**Comment by marten** [comment]
It's just `GET /api/v1/user_groups` to get the list of all groups a user is in.

https://rpm.newrelic.com/accounts/23619/applications/5149304/transactions#sort_by=slowest&id=5b22436f6e74726f6c6c65722f6170692f76312f757365725f67726f7570732f696e646578222c22225d

**Comment by marten** [comment]
Would getting `/api/v1/memberships` instead be faster?

**Comment by camallen** [comment]
not sure, we should optimize the get on user_groups index if it's slow.

**Comment by marten** [comment]
Fixed by #1762
