### ISSUE TITLE
Required subtasks sometimes record as 'null'

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes#1779]
I have a classification from back in the early months of Season Spotter Image Marking, in which I have required subtasks, but the recorded classification has no values (i.e. 'null') for this subtask. The classification in question is 2272952 if you want to go look at it. The tool in question has the label "Leaves that are NOT GREEN". (The subtask asks what color the leaves are.)

I have a handful of such classifications (~100). The problem may be related to #1737, although these null subtasks span July 21 (project launch) to August 23, 2015, instead of just being on a single day. In any case, the front-end seems to have been fixed, since there aren't any recent occurrences. But like #1737, these classifications are incomplete ones in the database. Maybe they should be somehow marked as 'incomplete' or 'invalid' at some point...

**Comment by camallen** [comment]
@mkosmala what do you want us to do with these? Mark them an "incomplete" and remove from retirement counts?

**Comment by mkosmala** [comment]
@camallen That would be great.
