### ISSUE TITLE
Send email notification when user's email address or password is changed

### ISSUE THREAD

**Issue by astopy** [zooniverse/Panoptes#1790]
For security reasons when a user changes their email address we should send a notification letting them know (to both their old address and their new address) in case the change was unauthorised.

**Comment by camallen** [comment]
Pinging @zwolf - this seems like a nice issue to touch a few different parts of the system.

**Comment by astopy** [comment]
Updating title to include password change (as suggested by @marten )

**Comment by mschwamb** [comment]
If you're working on this one related issue was that currently you can be added to a Zooniverse project without knowing unless you go to the lab section frequently. Having an email when you get added to any project role on a project builder project would be extremely helpful. 

https://github.com/zooniverse/Panoptes-Front-End/issues/1749

**Comment by zwolf** [comment]
I've got a basic idea of what these emails should say, but if anyone would like to specify the language used, please do.

**Comment by zwolf** [comment]
Currently: 

"Your Zooniverse email address has been successfully changed. 
(or)
Your Zooniverse password has been successfully changed.

If you believe this to be in error, please contact <emailaddress>.

Thanks,
The Zooniverse Team"

How's that? What should that email address be?

**Comment by camallen** [comment]
looks good ( I assume that's 2 different emails). 

Email from address is setup [here](https://github.com/zooniverse/Panoptes/blob/95671795f2790da789c16a35b4bb8fa1f677f637/app/mailers/application_mailer.rb#L2) and in the devise config as well.

**Comment by camallen** [comment]
also should this be `If you believe this to be in error, please contact support (email here?).`

**Comment by zwolf** [comment]
Yeah, oops. That's the email I'm looking for, the one for support.

**Comment by camallen** [comment]
@astopy @mrniaboc do we have support@ or should it be contact@

**Comment by astopy** [comment]
contact@zooniverse.org is the one to use I think.

**Comment by eatyourgreens** [comment]
I'm pretty sure Chris Snyder shut down support@ when he was tidying up Zooniverse gmail.

**Comment by camallen** [comment]
seems i should have known about this page, https://www.zooniverse.org/about/contact

**Comment by zwolf** [comment]
Closed by #1855
