### ISSUE TITLE
Set a workflow as default

### ISSUE THREAD

**Issue by srallen** [zooniverse/Panoptes#1793]
Currently, project builders have two options for how volunteers pick a workflow if there are multiple workflows: either let the interface select one at random or allow volunteers to select which one they want to use from the project home page. For Gravity Spy, neither of these options will work with the coming Nero workflow assignment. Volunteers should be defaulted to the simpler workflow and then if they are shuttled into the more advanced workflow by Nero, then they will be presented with an option to choose. 

I'd like to be able to set a workflow as default and be able to have the front end check for that before selecting a random workflow. Could we add a boolean `default` property on workflows?

**Comment by aliburchard** [comment]
I love the idea of having a default workflow. This could also solve the under-discussion issue of what happens when you click the "classify" tab on a project with multiple workflows.

**Comment by srallen** [comment]
Ok I've chatted with @brian-c and project config is the place for this to go.
