### ISSUE TITLE
Invisible error message on upload fail

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes#1795]
Might be a front-end thing, but figured that the front end just printed the message the backend supplies. Either way, I don't know which subject failed or why on this upload, as the message is invisible:

![screen shot 2016-05-06 at 11 50 44](https://cloud.githubusercontent.com/assets/6217406/15071090/f32bb4a6-1380-11e6-9e2e-cbd93155215a.png)

**Comment by camallen** [comment]
I'm not sure what is going on here...very hard to debug too.
