### ISSUE TITLE
expose user classification info by workflow

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/Panoptes#1796]
per Notes from Nature conversion request, to show user "badges" (earned by # of classifications) by "expedition" (which are workflows within Panoptes).

per conversation with @camallen:
-will be modifying [this code](https://github.com/zooniverse/Panoptes/blob/master/app/serializers/user_project_preference_serializer.rb#L19)
-maybe as an optional attribute or detecting the presence of a param

**Comment by parrish** [comment]
From our meeting today...
per-workflow classification counts are available (and indexed) with an aggregation:

```
select user_id, workflow_id, count(*) from user_seen_subjects where user_id = 123 group by user_id, workflow_id
```
