### ISSUE TITLE
Are tutorials versioned and saved like workflows?

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes#1802]
A question - as I'm thinking about the changes to the tutorial I need to make for Comet Hunters, I was wondering if it was versioned like the workflow and could be exported like the workflow can be? So you what tutorial content was shown to the volunteer  at the time of the classification.

**Comment by camallen** [comment]
Nope. Not sure this is really a high priority though - pinging @aliburchard for thoughts.

**Comment by mschwamb** [comment]
okay. Thanks. Mainly wanting to know so that when I switch things over to incorporate the indevelopment second workflow for Comet Hunters and modify the original tutorial that I should keep a backup of what we had incase something goes wrong and for record keeping.

**Comment by mschwamb** [comment]
Question answered so closing.  Thanks for the reply @camallen
