### ISSUE TITLE
Suggestion: Add quotes to CSV export headers, to avoid parsing issues with standard csv libraries on default settings

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes#1803]
(moved from https://github.com/zooniverse/Panoptes-Front-End/issues/2579 as this is a backend not PFE issue)

I was writing a script to parse the subjects exports file generated by PFE. I was having issues where I couldn't correctly reference the fields of the data. It turns out the problem is that the CSV file doesn't have quotes around the column names in the header line. CSV parsers such as [csv](https://www.npmjs.com/package/csv) and [fast-csv](https://www.npmjs.com/package/csv) which can automatically read the header line when you specify `headers` to `true` expect the header line to be strings, or else the header line ends up undefine, the rows end up with keys equal to their values, and the csv parsing doesn't advance properly.

By simply changing the source CSV file to have quotes around the header line column names, all these problems went away, so I think PFE export should change to avoid other people having this pain.

Instead of 
`subject_id,project_id,workflow_ids,subject_set_id,metadata,locations,classifications_by_workflow,retired_in_workflow`
the header line should be
`"subject_id","project_id","workflow_ids","subject_set_id","metadata","locations","classifications_by_workflow","retired_in_workflow"`.

We should check all our export CSVs as well to ensure that no string value is exported without quotes.

**Comment by marten** [comment]
There's nothing special about the header row, and in general CSV cells just need quotes if they're going to contain one of the delimiter characters (in our case a comma or a newline). There's absolutely nothing in the CSV format spec that requires quoting everywhere, so either you're doing something wrong, or those libraries are bugged.

Also, [the csv lib's own example](https://github.com/wdavidw/node-csv-parse/blob/master/samples/columns-discovery.in) doesn't have quotes around strings, but [claims to handle it fine](https://github.com/wdavidw/node-csv-parse/blob/master/samples/columns-discovery.js#L17-L20).

[Nor does FastCSV seem to need it](https://raw.githubusercontent.com/C2FO/fast-csv/master/examples/assets/snake_case_users.csv).

**Comment by alexbfree** [comment]
@marten My justification was this: I have a script that works successfully with a different CSV and fails with this one (with no modification to the script. The only obvious difference was the quotes, and indeed if I add the quotes then this CSV works too.

So why don't we just make everyone's lives easier and include the quotes?

I wasn't saying it couldn't be coded around, I was saying it'll make it easier for everyone if our CSV files "just work" with out of the box settings on parsers, and the easiest way to do that is just to ensure there are quotes. 

Even if not strictly a bug, I think this is worth doing if it saves even one or two users a little pain.

Let me turn the question around - what reasons are there for NOT adding the quotes? Seems to me there are no negative effects of doing so, only potential positives....

**Comment by eatyourgreens** [comment]
@alexbfree see my comment on https://github.com/zooniverse/Panoptes-Front-End/issues/2579#issuecomment-219110919 the `csv` module parses CSV fine without quoted headers.

So this could be a bug in your code, or a bug in the particular CSV parser that you're using. If that's `fast-csv`, I'd suggest opening an issue on their github repo: https://github.com/C2FO/fast-csv

**Comment by alexbfree** [comment]
I'm not saying it can't be solved by code changes on my end. I don't have a code problem to be solved, *this is not about my script*. I'm trying to make a *general* point rather than talk about my code. 

I'm saying that you can *make it easier* for everyone who wants to parse our CSVs by including quotes. We quote all the other strings in the file, so why omit it for the header line?

I haven't heard any reason why we omit quotes in the header while including them in the rest of the document. It is inconsistent, and while not breaking any standard, unnecessary.

Sample CSV export: [computer-vision-serengeti-subjects.csv.zip](https://github.com/zooniverse/Panoptes/files/268233/computer-vision-serengeti-subjects.csv.zip)

**Comment by alexbfree** [comment]
Never mind, I can see I am not managing to make myself understood.

**Comment by eatyourgreens** [comment]
We omit quotes because a correctly-formatted CSV doesn't have quoted headers.

Here's a script I just wrote that reads and parses a Panoptes subject export using the `csv` parser. There doesn't seem to be any problem at all with the CSV file.

```javascript
#!/usr/bin/env node

var SUBJECTS = './diagnosis-london-subjects.csv';
var csv = require('csv');
var fs = require('fs');

var input = fs.createReadStream( SUBJECTS );

function processLine(line) {
  console.log( 'SUBJECT METADATA', line.metadata );
}

var parser = csv.parse({columns: true}, function(err, data){
  data.forEach( processLine );
});

input.pipe( parser );
```

**Comment by alexbfree** [comment]
Thanks for taking time to do that Jim, I am genuinely surprised by your finding.
Maybe i'll find the time to investigate this more deeply in future then, and figure out what is different between your script and mine. I thought I was using a standard setup. For now, it's not important and I shall retire to my cave! ;-)

**Comment by marten** [comment]
We're not including quotes in the rest of the document. We're only including them whenever they are required to be there because of the content of the cell. That's what the CSV generator in Ruby does by default: look at the content and if it contains either a comma or a newline, then we need to wrap the cell in quotes (and escape any quotes inside the cell).

I'd be really intested to see what your code is that fails on these CSVs, because honestly I can't reproduce it at all.

**Comment by alexbfree** [comment]
It's ok @marten, I don't want to take up any more of your time, it's looking like whatever caused this must have been an issue in my code after all. I really thought it wasn't, and I can't explain how adding the quotes fixed it - but don't have time to dig deeper right now. Maybe I will come back to it at a less busy time, if I do I'll comment here. Sorry for wasting your time.
