### ISSUE TITLE
It is possible to have two memberships to the same group

### ISSUE THREAD

**Issue by marten** [zooniverse/Panoptes#1811]
Apparently the `memberships` table is missing unique index on `(user_group_id, user_id)`, which means some people have multiple memberships onto the same group. This causes issues when the roles vary per membership, as the ACL will just pick the one membership out of the database which means you sometimes don't get admin rights to a group you're an admin of.

### Desired behaviour

Joining a group should either merge roles or be a no-op.

**Comment by simoneduca** [comment]
Since this morning this has been happening. Perhaps something overwriting the fix was deployed? @camallen

**Comment by camallen** [comment]
I think this is an education API error, closing again as that is the first port of call. Please re-open with more specifics about how the unique index here is causing the issue.
