### ISSUE TITLE
subject_ids column in classification exports reporting double ids

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes#1841]
First, many thanks for reporting `subject_ids` as a column a-la #1637 - it's much appreciated.

I did notice that for my project (id=3) where each classification only deals with 1 subject, it's reporting the subject id twice in that column:
![screen shot 2016-06-23 at 6 16 40 pm](https://cloud.githubusercontent.com/assets/2357126/16325053/5bc934e8-396f-11e6-8b1a-ccbd1a2c0ee4.jpg)

I can easily work around this but just wanted to note it.

**Comment by marten** [comment]
Interesting, I had noticed that with @chrislintott's .astro hack day project but since they were submitting classifications via custom API calls I assumed the error was there. I'll investigate.

**Comment by marten** [comment]
Awesome. We're bitten by one of those Rails features everyone always says you shouldn't use: `default_scope`. We automatically do an OUTER JOIN between subjects and their images, so subjects with multiple images will be reported multiple times.

**Comment by camallen** [comment]
urgh - linking #1614
