### ISSUE TITLE
Annotations for unknown tasks are being exported as "error".

### ISSUE THREAD

**Issue by marten** [zooniverse/Panoptes#1845]
Wildcam has the amazing feature that they're sending annotations for task "survey" whereas the workflow defines "T1". (Or vice-versa, too lazy to look it up right now). And because workflows are versioned, there's no way to fix that! Yaaay.

This means none of the annotations are getting exported anymore. The formatter's else-clause should just always return the basic annotation itself. I can't really see any other way out of this hole that we dug.

/cc @shaunanoordin @camallen @zwolf

**Comment by zwolf** [comment]
I heard about this a bit ago and it should have been fixed by #1840. On 24 June @wgranger said that the exports were looking good again (for Wildcam? Possibly the Wisconsin one? Can't remember). When was the last export attempted?

**Comment by camallen** [comment]
eek - when did the submitted annotations change (or did they?) We could hack the workflow (turn off versioning while we do it) to update this to be consistent with the submitted annotations.

**Comment by wgranger** [comment]
Ahh, yes, the fix I noticed was that annotations were coming back correctly from Oldweather whereas before the field said `task cannot be exported`. I haven't checked the export from any other project.

**Comment by marten** [comment]
@zwolf Yeah, in this case the task cannot be found, because the annotation refers to a task key that doesn't exist in the workflow.

@camallen I think it's always been this way, we'd have to rewrite all the old versions that Papertrail stored.

**Comment by zwolf** [comment]
That should still be covered, right? What you suggested (returning the annotation in the else) is precisely the change that I made to fix those annotations.

**Comment by zwolf** [comment]
I believe the fix from #1840 should have fixed the WCG export despite the bug in that repo. After that PR was merged (6/23), that error should only only seen if a task type that is not drawing/single/multiple/text is nested within a combo task (which was the desired behavior). I don't have collab access to that project, but I'll find someone who does and double check.

**Comment by zwolf** [comment]
WCG export looks okay. I'll come back around to this if we get another complaint.
