### ISSUE TITLE
Validate annotations against the workflow task definition

### ISSUE THREAD

**Issue by marten** [zooniverse/Panoptes#1846]
Anyone working on this should probably first issue a PR that only reports to Honeybadger, but still saves the classifications. Once that manages to stay quiet we can look into being stricter and flat out rejecting classifications if someone wrote a bad frontend.

**Comment by camallen** [comment]
Also this should save classifications but if they don't conform to the expected format, raise an error (report) then mark as invalid in the background processing worker. Any invalid classifications are ignored for other events, e.g. retirement, aggregation, exports, etc.

Look at modifying the [lifecyled_at](https://github.com/zooniverse/Panoptes/blob/c0a8a2d43cb2ce7a9a10e6625ea31f1240deb400/db/structure.sql#L191) for the state tracking
