### ISSUE TITLE
Users seeing the same subject more than once

### ISSUE THREAD

**Issue by VVH** [zooniverse/Panoptes#1853]
A few people on Shakespeare's World and AnnoTate have reported seeing the same page on two separate sessions. In some cases it could be because they were anonymous one time and logged in another, but in [this case](https://www.zooniverse.org/projects/zooniverse/shakespeares-world/talk/194/62912?comment=123085) the person was signed in both times. [at]mutabilitie writes: 'After transcribing and transmitting this document this morning, I was taken back to the same document (minus the blue dots I had placed). I wasn't sure whether my transcription had really been registered, so I transcribed the page again. According to my stats page, though, only one of those two transcriptions was counted. I'm not really too upset about the waste of time, because it was a short and easy document and didn't take too long to transcribe, but either way this probably shouldn't be happening...' Talked to @marten and he said this could be a backend issue, but I'm also @simoneduca for ideas.

**Comment by camallen** [comment]
This can still happen and we're working on it..should be a rare event at the moment.
