### ISSUE TITLE
Adding general location info to raw_classification export

### ISSUE THREAD

**Issue by trouille** [zooniverse/Panoptes#1856]
See https://zooniverse.slack.com/archives/general/p1467394169000361 for the Slack thread on this question. 

Original motivation comes from the Snapshot WI team being interested in using user_ip to map where their classifications are coming from, in order to estimate impact of their outreach efforts across the state of WI to recruit new volunteers into the project. Currently user_ip is anonymized in the raw_classification.csv to protect privacy, as it should be. 

@marten mentioned a possible solution of including general location info in the raw_classification.csv (e.g, town). 

Another solution would be to provide the Snapshot WI team the user_ip addresses and general timestamp (day-month-year or just month-year) as a separate file. This would be less desirable: 1) something specific we'd have to do just for Snapshot WI every X months and 2) Snapshot WI would be able to do less with this info, since it'd be disconnected from annotations, etc.

**Comment by trouille** [comment]
@vrooje noted in Slack that town would de-anonymize users for projects and even country would for small countries with few users (here's looking at you N. Korea). Hmm.

**Comment by marten** [comment]
Yeah it's hard. For ref: https://tech.vijayp.ca/of-taxis-and-rainbows-f6bc289679a1#.i6izzm4xf

- Marten

**Comment by camallen** [comment]
@trouille did this get sorted via the pusher stream / can we close this?

**Comment by trouille** [comment]
Yes, thanks @camallen
