### ISSUE TITLE
RetireSubjects doesn't validate input parameters

### ISSUE THREAD

**Issue by astopy** [zooniverse/Panoptes#1863]
Submitting this:

```
{"retirement_reason":"other","subjects":[598274,598272,598257],"workflow_id":"2210"}
```

Should have raised an error because "subjects" should have been "subject_ids", but it just returns a 200 like everything was fine.

**Comment by marten** [comment]
Due to Array.wrap I'd bet. `Array.wrap(nil) == []`

**Comment by camallen** [comment]
should these [params defs]( https://github.com/zooniverse/Panoptes/blob/master/app/operations/workflows/retire_subjects.rb#L8) validate at least one exits?
