### ISSUE TITLE
Filtering talk comments by project ID is including Zoo-wide comments 

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes#1870]
![screenshot 2016-07-19 13 09 00](https://cloud.githubusercontent.com/assets/1473244/16949339/2d2d1bb6-4db2-11e6-90ae-4cf4d5375134.png)

I have found that when you specify a project ID as a filter on the `comments` endpoint, it correctly omits comments from other projects - but it still includes comments on "zoo-wide" boards (ie those with `project_id=""`. 

This appears to be a bug in the API.

In the example above in the screenshot, the first and fourth comment returned are not from the specified project. Only the second and third should have been returned.

**Comment by camallen** [comment]
This is not a panoptes api issue, it should be filed on the talk-api repo.

**Comment by alexbfree** [comment]
Sorry I didn't realize talk API had a separate repo.
May not be an issue anyway, turns out it's not supposed to filter by `project_id`, only by `section`
