### ISSUE TITLE
New API Route to retrieve retired subjects

### ISSUE THREAD

**Issue by amyrebecca** [zooniverse/Panoptes#1886]
I need a route that lets me retrieve the subjects that have been retired in a given workflow, optionally since a given datetime. Zach and I discussed this a while ago and I forgot to create an issue about it for tracking purposes.

**Comment by camallen** [comment]
@marten time to expose the subject workflow counts model?

**Comment by marten** [comment]
Missed this, but agreed. If we can come up with a better name for it, now would be the time to change it. It's not just counting anymore.

**Comment by camallen** [comment]
`SubjectWorkflowStatus`?

**Comment by astopy** [comment]
Having this endpoint available soon would be really useful for aggregation too.

**Comment by marten** [comment]
I like `SubjectWorkflowStatus`

**Comment by astopy** [comment]
@marten @camallen Any change of getting this either this week or early next week?

**Comment by camallen** [comment]
yes but time is a bit tight with existing work. Might be late next week.
