### ISSUE TITLE
Workflow completeness metric should only use the current linked set of data

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#1890]
Linked to https://github.com/zooniverse/Panoptes-Front-End/issues/2591#issuecomment-237246221

The metric currently uses the total retired count instead of the active linked retired count so the values are skewed as a project grows older and sets are linked / unlinked.

**Comment by mschwamb** [comment]
@camallen looks like there was a ticket in for this. Should this be closed?

**Comment by camallen** [comment]
thanks for the housekeeping @mschwamb :+1:
