### ISSUE TITLE
Will the workflow version update every time you add/remove a subject set if you set workflow to not active to add a new workflow?

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes#1907]
I was told by @srallen that now project owners should be setting a workflow to not active to update which subject sets are live. It says on the workflow page:

> Version indicates which version of the workflow you are on. Every time you save changes to a workflow, you create a new version. Big changes, like adding or deleting questions, will change the version by a whole number: 1.0 to 2.0, etc. Smaller changes, like modifying the help text, will change the version by a decimal, e.g. 2.0 to 2.1. The version is tracked with each classification in case you need it when analyzing your data.

If you're just adding a subject set is the workflow version updating and should it?

**Comment by camallen** [comment]
Nope - changes to the active state and/or the set links do not change the major version number.
