### ISSUE TITLE
Finer grained api user roles for data access

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#1909]
Look at adding more roles than what we currently have. 
- [ ] Specifically should web split the admin role into zoo wide project testers and full admin. 
- [ ] Also we'll need a role for data access across projects.

**Comment by marten** [comment]
Possibly an internal "webservice" role that isnt quite admin but close (for nero etc, doesnt need access to user details for instance).

- Marten

**Comment by jmaddock** [comment]
A "researcher" role that has access to classification data across all projects would be useful.  The current approach of requesting permission from each project isn't feasible for analysis across the entire platform.

- Jim
