### ISSUE TITLE
Add bounced email count for users

### ISSUE THREAD

**Issue by astopy** [zooniverse/Panoptes#1921]
I've been thinking about how best to process bounces from Mailman and I think the best thing to do is to keep a count in Panoptes of how many bounces each user has had. The reason for this is that Mailman's bounce tracking is done on a per-list basis, but we don't send messages to the same lists often enough for that to be effective. It would also be useful to keep a single count of both Mailman and SES bounces in one place.

This could probably just be an integer stored on each user, but better than that would be if we had a log of dates and times for each bounce (so for example we could only mark addresses as invalid if they have a certain number of bounces in a certain time period).

I'm also not sure whether we should actually build this into Panoptes directly, or if it would be better off being a separate microservice.

What does everyone else think?

**Comment by camallen** [comment]
I'm not in favour of adding in the responsibility unless we use these bounces in the panoptes API itself. Sounds like an ideal use case another service with Redis ? storage.

**Comment by marten** [comment]
I think given that we already had some thoughts for other things a dedicated mailing-service could do, this would fit there?
