### ISSUE TITLE
Allow Subject_Sets to be sortable

### ISSUE THREAD

**Issue by wgranger** [zooniverse/Panoptes#1928]
Subject_sets cannot currently be sorted by updated_at, among other attributes.

**Comment by camallen** [comment]
we can do this but what's the use case for sorting on the update_at attribute. I'm just a little hesitant adding more indexes to the db if it's trivial use case.

**Comment by wgranger** [comment]
This is for the pullout news tab on the new signed in home page. Currently, the code is making an api call, getting all the subject sets for each project, and then sorting them by date when returned and plucking the most recent. It would be more efficient if the call could sort by updated at, then it would be able to only return the one most recent.

**Comment by camallen** [comment]
got it, we could certainly look at adding this (you can look at page_size=1 for each call OR we could do a bulk call to load by the set of project ids). 

Out of interest, why is it using subject sets to find out if new data has been changed / released. I'm not sure this is the best way of signaling this change though.

**Comment by wgranger** [comment]
Making as few calls as possible would be great, because right now it is making a call for the subject sets of each project, which is slowing things down a bit. Doing a bulk call would be nice. 

I was thinking making a call for a project's subject sets and seeing the most recently updated set would be an indicator of the most recent update. However, I'm all ears if there's a better or more efficient way of checking when a project has received new subjects, especially by solely using the project resource.

**Comment by camallen** [comment]
we have a most recently updated projects filter (projects page) already, `/api/projects?page=1&sort=-updated_at&launch_approved=true&cards=true&include=avatar`

**Comment by wgranger** [comment]
What causes a project to be updated though? If an owner tweaks the title or changes the workflow, is it still updated? I'm mainly curious if new subject sets have been added, but perhaps that is being too picky?

**Comment by camallen** [comment]
yeah a bunch of things like that (modification of the project resource via links, etc). Re change name, i can do the same thing on a subject set too.

**Comment by wgranger** [comment]
Yeah, considering we're only trying to know if new subjects have been added, sorting a subject set might be the best bet.

**Comment by camallen** [comment]
sounds like a plan.

**Comment by wgranger** [comment]
In talking with a couple people about this (Jim and Sarah), we might just sort projects by `updated_at` for the news pullout, which would save us from having to make the extra API call and would speed things up a bit. We can always explore how much quicker a bulk API call would be in the future, or we might be satisfied with how the page looks displaying the most recently updated projects.

**Comment by camallen** [comment]
Close this for now then, re-open if we need it.
