### ISSUE TITLE
Classification counter stuck on one value for some time

### ISSUE THREAD

**Issue by mwp-tj** [zooniverse/Panoptes#1939]
This is with regards to the MWP : https://www.zooniverse.org/projects/povich/milky-way-project

Our classification counter is stuck at 25,862 for ~18hrs now. The statistics page shows that there were no classifications made today. We have applied for full launch and the project is in the "live" mode.

Are our classifications being lost? I am curious about this! Any help would be appreciated :)

Thanks again for the great work Zooniverse!

**Comment by marten** [comment]
Sorry for the confusion, we're having some technical issues with the statistics page and the counter values on project homepages. 

Classifications are still getting stored. 

- Marten

**Comment by camallen** [comment]
We're working on this and should have a solution out today. For what it's worth the stats page graphs show the classifications are still being counted: 
https://www.zooniverse.org/projects/povich/milky-way-project/stats

<img width="561" alt="screen shot 2016-09-02 at 09 11 04" src="https://cloud.githubusercontent.com/assets/295329/18197065/38e74fcc-70ed-11e6-9b1f-c3352e2ae815.png">

**Comment by camallen** [comment]
this should be fixed now.
