### ISSUE TITLE
repeat entries for subjects classified in multiple workflows

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes#1942]
This might be a duplicate, but I couldn't find the ticket. If you have subjects classified in more than one workflow, you get  multiple entries in the subjects csv dump

subject_id,project_id,workflow_ids,subject_set_id,metadata,locations,classifications_by_workflow,retired_in_workflow

490089,17,[],73,"{""filename"":""APFT0000276a.png""}","{""0"":""https://panoptes-uploads.zooniverse.org/production/subject_location/deabab21-7bde-4d50-a6f9-9ca80d087cf4.png""}",null,"[16,2063]"

490089,17,[2063],4718,"{""filename"":""APFT0000276a.png""}","{""0"":""https://panoptes-uploads.zooniverse.org/production/subject_location/deabab21-7bde-4d50-a6f9-9ca80d087cf4.png""}","{""2063"":2}","[16,2063]"

Is it possible to only have on entry or create separate files for separate workflows?

 It's not expected that there would be duplicate entries

**Comment by camallen** [comment]
yeah - this is a by product of the way we process the data right now (via the linkage model). If we process by the project subjects link (distinct via sets) then we should only process this once.

**Comment by mschwamb** [comment]
I think it would be helpful if you did it by subject links. It means that basically I have process the file and find the duplicates if I want to find out even how many subjects I have on the site. I'm not sure all research teams will be as capable.

**Comment by marten** [comment]
This is by design. If we didn't, the other columns have to be JSON in order to provide their values on a per-workflow basis (retirement etc). For those less proficient in programming, I think that is the less of two evils: Excel is able to filter rows by making a column unique, but not able to decode and split out JSON, so the current setup allows more queries.
