### ISSUE TITLE
If a subject set isn't linked the classification count per workflow is NULL in the output csv dump

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes#1943]
subject_id,project_id,workflow_ids,subject_set_id,metadata,locations,classifications_by_workflow,retired_in_workflow
484099,17,[],73,"{""filename"":""APFT0000046f.png""}","{""0"":""https://panoptes-uploads.zooniverse.org/production/subject_location/55e4271a-603d-4a95-9e89-d3b6bcef4d4e.png""}",null,[16]

It would be nice if one could still see the classification count for the workflow even though the subject set is stilled linked to the classification interface.

**Comment by camallen** [comment]
I guess we could move the subject dump worker from only processing the linked data to processing all project subjects.

**Comment by camallen** [comment]
Noting this would actually be the project -> subject_sets (linked & unlinked) -> subjects join, not the project -> subjects join.

**Comment by mschwamb** [comment]
I wasn't what I was expecting that it was only for linked data. I think other project owners/researchers will be confused that sometimes there is a classification count reported and sometimes there isn't.  I used the subjects.csv to get quick statistics for classifications like how many classifications per workflow. 

I think if you can make that change  it would be helpful.

**Comment by mschwamb** [comment]
Can this please be added in in the near future. Right now I and other science team people have to calculate everything  for our projects. For example to know how many classifications completed in a given workflow or how many classifications did each subject get, I need to add up the classifications for each subject and save the value and then add up. As this info is in the database it seems like it's making more work for science teams when that information can  simply be outputted and then I can sum the columns.
