### ISSUE TITLE
My project has the green box saying it's out of data, but it's not

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes#1949]
P4: Terrains says its out of data, but I put in a years worth of images  a month ago. When you go to classify the pop up appears. Not sure if this is a backend or front end so I'll post in both and link the tickets. 

<img width="1136" alt="screen shot 2016-09-06 at 6 23 28 am" src="https://cloud.githubusercontent.com/assets/753325/18281997/d8fbcad2-73fa-11e6-86ad-892723ccd453.png">

<img width="1149" alt="screen shot 2016-09-06 at 6 23 23 am" src="https://cloud.githubusercontent.com/assets/753325/18282001/da88afd2-73fa-11e6-8dc6-0fa463e19ea0.png">

**Comment by mschwamb** [comment]
ticked on the front end: https://github.com/zooniverse/Panoptes-Front-End/issues/2977

**Comment by marten** [comment]
Probably related to #1639 which @camallen is working on. This old issue was triggered when we started fixing the counters, which went through a day or two when the counters didn't take into account whether or not old subject sets with retired subjects were unlinked from workflows.

**Comment by mschwamb** [comment]
Not sure why P4:T and not Comet Hunters, but Comet Hunters isn't displaying that message or any other project I checked if that helps.

**Comment by camallen** [comment]
Yeah - new data didn't reset it, I'm working on it. Should be fixed now @mschwamb .

**Comment by mschwamb** [comment]
Thanks @camallen and @marten for getting to this after hours.
