### ISSUE TITLE
Counters don't take into account already-seens?

### ISSUE THREAD

**Issue by marten** [zooniverse/Panoptes#1956]
I think https://github.com/zooniverse/Panoptes/blob/master/app/counters/subject_workflow_counter.rb is not taking subjects seen before by a user into account. Which is probably my fault since I missed it initially in this one: https://github.com/zooniverse/Panoptes/blob/master/app/workers/reset_project_counters_worker.rb

Solving this will probably take two things:
- Different counters for "total classifications" and "unique classifications". Otherwise reclassifications won't bubble up the counters to the project homepage.
- I couldn't get SQL to do this uniquing, might be easiest to just add a `counts_towards_retirement` column on classifications and fill that with the lifecycle. Then we can add a simple where clause on it in the counter. We can then also just trigger the count worker from the lifecycle, regardless of whether it's a create or an update, since the worker can look at that field to know if an increment is needed.

**Comment by camallen** [comment]
Agree re the 2 counters.

We do track the seen_before state on classification metadata [here](https://github.com/zooniverse/Panoptes/blob/e9da5ecba90e19ed4a289753f33053220e242413/lib/classification_lifecycle.rb#L119) but only if the subject_id was tracked in the seens in time (lost of cases where it won't be). 

The proposed `counts_towards_retirement` sounds like it would work well enought. I think it may suffer when same user /subject (dups) classifications are lifecycled at the same time and the seens are not created yet. Maybe moving the seen_ids from an array to rows with a uniq constraint on user_id / subject_id will solve that.
