### ISSUE TITLE
Add index for valid_email column

### ISSUE THREAD

**Issue by astopy** [zooniverse/Panoptes#1967]
It looks like there's no index for this field (in the `users` table). We use this to avoid including invalid addresses on our mailing lists, so it should really be indexed.

**Comment by astopy** [comment]
cc @mrniaboc

**Comment by astopy** [comment]
@camallen @marten @zwolf Could we make this a high priority? We absolutely have to start filtering on this column as soon as possible for all of our mailing lists, which we can't do when it's not indexed.

**Comment by camallen** [comment]
@astopy will you only be querying on the tr

**Comment by astopy** [comment]
I'm pretty sure we'll only need to find trues

**Comment by camallen** [comment]
@astopy see my comments on the PR.

**Comment by camallen** [comment]
closing this based on the results of the PR work.
