### ISSUE TITLE
Number of users remains fixed at one value

### ISSUE THREAD

**Issue by mwp-tj** [zooniverse/Panoptes#1968]
Hi guys,

This is regarding the MWP. We just fully launched today! Woohoo! However, the number of users working on our project seems to be static at 129. Could you look into this if it's possible?
https://www.zooniverse.org/projects/povich/milky-way-project
Thank you so much!

Best,
Tharindu

**Comment by marten** [comment]
#1982 might solve this when it gets deployed later today.

**Comment by mwp-tj** [comment]
Thanks guys! This fixed the problem 👍
