### ISSUE TITLE
Gold standard classifications stopped working

### ISSUE THREAD

**Issue by mwp-tj** [zooniverse/Panoptes#1969]
The gold standard classifications in the Milky Way Project workflow - Learning the ropes(#2250) have stopped working as of now. This used to work flawlessly but our users are now reporting that this feature is broken.
https://www.zooniverse.org/projects/povich/milky-way-project/talk/505/76483?comment=170287

Any idea as to why this is happening?

**Comment by eatyourgreens** [comment]
Looks like this was removed in zooniverse/Panoptes-Front-End#2923. Could you raise an issue on that repo?
