### ISSUE TITLE
Already seen flags not showing when loading an inactive workflow when already classified all the subjects in that workflow

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes#1971]
I just loaded workflow 2063 It's inactive but we're using for the science team review of data. I have classified all the data live on there from the annotations, but it didn't give me an 'already seen' when I loaded the url. I have previously gotten already seen on that workflow.

**Comment by camallen** [comment]
@mschwamb was this a new workflow? or the set of newly linked data on an old workflow?

**Comment by mschwamb** [comment]
old workflow with no new subject sets on it. 

We do have a new workflow and a subject set attached to it, but this new subject set is not linked to 2063
