### ISSUE TITLE
Project#classifiers_count was outdated for project 2025. Was 129, should've been 667.

### ISSUE THREAD

**Issue by marten** [zooniverse/Panoptes#1973]

**Comment by simensta** [comment]
I think this is an issue for Project 1506, as well. The project's classifiers_count was 124 before launch, and after launch the count remains 124.

**Comment by mwp-tj** [comment]
Hi Marten,

The MWP (Project 2025) classifiers_count is still stuck at 667 and this has been the case for 2-3 days. I am assuming that we have more users participating than being shown in the front page!

**Comment by marten** [comment]
Might be fixed by #1982

**Comment by marten** [comment]
Counter is behaving normally these days. Closing this issue.
