### ISSUE TITLE
Data completed message not showing on Supernova Hunters

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes#1974]
I was checking around on other projects for some inspiration for my own and encountered that Supernova Hunters is out of data and says finished for the subject  I see non-logged in but the automessage saying the site is out of data isn't showing. I thought I'd mention it.

**Comment by camallen** [comment]
@mschwamb this is a know issue, the fininshed banner is derived from the subjects vs retired counts matching. In this case the set counts include data that was used pre-launch and the retired counts only count from the launch date. Solutions are to unlink the pre-launch data set / modify the launch date to include the retired counts.
