### ISSUE TITLE
Volunteer having issues seeing subjects in Comet Hunters

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes#1989]
It might be he's out of data and the already seen data isn't showing. Thought I'd start with the backend.

operating system: Windows 10
browser: Google Chrome (53.0.2785.116)

 Here's the [thread](https://www.zooniverse.org/projects/mschwamb/comet-hunters/talk/210/98787?comment=181589) on Talk

**Comment by camallen** [comment]
I don't think this is related to being out of data. It Seems as if the subject images themselves won't load. 

Some screen shots of the problem if it still exists would be useful, e.g. does the subject api call resolve with media resource paths? it'll be a spinning wheel i think vs not resolving and it says loading classification (from memory).

**Comment by mschwamb** [comment]
Will do.

**Comment by mschwamb** [comment]
@camallen  The volunteer sent me a screen shot. I've sent it in email to you since he didn't want it posted publicly.

**Comment by camallen** [comment]
Thanks @mschwamb - seems like the subject isn't loading but the api response has worked (this is an assumption based on the UI). It could be privacy blockers or the like activated not allowing the image to load. Perhaps get them to try without (if they have them) or the browser incognito mode to see if it works?

**Comment by mschwamb** [comment]
seems like this issue has either resolved or the user moved on so I'm going to close and will reopen if it pops up again.
