### ISSUE TITLE
Pan and zoom as workflow configuration

### ISSUE THREAD

**Issue by srallen** [zooniverse/Panoptes#1991]
Pan and zoom UI was only hidden behind the `experimental_tools` project configuration array. It should be a workflow configuration since I don't think we want the UI enabled for everyone. I have a PR on PFE that makes it a workflow config option as well as make it public. Could we check for projects that have `pan and zoom` in its `experimental_tools` array and if true set all of its linked workflows' configuration with `{ pan_and_zoom: true }`?

**Comment by camallen** [comment]
Sounds like a plan. Once of use will have to get a rake task data migration for this.

**Comment by srallen** [comment]
I think @mrniaboc will send out an email about the new features we're making public sometime early next week. It'd be nice if we can include pan and zoom with this, so let me know if the rake task can be run early next week. If not, it can be included with an email later.

**Comment by camallen** [comment]
@zwolf something for this week?

**Comment by zwolf** [comment]
pair on this thusday?

**Comment by zwolf** [comment]
:sadpanda:

**Comment by zwolf** [comment]
All workflows on projects that have the "pan and zoom" experimental tool enabled now have "pan_and_zoom: true" in their configurations.
