### ISSUE TITLE
Classifications sort descending does not work

### ISSUE THREAD

**Issue by rafelafrance** [zooniverse/Panoptes#1993]
The tests scripts indicate that this should work
> https://github.com/zooniverse/Panoptes/blob/52910bb7c8cb77c7203cf7751f355c010f9d7cae/spec/support/recents.rb#L43-L48

However, when I send this request the items are not sorted
> https://panoptes.zooniverse.org/api/classifications?project_id=1558&user_id=404980&sort=-created_at

Maybe I'm formatting the request incorrectly? Or maybe the minus sign is getting stripped off before it hits the server logic the tests above hit?

**Comment by eatyourgreens** [comment]
That test is for Recents, so you need to call the user recents API endpoint. Here's an example from the Diagnosis London code.
https://github.com/zooniverse/diagnosislondon/blob/master/app/profile.cjsx#L35-L38
The URL will look something like https://www.zooniverse.org/api/users/149/recents?workflow_id=2368&page_size=12&sort=-created_at

**Comment by rafelafrance** [comment]
As long as I can filter on user_id then we're good.... And I see
https://github.com/zooniverse/Panoptes/blob/52910bb7c8cb77c7203cf7751f355c010f9d7cae/spec/support/recents.rb#L10

So I'll close this. Thank you very much for you help.

**Comment by eatyourgreens** [comment]
By the way, that endpoint gives you recently classified subjects. I'm using it to link to Talk for the 10 most recent pages that someone classified.

If you do need recent classifications, sorting by `-updated_at` on the classifications endpoint may work (but I haven't tested that and could well be wrong.)

**Comment by rafelafrance** [comment]
Excellent! It sounds like you're doing roughly the same thing as Notes from Nature's User Fieldbook. This may simplify my code a bit.

**Comment by eatyourgreens** [comment]
Cool, in that case you might be able to just copy the logic used here. https://github.com/zooniverse/diagnosislondon/blob/master/app/profile.cjsx
