### ISSUE TITLE
Change default text for Dropdown fields when Options not added

### ISSUE THREAD

**Issue by MobileMaggie** [zooniverse/Panoptes#2000]
Please change the default text from "Select..." to "Enter..." when a Workflow contains dropdown fields for which no Options have been added (i.e. purposely left "Allow Create" due to absence of relevant options list)
<img width="669" alt="when no options are added for dropdown fields" src="https://cloud.githubusercontent.com/assets/1629708/19409040/71d18486-92c3-11e6-9482-1c3dad014419.png">
![enter instead of select](https://cloud.githubusercontent.com/assets/1629708/19409041/74244106-92c3-11e6-90ec-4f14a60117a8.png)

This will improve the clarity of instructions for users, that they are meant to enter text in those fields, rather than select from a drop-down menu (because in those cases there is no drop-down menu)

**Comment by camallen** [comment]
Thanks for the report @MobileMaggie, this is the api repository and the UI / front end repo is https://github.com/zooniverse/Panoptes-Front-End. Best to file these reports on that repo as thereyou'll get the attention of UI developers.

That said I think these UI elements are built using HTML select tags to create the selection dropdowns, https://developer.mozilla.org/en/docs/Web/HTML/Element/select and I think this is the default setting across all browsers.
