### ISSUE TITLE
Add new push notification preferences

### ISSUE THREAD

**Issue by marten** [zooniverse/Panoptes#2006]
- Add `global_push_notifications` and `project_push_notifications` to User.
- Add `push_notifications` to UserProjectPreference.
- Modify initializer for new project preferences so that `push_notifications` field populates correctly.
- Add migration to use the `global_email_communication`, `project_email_communication` and `email_communication` values as the initial values for the new columns in the DB.

/cc @robinschaaf

**Comment by robinschaaf** [comment]
Hi @marten - by any chance is this something you (or someone else) could get to within the next couple of weeks?
Thanks!

**Comment by marten** [comment]
Closing this. It'll come up again once we have a mobile developer again.
