### ISSUE TITLE
Project 2025: retired subject count and % completion incorrectly reported

### ISSUE THREAD

**Issue by mwp-tj** [zooniverse/Panoptes#2023]
For the MWP (Project 2025), we are seeing incorrect stats on our workflow stats page.

Retired subject count was approaching 130 but a few days back, it was reset to 3. Just today, the % completion rate was reset to 0% from 17%. 

Anyone know what's going on?

Thanks for your help!

**Comment by camallen** [comment]
https://github.com/zooniverse/Panoptes/pull/2012

**Comment by camallen** [comment]
Have you recently unlinked subject sets that have only got new data in them?

**Comment by mwp-tj** [comment]
We have not unlinked subject sets since we launched! To be more specific, we have not edited our workflows/subject sets since launch.

Also Cam, do you know if it is possible for us to intelligently retire subjects based on the following criteria : If X users did not classify anything, retire subject. ?

Thanks!

**Comment by camallen** [comment]
@mwp-tj we added the launch_date to your project recently (it should have had this set the day the email went out). This date is used as a starting point for the counters. 

So you've got data retired before the actual launch event, i can modify the launch date to try to catch these earlier retirement events, what date did you you start getting real classification data from?

**Comment by camallen** [comment]
Re smarter retirement, we can do certain events at the moment depending on the workflow. What kind of rules are you looking for?

**Comment by mwp-tj** [comment]
Hi Cam,

We did not have any retirement events prior to the launch date (Sept-15).. but before you fixed the launch date, we had roughly 123 retirement events. I am assuming that this should not have changed when you made the change.

We are looking for the following rule: if X users classified NOTHING in a given subject, retire that subject.
(ex: If 5 users found nothing of interest in a given subject, i.e they did not use any classification tool, we would retire this subject rather than make 30 users classify it (rather unnecessarily I should say)

Thanks for your help!

**Comment by camallen** [comment]
The database shows 176 total retired but only 3 since launch.

**Comment by camallen** [comment]
But that count is using the incorrect field to determine the retirement date. @mwp-tj you are entirely correct, i'll get a PR up to fix this. 

Thanks for your persistence :+1:

**Comment by camallen** [comment]
@mwp-tj can you please open a new issue for the workflow retirement rules?
> We are looking for the following rule: if X users classified NOTHING in a given subject, retire that subject.
(ex: If 5 users found nothing of interest in a given subject, i.e they did not use any classification tool, we would retire this subject rather than make 30 users classify it (rather unnecessarily I should say)
