### ISSUE TITLE
Workflow retirement rules : Getting rid of unnecessary classifications

### ISSUE THREAD

**Issue by mwp-tj** [zooniverse/Panoptes#2026]
We(project 2025) are looking for the following rule to retire our subjects: if X users classified NOTHING in a given subject, retire that subject.
(ex: If 5 users found nothing of interest in a given subject, i.e they did not use any classification tool, we would retire this subject rather than make 30 users classify it (rather unnecessarily I should say).

Is this possible?

Thank you for the great work you do Zooniverse devs 👍

**Comment by camallen** [comment]
I assume you don't want this for the learning the ropes workflow?

**Comment by mwp-tj** [comment]
That's correct. We only want this feature for our main "Mapping the Milky Way" workflow (ID:2245)!

**Comment by camallen** [comment]
@mwp-tj fyi, the retirement change went live in the last hour, it's not retrospective though. We are working on making our system do this but it's not live yet.
