### ISSUE TITLE
Allow Words from the Researcher in Project Resource

### ISSUE THREAD

**Issue by wgranger** [zooniverse/Panoptes#2035]
In preparation for the new project landing page, there should be a tag on the project resource that allows project builders to insert text as "Words from the Researcher." This text will be added under the "project details" section of the project builder on the front end. See attached image (lower left) for how the text will later appear on the new landing page.

![desktop copy 21](https://cloud.githubusercontent.com/assets/14099077/20153496/8de2a55a-a688-11e6-8621-2c171cec30d1.png)

**Comment by camallen** [comment]
@wgranger we should be able to add a new project page for this. It'll have a specific key and be called out like the about / education / results project pages. 

I think you'll just need to add another editor to the lab for this, similar too https://github.com/zooniverse/Panoptes-Front-End/tree/master/app/pages/lab/about

**Comment by wgranger** [comment]
It could work that way. The aim is to have the researcher or project builder input this info via an input box in the "project details" section of the lab, rather than the about section. In this sense, it would work similarly to the project description, introduction, or workflow description. Were you thinking to put it into a URL key instead to keep the project resource from getting too bloated?

**Comment by camallen** [comment]
@wgranger does the content need to be translated?  @zwolf thoughts on how we do this?

**Comment by zwolf** [comment]
Could be:

1. added as an attribute to the project table
2. added to the project's configuration jsonb
3. added as an attribute to the project_contents table
4. added as a new project page

My vote would be for option 3. Translation seems as necessary for this as for anything else on the page, and sitting it alongside other project descriptors seems like the most obvious way to go about it. Obviously the vast majority of projects won't have this new text, so will the block just be blank for most projects? If this should only be visible for certain projects (along with the rest of the project page update) then it will have to be a page, keyed in the url.

**Comment by wgranger** [comment]
@camallen If we are currently translating a project's description and about tabs, it makes sense that this should also be translated.

Also, just for clarity, this work is for the new project landing page that is replacing the current project landing page.

**Comment by camallen** [comment]
I'm deferring to @zwolf on this as he's outlined all the issues and highlighted solution 3 (which seems appropriate for me). 

Looping in #1304 too as we could solve both issues for this work.

**Comment by wgranger** [comment]
@zwolf How about we name this `researcher_quote`?
