### ISSUE TITLE
Subject serializer metadata loses query params

### ISSUE THREAD

**Issue by zwolf** [zooniverse/Panoptes#2053]
The `next_href` and other URL values in the subject metadata do not include query parameters that were on the original request. I was going to use the python client to add a subset of a subject set to a different set. The client uses the metadata for pagination, so the first page was fine, but the second page's URL metadata was just `/subjects?page=2` and I got a bunch of Snapshot Supernova data.

**Comment by camallen** [comment]
this was fixed by #2239
