### ISSUE TITLE
Project workflow links

### ISSUE THREAD

**Issue by srallen** [zooniverse/Panoptes#2054]
While testing zooniverse/Panoptes-Front-End#3235, I found that my test project in production, id `1761` has workflow `2111` in its links, but 404s. This is causing an issue with the workflow exports UI since it is written currently to use a project resource's workflow links. I would presume at some point in the past I deleted workflow `2111` via the UI. Should that workflow still be in the project resource's links?

**Comment by zwolf** [comment]
Keeping them linked isn't a bug. But maybe deactivated workflows should be filtered out of a project's links in the project serializer.

**Comment by camallen** [comment]
Duplicate of #1861

**Comment by srallen** [comment]
Fixed in #2073.
