### ISSUE TITLE
Survey values are weirdly processed in data exports

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes#2066]
Treeversity is a project that uses the survey tool. When I look at the data from the survey in the data exports, I see that the chosen values are all-caps versions of the original text with all spaces and vowels(!) removed. So, for example, the option "Leaf" becomes "LF" and the option "Autumn leaf color" becomes "TMNLFCLR". This is really unintuitive for project groups. I'm okay with dropping spaces, but please keep the vowels! It would also help to keep the original capitalization.

**Comment by camallen** [comment]
@mkosmala what do the task survey key => values look like in the workflow. I think this is a vestige of the survey csv uploader setting those keys.

**Comment by mkosmala** [comment]
@camallen The CSV that we upload doesn't have a key column. We have a name and a description. I'm sure something is converting names to (weird) keys, but I don't Panoptes well enough to know where. The Project Builder doesn't have anything other than names showing. I'm pulling a workflow export right now...
CC: @donnytree

**Comment by eatyourgreens** [comment]
Looks like this is something that the survey task editor is doing in the front end here: https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/classifier/tasks/survey/editor.cjsx#L370

**Comment by eatyourgreens** [comment]
Issue moved to [zooniverse/Panoptes-Front-End #3290](https://github.com/zooniverse/Panoptes-Front-End/issues/3290) via [**ZenHub**](https://www.zenhub.com/)

**Comment by camallen** [comment]
I think we should interpolate the translated strings instead of the task lookup keys in the classification dumps for the survey tasks. somewhere around [here](https://github.com/zooniverse/Panoptes/blob/c74a9afc583c408c64fd530797e86feb9c56247e/lib/formatter/csv/annotation_for_csv.rb#L14)
