### ISSUE TITLE
Ensure subject set counters run after all uploads

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#2067]
The python api client (i think the project builder) sensibly batches the linking of subjects to a subject_set. However since https://github.com/zooniverse/Panoptes/commit/9922106ab11f1a6e6fdd72ae3ed02d97bf5caca7 the counters will cancel and not reschedule. As each batch call to link will trigger the rate limit checker the final final batch upload recount may not run and thus leave the counts off. 

This is particularly bad as a lot of metrics (e.g. finished) are derived from these counts. We should ensure the counters produce correct results without swamping the database on rescheduling.  

@marten @zwolf thoughts?

**Comment by marten** [comment]
@parrish is there any way of making sure a congested worker *always* runs once after the congestion timeout window?

**Comment by camallen** [comment]
This issue needs to be fixed asap as it can leave subject_set subject counts short of the actual count. These subject_counts are then used in the finished calculations and this means we may be reporting the workflow / project as done when it still requires more effort.

Thankfully the subject selector will still return users non-retired / unseen images if they proceed past the finished banner but most likely there weren't that many users.

**Comment by parrish** [comment]
If you're [canceling](https://github.com/zooniverse/Panoptes/blob/master/app/workers/subject_set_subject_counter_worker.rb#L7) the jobs when it's too busy rather than rescheduling (`reject_with: :reschedule`), then congestion doesn't worry about it.

Alternatively, you could create a job to run later and on each rejection update the job to occur after the backoff time reported by congestion.

**Comment by camallen** [comment]
closing as count workers reschedule now, https://github.com/zooniverse/Panoptes/blob/422cfe7cfdfe98e542a43d17958699ae43f76380/app/workers/subject_set_subject_counter_worker.rb#L7
