### ISSUE TITLE
Sort alphabetically project list in email preference in account settings

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes#2077]
I noticed the project subscription list is not in a weird order, so you have to search for the project you want to uncheck or check. It would be easier if it was in alphabetical order. The user after 5 entries is going to expect that this will be alphabetical, and it would make it a lot easier to take find the project you're looking to remove yourself from.  This was originally on the front end by @parrish says it is a backend issue (https://github.com/zooniverse/Panoptes-Front-End/issues/1489#issuecomment-265269756)

![1ee874f4-4ee6-11e5-8f12-4ec39f977135](https://cloud.githubusercontent.com/assets/753325/20943780/f6a1ef5c-bba4-11e6-8893-bcfd589b6456.png)

**Comment by parrish** [comment]
Thanks!
