### ISSUE TITLE
not receiving comet hunters classification export

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes#2104]
I'm not getting the Comet Hunters classification data export. I do get Planet Four: Terrains. I waited for 18 hours with no email. I tried again today and it's on the 5 hour mark and no export has been received. I think something's wrong/breaking for Comet Hunters. Can someone take a look?

**Comment by mschwamb** [comment]
10 hours and still no export.  Might be related to https://github.com/zooniverse/Panoptes-Front-End/issues/3084

**Comment by mschwamb** [comment]
I should note, there's no issues with the subjects export. I was sent that sucessfully

**Comment by mschwamb** [comment]
I'm giving a talk at a conference on the 4th, so I'm using the old classification dump that's linked on the side of the export page. I don't actually know when that's from so I'll have something to show, but I'm not getting any annotation export emails for Comet Hunters. So something has definitely broken here. I get them from my other Zooniverse panoptes projects just fine. If it's possible to manually send me the latest classifications when folks are back in the office after the holidays and new year's break , that would be helpful.  Thanks,

**Comment by camallen** [comment]
I'll look into it @mschwamb

**Comment by mschwamb** [comment]
Thanks @camallen
