### ISSUE TITLE
Feature flags for all non-essential features

### ISSUE THREAD

**Issue by marten** [zooniverse/Panoptes#2118]
For instance, most workers should have something like `reschedule_until_later if disabled_by_flipper?` as their first line, so that we can disable them easily if a specific one causes issues (locking, ...) under high loads.

There are probably plenty of other things that aren't workers.

**Comment by zwolf** [comment]
superset that includes https://github.com/zooniverse/Panoptes/issues/2252

**Comment by zwolf** [comment]
and https://github.com/zooniverse/Panoptes/pull/2262 and https://github.com/zooniverse/Panoptes/pull/2261 and https://github.com/zooniverse/Panoptes/pull/2263
