### ISSUE TITLE
Tweaks to Organizations resource

### ISSUE THREAD

**Issue by amyrebecca** [zooniverse/Panoptes#2123]
Trying to keep track of the conversation in lab-app so that little changes we might need don't get lost

- [x] PUTting incomplete patches gets rejected by validation
- [x] primary_language field not returned when an organization is fetched
- [x] sort params don't appear to be working
- [x] remove redundant `name` field
- [x] add owner's user resource `display_name` to owner link for organization roles
- [ ] add organization documentation to apiary
- [x] add pages for organizations
- [x] add `:listed-at` to the attributes being serialized
- [x] API should handle setting the title field like the project resource does
- [ ] add organization slug serialized attribute to resource similar to projects. I remember vaguely a conversation about organization slugs, but I don't remember what the decision is, so let me know if there's a good reason to not do this. Looks like this is what builds the slugs: https://github.com/zooniverse/Panoptes/blob/52910bb7c8cb77c7203cf7751f355c010f9d7cae/app/models/concerns/slugged_name.rb
~~- [ ] add a serialized `avatar_src` and `background_src` to organizations. Not a high priority, but I recall this was done for projects for optimization~~

**Comment by srallen** [comment]
Just another note: `name` appears to be redundant with `display_name`. `display_name` is what is used by projects on the front end and so the `name` property can probably be dropped.

**Comment by chrislintott** [comment]
At one point, name was the name used for publications - i.e. the ‘Real name’ we ask for on signup. Or am I confused?

**Comment by amyrebecca** [comment]
If you're confused we are too :) But wouldn't what you're describing also be the `display_name`?

**Comment by srallen** [comment]
@chrislintott I believe that's true for users, not projects.

**Comment by amyrebecca** [comment]
AH now I understand the distinction that's being drawn. Thank you for that :)

**Comment by srallen** [comment]
@zwolf Another tweak: it would be useful for the returned resource for organization roles to include in the owner links the user `display_name` so we don't have to fetch for each user to get their display names for the UI. This would also be beneficial for projects' project roles too at some point.

**Comment by zwolf** [comment]
This is getting kind of awkward with all the checkboxes being added. 

Regarding slugs: orgs are going to live at top level domains and are otherwise reachable by id. What would you use them for?

Re: media includes, there is no `background_src` on projects, but it is included (along with avatar and attached_images) in the linked media. `avatar_src` already exists in both, serialized like this: https://github.com/zooniverse/Panoptes/blob/52910bb7c8cb77c7203cf7751f355c010f9d7cae/app/serializers/project_serializer.rb#L84 Does that work or do you need something different?

**Comment by mcbouslog** [comment]
I think this has been substantially addressed? Closing in favor of opening a new specific issue if something comes up related to the many topics this issue covers, but anyone please feel free to re-open if prefer.
