### ISSUE TITLE
add in an entry for  retirement_reason  in subject export if subject is retired due to normal classification limit hit

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes#2182]
It's really confusing that the  retirement_reason column is empty if the project doesn't have custom retirement rules. It's possible a project may switch from one type of retirement to another, so it would be good to have an entry for all retirement types including normal non-custom ones.

**Comment by marten** [comment]
Agreed, we should set it to "classification_count" when we retire using the default rule.

**Comment by mschwamb** [comment]
That would be great.
