### ISSUE TITLE
Panoptes Talks loading issue

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes#2189]
I can't successfully use Panoptes Project Talks or Panoptes Talk of and off. I presume it's due to loading elsewhere on the site. In case it's helpful:

The project site loads fine, but Talk loading goes to a crawl again. Originally a few hours ago. The recent comments page/query https://www.zooniverse.org/projects/mschwamb/planet-four-terrains/talk/recents isn’t coming up for me until after a 1 minute 20s. Any comments I click on don’t load properly.Took over 2 minutes of sitting there for it to load. It starts off initially as a comment box and not the original comment, and then the side bar and project bar show up.

It's not my internet connection as I can load Ouroboros project websites and Talk just fine.

**Comment by mschwamb** [comment]
If it's helpful. I noticed things have gotten a lot faster on Talk. Some things are still slow, but it's taking less time than above. Not sure if that's related to Europe going to bed. Thought I'd mention it, in case it's useful.

**Comment by camallen** [comment]
Thanks @mschwamb i've made some configuration changes to alleviate some of the load on the database, things should start improving from here (like you've mentioned).

**Comment by mschwamb** [comment]
@camallen thanks. Let me know if you want to keep logging here if  I see things slow down again or it appears fine for the rest of my day.

**Comment by camallen** [comment]
@mschwamb if you feel like reporting, then please do. We've got performance logs we can check but having correlating with your reports can be useful too. 

Also FYI - panoptes talk just came up and down a few times, i've got the system stabilized so performance should improve now.

**Comment by mschwamb** [comment]
Will do.  I'm working on a paper draft, but I'm sure I'll be checking in on Talk more than a few times the rest of today. Thanks for working on this  If you feel inclined to give an update here on [Zooniverse Talk](https://www.zooniverse.org/talk/17/186670?page=1&scrollToLastComment=true) someone started a thread.

**Comment by mschwamb** [comment]
So now the login server is having issues for a bit then it came back. Tried it multiple times from panoptes projects and directly from the Zooniverse site

<img width="1121" alt="screen shot 2017-02-20 at 5 39 24 pm" src="https://cloud.githubusercontent.com/assets/753325/23149966/bfd9e274-f793-11e6-8928-cd4c22cf0a22.png">

<img width="1129" alt="screen shot 2017-02-20 at 5 39 46 pm" src="https://cloud.githubusercontent.com/assets/753325/23149967/c16f5704-f793-11e6-8cf3-f6e38985db2f.png">

While writing this ticket it came back. So not sure if it is intermittent

**Comment by mschwamb** [comment]
and logged out and logged back in and panoptes is having the same slowness of logging and then shows the e body is Null error

**Comment by mschwamb** [comment]
It's typically a 10-20s load time from Hawaii for the classification interface the first time getting to it, and then it's quite responsive. Talk is still responding at the rate as 4 hours ago. It's a little bit slower than normal, but not extremely noticeable.

**Comment by mschwamb** [comment]
Login just got way more responsive.

**Comment by mschwamb** [comment]
Loading of the classification interface also just spend up as well.

**Comment by camallen** [comment]
@mschwamb we had some IO latency issues with the database during those windows you outlined. Things have settled down again now so should be back to normal operations under higher request loads.

I'm going to close for now, feel free to re-open / comment if you want.

**Comment by mschwamb** [comment]
Thanks @camallen. Is it okay if I start uploading subjects today for two of my projects. I currently use the web interface in 350 subject chunks. Happy to hold off for a day or so if that would be useful?

**Comment by mschwamb** [comment]
It just got really slow again on Talk.  I can't reopen the ticket, I don't think I have any permissions on this repo.
