### ISSUE TITLE
Project `active_workflows` ignored deletedness (i.e. `activated_state`)

### ISSUE THREAD

**Issue by marten** [zooniverse/Panoptes#2191]
## Steps to reproduce

* Create project
* Create two workflows and give each of them a distinct subject set with some images
* Mark both workflows as "Active" on the Visibility tab.
* Delete one workflow

*Expected result*: Number of subjects on the project page goes down
*Actual result*: Number of subjects stays the same.

This seems to be the result of `Project#active_workflows` ignoring the `activated_state` of workflows (ignoring the soft-delete).

@camallen pretty sure this isn't intentional, but wanted to double check with you since you added that `Project#active_workflows` scope.

**Comment by camallen** [comment]
Unintentional, it should not be returning deactivated workflows :(
