### ISSUE TITLE
completion bar doesn't update very quickly when you swap subject sets

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes#2201]
I've added subjects to P4: Ridges and nearly 12 hours later the project still says 100% complete. Is there a way that changing subject sets could trigger a recalculation of the progress bar? 

<img width="1125" alt="ba71526c-fa14-11e6-837b-267fea150e53" src="https://cloud.githubusercontent.com/assets/753325/23307049/281a40be-fa4a-11e6-85ed-231748d9259c.png">

**Comment by camallen** [comment]
Removing a subject set from a workflow should trigger a retired subjects recalculation event, currently we're not firing this worker when unlinking sets from a workflow [here](https://github.com/zooniverse/Panoptes/blob/8f800be691d520b5fe6b4ceaab11d17f106399b7/app/controllers/api/v1/workflows_controller.rb#L82). 

@mschwamb fyi - The workflow & project completeness metrics gets updated every hour based on the subject and retired counts for the project's workflows. 

And thanks for the report.

**Comment by mschwamb** [comment]
Yeah @camallen it usually updates, but I'm not sure why it's currently not. Maybe not enough people classifying yet so progress is still 0?

**Comment by mschwamb** [comment]
same thing happening in #2209

**Comment by mschwamb** [comment]
I'm having the same thing happen on P4: Ridges with the new set of data on the site. It's confusing messaging that the out of data box is up and the blue announcement ribbon saying there is data on the site.  I know the more permanent fix isn't in yet. Could someone change the completed flag if possible?

**Comment by mschwamb** [comment]
So because the counters aren't updating, the out of data banner is remaining on the site. I'm getting some complaints from volunteers on why this message doesn't go away.  Can the counters be set to run for P4: Ridges manually if this isn't going to be fixed soon? Thanks.

**Comment by mschwamb** [comment]
Thanks @camallen

**Comment by camallen** [comment]
@mschwamb this is deployed now, let us know if the issue persists.

**Comment by mschwamb** [comment]
@camallen  - this is still happening - just updated images for P4: Ridges several hours ago and P4: Ridges front page is showing there is no data (see https://www.zooniverse.org/projects/mschwamb/planet-four-ridges)

**Comment by camallen** [comment]
@mschwamb it's something that needs some work (https://github.com/zooniverse/Panoptes/issues/2242#issuecomment-315389136). The comlpeteness metric does reset every hour and it's fixed now on it's own accord.
