### ISSUE TITLE
Return user avatar directly in user json (and tell PFE to use it)

### ISSUE THREAD

**Issue by marten** [zooniverse/Panoptes#2204]
The `/api/users/123/avatar/` route in Panoptes is seeing quite a bit of requests from Talk. It's basically an N+1 query, but over HTTP. For each user, Talk has to go and fetch their avatar via a whole separate request.

We should simply include a `avatar_url` in the serialized user response.

**Comment by marten** [comment]
@zach this is pretty much along the same principle as the https://github.com/zooniverse/Panoptes-Front-End/issues/3494 which you're assigned to yourself already. Perhaps you could pick both of them up, or at least the backend bit of this one too?

**Comment by marten** [comment]
Panoptes side: #2216
PFE side: https://github.com/zooniverse/Panoptes-Front-End/pull/3576

**Comment by astopy** [comment]
Should I revert zooniverse/panoptes-python-client#74?

**Comment by marten** [comment]
Technically the avatar contains more things than just the URL, so that method might be fine. @camallen ?

**Comment by camallen** [comment]
@astopy i'd stick with what you have.
