### ISSUE TITLE
duplicate classifiers counted in some classification counts for subject retirement

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes#2207]
On P4: Ridges, we have 
The classification count says there are 9 unique classifications but there aren't

Prothon	2017-02-01 09:01:10 UTC	5495160
Prothon	2017-02-01 09:01:46 UTC	5495160
jmang	2017-02-02 01:18:33 UTC	5495160
geocanuck	2017-02-02 02:23:25 UTC	5495160
Brain_boy128	2017-02-02 11:10:56 UTC	5495160
amartineau	2017-02-02 16:15:03 UTC	5495160
Mr_Astronomy	2017-02-08 15:30:06 UTC	5495160
Mr_Astronomy	2017-02-08 15:30:06 UTC	5495160
not-logged-in-4c383f55c9866d278c2e	2017-02-10 16:42:16 UTC	5495160

export says subject count is 10 - it's actually  7 unique classifications
Prothon	2017-02-02 18:41:49 UTC	5542686
Prothon	2017-02-02 19:38:04 UTC	5542686
phelinity	2017-02-03 08:36:49 UTC	5542686
heldu	2017-02-04 16:53:32 UTC	5542686
heldu	2017-02-04 16:55:51 UTC	5542686
safitoledo	2017-02-04 19:27:59 UTC	5542686
psw42	2017-02-04 22:25:06 UTC	5542686
retepaskab	2017-02-05 17:03:53 UTC	5542686
retepaskab	2017-02-05 17:04:29 UTC	5542686
Henrik-kj	2017-02-05 18:53:02 UTC	5542686

deedlo	2017-02-02 20:16:06 UTC	5541786
deedlo	2017-02-02 20:16:44 UTC	5541786
Prothon	2017-02-02 21:24:39 UTC	5541786
Prothon	2017-02-02 21:27:02 UTC	5541786
mbpriddy	2017-02-02 22:51:34 UTC	5541786
mbpriddy	2017-02-02 22:52:32 UTC	5541786
madeline67	2017-02-05 10:50:54 UTC	5541786
madeline67	2017-02-05 10:52:44 UTC	5541786
Uganalandia	2017-02-06 06:53:47 UTC	5541786
squish5	2017-02-06 09:26:10 UTC	5541786

2% of my subjects got less than the full unique classification count, which isn't a huge deal, but there are 258 subjects out out of my ~40,000 that had 3 or more duplicates in the classifications count, which starts to hurt badly when you're only asking for 10 classifications. 

I know there's been some changes to the backend, so I thought I'd bring it up. Fully understand if this is a do not fix.

**Comment by camallen** [comment]
@mschwamb i think this is a bug in how we count classifications as we don't distinctly query the users (i.e. remove the dups from logged in users). 

@marten @zwolf - thoughts on fixing this using a distinct count around [here](https://github.com/zooniverse/Panoptes/blob/b9b3c6c5d0dd5f79ca703abb0667eacadb89f475/app/counters/subject_workflow_counter.rb#L10) that includes all anonymous classifications and distinct users?

**Comment by mschwamb** [comment]
@camallen I also should mention I didn't check if these classifications were flagged  by panoptes as already seen. I ignore the flags when I parse the classifications csv+json intom something easier to manipulate and remove duplicates based on userid and the hashed ip address i have non-logged in users keeping the first time a user saw the subject.

**Comment by camallen** [comment]
this should have been fixed in #2636
