### ISSUE TITLE
Comet Hunters stats are way off - backend reporting retired subject count incorrectly?

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes#2209]
I noticed today that the Comet Hunters status pages are giving very strange answers. Everything looks okay on P4: Ridges, so I'm not sure what's going on.

<img width="1012" alt="screen shot 2017-03-02 at 6 46 38 am" src="https://cloud.githubusercontent.com/assets/753325/23517374/4452fa5e-ff14-11e6-9b95-ac74e72a1113.png">

I just finished uploading subjects on Friday night Hawaii time , so there's no way they're done. I only have one subject set linked. There are no subjects that have 15 classifications yet according to subject data dump's classification count and I use retirement count for the stats page plots. So my stats should not be anywhere close to 64% complete for the HSC Search workflow. 

I only have one subject set linked 8398 on workflow 1949. I haven't checked the other workflow, but it also seems off from where it was on Friday.  I thought it was further along, but it will take me longer to check it.

**Comment by camallen** [comment]
@mschwamb i think this is related to the same bug that I mentioned here, https://github.com/zooniverse/Panoptes/issues/2201#issuecomment-282308281 

I don't think we're resetting the retired counts properly.

**Comment by mschwamb** [comment]
closing as duplicate of previous ticket.
