### ISSUE TITLE
remove jisc mailer sync workers

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#2223]
e.g. remove [these](https://github.com/zooniverse/Panoptes/blob/03f61b1ee185805704f5ca21ca13a0dec8793acf/app/mailers/jisc_mailer.rb) jisc mailers / convert them to sync with mailman

**Comment by astopy** [comment]
I don't think Mailman has an email command analogous to Listserv's `quiet add` command, and I don't think it can do authenticated requests via email. The jisc mailers should just be removed completely in favour of #1889.

**Comment by camallen** [comment]
Sounds like a plan @astopy thanks for the feedback 👍
