### ISSUE TITLE
Open Shortcut Task Export to Multiple Answers

### ISSUE THREAD

**Issue by wgranger** [zooniverse/Panoptes#2228]
In anticipation for the Stellar Watch launch on Wednesday (3/15) the Shortcut task needs to allow the possibility of multiple shortcut answers. Currently, only one shortcut answer is allowed. The logic has been hooked up on the front-end with this [PR](https://github.com/zooniverse/Panoptes-Front-End/pull/3532). 

I believe the only backend change needed is with the exporter? If so, I believe [this](https://github.com/zooniverse/Panoptes/blob/0871ff599d7f11c4715acd3746eebca6efad272e/lib/formatter/csv/annotation_for_csv.rb#L54) is the line that needs to be addressed so the `shortcut` type behaves more like `multiple` by receiving an array of index values. However, I could be missing something.

**Comment by marten** [comment]
Good point, seems like that line you pointed out should do away with the whole distinction of singlular label vs. multiple labels. How about just getting all labels, and if there's only one label, unwrap the array and return the only element rather than an array? Might be nicer than yet another special condition in there.

**Comment by marten** [comment]
Take note, I don't have time to work on this. Most of us have clocked out for the week, if it's urgent, you might need to remind people on monday.

**Comment by wgranger** [comment]
Doesn't need to be done today (PR is still up on the frontend fix), but would be nice to have it done Monday.

**Comment by zwolf** [comment]
That'd work, @marten, but the "multiple" type can have a single answer as well so the type still needs to be checked. That is, unless we can return just a type-consistent, single-element array in all cases, which would make more sense from a data processing standpoint.

I'll take a better look at this tomorrow when I'm back but it's not the greatest time to need something turned around overnight. This won't impact the project outside of exports, though.
