### ISSUE TITLE
Track when changes are made to a project

### ISSUE THREAD

**Issue by beckyrother** [zooniverse/Panoptes#2235]
Including adding new subjects and additional language translations, to be shown on the updated home page in the News section as well as possibly on the project's home page.

@eatyourgreens @srallen

**Comment by wgranger** [comment]
Is this still under consideration? The new landing page is about finished, but I don't think this is available yet in the backend. This descriptor could be omitted on the landing page until the backend update is made. Attaching an image for reference:

<img width="225" alt="screen shot 2017-05-04 at 3 22 38 pm" src="https://cloud.githubusercontent.com/assets/14099077/25723428/93cd7bf4-30dd-11e7-823b-060da43efd61.png">

**Comment by beckyrother** [comment]
If it's not, is it possible to show the three most recently launched projects from the Projects page?

**Comment by wgranger** [comment]
That can be done. As the landing page currently sits, "New ___ added" has simply been removed and the three most updated projects are still listed. If showing the three most recently launched projects, the layout might need to be changed a bit since there is a project card of the newest project directly above this section.

**Comment by beckyrother** [comment]
Good point, that does seem a bit redundant. @camallen is tracking changes a possibility?

**Comment by camallen** [comment]
We can. Just noting that adding new subjects doesn't modify anything on a project but we could look at modifying the project's updated_at timestamp when new subjects come in. Likewise when updating / adding new translations.

**Comment by marten** [comment]
That mockup lists the specific change in text though, so just the timestamp is probably not enough. Also, that timestamp might be changing for many other reasons too, so we probably don't really want to use that for this specific use case?
