### ISSUE TITLE
Remove retired N+1 in subject selector serializer

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#2236]
Modify the lookup [here](https://github.com/zooniverse/Panoptes/blob/942f74d1fe23b1667cb1e37f7544a22cdee30780/app/serializers/subject_selector_serializer.rb#L25) for the retired subject status to not be an N+1. Probably push it into the selection context like the favourites finder did to consolidate the db work.

**Comment by camallen** [comment]
@zwolf you got any bandwidth to work on this?

**Comment by zwolf** [comment]
Yeah, I can take a look.
