### ISSUE TITLE
Reset the project completeness when linking workflows

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#2242]
make sure we reset the completeness values when linking worklfows and touch the project updated_at timestamp to reset the metric as it's used to signal finished banners on the client.

**Comment by camallen** [comment]
Also attempt to reset the completeness metric on any subject set linkage but take care to run it after re-calculating the subject counts / retired counts

**Comment by camallen** [comment]
Changing this would speed up the removal of the finished banners, a persistent bug bear of project owners.

**Comment by mschwamb** [comment]
This is still happening. Which looks confusing when you tell volunteers via social media a site is back with data, but then the messaging is really confusing

![image](https://user-images.githubusercontent.com/753325/40190884-a91f3668-599b-11e8-82e9-0cc4e4a70694.png)
