### ISSUE TITLE
Collection default subject

### ISSUE THREAD

**Issue by srallen** [zooniverse/Panoptes#2256]
Gravity Spy would like for their volunteers to be able to select what the prototypical subject is for a collection. Right now, the front end just fetches the first subject in the links array and displays that. Instead, the volunteer should be able to select which one to load for the collection preview. 

I thought that a `configuration` object similar to workflows might work for this purpose where we can write arbitrary key value pairs. Which ever subject is selected, its id and media source would be written to the configuration and that would be what is loaded as the prototypical subject. 

I'm also open to suggestion about any better way to do this.

**Comment by camallen** [comment]
@srallen do you have other key value pairs you'd like to write to a collection resource? If not then i think we should just have a default_subject_id column that can be set for each collection. Happy to add the config object if it'll be useful though.

**Comment by srallen** [comment]
@camallen looking over their list of feature requests, I don't _think_ so. A `default_subject_id` column would work for this.

**Comment by eatyourgreens** [comment]
How about `avatar_src`, like serialised users? To avoid the extra resource lookup just to get an image URL.

**Comment by camallen** [comment]
Nice!

**Comment by srallen** [comment]
That's a good idea. If we do serialize the media source, could the fallback behavior if there is no default subject selected return the media source of the first linked subject? That is what we do on the front end. We refactored that request to pass an array of subject ids, but having no subject request at all just for their media sources would be great.

**Comment by camallen** [comment]
@srallen is this needed for SGL? or can it wait?

**Comment by srallen** [comment]
@camallen it can wait. It's just a request for Gravity Spy.

**Comment by srallen** [comment]
Closed by #2296
