### ISSUE TITLE
should we feature flag counting subjects for users

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#2264]
@zwolf should we feature flag to avoid counting the subjects for users on login? We cache that value but a lot of people logging in may cause some heavy reads on the subject table. Thoughts?

**Comment by zwolf** [comment]
My concern would be how PFE would handle that value being missing. If it would just drop the whole thing, that'd be fine, but I'm afraid it would choke on the nulls.

**Comment by camallen** [comment]
That value is only used in messaging to the user when they are uploading data in the lab and it's also used on the admin page. It's mostly used api side to allow subject creates to proceed.

**Comment by camallen** [comment]
closing this for now.
