### ISSUE TITLE
/subjects/queued endpoint doesn't have links for subjects

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/Panoptes#2268]
I'm not sure if this is a feature or a bug, but I'm seeing a difference between the subjects returned by a query like `/api/subjects?page_size=30&workflow_id=2368` and `/api/subjects/queued?page_size=30&workflow_id=2368`. The response to the second query doesn't have `subject.links` for any of the returned subjects.

Not a big deal at the moment, but I noticed it while running some Diagnosis London code that looks up linked subject sets to display metadata (eg. volume title) next to each subject, similar to the group metadata in Operation War Diary or Science Gossip.

**Comment by camallen** [comment]
Right - we're using a different serializer to streamline the response on this end point for subject selection. We could take some additional param context that would include the links in the serialized repsonse. What links do you need, just the subject_set ones?
