### ISSUE TITLE
Tutorial request with workflow ID and include of attached images returns all project images

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/Panoptes#2279]
[FOR AFTER SGL]

The following request:
`https://www.zooniverse.org/api/tutorials?workflow_id=1610&include=attached_images`
returns the desired tutorial (ID 143) and linked media to 20 (`page_size` default) attached images related to resources with id `52`(?), not just the tutorial attached images as expected:
<img width="683" alt="screen shot 2017-03-27 at 3 41 14 pm" src="https://cloud.githubusercontent.com/assets/12118751/24378929/622a4f82-130a-11e7-929c-5dc2a9da0a91.png">

Example above from Gravity Spy (project ID 1104), Beginner workflow (ID 1610).

**Comment by camallen** [comment]
This does look like a bug in the media links we're serializing, though not sure why. 

Any solution should should move the controller joins [here](https://github.com/zooniverse/Panoptes/blob/7a856c3a41882e264839bcd945624dd6994736fb/app/controllers/api/v1/tutorials_controller.rb#L16) to use the serializer [has_many_filters](https://github.com/zooniverse/Panoptes/blob/7a856c3a41882e264839bcd945624dd6994736fb/app/serializers/concerns/filter_has_many.rb) to preserve paging links correctly and we can use the serializer filter DSL to filter by kind as well.
