### ISSUE TITLE
/subjects/queued endpoint is scrambling subject locations

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/Panoptes#2293]
Subject locations should match the order specified when the subject was created.

zooniverse/Panoptes-Front-End#3577 shows that this is fine for subjects requested by ID from the `/subjects` endpoint, but the array order is not being preserved for subjects requested from `/subjects/queued`.

**Comment by marten** [comment]
I've done some minor digging. Looks like `SubjectSelectorSerializer.page({}, Subject.where(id: 6532831)).to_json` exhibits this issue. But not `SubjectSelectorSerializer.resource({}, Subject.where(id: 6532831)).to_json`.

**Comment by camallen** [comment]
@marten i've got a PR up to solve this, #2294
