### ISSUE TITLE
I'm on the upload white list  now it says I've hit my upload limit and need to contact the Zooniverse

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes#2301]
I should be on the white list on all my projects, it says the same message

<img width="820" alt="screen shot 2017-04-16 at 9 16 34 am" src="https://cloud.githubusercontent.com/assets/753325/25073583/6e574c76-2285-11e7-815c-d8cdffa541e7.png">

**Comment by srallen** [comment]
This is a front end issue. Closing and will open issue there.
