### ISSUE TITLE
exports stalled

### ISSUE THREAD

**Issue by marckuchner** [zooniverse/Panoptes#2307]
Hi--

My teammate Aaron Meisner requested classification and subject exports for Backyard Worlds
last Monday 4/17 at 6:46pm pacific time, but have still not received
the data. When I go to:

https://www.zooniverse.org/lab/2416/data-exports

It still says "Processing your request." At this point I think
something must have gone wrong.

**Comment by zwolf** [comment]
Please have him re-request his export and if it doesn't come through again, let us know. Exports with a lot of classifications can take a while to generate, but generally if it's been over a day I suggest re-requesting.

**Comment by shaunanoordin** [comment]
@marckuchner , can I check if your follow up attempts to re-export Classifications & Subjects for Backyard Worlds succeeded?

**Comment by marckuchner** [comment]
Yes they did!  Thanks.

**Comment by shaunanoordin** [comment]
Great to hear! 👍
