### ISSUE TITLE
`project_contents` is returned in a project's `links` but `workflow_contents` isn't.

### ISSUE THREAD

**Issue by simoneduca** [zooniverse/Panoptes#2333]
It would be handy to have that id in project `links` too.

**Comment by eatyourgreens** [comment]
I think we can close this. Pandora is [loading workflow contents from the workflow resource](/zooniverse/pandora/blob/master/src/ducks/resource.js#L24-L27).

**Comment by camallen** [comment]
thanks @eatyourgreens
