### ISSUE TITLE
Sometimes data export requests 500 randomly

### ISSUE THREAD

**Issue by srallen** [zooniverse/Panoptes#2335]
I have a staging project that has three workflow classification exports (the first three in the list). Sometimes any one of those when requesting for the media will 500. It may take a few refreshes to get the error (if successful the first time, it'll cache and you won't see the error if you close the modal and try again). So far, this issue has only been found on staging, but I have yet to check production. 

https://workflow-exports-links.pfe-preview.zooniverse.org/lab/1616/data-exports

**Comment by zwolf** [comment]
https://app.honeybadger.io/projects/40595/faults/33723475

`URI::InvalidComponentError: bad component(expected absolute path component): /#<AWS::S3::Bucket:0x00000009f994b8>/panoptes-uploads.zooniverse.org/staging/project_aggregations_export/791387c5-35d1-4ef6-ae14-3f8b71d7221c.tar.gz`

Strangely intermittent.

**Comment by zwolf** [comment]
This is due to mismatching languages (`en` vs `en-US`) on content/pages/etc.

**Comment by srallen** [comment]
@zwolf The mismatching languages is why #2318 was happening. Not sure if that is true for the export media file request here. I'll see if I can get it to happen (randomly?) again so you can check out logs as the request comes in.

**Comment by zwolf** [comment]
Yeah, commented on wrong issue. Don't know what this is about yet, even with the trace.

**Comment by camallen** [comment]
I have never figured this out, i think it's an aws adapater connectivity issue where the ruby instance data gets interpolated to the strings path. this will keep on happening, updgarding the sdk from 1 to 3 could help.
