### ISSUE TITLE
Pages are hardcoded to `en` language

### ISSUE THREAD

**Issue by srallen** [zooniverse/Panoptes#2348]
Found when debugging #2318, pages are hardcoded to `en` rather than set to the parent resource's `primary_language` on create. https://github.com/zooniverse/Panoptes/blob/master/app/controllers/concerns/pages.rb#L48

I think this may need to change to make translations work. Also, other linked resources like tutorials will need to be checked as they're also likely hardcoded to `en` right now.

**Comment by camallen** [comment]
related to #1091

**Comment by eatyourgreens** [comment]
Project 908 on staging has some copies of the research page (url_key = 'science-case') that I've set up with language codes 'it' and 'es, but only the English version of that page ever comes back from `/api/project/908/pages?url_key='science-case'`

**Comment by eatyourgreens** [comment]
That might be correct behaviour, by the way, but the translations app would need a method to get all translations of a page back from the API.
