### ISSUE TITLE
HTTPS not being used for redirect_uri

### ISSUE THREAD

**Issue by x0xMaximus** [zooniverse/Panoptes#2356]
I apologize if this isn't the right place to outline the issue we're experience, but after creating our Application and setting the Callback urls to https://example.com/zooniverse-callback/ (trailing slash included 😉)

![](http://i.imgur.com/OW0F6w2.png)

the id + secret are then used without our oauth implementation, but we get this error page when returning from signing into Zooniverse:

![](http://i.imgur.com/jq3MwuH.png)

that we believe originates from the https protocol not being preserved in the redirect. This was not an issue when testing locally with https://localhost:8000/zooniverse-callback/ for example.

(Screenshots intentionally removed information)

Is this suggestive of a different error that's originating because of a setting our our end?

Thank you for your time and consideration,
- Max

**Comment by marten** [comment]
The return_url in that last screenshot is a parameter provided by the calling application, so I think it's probably your code that's not sending in an HTTPS url, and then our app rejects it because it doesn't match one of the configured URLs..
