### ISSUE TITLE
Should changing the retirement limit change the workflow version?

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/Panoptes#2363]
I'm working on some stuff for Grant to help with managing projects, and one of the checks he wanted to be able to make is to test if the retirement limit has been changed.

I originally thought I could reduce the version changesets for a workflow to find out whether this had happened, but it looks like changing the retirement limit doesn't create a new version.

Should it? No worries if not, I can hardcode the default value and check against that, but just thought I'd ask.

**Comment by camallen** [comment]
No but we should be able to detect this from the workflow and serialize this information if you need.

E.g. add a field called default_retirement in the serializer.

**Comment by rogerhutchings** [comment]
That would be handy 👍
