### ISSUE TITLE
pause a project when active workflows are finished 

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#2365]
We should automatically pause a project when all the active workflows are finished. Like wise we should unpause it when new data is linked / new workflows are added.

**Comment by mschwamb** [comment]
Currently only the Zooniverse core team can set this for a project so most projects that are out of data don't ever go to the paused section. Like P4: Ridges has been out of data for months and it shows on the active page. Same thing with Snapshots at Sea. I have a message up on the project, but it seems like I should be able to in the visibility tab if the project is Zooniverse approved. Another option would be if the out of data message shows to automatically put the project's status to paused. Though I think it would be easier without Zooniverse interaction for a project owner to end a project and change its status to finished.
