### ISSUE TITLE
"gold mode" classifications shouldn't count toward retirement

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes#2394]
When research teams want to validate volunteer answers (say, to assess accuracy for publications), they need to create a "gold standard" dataset that they can compare volunteer answers to. 

When we compare the volunteer answers to the gold standard dataset, we have to strip out the gold standard data from the classification data, because otherwise you're counting your gold standard data as a volunteer classification and inflating your measure of accuracy. (If you compare the project owner's answer to itself and say you have 100% accuracy, that's not really fair...)

Note that "experts" classifying on the site is different than creating a "gold mode" classification. "gold mode" classifications are created deliberately; people with "expert" roles on the project have to deliberately select the gear icon and select "gold mode" prior to submitting every single classification. So this isn't just "experts" classifying on the site - this is deliberately creating a separate dataset that you can compare volunteer answers to.

However, gold mode classifications currently count towards retirement. This is especially problematic when you're trying to assess accuracy for projects with low retirement rules. 

**Example** 
For example, I'm assessing accuracy on Snapshots at Sea, which circulates images to 5 people; when at least 4 out of 5 people say "YES" the aggregate answer is "YES." The project owner created the gold standard dataset to compare the aggregate answers to using "gold mode." However, because this contributed to retirement, I've now only got 4 volunteer answers for these photos. Unfortunately, many of them have 3/4 people saying "YES" so that last volunteer answer is actually really important for producing the aggregated answer. Including Ted's gold mode classification - the "known answer" in the volunteer dataset would inflate our measure of accuracy.

**Question** 
Should gold mode classifications count towards retirement? How hard would it be to make them not count toward retirement? We could tell project owners to up their retirement limits if they want to create gold standard data, but I don't think that's an elegant solution.

**Comment by astopy** [comment]
Would it make sense to take it a step further and not retire subjects which have gold standard classifications at all? If you're using them to measure accuracy/for calibration, then you'd want as many classifications as you can, right?

**Comment by aliburchard** [comment]
Oh that's a good point. Yeah, I think it could be really useful to overclassify gold standard data because that would give you the freedom to more accurately calculate *just how many* classifications you need to get X level of accuracy. (And maybe to realise that it's actually higher than your retirement rules...)

I can see that getting messy if the subjects with gold standard data are the *only* subjects left in a subject-set/workflow. But there's got to be a workaround for that.

**Comment by camallen** [comment]
it would be nice not to have to filter gold standard "subjects" out of counters as we have no notion of this on the subject side, it's on the classification side.

I'm all good to ignore retirement for gold standard classifications, seems like a legit use case and one i'm sure someone will request the inverse of in time ;)

**Comment by aliburchard** [comment]
Ah, fair point. I'm happy ignoring retirement for gold standard classifications, and keeping "gold standard" as a classification-level attribute. I suppose it's a bit different for projects that have sims, as that actually seems to be a "gold standard subject." I suppose project owners could, if they really wanted, to create a specific "gold standard" subject set and set different retirement rules for different subject sets. (Note, that actually isn't supported in the GUI, but I imagine Caesar could, in theory, support this?)

Also, love this timely request from a project builder: https://www.zooniverse.org/talk/18/392203

**Comment by camallen** [comment]
I think we should support not counting gold standard classifications for retirement. not sure about not retiring gold standard subjects yet.

**Comment by marten** [comment]
Noting that if project owners want, Caesar would support this already.
