### ISSUE TITLE
looks like 'finished' flag is showing up on all subject images of the new subject set just loaded and turned on on P4: Ridges

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes#2399]
Volunteers are reported constantly seeing retired images with a banner saying retired on P4: Ridges but from the lab interfaces it is showing the new subject set is linked. Checking on what image I classified, it is an image from the new subject set. The stats page shows the subject set is not finished and that most of the subjects are not finished. I think there's something wrong. Could someone check on P4: Ridges? Many Thanks cc @camallen

**Comment by camallen** [comment]
@mschwamb un / re-linking subject sets in the workflow fixed it. Was this an old worklfow that you re-activated or one you just linked new data to? Trying to figure out why the link actions didn't update the workflow state.

**Comment by mschwamb** [comment]
I forgot you don't have to un-activate a workflow to switch subject sets. So I'm pretty sure I unactivated it, linked the subject set, and made it active again.

**Comment by camallen** [comment]
did you unlink a set or multiples before linking a new one?

**Comment by mschwamb** [comment]
I unlinked one subject set before or after I linked the new one. I can't remember which order.

**Comment by mschwamb** [comment]
But I'm pretty sure when I did the linking and unlinking it was when the workflow was inactive.

**Comment by camallen** [comment]
thanks @mschwamb - i'll look into why the new linking of a set didn't fire the expected reset workers.
