### ISSUE TITLE
Registration page is titled "Sign in..."

### ISSUE THREAD

**Issue by murraycu** [zooniverse/Panoptes#2408]
This page,
https://www.zooniverse.org/accounts/register
which mobile users see, has this title
"Sign in with your Zooniverse account"
but it's about registration, not signing in.

Also, the "Sign in with" Facebook/Twitter/Google buttons do nothing.

(Desktop browser users see this in a popup window, which hides the title and the "Sign in with" buttons.

**Comment by srallen** [comment]
@murraycu I've opened this on zooniverse/Panoptes-Front-End#3942 since this is a front end client issue. The oauth for Facebook and Google with the API should be working.
