### ISSUE TITLE
Support sign in / register on smaller screen devices

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#2410]
Make the [form component](https://github.com/zooniverse/Panoptes/blob/master/app/assets/stylesheets/forms.css) respond to different screen sizes. 

Currently looks like this for simulated Nexus 5x (412 x 732)
<img width="496" alt="screen shot 2017-07-21 at 14 28 28" src="https://user-images.githubusercontent.com/295329/28465522-f74cf1b6-6e20-11e7-9697-c246d87d958c.png">

**Comment by camallen** [comment]
@murraycu if this was fixed would you then switch the signup routes from your app to use it?

**Comment by murraycu** [comment]
Yes, I guess so.

I haven't forgotten that this really needs to be be done properly: https://github.com/zooniverse/Panoptes-Front-End/issues/3942#issuecomment-316754369
But I haven't found time for that yet.
