### ISSUE TITLE
Moving Snapshot Serengeti to Panoptes

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes#2438]
We should move SS to PFE before adding any more data to the project. I've recreated SS here: 
https://www.zooniverse.org/projects/aliburchard/snapshot-serengeti

@camallen these are the remaining to-dos we've discussed. I'm happy to be in touch when the time actually comes to move things over if there are any issues.

TO DO:
- [ ] Change ownership of the project from aliburchard to zooniverse
- [ ] Redirect www.snapshotserengeti.org to  https://www.zooniverse.org/projects/zooniverse/snapshot-serengeti
- [ ] Redirect www.snapshotserengeti.org/#/authors to https://www.zooniverse.org/projects/zooniverse/snapshot-serengeti/about/results
- [ ] Keep Talk so that volunteers can still access their old collections and comments, but discourage (eventually disable?) activity on that forum
- [ ] Message the change to moderators and volunteers (I'm alerting the science team to the change, but @mrniaboc will be good if you can coordinate with them to when the time comes). I'm especially keen to alert mods ahead of time to the change *and* to translations (which will likely be in place before S11 goes up).

**Comment by trouille** [comment]
Since Serengeti is now on project builder, should we close?
