### ISSUE TITLE
classifications from a project I don't own or in my classification data export

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes#2450]
I was processing the classifications from Planet Four: Terrains and the my scripts parsing the csv file stopped. Looking at what line in the csv it stopped on, I can see the workflow name is not from my project and the content looks like another project:

{'classification_id': '31432736', 'user_id': '', 'expert': '', 'workflow_name': 'Snow Interception: Sequoia', 'annotations': '[{"task":"init","value":[5]}]', 'user_ip': 'b3232aacbcdc8f1729f0', 'workflow_id': '3463', 'gold_standard': '', 'subject_ids': '5421074', 'subject_data': '{"5421074":{"retired":{"id":3862049,"workflow_id":3463,"classifications_count":10,"created_at":"2017-02-16T04:18:22.873Z","updated_at":"2017-03-03T20:30:30.734Z","retired_at":"2017-03-03T20:30:30.657Z","subject_id":5421074,"retirement_reason":null},"Filename":"sequoia_2011_01_02_130100.jpg"}}', 'user_name': 'not-logged-in-b3232aacbcdc8f1729f0', 'created_at': '2017-03-03 20:30:28 UTC', 'workflow_version': '47.67', 'metadata': '{"session":"0280623173bf860477581d460554960455426a85bce6b7638848c759fb84a712","viewport":{"width":1280,"height":689},"started_at":"2017-03-03T20:29:22.339Z","user_agent":"Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0","utc_offset":"28800","finished_at":"2017-03-03T20:30:27.057Z","live_project":true,"user_language":"en","subject_dimensions":[{"clientWidth":631,"clientHeight":473,"naturalWidth":640,"naturalHeight":480}]}'}
Traceback (most recent call last):

I haven't asked for another classification export, so you can check the ones that were generated about why it was outputted to P4: Terrains

**Comment by marten** [comment]
Thanks, that's really weird! I'll let you know when I've had a look. If you could hold off on generating a new export until then (probably tue/wed next week, monday is a holiday here) that'd be great.

- Marten

**Comment by mschwamb** [comment]
Yeah no problem.  I just checked and it appears it's only this one entry. I had generated a specific workflow export first then realized it wasn't in the format my scripts easily handle  (or rather my code broke when running on it )so I went to the full classification export since I've got scripts for that

**Comment by marten** [comment]
Okay, so:

* The classification is linked to project_id 17, which is P4:T.
* The classification is linked to workflow_id 3463, which belongs to Snow Spotter.
* The annotations give an answer for the "init" task, which Snow Spotter doesn't have, but P4:T does. So it appears that it is a valid classification for your project, for some reason linked to a workflow that doesn't belong to your project.

* Looking at classifications from that IP (since the user is not logged in), we start getting a load of classifications for all sorts of projects starting from 20:22. The IP address is registered to a group of public schools in the US, and the classifications are coming from various browsers and window sizes, so this IP is probably shared by many computers.

* The specific session identifier for the offending classification identifies 6 classifications around that time. The weird classification is the second one chronologically. The other 5 are fine.
* When you request a project-wide export, we export all the classifications linked to the project, and don't filter by the workflows for that project

### Followup

* I'm running a query to see if this issue happens more often, or if it's a one off fluke.
* Since this classification seems to belong to your project, I'll change the workflow_id to 16.
* I'll add issues to Github that we should probably be checking that project & workflow make sense when a classification gets saved.

**Comment by mschwamb** [comment]
@marten  I'm confused what 'annotations': '[{"task":"init","value":[5]}]'" - My responses for my project don't include '5', a typical classification for P4:Terrains is like this:

68307916,Aveely,1678824,01b486937891ed40ff30,16,CTX workflows,128.9,2017-08-26 09:26:01 UTC,,,"{""session"":""57c702c057acc0e2cdd35c31f6c68d7bc2ddb4f605ca4b4c08768b9bd5726e87"",""viewport"":{""width"":360,""height"":616},""started_at"":""2017-08-26T09:25:36.547Z"",""user_agent"":""Mozilla/5.0 (Linux; Android 6.0.1; SM-S907VL Build/MMB29K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.107 Mobile Safari/537.36"",""utc_offset"":""25200"",""finished_at"":""2017-08-26T09:26:00.247Z"",""live_project"":true,""user_language"":""en"",""user_group_ids"":[],""subject_dimensions"":[{""clientWidth"":338,""clientHeight"":254,""naturalWidth"":800,""naturalHeight"":600}]}","[{""task"":""init"",""task_label"":""What features do you see in the image? (**Select all that apply**)"",""value"":[""Spiders"",""Baby Spiders""]}]","{""6763426"":{""retired"":null,""!filename"":""APFT400003199.png"",""!CTX_filename"":""F11_040238_1075_XI_72S082W"",""!Public_CTX_link"":""http://viewer.mars.asu.edu/viewer/ctx#P=F11_040238_1075_XI_72S082W\u0026T=2""}}",6763426

**Comment by mschwamb** [comment]
I'm going to have to filter that classification out since 5 doesn't match any of the strings that would be in the value entry, so if we can remove it that would be easier for me since my project values are 'Spiders', 'Baby Spiders', 'Channel Networks', 'Craters', 'None of the above'

**Comment by marten** [comment]
Internally, you do have a "5" though. But because it was linked to the wrong workflow, when Panoptes exported, it couldn't find the appropriate string, and thus just printed the raw value. Next export, it'll be able to find what "5" means, and get you the string in the CSV file.

**Comment by mschwamb** [comment]
@marten I see. But the SnowSpotter also has an option 5. Checking the subject image, it's not actually a P4: Terrains image. 

Subject 5421074 is an image of a landscape with snow and blue skies and the metadata says sequoia_2011_01_02_130100.jpg which I think means this shouldn't be in my classification data dump 

So I'm a little confused why you changed the workflow to 16 and are keeping it in the exports for P4:T? If the subject info is wrong, I have no idea what subject to associate it with.

**Comment by marten** [comment]
Huh. I was sure that workflow 3463 doesn't even have a task "init". I'll check again.

**Comment by mschwamb** [comment]
This is the subject image in case it's helpful: Definitely the other project

![08d3d00b-8d4f-4c1e-914b-0fbb1f746241](https://user-images.githubusercontent.com/753325/29915072-5ef88e72-8dd6-11e7-9ffb-fc59532bc94f.jpeg)

**Comment by camallen** [comment]
I think this can happen when the workflow state in PFE mismatches the project classify page for some reason. In theory it would probably have wired up an interface for snow spotter in the comet hunters project.  

@eatyourgreens @srallen thoughts on how this could happen?

**Comment by mschwamb** [comment]
@marten you set the workflow to the main one for my project, can you make sure it's adjusted to something else or so it's not in my classification data dumps as it's clearly not a P4T subject image.

**Comment by marten** [comment]
Okay, well I can't really reassign it to something else, so I'll delete it outright.

For my own for future reference this was the record in the DB: 

```
panoptes=> select * from classifications inner join classification_subjects cs on cs.classification_id = classifications.id where id=31432736; 
-[ RECORD 1 ]-----+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
id                | 31432736
project_id        | 17
user_id           | 
workflow_id       | 16
annotations       | [{"task": "init", "value": [5]}]
created_at        | 2017-03-03 20:30:28.376572
updated_at        | 2017-03-03 20:30:29.245232
user_group_id     | 
user_ip           | a.b.c.d
completed         | t
gold_standard     | 
expert_classifier | 
metadata          | {"session": "0280623173bf860477581d460554960455426a85bce6b7638848c759fb84a712", "viewport": {"width": 1280, "height": 689}, "started_at": "2017-03-03T20:29:22.339Z", "user_agent": "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0", "utc_offset": "28800", "finished_at": "2017-03-03T20:30:27.057Z", "live_project": true, "user_language": "en", "subject_dimensions": [{"clientWidth": 631, "clientHeight": 473, "naturalWidth": 640, "naturalHeight": 480}]}
workflow_version  | 128.9
lifecycled_at     | 2017-03-03 20:30:29.200201
classification_id | 31432736
subject_id        | 5421074
```

**Comment by eatyourgreens** [comment]
@camallen @srallen only thing that occurs to me is that perhaps PFE doesn't validate the workflow ID against the project on the classification page. In that case you could render a workflow task, and linked subjects, for any public workflow ID on the classify page of any project. If that's true, then Comet Hunters could render the Snow Spotters classifier if it was passed a Snow Spotters workflow ID.

**Comment by srallen** [comment]
@camallen @eatyourgreens I think you're right in that the workflow id isn't being validated. There are only two places where workflow ids are loaded from: the users' project preferences or the project's default workflow configuration or randomly chosen from its links. The incorrect workflow likely came from the project preferences maybe from cache or the local component state that didn't get cleared out correctly.

**Comment by marten** [comment]
This was a non-logged-in user though, so probably not the project preferences. I think that must be a bug somewhere in PFE then.

**Comment by srallen** [comment]
Actually it can be. Logged out users get a temporary project preferences created and stored in the panoptes-javascript-client's cache: https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/pages/project/index.cjsx#L163-L167

It's caused other bugs before that I've found.

**Comment by camallen** [comment]
@srallen thanks for the update on this - maybe the backend should reject classification that don't match the project -> workflow links?

**Comment by srallen** [comment]
@camallen That would be a sensible validation to have. The front end could validate too, like @eatyourgreens suggested. If it is an issue with the cache like I suspect, the long term fix is in with our rewrite of the client.
