### ISSUE TITLE
non org owner requesting launch approved project cards for projects linked to organization

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/Panoptes#2462]
on staging, when logged in as organization #2's owner
https://panoptes-staging.zooniverse.org/api/projects?organization_id=2&http_cache=true&admin=true&cards=true&launch_approved=true
returns what I'd expect and would like:
```
[
  {
    "id": "1686",
    "display_name": "ORGTEST Arkansas Dendrology",
    "classifications_count": 0,
    "updated_at": "2017-08-01T08:02:08.999Z",
    "description": "ORGTEST Arkansas Dendrology",
    "slug": "markb-panoptes/orgtest-arkansas-dendrology",
    "redirect": "",
    "avatar_src": "panoptes-uploads.zooniverse.org/staging/project_avatar/f9f74bc8-299b-47fb-b3f9-d7ef945324f3.jpeg",
    "links": {}
  },
  {
    "id": "1687",
    "display_name": "ORGTEST WeDigFLPlants",
    "classifications_count": 0,
    "updated_at": "2017-08-03T18:51:31.183Z",
    "description": "ORGTEST WeDigFLPlants",
    "slug": "markb-panoptes/orgtest-wedigflplants",
    "redirect": "",
    "avatar_src": "panoptes-uploads.zooniverse.org/staging/project_avatar/e4c7dc11-6f4f-4b57-8e9b-4a46b2b12120.jpeg",
    "links": {}
  }
]
```
but when logged in as an org #2 collaborator, unrelated user or signed out an empty array is returned.

Would it be possible to return the response noted above as a user other than the org owner?

The goal is that if a user is on an org landing page they will see launch approved project cards linked to the organization.

**Comment by camallen** [comment]
@mcbouslog those projects are private so i assume the filtering re org collab / non-logged in is related to this. Strange you aren't getting other launch approved projects in those requests though

Will org projects have to be public for access? Currently all launch approved projects are public as that is the only way they can be listed so i assume them being private is a prerequesite. I've just added org id filtering to the api in #2463

**Comment by camallen** [comment]
What does the request / response look like without the `organization_id=` and `admin=true` params. You shouldn't need the admin one for this and it will change behaviour if you are logged in.

**Comment by mcbouslog** [comment]
ah my bad. 

the intent is that org projects will have to be public and launched approved to show on an org landing.

once I changed the test projects noted from private/dev to public/live, the org landing responses for various users (not logged in, not collab) are what I'd expect/want.

the request without `organization_id=` and `admin=true` gives me 20 launch_approved/public/live projects as I'd expect. 

now that the projects are public/live, while signed out the request 
`https://panoptes-staging.zooniverse.org/api/projects?organization_id=2&http_cache=true&cards=true&launch_approved=true`
responds with the two project cards as I'd hope.

there are other reasons I'd like the project filter on org ID, so thank you and please keep that PR, but I'll close this issue as there wasn't ever really any issue. thanks!
