### ISSUE TITLE
[RFC] add status or launch_approved to project card

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/Panoptes#2466]
Currently a request for projects with `cards: true` returns an awesomely bite-size project with:
`{ avatar_src, classifications_count, description, display_name, id, links, redirect, slug, updated_at }`

Could we add `state` and/or `launch_approved` to what's returned with a project card?

Potential use cases:
- `state`: [this Talk comment](https://www.zooniverse.org/talk/14/439115), also mentioned by @astopy in Slack
- `launch_approved`: [on the org landing view for org collaborators](https://drive.google.com/open?id=0B1YBtez3cv8AeWNURjJsMGZfLTg) that'd show all org associated projects and their launch approved status

I know we want to keep the project card as small as possible, so I'm not sure if adding anything is a good idea, hence the RFC.

**Comment by mcbouslog** [comment]
Not sure this is feasible, but a different approach, could the `fields` functionality available when requesting workflows be implemented with projects?

**Comment by camallen** [comment]
@mcbouslog we can add those in attributes into the cards. Serializing the model attributes is fast and fine, it's the join models that slows us down here.

**Comment by camallen** [comment]
Also long term having the optional field attributes specified from the client should be on all resources (not just workflows). We have to generalize the workflow code but it's doable. 

This is something that graphql does for free FYI.

**Comment by mcbouslog** [comment]
Closing. Will open issue for specific request.
