### ISSUE TITLE
Sort order for collection subjects

### ISSUE THREAD

**Issue by srallen** [zooniverse/Panoptes#2473]
Based on [this talk thread](https://www.zooniverse.org/talk/17/443780?comment=742168&page=1).  Volunteers are reporting that the subjects in the collection aren't in any particular useful sort order. They would like the subjects to be in order of most recently added to the collection. It'd be probably useful to have a UI toggle to change between most recent/least recent. 

Digging through the code, I see a model for collection subjects, but no serializer, so I assumed the default would be most recently added, but the volunteers are reporting this is not accurate.

**Comment by camallen** [comment]
@srallen sorry for the delay on this. 

We can add a sort order on the collection->subjects assocation if it really is a default all the time. Or we can filter the incoming sort params and add this order clause to the scope lookup, e.g. `?sort=most_recently_added` or some other param that makes sense.
