### ISSUE TITLE
Workflow task string extractors missing description field

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#2474]
We should extract the description field from the task json blobs for use in translations. Currently survey tasks have the key still on the workflow resource and not the contents model. Adding the `visit_description` alias here would do it. 
https://github.com/zooniverse/Panoptes/blob/df32f520e7faed0533e9a1a65d2a8b643625bfae/lib/tasks_visitors/extract_strings.rb#L22

**Comment by camallen** [comment]
This will need to have an associated migration that adds the `description` task strings to the worfklow_contents model. It would be best to do this without version tracking as well to avoid bumping the minor workflow version number.

**Comment by eatyourgreens** [comment]
Task strings for the test survey task might also seem be missing the confusions strings:
https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/pages/dev-classifier/mock-data.coffee#L228-L229

I'll double check in case it just turns out that these haven't been set up for the test project.

**Comment by camallen** [comment]
closed by #2539
