### ISSUE TITLE
.mpeg subject blocked from uploads

### ISSUE THREAD

**Issue by trouille** [zooniverse/Panoptes#2476]
Related to https://github.com/zooniverse/Panoptes/issues/2458 (.mp3 file blocked from uploads through Project Builder UI). Related only in the sense that we still can't upload .mp3 in Chrome, but importantly we can upload .mp3 in Firefox (so that issue was closed because Yunpeng was able to use Firefox for now). 

This issue is that it is not possible to upload .mpeg file types on Chrome, Firefox, or Safari, even though the interface says that you can. Note: I've only tried this on a mac. 

![screen shot 2017-09-28 at 1 32 35 pm](https://user-images.githubusercontent.com/4975655/30983941-84437f84-a451-11e7-9901-705a18798bee.png)

It may be that we don't want to allow .mpeg through the project builder. In that case, we should just update the text to remove .mpeg from the list of accepted file formats. 

Example .mpeg file tried in firefox v55.03 to upload through project builder: https://drive.google.com/a/zooniverse.org/file/d/0BzeL_TYT7IYPZ2w3MkR6eUlhNW8/view?usp=sharing

Note: this is for a video-based project with e-Bird (the cornell lab of ornithology). I am pointing them towards using the Panoptes-cli or Python client, but I believe we can't currently use either of those for .mp4 or .mpeg upload either. E.g., https://github.com/zooniverse/panoptes-cli/issues/54 

Currently we're at the stage of just wanting to test out having a small sample of subjects uploaded in the interface to play with as we try out different workflow ideas.

**Comment by srallen** [comment]
Could you share what the error is and any manifests they may be using? This may not be failing for the same reason. Just casually trying the video file in the UI, the UI appears to not be auto-detecting the file for upload correctly. 
<img width="376" alt="screen shot 2017-09-28 at 1 51 11 pm" src="https://user-images.githubusercontent.com/5016731/30984826-22a5f7e0-a454-11e7-9866-6ab55d0b880b.png">
Which indicates an issue on the PFE side.

Whereas the mp3 files were failing the actual subject creation with Panoptes due to a MIME type validation error with the API.

**Comment by trouille** [comment]
You're right @srallen It's not even detecting a .mpeg as a possible file to upload.

**Comment by trouille** [comment]
I can make a new issue within PFE if that's best, and close this one.

**Comment by eatyourgreens** [comment]
It's worth checking if a browser will even play that video file. MP4/H264 should work across most desktop browsers, plus mobile.

**Comment by trouille** [comment]
It may be that this is an unnecessary red herring. The team I'm working directly with right now (the Cornell Lab e-Bird group) would prefer to use .mp4 format files for their videos and they would prefer to use the panoptes-cli or python-client. We just hoped to be able to upload a few example .mpeg through the Project Builder to test with, since currently we're not able to upload .mp4 through panoptes-cli or python client. 

It does seem that if no-one has an .mpeg that they're able to upload through the Project Builder that we should remove that from the list of possible file types that we include in the list in the Project Builder (see screenshot above).

**Comment by eatyourgreens** [comment]
I double-checked, and Hugh added `.mpeg` as an allowed type for audio. We should definitely edit the instruction text if it isn't available publicly via the PFE subject uploader.
