### ISSUE TITLE
'Already seen' banner persisting / only a few images showing in new dataset

### ISSUE THREAD

**Issue by tedcheese** [zooniverse/Panoptes#2489]
We have a new dataset up on Whales as Individuals -- https://www.zooniverse.org/projects/tedcheese/whales-as-individuals -- yet the 'project is out of data banner' persists, all images show up with a 'finished' or 'already seen' tag, and only a few images are showing up. How do we overcome this? (Happens repeatedly when we upload new data)

Thank you ~ Ted

**Comment by camallen** [comment]
the banner will update after ~1hr when the next project completness worker runs. this is a work in progress and it's being improved specifically in #2646
