### ISSUE TITLE
add researcher_quote, retired_subjects_count and subjects_count to project card

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/Panoptes#2504]
Per [PFE Issue #4089](https://github.com/zooniverse/Panoptes-Front-End/issues/4089), could we add a project's `researcher_quote`, `retired_subjects_count` and `subject_count` to the project card?

Project researcher quotes will be carouselled through in the upper left of an organization landing details section.

Project retired_subjects_count and subject_count will be totalled for the organization landing stats section.

Related to #2466, #2483.

Might just be me, but it seemed strange that while the researcher quote itself is a string on a project's `researcher_quote` attribute, the researcher ID selected to be associated with the quote is in `project.configuration.researcherID`. Not necessarily related to this issue, but thought would note.

**Comment by zwolf** [comment]
@camallen Seems like including `retired_subjects_count` and `subjects_count` would defeat the purpose of separating the card fields. Confirm?

@mcbouslog For pages that need counts like those, can you just use the regular projects request? Seems like only aggregation pages (i.e. /projects) should use the card param for the above reason.

**Comment by mcbouslog** [comment]
`retired_subjects_count` and `subjects_count` would be for [the org landing stats section](https://zooniverse.slack.com/files/beckyrother/F683P4SQ1/organization_page_-_talk.png) (though Volunteers is changing to just a projects count).

there'll be a separate page (organizations/username/org-name/stats) where I'll make the regular projects request to populate more robust stats on the organization's projects. working on that this week.

we'll prob want to keep the org landing as is, requesting project cards, and change the design for the org landing stats section if adding the counts aren't as straight-forward as adding things like `launch_approved` or `researcher_quote`, which of course is totally ok and understandable. I think I saw `classifications_count` on the current project card and presumed those other counts could/should be added, but no worries if that's not the case, we'll come up with something clever.

**Comment by camallen** [comment]
The original intent of the project cards was to speed up the endpoint by serializing the projects table fields only (not joining other models). 

Adding `researcher_quote` would require a join on the project_contents model, not ideal as the query to find the contents is non-trivial. The `*_subjects_count` fields are computed from the linked workflows / subject sets at runtime so they would be costly too. We could certainly add these to the cards but they come with a cost. 

I think the best solution to this is to provide a way to paramterize the response object fields as we do for the workflows, e.g. `projects?ids=1,2,3&fields=researcher_quote,retired_subjects_count,subjects_count,....`. This will allow the client to get what it needs and avoid modifying the cards endpoint. In hindsight we should have done this for the cards endpoint. https://github.com/zooniverse/Panoptes/issues/1995

**Comment by marten** [comment]
That sounds like GraphQL

**Comment by camallen** [comment]
That said we already do have this on workflows and it could easily be extracted and generalized to work with all the json api resource controllers.

**Comment by zwolf** [comment]
So the question, I guess, is this: if I parameteratize the response fields, is @mcbouslog's query going to be faster than using grabbing each project by id? Because it sounds like what he's looking for (researcher quote, counts) is the slow stuff. 

No way to know for sure until I do it and this is probably a good idea anyway, but interested in your thoughts. I'll probably start this after I get through the other org issues (namely tags, https://github.com/zooniverse/Panoptes/issues/2436)

**Comment by camallen** [comment]
I should be quicker in 1 request vs multiples. If you get them all in 1 then the cost of this vs a full representation (pay the cost of loading extra data) may be negligible no matter how flexible the fields response mechanism is. 

I think we might have to benchmark a basic implementation (using cards with extra data vs full to save the fields implementation) to decide what is the best. Is the end point heavily used (i.e. the landing page for projects?), etc will help decide which way to go.  

We should probably cache the *subjects_count on projects / workflows especially as these numbers don't change quickly. That will help all representations.

**Comment by zwolf** [comment]
I was thinking a single request with a list of ids as it's query param, but a bit of testing indicates that doesn't work like I thought it did. Routes would seem to agree that it isn't doable that way, but would allowing projects to be filtered by organization be another way to get all the ones you want at once?

**Comment by camallen** [comment]
It should work via restpack ids / FK filtering, https://github.com/RestPack/restpack_serializer#by-primary-key

GET `/api/projects?ids=1,2,3&organization_id=10` Note, you could use either filtering sets here the ids are most restrictive if you know the org's projects.

**Comment by mcbouslog** [comment]
I'm going to close this issue, as whether we parameteratize or try a GraphQL endpoint no solution will involve muddling up the project card with the attributes noted, and new issues can be opened for the other solutions if need be.
