### ISSUE TITLE
Queued Subjects coming from different Subject Sets, despite specifying Subject Set

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/Panoptes#2510]
## Issue Report
- When requesting a queue of Subjects from the `/queued` endpoint, if a Subject Set is specified, sometimes the endpoint returns Subjects from multiple Sets instead.
- This issue _only_ appears when the user is _not_ logged in.
- If the user logged in, the queue only returns Subjects from the specified Set, as expected.
- Context: the error was noticed on the Anti-Slavery Manuscripts project, where users are given the choice of transcribing letters from different time periods (subject sets). This is mostly noticeable on staging, where the ASM uses a very small set of Subjects and Subject Sets.

### Testing
Setup:
- On `staging`, we've created project `1764` / `wgranger-test/anti-slavery-testing`
- The project has one workflow, workflow `3017`
- The workflow has 5 Subject Sets, with one Subject each:
```
subject set 4420: [ subject 73330 ]
subject set 4422: [ subject 73331 ]
subject set 4423: [ subject 73332 ]
subject set 4424: [ subject 73333 ]
subject set 4425: [ subject 73334 ]
```

Expectation:
- When I request `/queued?subject_set=4422`, I should receive only `[73331]`

Note: Anti-Slavery Manuscripts's staging is tested mostly on localhost, but a potential quick test can be done via https://www.antislaverymanuscripts.org/?env=staging

**Testing 1:** User **isn't** logged in, attempts to select Subject Set 4422.

Request: `GET https://panoptes-staging.zooniverse.org/api/subjects/queued?http_cache=true&workflow_id=3017&subject_set_id=4422`

Response: Response body contains 5 Subjects: `[73333, 73331, 72815, 73330, 73332, 73334]`. This is unexpected. (Wait, where did 72815 even come from? That's from Subject Set 4384.)

Response will _always_ contain those Subjects, in that order.

![screen shot 2017-10-31 at 13 47 03](https://user-images.githubusercontent.com/13952701/32227130-5214e6d2-be42-11e7-9bf9-669ecb35e5e8.png)

**Testing 2:* User **is** logged in as user `zootester1`, attempts to select Subject Set 4422

Request: `GET https://panoptes-staging.zooniverse.org/api/subjects/queued?http_cache=true&workflow_id=3017&subject_set_id=4422`

Response: Response body contains 1 Subject: `[73331]`; This is expected.

![screen shot 2017-10-31 at 13 55 37](https://user-images.githubusercontent.com/13952701/32227396-362b2f7a-be43-11e7-9fa5-d788d4bf5203.png)

### Status
Open for investigation, tagging @camallen . Let me know if I need to share project setup details and/or other API calls to rule out errors on the front end/project setup side of things.

I'm not sure how to describe the priority here; one one hand, I'd like to see this fixed for the ASM beta test on 8 Nov. On the other hand, the project is otherwise functioning, and it's possible for users to actually classify Subjects, they just can't choose the ones they want. On the third mutated hand growing out of my chest, if this really is an issue (and not just poor API calls/project setup on my behalf) then other projects may be affected, which can't be good.

**Comment by marten** [comment]
The workflow is set to use the default subject selector, which recently changed to always be Designator. Designator doesn't do grouped selection (yet). I've switched it over to Cellect. @shaunanoordin Did this fix your issue?

@camallen should the workflow bypass designator and use built-in selection for grouped?

**Comment by camallen** [comment]
@marten thanks for looking into this, if we don't have on the horizon plans to support grouped selection then yeah we should modify the code path to deal with this. I think this is pretty local to us right now though so happy to just switch the workflow selectors to deal with it. 

@shaunanoordin Also noting there is a bug with cellect if all the data is retired it'll switch back to a random group, not the one you asked for. It's on my list to work on but please do remind me as it'll only start showing up once the data starts retiring for your workflow.

**Comment by shaunanoordin** [comment]
@marten SWEET. 👍  The switch to Cellect now **fixes the issue.** As _either_ a logged in user or a not-logged-in user, when I choose a Subject Set, I am _only_ served Subjects from that Set. This has been confirmed on staging.

@camallen Noted on the bug with cellect, and thanks for the alert! I wouldn't be too worried about having that retirement issue settled for ASM so soon (although I assume this is related to the "retired images seen again" issue of WildCam), but I'll have to pay closer in a few months.
