### ISSUE TITLE
Allow the tester role to be able to access inactive workflows

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes#2540]
I wanted to test out with a small group of users our new workflow, but apparently the tester role can't see a inactive workflow even with the direct link. 

Can it be changed to allow testers to access inactive workflows via the direct url. It would be great for beta testing of new workflows or future upgrades to a project.

**Comment by mschwamb** [comment]
Note this is for P4: Ridges. I thought the tester role would have access to an inactive workflow just like the tester role can see a private project.

**Comment by camallen** [comment]
@mschwamb this is a UI issue, I've enable the experimental feature to allow worfklow URLs to be passed around for testing.

**Comment by camallen** [comment]
FYI there is nothing API stopping this from happening, the UI won't wire up workflow params unless you have collab / owner roles or the experimental feature is turned on. Might be best to start this discussion over there.
