### ISSUE TITLE
Add support for video/mp4 files

### ISSUE THREAD

**Issue by zwolf** [zooniverse/Panoptes#2558]
Video files are being uploaded by admins to bypass the lack of the content type being included here:

https://github.com/zooniverse/Panoptes/blob/master/app/models/medium.rb#L13

Whatever content type they are (`video/mp4`?) should be added to this whitelist so they can be uploaded by project owners/collabs and also so that the validation doesn't fail immediately whenever someone tries to alter them.

**Comment by camallen** [comment]
closed by #2728
