### ISSUE TITLE
Featured project

### ISSUE THREAD

**Issue by srallen** [zooniverse/Panoptes#2598]
This came up in Slack's design thoughts channel. The featured project on the home page should be managed via the API instead of us updating static content every few weeks. What this would needs is:
- a `featured` boolean
- a query param on the `/projects` endpoint

@beckyrother only wants one featured project at a time. We thought that this could be managed by a toggle on the admin page for a project. Perhaps there could be a validation on projects that only allows a single project be `featured: true` at any time?

**Comment by beckyrother** [comment]
It would be great to make a note about only one featured project at a time: 
`This will override the current featured project`
..or a similar message

**Comment by VVH** [comment]
Could we feature projects for just 1-2 weeks, and include all active Zooniverse projects that have full approval? So, including things on Ouroborous and custom projects, if this isn't done already?

**Comment by marten** [comment]
The linked PR fixes the API side of things. The frontend would need to be updated to:

- In the Admin section, add a button "Make this the featured project". This button would first maken an API call to "unfeature" the current featured project, and then another API call to feature the specified project. *The API merely disallows having > 1 featured project, it does not remove featuredness from projects when you try to update another one to become featured*.

- On the homepage, it would make an API call to `projects?featured=true`. This will still return an array of projects (even though it's guaranteed to always return at most 1 resource in that array).

- On the homepage, make sure to account for the case when **no** project is featured (i.e. the API returns an empty array). This will sporadically happen while switching featured projects (see bullet point 1) but also means we can unfeature a project without coming up with the next one.
