### ISSUE TITLE
filter launch approved org linked projects from zooniverse.org/projects

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/Panoptes#2617]
We're hoping to launch organization [Snapshot Safari](https://www.zooniverse.org/organizations/meredithspalmer/snapshot-safari) in early February, which currently includes 5 projects. 

The projects would like to be launch approved so there is no "Under Review" near the project name, and the disclaimer that the project is not official, under the project description, is removed.

However, launch approving these 5 projects would crowd zooniverse.org/projects in a way we would prefer not to. Please see [this comment](https://github.com/zooniverse/Panoptes-Front-End/issues/3977#issuecomment-321641413) for a more detailed explanation of why.

Is there a back-end solution to filter launch approved projects linked to listed orgs from the project cards returned for zooniverse.org/projects?

I'm happy to provide details, but the front-end solutions weren't working well for me, i.e. if requested project cards and orgs then filtered projects based on all the org.links.projects it created different project cards per zooniverse.org/projects page and added another API call.

Historically launch approving a project has meant 1) we give it our seal of approval and 2) add it to zooniverse.org/projects. Because of organizations (sorry!) we want to separate those attributes. Maybe this is somewhat related to a recent issue we've had about how we signal a project has been approved/official/verified, as noted in [PFE Issue 4304](https://github.com/zooniverse/Panoptes-Front-End/issues/4304)? 

In which case (gather rotten fruit) maybe we need to add an attribute to the project resource (throw rotten fruit) to differentiate between how we're using `launch_approved`? Or maybe there's a creative way to utilize a project's `state` here?

related to #2573, [PFE Issue 3977](https://github.com/zooniverse/Panoptes-Front-End/issues/3977).

mentioning @camallen @zwolf @srallen @trouille

**Comment by srallen** [comment]
I don't think we should use project state for this. This sounds like a filter to me. Perhaps the filter could be for the projects endpoint and return projects that are or aren't linked to organizations: `?organization_linked=false`

**Comment by mcbouslog** [comment]
Honestly I don't like either option I mentioned (new field or using `state`), so I'm all for something like Sarah has mentioned. Or to put differently, all ideas for a way to address the issue welcome!

**Comment by marten** [comment]
I still think that either all org projects should be included on the `/projects` listing, or none of the organization-associated ones should.

```
 +------------------+  +-------------------------------------------------------+
 |Organizations:    | +|                                                       |
 |------------------|  |                                                       |
 |All projects     ||  |                                                       |
 |Zooniverse       ||  |                                                       |
 |Notes from Nature||  |                                                       |
 |Snapshot Safari  ||  |                                                       |
 +------------------+  |                                                       |
                       |                                                       |
 +-----------------+   |                                                       |
 |Disciplines:     |   |                                                       |
 |-----------------|   |          PROJECT CARDS GIVEN FILTERS                  |
 |Arts             |   |                                                       |
 |History          |   |                                                       |
 |Medicine         |   |                                                       |
 |Spaaaaaaace      |   |                                                       |
 |...              |   |                                                       |
 |                 |   |                                                       |
 |                 |   |                                                       |
 |                 |   |                                                       |
 +-----------------+   |                                                       |
                       |                                                       |
                       +-------------------------------------------------------+
````

**Comment by camallen** [comment]
I think the concerns are valid about crowding, however this is really a UX issue and we should consult with @beckyrother on this. Failing any concrete decisions i think all projects should remain on the project listing and we add in the organizations filtering / own page somehow as well. 

We can see how annoyed our volunteers get by having a bunch of new projects at the top of the list. It may not even be an issue as most might use that page for searching instead of discovery (i do though i understand that I have my own workflow for this: emails, then search).

**Comment by mcbouslog** [comment]
That's a great point, so few may use `/projects` in the way I'm worrying about that would be a bad UX that we might as well wait and see if anyone actually complains.

**Comment by beckyrother** [comment]
Hi all, thanks for tagging me. The projects page is my next focus once we've got the classify update a bit farther along. These are really helpful suggestions, but if you don't mind, please hold off on making any major layout changes until I've had the chance to spend some time with this section.

**Comment by mcbouslog** [comment]
Ok unless there are any objections we'll have organization linked projects show as launched approved just like any other project. I'll close this issue in favor of user feedback and general `/projects` redesign (https://github.com/orgs/zooniverse/projects/4#card-6495644). Thanks all for your patience and input!
