### ISSUE TITLE
 Return back an error if can't get a data export 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes#2623]
If you try and request an export twice in 24 hours, there is no message saying you're not actually getting an export. It just says 'Processing your request' on the front end data exports page. If there's an error or it can't send the export, the front end should let you know or at least an email saying the query coudln't complete. Otherwise you're waiting and waiting and it looks like things are okay.

**Comment by mschwamb** [comment]
Originally posted on the front end repo and told to move the issue here https://github.com/zooniverse/Panoptes-Front-End/issues/4293

**Comment by mschwamb** [comment]
I still think this would still be useful especially if you've already hit your quota for data exports or it is shutdown due to stargazing live.

**Comment by camallen** [comment]
You get an error if it's disbaled for SGL, not for the rate limit though as this rate limiting is in a part of the system after the request is responded to.

**Comment by mschwamb** [comment]
Ah. It would be nice if there was an error if your request never finishes even if it's an email saying sorry this can't complete rather than a message on the front end.

**Comment by camallen** [comment]
I'll make a note to look at how we report errors for this. I can see how we can send an email error.

**Comment by mschwamb** [comment]
I still think this would be useful, especially since it takes hours to get classification exports that it might seem like there is a problem when there isn't or you don't know if it is because of the one export per  24 hour rule
