### ISSUE TITLE
No user referenced when not logged in

### ISSUE THREAD

**Issue by miclaraia** [zooniverse/Panoptes#2649]
When a user submits a classification while not logged in, the classification dump is made with the user_id field left blank and a unique string that is associated to a user's hashed ip.

If however the python client is used to inspect a classification made by a user who is not logged in, there is nothing in the raw data received by the client that would allow us to associate the classification to the same unique user identifier. While there is a unique session string in the metadata field, this is not the same as what is in the username field in the csv dump.

Classification raw data in python client:
`{'id': '88474114', 'annotations': [{'task': 'T0', 'value': 0}], 'created_at': '2018-02-03T01:38:05.235Z', 'updated_at': '2018-02-03T01:38:11.037Z', 'metadata': {'session': '9440df0368e7819e53e5ba72b3db94133d9c4a4a4d75014fce12910e4ed968a7', 'viewport': {'width': 1918, 'height': 869}, 'started_at': '2018-02-03T01:37:59.739Z', 'user_agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36', 'utc_offset': '21600', 'finished_at': '2018-02-03T01:38:05.116Z', 'live_project': False, 'user_language': 'en', 'subject_dimensions': [{'clientWidth': 782, 'clientHeight': 782, 'naturalWidth': 2000, 'naturalHeight': 2000}], 'workflow_version': '32.38'}, 'href': '/classifications/88474114', 'links': {'project': '5918', 'workflow': '5734', 'subjects': ['17511849']}}`

Same classification data in csv dump:
`{'classification_id': '88474114', 'user_name': 'not-logged-in-84e52d3d29185275d480', 'user_id': '', 'user_ip': '84e52d3d29185275d480', 'workflow_id': '5734', 'workflow_name': 'cluster classifiation', 'workflow_version': '32.38', 'created_at': '2018-02-03 01:38:05 UTC', 'gold_standard': '', 'expert': '', 'metadata': '{"session":"9440df0368e7819e53e5ba72b3db94133d9c4a4a4d75014fce12910e4ed968a7","viewport":{"width":1918,"height":869},"started_at":"2018-02-03T01:37:59.739Z","user_agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36","utc_offset":"21600","finished_at":"2018-02-03T01:38:05.116Z","live_project":false,"user_language":"en","subject_dimensions":[{"clientWidth":782,"clientHeight":782,"naturalWidth":2000,"naturalHeight":2000}]}', 'annotations': '[{"task":"T0","task_label":"Which class dominates this cluster?","value":"All Muons"}]', ... , 'subject_ids': '17511849'}`

**Comment by marten** [comment]
One quick note: it's not a hashed IP. That wouldn't be secure, since a project owner can spend a week crunching hashes and find all the unhashed ones if we did that, even with salting. 

Instead, we assign each IP a random string. Right now we just generate these on the fly during exports (so if you generate a new dump, the identifiers will be different for the same classification). I think we could safely store these on a per-project basis (in the UserProjectPreference resource) and use them for both the CSV dumps and the API. @camallen @zwolf thoughts?

**Comment by camallen** [comment]
Question, how will this work for non-logged in users on the project preferences? 

I like the idea of pre-computing a value here and ideally it should be in the classification payload via the API to solve this and the dumps issue. Ideally this would be an API we can call to backfill a table / include when serializing dumps, etc, noting it will need to be robust enough to track the same user / ip over time.

**Comment by marten** [comment]
Ah. D'oh.
