### ISSUE TITLE
Unable to access data dump links within the 24 hours window

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes#2659]
I requested classification dumps from P4: Terrains. I received the emails at 10:00 am HAST yesterday. It's 5 am so I should still have time to download the files. Now trying to open them before the 24 hour window I'm getting both links giving errors saying 'The provided token has expired.'

**Comment by mschwamb** [comment]
The front end says I requested a data dump for all the classifications  17 hours ago and the one for a classification dump for a specific workflow incorrectly says I requested the previous request a few seconds ago (which isn't true so something is incorrect there)

**Comment by camallen** [comment]
Closing to consolidate in #2830
