### ISSUE TITLE
Doorkeeper: 422 error when editing a redirect URL

### ISSUE THREAD

**Issue by simensta** [zooniverse/Panoptes#2709]
After editing a redirect URL in Doorkeeper and pressing the submit button, I receive the following error: HTTP ERROR 422. The name of the application is Ancient Lives Frontend. Let me know if you need further info!

**Comment by camallen** [comment]
This will be due to the mixed security schemes (http & https) as redirects. I've manually fixed this in the doorkeeper app via the UI.
