### ISSUE TITLE
next_href drops emails param

### ISSUE THREAD

**Issue by adammcmaster** [zooniverse/Panoptes#2733]
If I request something like:

```
/api/users?email=user%40example.com%2Cuser%40example.com%2Cuser%40example.com%2Cuser%40example.com%2Cuser%40example.com%2Cuser%40example.com%2Cuser%40example.com%2Cuser%40example.com%2Cuser%40example.com%2Cuser%40example.com%2Cuser%40example.com&admin=True
```

The `next_href` is returned without the `emails` param: `/api/users?page=2&admin=True`

I assume something was missing from #2673

**Comment by camallen** [comment]
@astopy instead of deleting the email param as you have done in #2673 you should leave it and it'll filter into the `href` response via the serializers. As it stands deleting the param doesn't allow the serializer to insert it.
