### ISSUE TITLE
is backend sending last subject to be classified?

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes#2734]
I've found this odd that the last Planet Four: Ridges subject isn't getting classified. It's been a few days and we're still 1 subject shy of completion. I don't classify very often so I would expect if I logged in, I'd get the lone subject. I figured I'd mention it if there is something stopping it from triggering the out of data messages since I haven't seen the site stuck with 1 subject left to do.

**Comment by camallen** [comment]
All the data had been classified but a counter had not been updated,. It should have run but i can see one scenario where it may not. I'll look into this. 

The out of data message is now up and the completeness is 100%. I've moved it to paused status in the meantime, let me know if you'll be adding new data soon.

**Comment by mschwamb** [comment]
Thanks.
