### ISSUE TITLE
project that was paused but now has new data, doesn't show up on list of live projects

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes#2772]
Planet Four: Terrains is not showing on the project page. I was looking here:

https://www.zooniverse.org/projects?discipline=astronomy&page=1&status=live

It didn't have data for awhile,but it does now. Can someone set the project's status back to active. Does this need to be done every time there is data on the site after the site runs out?

**Comment by mschwamb** [comment]
Closing since I see the project listed now. Thanks

**Comment by camallen** [comment]
this should be happening automatically when you add new data and link it up.
