### ISSUE TITLE
Landing page stats update - exclude never retire subjects

### ISSUE THREAD

**Issue by aprajita** [zooniverse/Panoptes#2795]
copied from PFE on @camallen's advice.

## Expected behavior
Stats should exclude any subjects set to 'never retire'

## Current behavior
included all active sets, even if they will never be retired

## Steps to replicate
visit https://www.zooniverse.org/projects/aprajita/space-warps-hsc

![image](https://user-images.githubusercontent.com/1917970/41095606-d01f6fee-6a49-11e8-80af-c38f49166db6.png)

includes 19748 training subjects so will never be 100% complete

caused a large misunderstanding during science friday week causing many users to only get the already seen flag and multiple classifications on the same images.

thanks!

**Comment by marten** [comment]
@camallen was there an idea as to how to fix this? Since the workflow is actually the one set to 'never retire', for all subjects. And then it just happens that Caesar comes along and retires things, but Panoptes doesn't really know how many subjects will or will not retire that way.

Are we adding retirement limits per set?

**Comment by marten** [comment]
In this particular case, their external script outputs a field "gold" which Caesar uses to ignore gold subjects. Some other projects we read from the subject metadata directly (which I think is what the SW script is also using).

**Comment by camallen** [comment]
We can adopt the caesar training data setup by using the `training_subject` subject metadata to identify training data in the Panoptes API. 

This subject metadata attribute can be copied to internal records (SMS) to allow us to filter the training subjects data for completeness counts. 

If we copy that metadata to the SetMemberSubject(SMS) attribute (index?) we can filter those SMS training subjects for both the subject_set#subjects_count field 
https://github.com/zooniverse/Panoptes/blob/051a49db038b83ed0e758bc15eaf94b55675f127/app/workers/subject_set_subject_counter_worker.rb#L16

As well as the query on retired counter 

https://github.com/zooniverse/Panoptes/blob/051a49db038b83ed0e758bc15eaf94b55675f127/app/counters/workflow_counter.rb#L19

Caesar docs on marking training subjects:
https://github.com/zooniverse/caesar/blob/75ba896d7221c39a1f1209645796fc80fc5121cc/docs/source/includes/_subject_metadata.md#training_subject

**Comment by lcjohnso** [comment]
Regarding #training_subject = @zwolf and I (@lcjohnso) had a good conversation about adopting the Caesar-style metadata tag for subjects that will not retire in two contexts: 1) PH-TESS like training subjects that are served along with real-data subjects in a single workflow; 2) Practice Workflows where all subjects are for training purposes only, such as used by Earthquake Detective.  In both cases, it will be good to tag and remove these subjects from completion counters.

Copied here from https://github.com/zooniverse/Panoptes/pull/3130 to make sure my bases are covered!

**Comment by zwolf** [comment]
PR above was merged, but this issue was deemed out of scope for it. This will remain open and we'll design a scheme for denoting training subjects and their meanings across our platforms at some point in the future.

**Comment by aprajita** [comment]
Thank you Zach!
