### ISSUE TITLE
60K subjects retired with no retirement_reason, retired.id or other retirement info 

### ISSUE THREAD

**Issue by mfidino** [zooniverse/Panoptes#2845]
Looking through the historic Chicago wildlife watch (CWW) it appears that roughly 60K images from past seasons were retired but 1) no reason was given and 2) they were not given a retirement id. Furthermore, roughly half of these subjects were only seen by a single CWW user. While photos tagged as `HUMAN` or `HMN` get retired after one ID, a majority of these 'retired' subjects that were seen only once were not tagged as `HUMAN`. 

Here is a text file (comma delimited) with the 63494 subject_ids that are lacking retirement information (though they were linked to previous seasons that hit 100% completion). 

[CWW_false_retirement.txt](https://github.com/zooniverse/Panoptes/files/2202264/CWW_false_retirement.txt)

**Comment by marten** [comment]
I've had a look at a random subject from that list, 3414932.

It doesn't appear to be retired as far as I can see. It does have 1 classification, but for some reason it doesn't appear to have a SubjectWorkflowStatus to go with that (at all!), which any subject that has one or more classifications should have. 

That status object is also what records retirement, so with it not there at all, it won't be retired.

Where did you get the initial data from that indicates that these subjects are retired? Perhaps you could find the corresponding row for this subject in that, and paste the entire data for that one subject?

**Comment by mfidino** [comment]
That subject came from our Fall 2014 camera trapping season which was tagged on CWW in 2016. Once that specific season had hit 100% completion on the CWW project page we assumed that all images had to have been retired.

From looking through these images, it appears that this error mostly occurred on our SP14, FA14, and FA15 seasons (tagged on CWW between August 2016 and Janurary 2018) over multiple workflows (2334, 3656, 2660, 2664, 3054, and 4377). 

I got the data as a classification export from the CWW project builder page. Here is the row of data from subject 3414932.

[sid3414932.txt](https://github.com/zooniverse/Panoptes/files/2202403/sid3414932.txt)

**Comment by camallen** [comment]
I'd suggest making a new subject set with the non-complete data based on your interpretations and re-linking them to the workflow to get them classified.

**Comment by marten** [comment]
I think there's not much we can do on this at the moment, so I'll close it for now. Feel free to reopen if desired.

**Comment by trouille** [comment]
@camallen Do you have thoughts on what might have happened around this time for the project to show up as 100% complete but have subjects that weren't yet retired? It's understandable that when Mason saw that 100% complete message that he then moved on to the next season. Moving forward, I know he'll be double checking that all subjects have truly reached their retirement limit before hooking up the next season. 

I think it will be helpful for me to post a blog to the Chicago Wildlife Watch blog explaining the error and apologizing for it, with the timing coinciding with when the CWW team links a subject set with these subjects that still need classifications to an active workflow. This will help the volunteers understand why they're being asked to classify again on previous seasons. 

Mason, thanks for bringing this to our attention. Let me know what you think about me posting a blog post in time with your re-linking these subjects. And/or posting one together -- but I'm happy to help explain and also apologize to your volunteers. 

Also, @camallen or @adammcmaster Is there a systematic way with https://github.com/zooniverse/panoptes-cli to link a given set of existing subject IDs to a new subject set? 

Thanks all!

**Comment by mfidino** [comment]
@trouille. Hi Laura, it's going to be a while before our current season is finished, but I will keep you in the loop for when we send out the next season that will be comprised of these images. Thinking about it the 100% complete message not only encourages me to move to a new season but no doubt influences tagging rates from users as well (it's not like people are going to continue tagging photos if you visit the site and it says 100% complete, even though it isn't). 

I'll definitely be double checking to make sure that images have their associated retirement ID before moving to another batch of photos.

**Comment by adammcmaster** [comment]
> Also, @camallen or @adammcmaster Is there a systematic way with https://github.com/zooniverse/panoptes-cli to link a given set of existing subject IDs to a new subject set?

Assuming you already have the subject IDs in a text file, one per line, you can use the `xargs` command to wrap the CLI:

```
cat subject-ids.txt | xargs panoptes subject-set add-subjects 12345
```

Where `12345` is the subject set ID.
