### ISSUE TITLE
Migrate to jenkins file deployment for panoptes production - how / what is the best strategy?

### ISSUE THREAD

**Issue by marten** [zooniverse/Panoptes#2856]
Cam to replace this with thoughts/decision

**Comment by camallen** [comment]
Staging env is now setup to work as it previously was via https://github.com/zooniverse/Panoptes/blob/2bc874ef986999c986c52825e89e0553f50d49a1/Jenkinsfile#L15, i.e. on merge to master build latest image, trigger ami builds, run pending migrations and launch new api & worker instances. 

Production is a little trickier in that we want to choose when to run migrations before / after deployments. One solution to this is to reflect on the state of the merge event to flag a migration needs to run before the instance deployment, i.e. we can include a file in the repo that would block the Jenkinsfile script deployments from running or cause jenkins pause the pipeline for user intervention (possible?). As much automation should happen, i.e. each production tag/branch merge should still build and push a production tag docker image and build the AMI to save time.

While we don't know exactly how to achieve the above we can still proceed to migrate to this system and still use chat ops to deploy the panoptes infrastructure as we do now. 

As we evolve our jenkins knowledge to handle the issue of choosing when to run migrations we can finish automating the production deployments as well.
