### ISSUE TITLE
Comet Hunters still says it is out of data hours after new images added to the site

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes#2872]
It's not  a huge number of subjects, but I did add new subjects to the Comet Hunters website and the front end continues to show the out of data message. I presume this is a backend delay posting here.

**Comment by adammcmaster** [comment]
Just to rule out the easy possibilities, which subject sets did you upload subjects to? Are the right sets active?

**Comment by eatyourgreens** [comment]
Data set 5 has `set_member_subjects_count` of 0, despite containing subjects. https://www.zooniverse.org/lab/724/subject-sets/48021

**Comment by mschwamb** [comment]
data_set 5 is the new one. It is linked and active. I uploaded via the command line client.  And yes is stays number of subjects is 0. I'm not sure why.

**Comment by mschwamb** [comment]
@adammcmaster I did do an update on the command line client with pip before using it so I'm using the latest version

**Comment by mschwamb** [comment]
hiya, any help on this would be appreciated. I can't send a newsletter out until the messages of out of data get off the site and it's not clear the retirement rates will be correct if the subject set count is 0

**Comment by camallen** [comment]
@mschwamb this should be fixed now. OOI did you unlink the finished sets from the data base as well?

**Comment by mschwamb** [comment]
Thanks. This time I did not. I'm having a hard time keeping track of what's what with just subject set name so I kept all the reprocessing suprime data linked

**Comment by camallen** [comment]
Ok - then the counters make sense. I'm closing this, feel free to re-open if needed.

**Comment by camallen** [comment]
Thanks @CKrawczyk i'm going to recount all the live linked sets to make sure they are up to date.
