### ISSUE TITLE
Return empty list when there are no existing links?

### ISSUE THREAD

**Issue by adammcmaster** [zooniverse/Panoptes#2902]
I'm adding a class to the Python client to handle management of links (see zooniverse/panoptes-python-client#181). This class will be used automatically for any links that are returned as a list of IDs rather than a single ID, and will allow simple code like `Project.find(1234).links.workflows.add(5678)` to link objects together.

I'm running into a problem, though, if there aren't any links already, because the Python client doesn't know anything about what attributes/links each type of object has. I'd rather not have to hard code in which classes of objects are linked to each other, since that will require keeping the client and the API code updated together.

Is it feasible for the API to just return something like this?

```json
{
  ...
  "projects": [
    {
        ...
        "links": {
          "workflows": [],
        }
    }
  ]
}
```

I know there's also a top-level `links` key in the response, which should list all the linked classes, but it doesn't give any hint about which ones are one-to-one and which are (one|many)-to-many. Another option could be to add a type field to there.

**Comment by marten** [comment]
To clarify, if I understand it correctly the API is just omitting the "workflows" key from the links hash altogether when there are no workflows. This wasn't immediately clear to me, but I think it's a fair suggestion. I might have a time-boxed stab at this, but not for a week or so probably.
