### ISSUE TITLE
Classifications and Subject Storage

### ISSUE THREAD

**Issue by edpaget** [zooniverse/Panoptes#292]
Storing in Postgres is going to be slow.

**Comment by camallen** [comment]
We'll probably need a GIN index on the 'set_member_subject_ids' field on the classifications table to filter classifications / subject for stargazing.

**Comment by edpaget** [comment]
We've decided to use Cassandra for storage if its needed in the future, but we won't be using for stargazing.

**Comment by camallen** [comment]
If greg wants to retrieve classifications by subject Ids then we will still probably want the index on the db: https://github.com/zooniverse/Panoptes/blob/829be6289731513dacc8ad7d5abb1f2ed0e6f8cb/db/schema.rb#L59

Might be costly long term so we could ditch it after stargazing.

**Comment by edpaget** [comment]
I was still intending to save classifications for that query in some other way for greg to access.

**Comment by camallen** [comment]
Interesting, I was planning running a read only rds replica with non-public api nodes so greg can run long running queries. Other solutions welcome!

**Comment by ggdhines** [comment]
So support for JSON in Cassandra seems to be slightly limited - http://stackoverflow.com/questions/25026887/json-type-in-cassandra-data-model. You can get around that by using User Defined Types which (I think) make you spell out the exact details of everything about a JSON object in advance - definitely removes the flexibility. Also, the current Python/Cassandra connection (cqlegine - https://github.com/cqlengine/cqlengine) does not currently support UDTs - https://github.com/cqlengine/cqlengine/issues/317. They are working towards it but definitely not there yet. So for the mean time, JSONs in Cassandra are just going to be strings which means not being able to search/sort based on any fields in the JSON object.

**Comment by camallen** [comment]
Thats not entirely correct, we can use maps to store arbitrary data (e.g. JSON):
http://www.datastax.comhttp://www.datastax.com/documentation/cql/3.1/cql/cql_reference/cql_data_types_c.html
An example: http://dba.stackexchange.com/questions/55165/cassandra-query-a-column-with-collection-type

The question really is what is our query (use-case) paths will be and if we should de-normalise the data into their own columns to improve query performance. 

We really need to evaluate and test some different datastores. Cassandra, Riak, HBase are the main contenders for me but we should look broadly like Couchbase, Mongodb, Redis and others.

**Comment by ggdhines** [comment]
Cassandra 2.1 and later supports indexing on collections (so subject_ids which was what was causing the problem with Stargazing). My computer is running Ubuntu 14.10 and only has Cassandra 2.0.11 - not sure how easy it is to get 2.1 running but it looks as if the default version of Cassandra is not current enough.

**Comment by ggdhines** [comment]
Cam - it was "workflow_version" under "metadata" that I needed to query during Stargazing. I think this is important enough (I will always be filtering based, in part, on workflow_version) that it might be nice to have it as its own field.

**Comment by camallen** [comment]
Re getting 2.1 installed, looks like this will do it: http://www.datastax.com/documentation/cassandra/2.1/cassandra/install/installDeb_t.html?

So denormalising the data for the aggregation use case is where we can get specific gains vs those of the API use case (storing data quickly via HTTP requests). I.e. extracting out your subject Ids, workflow versions, etc to their own columns for indexing / querying. We can really do what we want here via the data transfer bus (kafka / other message broker) producer / consumer code. 

What we should define is the operational requirements on your end (query paths / field indexing) and then evaluate the different tech solutions in this context plus the context of long term storage / scalability over time / data volumes.

**Comment by ggdhines** [comment]
So Cassandra doesn't currently support queries like 
select * from users where first_name in ('françois','frank');
https://issues.apache.org/jira/browse/CASSANDRA-4386
Minor issue but just something to weigh when considering different DBs (the above style of query would be really useful when querying for multiple subject IDs, for example) - the alternative code could definitely get painful.

**Comment by ggdhines** [comment]
Also just got this error from Cassandra - 
code=2200 [Invalid query] message="ORDER BY is only supported when the partition key is restricted by an EQ or an IN."
Was trying to order by subject_id. This is definitely a bigger pain than the previous issue. Not too much of an issue if/when we decide to use Spark (I can just use the subject_id as the key when mapping) but for just writing simple analysis this is a definite issue.

**Comment by camallen** [comment]
Cassandra does support those queries they just have to be setup properly on the primary index. https://www.datastax.com/documentation/cql/3.1/cql/cql_reference/select_r.html?scroll=reference_ds_d35_v2q_xj__selectIN

The example you provided was on secondary indexes not primary as discussed in the link above. they have some text about when not to use IN [here](https://www.datastax.com/documentation/cql/3.1/cql/cql_reference/select_r.html?scroll=reference_ds_d35_v2q_xj__selectInNot).

Cassandra has a very different data model to normal databases. We have to transform the data from a relational structure (PostgreSQL) to fit cassandra and how we will be accessing the data, query paths, etc. It's not a straightforward mapping but a rethinking of the data set and the internal stuctures, e.g. metadata hash can mostly be extracted to their own columns in cassandra. Then we create indexes on these that fit our query paths. Perhaps even extracting to multiple tables that fit different index / query paths, http://wiki.apache.org/cassandra/DataModel.

Happy to chat about this further.

**Comment by camallen** [comment]
@ggdhines your last issue is again a data modelling issue, i assume you've done a direct transfer of the SQL db data to cassandra? Check this out for more info on setting up your primary partition keys, etc https://www.datastax.com/documentation/cql/3.1/cql/cql_reference/refCompositePk.html

**Comment by ggdhines** [comment]
My understanding of a primary index is that the key must be unique - is this not the case?

**Comment by camallen** [comment]
You can define composite / compound primary keys. So the uniqueness can come from the columns you want. Off the top of my head something like user_id, workflow_version, subject_id, date_time, (others?) should get you decent primary key. 

The links before have good examples about creating primary keys for use in queries.

**Note: i haven't actually spent anytime delving into the docs this is off the top of my head**

**Comment by ggdhines** [comment]
So Cassandra doesn't allow for lists to be a part of an index. We need to be able to sort the classifications by the corresponding subject_ids. For classifications, we store the subject_ids as a list, since a classification might relate to more than one subject.

**Comment by camallen** [comment]
Can't we just de-normalise the list, i.e. add a classification row for each of the subject_ids?

**Comment by ggdhines** [comment]
If a classification is about two subjects - say A and B, then the classification gives a relationship between A and B, eg there is more algae in A than in B. So we need a way of storing that relationship. If we just de-normalize stuff then we could lose that. If someone compares A to B and then C to D, if we wind up with 4 separate classifications, how do we reconstruct the comparisons?

**Comment by camallen** [comment]
How about the stored classification id from the DB?

**Comment by ggdhines** [comment]
I need to be able to sort by subject id - for example, give me all the classifications for subject A. So the index has to be on the subject id.

**Comment by edpaget** [comment]
@ggdhines you can create a secondary index on a collection in Cassandra > 2.1 http://www.datastax.com/dev/blog/cql-in-2-1

**Comment by ggdhines** [comment]
are lists allowed in secondary indices?

**Comment by edpaget** [comment]
Yes, from all the docs I've seen, Lists are a collection type and can be indexed.

**Comment by ggdhines** [comment]
sorry @edpaget, I should have just checked myself. Seems to work fine

**Comment by edpaget** [comment]
Also Greg I don't know if you want to hold off on trying to get the Spark/Cassandra pipeline up and running until after we launch, but we can probably just work with straight python and another postgres database if that'd be easier to make sure we have something set up for the 21st.

**Comment by ggdhines** [comment]
I think that is @camallen's call. I think we can definitely get Cassandra/Python working by the 21st - would hopefully make adding in Spark later easier.

**Comment by camallen** [comment]
@ggdhines - My understanding was live aggregation is not required for launch on the 21st but it would be good to have working as soon as we can. We can replay data out after the fact to populate the cassandra data store when you're code is ready.

**Comment by ggdhines** [comment]
@edpaget - I have set up a secondary index for subjects. I then tried:
select * from classifications order by subject_ids;
and get:
"ORDER BY is only supported when the partition key is restricted by an EQ or an IN."
See http://www.maigfrga.ntweb.co/counting-indexing-and-ordering-cassandra/ for more details. Any suggested workarounds?

**Comment by camallen** [comment]
@ggdhines I still think that de-normalizing the data into mutliple rows and using a primary key like `PRIMARY KEY(id, classification_id(postgres), subject_id, workflow_version_id, user_id, created_at)` would work. 

Alternatively we could use another table to do this as well and keep the classifications table as is but have some key to bind them together (postgres classification id perhaps)?

I think they key to accommodating these queries is knowing what the query paths are ahead of time and designing the data model (table), to achieve it. That said we live and learn.

**Comment by ggdhines** [comment]
@camallen I'm happy to denormalize too - just not sure how aggregation would work when we have people classify multiple subjects at once. For future thought. Anyways, the basic command in Cassandra to set up the DB sorted by subject_id is (not all fields are included but the idea is there)
CREATE TABLE classifications( project_id int, subject_id int, user_id int, annotations text, created_at timestamp, user_ip inet,  PRIMARY KEY(project_id,subject_id,user_id,user_ip,created_at) ) WITH CLUSTERING ORDER BY (subject_id ASC, user_id ASC);

**Comment by camallen** [comment]
Just backing up a bit, what's the use case for `select * from classifications order by subject_ids;`? Wouldn't one want to get all classifications for a known subject id? I assume you're doing this because we don't have a set of known subjects for the project's workflows?

**Comment by ggdhines** [comment]
When you are running aggregations, you need all of the classifications sorted by subject. BTW I don't know how the aggregation results will be stored if a classification relates to two or more subjects.

**Comment by camallen** [comment]
Won't the sort order be arbitrary based on the subject_ids across the whole set of classifications? Wouldn't you just retrieve all classifications that contain a specific subject id and loop through the know set of subject ids?

Perhaps `SELECT * FROM classifications WHERE subject_ids CONTAINS '1';`

**Comment by ggdhines** [comment]
An arbitrary order would be fine - e.g. if the subject_ids are ordered 5,3,9,1, then I just update the aggregations for the subjects in that order. Looping through a set of subject ids would be only used if there were specific subjects we want to update the aggregations for. Even in that case we need the DB sorted by subject_id, we don't want to have to search through the whole DB every time we want the set of classifications for a given subject_id.

**Comment by ggdhines** [comment]
Hey -  I don't understand the difference between Apache SQL and Cassandra. Not sure how to write data to a DB in Apache SQL but other than that, it seems like a better option than Cassandra (Cassandra+Spark+Python is currently somewhat limited)

**Comment by edpaget** [comment]
@ggdhines can you link to apache sql?

**Comment by ggdhines** [comment]
@edpaget - sorry I meant Apache Spark SQL https://spark.apache.org/sql/

**Comment by edpaget** [comment]
Ah yeah it seems like it would make sense to use that. We just have to the figure out where to store the classification data for spark, in s3 or hdfs and what format to store it in.
