### ISSUE TITLE
Subject Queue Behaviour/Expert Classifications 

### ISSUE THREAD

**Issue by edpaget** [zooniverse/Panoptes#293]
Let's figure this out.

**Comment by edpaget** [comment]
Hey all (maybe @ggdhines in particular), will every workflow in a project need to have expert classifications? If so, I'll create an extra subject set along side every workflow that can hold the subjects for expert classification.

**Comment by chrislintott** [comment]
There is a use case that won’t have expert classifications - for rare animals on classification projects, for example, it won’t be feasible to create a suitable training set until the first data comes in.

So there could be a workflow with no expert data.

Chris
