### ISSUE TITLE
Optimistic Locking using Versions

### ISSUE THREAD

**Issue by edpaget** [zooniverse/Panoptes#296]
We should add locking for resources that can be collaboratively edited.

**Comment by edpaget** [comment]
@brian-c how do you feel about using the `Last-Modified`/`If-Modified-Since` headers. It would work similarly to ETags, but when you retrieve a collection the Last-Modified header will have the date of the most recently modified resource. That way you still send that back as the `If-Modified-Since` header of a PUT or DELETE request, and if the resource you're deleting or updating was modified in the since you fetched the collection it will fail and return a `409 Conflict` response.

**Comment by brian-c** [comment]
I imagine that'll work fine, as long as "Last-Modified" is in `Access-Control-Expose-Headers`.

**Comment by edpaget** [comment]
The actual header for PUT and DELETE requests will be `If-Unmodified-Since` optionally you can send `If-Modified-Since` headers for GET requests and the API will respond with `304 Unmodified` if nothing has changed.
