### ISSUE TITLE
Should we run the default selector on external selector failure?

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#2982]
https://github.com/zooniverse/Panoptes/blob/79df16a8151372cee852bca63f292e3ea778a495/lib/subjects/strategy_selection.rb#L38

Here we catch connection errors to the external selector services and run the default selector instead. 

Now we've added some status reporting into the selector i think this should just return an empty array and allow the selector to handle situation and report the failure mode correctly too. https://github.com/zooniverse/Panoptes/blob/79df16a8151372cee852bca63f292e3ea778a495/lib/subjects/selector.rb#L37

With a situation such as a user that has finished all available data, this change could save 1 extra selection path for an event, e.g.:
```
1. request to get new subjects
2. external selector connection error
3. run internal selector and returns [] (no available data)
4. run internal fallback selection in selector again return []
```
vs 
```
1. request to get new subjects
2. external selector connection error and returns []
4. run internal fallback selection in selector again return []
```

**Comment by marten** [comment]
Should we add explicit statuses on top of the returned array coming from selectors? If the external selector worked fine but the user has seen all data, it could signal that so that we can skip the internal selector in that case. When the external selector is actually erroring it would still make sense to try the internal selector?

**Comment by camallen** [comment]
> Should we add explicit statuses on top of the returned array coming from selectors?

I'd be up for that. 

>If the external selector worked fine but the user has seen all data, it could signal that so that we can skip the internal selector in that case.

That's a good idea, the only issue i see is if the selector is out of sync and returns no data but we still signal correct behaviour and don't run the internal selector (which would return unseen, unretired data). This is def and edge case though, normal behaviour would have consistent state between the two systems. That said I've had some reports (from @yshish) about seens mixed into their selected queue.

>When the external selector is actually erroring it would still make sense to try the internal selector.

I think so, in case of say server error / network failure we'd still want to run our internal selector, though not here, instead say via https://github.com/zooniverse/Panoptes/blob/80dd550ce478496b643590b8b7848a0e5d1d5f4f/lib/subjects/selector.rb#L39
