### ISSUE TITLE
Should we rename this attribute to interventions?

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#3007]
https://github.com/zooniverse/Panoptes/blob/15595ed92cab784c138a2aac88ba4467225a23d1/db/structure.sql#L1593

`intervention_notifications` -> `interventions`

This boolean attribute specifies if a user chooses to participate in interventions or not. I think we can remove the notifications part of the attribute name as interventions may include more than just message notifications.

PFE would have to coincide changes for the following files https://github.com/zooniverse/Panoptes-Front-End/search?q=intervention_notifications

**Comment by eatyourgreens** [comment]
Makes sense to me. If this flag covers all interventions, then PFE should delay adding the Sugar experiments listener until after the user is logged in, and then only add the listener if `interventions` is true.

**Comment by marten** [comment]
:+1:
