### ISSUE TITLE
pause a project when all workflows are unlinked

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#3037]
Some project owners 'pause'  a project by unlinking all the workflows. We should detect this event and set the project state to paused if there is no data to process.

**Comment by chrislintott** [comment]
If we do that, how would we let people pause their projects? I guess they can just use a banner but the fact they’re doing this suggests there is a need we’re not meeting here.


On 3 Jan 2019, at 00:25, srallen <notifications@github.com<mailto:notifications@github.com>> wrote:


Is this something that we should support? Inactivating all the workflows makes the project look broken. I'd rather disallow project owners from being able to inactivate all of their workflows for live/launched approved projects.

**Comment by eatyourgreens** [comment]
Is there any reason why we don't let owners pause their projects from the status page in the project builder?

**Comment by srallen** [comment]
I think Panoptes would unpause them because of the automation if they aren't actually at 100% complete.

**Comment by camallen** [comment]
closed by #3075
