### ISSUE TITLE
Request: improve Classifications fetching efficiency, for large page numbers

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/Panoptes#3068]
## Improvement Request

Request: improve efficiency when fetching Classifications from `/classifications` with a _large page number._ e.g. `https://www.zooniverse.org/api/classifications?workflow_id=1234&page=100`

### Context

In [WildCam Darien Lab](https://classroom.zooniverse.org/#/wildcam-darien-lab), Student users have a feature that lets them download their work (i.e. _their_ Classifications) for a _specific_ Workflow. e.g. `https://www.zooniverse.org/api/classifications?workflow_id=1234`

Since simply setting page_size=100000000 to fetch all Classifications would be a bad idea, the currently planned method is to download the data in chunks - i.e.
```
Fetch https://www.zooniverse.org/api/classifications?workflow_id=1234&page=1 
If still more data, then
Fetch https://www.zooniverse.org/api/classifications?workflow_id=1234&page=2 
If still more data, etc etc etc
```

### The Problem

It's been brought to my attention that with large page numbers - e.g. `https://www.zooniverse.org/api/classifications?workflow_id=1234&page=100` to fetch Classification items number 1980 to number 2000 - the database might _still_ need to figure out what are the first 1979 items.

### The Solution?

@camallen has alerted me that there's a solution where a request to a resource can also return a `last_id` value, which can in turn be passed to the _next request_ to let the database efficiently 'skip' items up to that id.

### Status
This request isn't blocking the development of WildCam Lab/the Education API Front End, but it may cause efficiency issues if not eventually addressed.

In the meantime, WildCam Lab's chunking solution will also add an additional 'junk' parameter - e.g. `https://www.zooniverse.org/api/classifications?workflow_id=1234&page=100&classroom=5678` - that will be safely ignored by the API, but will be useful for checking the logs to see if Classroom requests _are_ causing DB problems.

**Comment by camallen** [comment]
The solution here would involve porting the `last_id` scope augmentation to the index controller action. This would allow the requesting user to access their completed classification but avoid the long request times when paging into a large scope of data. 

https://github.com/zooniverse/Panoptes/blob/ea0af1649b34a0bd1ca919375bfba8dca166f409/app/controllers/api/v1/classifications_controller.rb#L60
