### ISSUE TITLE
Enable workflow to only show in mobile app

### ISSUE THREAD

**Issue by trouille** [zooniverse/Panoptes#3127]
Is there back-end Panoptes work needed before mobile dev can set things up so an active workflow can be flagged to only show up on the mobile app, rather than in both the app and the browser? 

This is relevant for the Mapping Historic Skies project and has come up with other projects that want the workflow to only show up in the app rather than both app and browser. Note: there's still the use case where the researcher will want an active workflow to show up in both the app and the browser. 

This is also relevant for the GZoo Touch Table project -- we'll want that active workflow to only show up on the touch table and not also as part of the GZoo browser experience.

**Comment by srallen** [comment]
I think it's a bad idea to limit access to workflows like this, but if you must, then leave the workflow inactive and have the app request by id the project intends to be mobile only. The lab could be updated to store in the project config an array of mobile only workflow ids perhaps. I don't think we should change how Panoptes serializes or filters workflows based on this.

**Comment by trouille** [comment]
Thanks for this comment @srallen 

By leaving the workflow inactive, can retirement rules still apply? Are the classifications stored?

**Comment by srallen** [comment]
If an HTTP POST request is made, then classifications are always stored in the database regardless of workflow activeness or project's liveness. Retirement is based on a project's liveness, not a workflow's activeness. Once a project is made live, the counters start running and retirement triggers when the classification count for a subject hits the number configured on the workflow.

Workflow activeness really is only for the front-end to filter workflows based on display or access requirements.

**Comment by srallen** [comment]
That being said, I really don't think we should limit where volunteers are coming from. Why would it be a bad thing that a desktop user classifies on the workflow for the touch table for instance?

**Comment by trouille** [comment]
For the touch table -- One reason: there's a possibility that an online audience will go through the 1-task workflow at a very high pace and we won't have any un-retired data left in the system for museum guests to keep working on. So we want to keep the effort to just museum visitors.

**Comment by srallen** [comment]
Please correct me if I'm wrong, but I think the touch table is keeping a local database of subjects and is not going to be in real time querying Panoptes for subject queues that have the retirement state serialized? 

In this case, again, if this is a must, I'd just say keep it inactive and the touch table can load the workflow by id and keep that id hard coded somewhere. In the general case, I don't think there's a good reason to limit workflows to mobile only. Does this also mean mobile browsers?

**Comment by wgranger** [comment]
Yes, the touch table will use a local database as you described. For the table, the hard-coded workflow id is only used on a workflow GET from Panoptes and a classification CREATE (as the classification's linked workflow id).

If the workflow is kept inactive, but classifications are still submitted/recorded for that workflow, will those classifications still be reflected on the stats count?

**Comment by srallen** [comment]
Which stats are you asking about? The summary stats that appear on a project home page, the more detailed stats page, or something else? The workflows shown on the detailed stats page are filtered by the workflow active param.

**Comment by camallen** [comment]
> In this case, again, if this is a must, I'd just say keep it inactive and the touch table can load the workflow by id and keep that id hard coded somewhere.

I agree with @srallen here, if you know what workflow you want to load then just load it. If you need more general filtering here then we can add another relation or configuration setting to the project resource to specifies the known mobile workflow(s).

> If the workflow is kept inactive, but classifications are still submitted/recorded for that workflow, will those classifications still be reflected on the stats count?

Classifications will not count towards the main project counters, they will contribute to the inactive workflows counter though which may be useful for tracking completeness in isolation

https://github.com/zooniverse/Panoptes/blob/1cf49c6779346578551d40216f6a4eb083f283f5/app/workers/calculate_project_completeness_worker.rb#L41

**Comment by srallen** [comment]
> If you need more general filtering here then we can add another relation or configuration setting to the project resource to specifies the known mobile workflow(s).

I don't think we should support a general case for many reasons. If a strong case can be made to support this, then this should include effort to disallow loading on mobile browsers too, not just the app, which is not easy to do. Do we stop load by user agent sniffing or by a viewport size? At which point to we cut people off?

**Comment by camallen** [comment]
> If a strong case can be made to support this, then this should include effort to disallow loading on mobile browsers too, not just the app, which is not easy to do. Do we stop load by user agent sniffing or by a viewport size? At which point to we cut people off?

Noting that a configuration directive would not be compatible with existing code and you might have to detect / sniff agents, good catch :)

A better solution would be to add a new `mobile_workflows` relation to the project resource and workflows are either in `workflows` or `mobile_workflows`. Existing client code would respect the workflows resources without change and new code would use the new `mobile_workflows` relation instead.

**Comment by eatyourgreens** [comment]
Just to add to @srallen's comment, how do we know I'm not looking at the workflow in a browser on an iPad pro, or a Surface, or some other device with a reasonably large screen. Or I have poor eyesight and am zooming the classifier on a larger screen.

If we did filter, could I get around it on desktop by increasing the browser zoom level until I get the mobile layout eg. 400px width viewport magnified to 300% on a 1200px display.

**Comment by srallen** [comment]
@camallen a new relation that only the mobile app would use would be the way to go, but I don't think a good case has been made for that yet. I think dev effort could be better used elsewhere.

We need to ask ourselves what is the goal here? Is it enabling the researchers to complete classification their data set? Or is it to demo, educate, and explain about projects in an educational setting like a museum?

If the goal is to do research, then I don't think we should limit access to workflows. If the goal is to be a museum exhibit, then we could put a workflow into a `never_retire` setting for display, leave it inactive like suggested for the touch table, or let it function as is and show the retirement message (and explain it!).

**Comment by camallen** [comment]
I do agree with you as noted before, we have a solution like you mention using active workflows for this case.

FWIW I'm outlining a solution if we want to take it forward for a general case so it's on record.

**Comment by wgranger** [comment]
> 
> Classifications will not count towards the main project counters, they will contribute to the inactive workflows counter though which may be useful for tracking completeness in isolation
> 

For the touch table's use case, classifications from the inactive workflow should satisfy the following
- Count towards the `retired_subjects_count` on a project resource. 
- Count towards the total classification count of a workflow, retrieved from the stats api similarly to the detailed stats page
- Count towards the total classification count of a project, retried from the stats api similarly to the detailed stats page

**Comment by camallen** [comment]
> Count towards the retired_subjects_count on a project resource

Why? Is the data going to be used in the same way the other GZ worfklow data will be?

> Count towards the total classification count of a workflow, retrieved from the stats api similarly to the detailed stats page

Yep - they will be in there, filter on the project or workflow id to get them.

> Count towards the total classification count of a project, retried from the stats api similarly to the detailed stats page

Stats API will have the classifications.

**Comment by srallen** [comment]
I think you could calculate that number yourself and sum it into the overall stats by using the `completeness` and `subjects_count` attributes on the workflow resource.
