### ISSUE TITLE
Increase number of 'finished' subjects in rotation when site is out of data

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes#3141]
A college professor was using Planet Four: Ridges for a classroom project. The site is currently out of data and the professor emailed me. I said that although it said 'finished' images were showing on the site. He claims that there's about 10 or so images in rotation and then they repeat. It looks about that to me as well. I see already seen in about 12 images when not logged in. Is it possible to increase the number of finished images shown before 'already seen' pops again? One of the reasons subjects are showing when the site is out of data is for classroom activities. Having a larger set of subjects for teachers to go through their students I think would be helpful

**Comment by camallen** [comment]
The number of subjects returned for a workflow selection event defaults to 10 if not set by the calling client. If the workflow is out of data then most likely the same 10 subjects will be returned every time as we short circuit the selection algorithms to avoid undue load on the API servers.

> Is it possible to increase the number of finished images shown before 'already seen' pops again?

This would be a code change from the calling client (PFE) to increase the number of subjects to cycle through when a workflow is marked as finished e.g use the page_size param to get more subjects `get /subjects?page_size=100`

> One of the reasons subjects are showing when the site is out of data is for classroom activities

I'm not sure that is the main reason, mostly it's to keep the UI system working so folks can understand how the system worked to derive the resulting data. 

Perhaps they are interested in https://classroom.zooniverse.org/ or getting your project to work in this setting?

I'm going to close this as this feature is already available via the API `page_size` param.
