### ISSUE TITLE
Enable Museum Mode from the API

### ISSUE THREAD

**Issue by chelseatroy** [zooniverse/Panoptes#3154]
We're working on giving the mobile app a "museum mode." In this mode, the app would show a single workflow, and users cannot navigate away from this workflow without quitting the app. The workflow will have a Zooniverse banner at the top and will have a dark theme enabled. This will allow museums to let guests work on a specific project. 

The app should be the same app as the mobile app, to prevent confusion in the app store with respect to which one to download. However, museum mode should _only_ be accessible to museums, to prevent citizen scientists from accidentally trapping themselves in museum mode on a project.

In order to facilitate these technical requirements, we'd like to allow only specific users to enable museum mode.

**We have talked about a few implementation options** ("we" being @chelseatroy, @zwolf, @srallen, and @amyrebecca):
1. Attach a  workflow id to a specific account, so that any login from that account automatically navigates to that workflow
1. Create a user role for museums, so a museum account can log in and automatically navigate to a designated workflow
1. Create a user role for museums, so a museum account can log in, manually navigate to a designated workflow, and select museum mode (to only be exited by quitting the app)

We'd love to hear suggestions from others, but we'd like to come to a decision on the implementation by mid-week (Wednesday, July 17) so that @chelseatroy can get started on execution, either mobile side or server side.

**Comment by zwolf** [comment]
@chelseatroy's original suggestion is to add a default-null foreign key (`museum_workflow`) to users and serialize it. If that attr isn't null on serialized user -> different mobile app behavior. I didn't love the idea of making this a User field at first but everything else (project prefs, wf config, user roles) is more complicated and/or a lot more API calls for what will be less than 10 known cases right now.

First option/instinct may be the best way to go here.

**Comment by camallen** [comment]
> This will allow museums to let guests work on a specific project.

I assume these guests will not be logged in? Or does the project want to track the incoming classifications to a certain 'known' user? Do they want to have extra classification metadata showing the classification came from museum mode? Do they also use that same user but in non-museum mode interfaces as well? Ideally during analysis they can isolate which classification came from which mode for the users.

>However, museum mode should only be accessible to museums, to prevent citizen scientists from accidentally trapping themselves in museum mode on a project.

My initial thoughts on this were why doesn't the app hard code known IDs that can activate / deactivate museum mode for different projects? I.e. the app is responsible for handling this UI presentation 'mode' trigger and it's not linked to a user account. These codes can be handed out to the relevant project owners upon request to us.

If the scope of this 'museum mode' will increase and become more complex regarding which projects / workflows get activated and how the app automatically wires up the interface then it's best to avoid the app release changes to handle them and we add the functionality API side. 

I can see a user login being the logical choice to isolate the behaviour though I think we need to think how this applies across projects, workflows etc. I.e. should one project be in museum mode vs a different project?
Can the user navigate to a different project in museum mode (i assume not)? 

The current domain model doesn't really address these requirements, it may be best to spin up a new API / add a whole new end point that links users and this 'museum mode' behaviour with the required details the app needs to wire itself to the desired museum mode behaviour.

Happy to jump on a call for this as well.

**Comment by zwolf** [comment]
Individual users not logged in, the user could represent the museum/workflow combination and the app UI would only allow classification on that workflow with no navigation possible. 

Hard coding project ids was something I also thought of but the deployment process for mobile apps (via Apple/Google) seems convoluted and out of our hands enough that I wasn't convinced. Even with an OTP code-type login, we either still hard code the project/workflow ID in the app or create a new endpoint to retrieve same from the API which would be more trouble than just adding an attr to the user, I think. I haven't heard anything that implies the scope will expand, but that's worth exploring before making a decision. The above solution is pretty simple, though.

**Comment by chelseatroy** [comment]
Hiya folks. Would like to wrap this up and begin execution today. @zwolf, how do you think we should proceed?

**Comment by camallen** [comment]
Summary of the proposed solution to the internal discussion. We will use a new 'museum' per project role for a specific user. this will allow the app UI to provide a museum mode button for any project the user has the role on. 

Con: This will allow any workflow to have museum mode on it, short term we think that is ok. 

Pro: we have all the API mechanics in place to support this and it will be small feature work to add these roles to the lab UI if needed. 

Con: Adding roles is manual by a dev team member on the api console now. short term that's ok.

Pro: App UI doesn't have a mode that folks can't access, they won't see the museum mode UI components unless their user has the relevant project roles. 

I'm closing this issue now but please re-open if needed / we want to have more discussion.

**Comment by chelseatroy** [comment]
> Summary of the proposed solution to the internal discussion. We will use a new 'museum' per project role for a specific user. this will allow the app UI to provide a museum mode button for any project the user has the role on.
> 
> Con: This will allow any workflow to have museum mode on it, short term we think that is ok.
> 
> Pro: we have all the API mechanics in place to support this and it will be small feature work to add these roles to the lab UI if needed.
> 
> Con: Adding roles is manual by a dev team member on the api console now. short term that's ok.
> 
> Pro: App UI doesn't have a mode that folks can't access, they won't see the museum mode UI components unless their user has the relevant project roles.
> 
> I'm closing this issue now but please re-open if needed / we want to have more discussion.

Thank you for writing up this summary Cam! I'm sure we'll appreciate the context when we come back to this issue in the future :)
