### ISSUE TITLE
Anonymous users only see training subjects

### ISSUE THREAD

**Issue by NicoAdams** [zooniverse/Panoptes#3166]
## Expected behavior

Found in the Clump Scout project: https://www.zooniverse.org/projects/hughdickinson/galaxy-zoo-clump-scout

Users who are not logged in should never be given any training subjects. (This currently is not the behavior.)

Users who ARE logged in should be given training subjects at the beginning, which eventually transition to real only. (This currently works as intended)

## Current behavior

Users who are not logged in see ONLY training subjects. No matter how many subjects have already been classified, users continue to be shown subjects from the training set.

## Steps to replicate

- Navigate to the Clump Scout default workflow as a user who is not logged in: https://www.zooniverse.org/projects/hughdickinson/galaxy-zoo-clump-scout/classify
- Classify an arbitrary number of subjects. Currently, they are all training subjects with feedback attached and no real subjects are provided.

## Additional information

This would be expected behavior if `training_default_chance = 1` for workflow 7450 (the active workflow). However, according to the Panoptes client, the default training chance is currently set to 0. Here is the full workflow configuration as we see it:

```
{'pan_and_zoom': True,
 'invert_subject': True,
 'multi_image_mode': 'separate',
 'training_chances': [1,
  1,
  1,
  0.3333333333333333,
  0.3333333333333333,
  0.3333333333333333,
  0.3333333333333333,
  0.3333333333333333,
  0.2,
  0.2,
  0.2,
  0.2,
  0.2,
  0.2,
  0.2,
  0.2,
  0.2,
  0.2],
 'training_set_ids': [76900],
 'multi_image_layout': 'grid2',
 'versions_backfilled': True,
 'stats_completeness_type': 'classification',
 'training_default_chance': 0,
 'multi_image_clone_markers': True,
 'hide_classification_summaries': True}
```

**Comment by camallen** [comment]
Hi @NicoAdams -  thanks for a thorough bug report, it's very useful. 

However, the panoptes API isn't responsible for selecting training images. Our custom subject selector service is, @hughdickinson has logged a similar issue on that repo https://github.com/zooniverse/designator/issues/87

I'm going to close this here, feel free to add details on the linked issue.

**Comment by NicoAdams** [comment]
Thanks Cam! Agreed - designator is the right place for this issue
