### ISSUE TITLE
Workflow data export GET request 404

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/panoptes#3169]
mentioning @rbruhn 

Regarding requests to https://panoptes.zooniverse.org/api/workflows/11705/classifications_export, but not workflow specific.

Workflow data export GET request is returning a 404 "No classifications_export exists for workflow #11705", when similar request from within [PFE Lab/Data Exports/Request New Workflow Classification Export](https://www.zooniverse.org/lab/9275/data-exports) returns expected response with 200.

Workflow data export POST request (with same headers and auth) returns expected 200 response noting export `metadata.state: "creating"`.

I believe auth is from user `biospex`, confirmed collaborator on project.

Related scripts, working historically, unchanged recently: 
- [this is the main class for calling the API](https://github.com/iDigBio/Biospex/blob/master/app/Services/Api/NfnApi.php)
- [which extends this class](https://github.com/iDigBio/Biospex/blob/master/app/Services/Requests/HttpRequest.php)
- these are the jobs that run to [create (POST)](https://github.com/iDigBio/Biospex/blob/master/app/Jobs/NfnClassificationsCsvCreateJob.php) then [check (GET)](https://github.com/iDigBio/Biospex/blob/master/app/Jobs/NfnClassificationsCsvFileJob.php) the csv files

If it makes sense I could try testing locally on Postman or similar, but I might need a little help with setup to request on production (vs staging, which I don't think requires same level of auth). Is there any existing related documentation?

Long shot, but maybe related to #3157?

**Comment by camallen** [comment]
> Long shot, but maybe related to #3157?

Doubtful, i think we need more information about the request formats / HTTP traffic to rule this out though.

> Workflow data export GET request is returning a 404 "No classifications_export exists for workflow #11705", when similar request from within PFE Lab/Data Exports/Request New Workflow Classification Export returns expected response with 200.

The API will return a 404 if the requesting user doesn't have the correct access privileges vs saying unauthorized (we chose to do this based on github API). 

https://github.com/iDigBio/Biospex/blob/5c80758265d4b03aa55bdeacefec33dae584d242/app/Services/Api/NfnApi.php#L34

Noting that the calling code uses a OAuth client to get API tokens, which user owns that OAuth application, they will be the user that is checked in authorization. 

Ideally we'd get some debugging HTTP traffic to help with this (avoiding posting the auth token) 

Another thing to try would be via the python cli tool to see if it works for the user they are expecting it to? 

https://github.com/zooniverse/panoptes-cli#generate-and-download-a-classifications-export
`panoptes workflow download-classifications --help`

**Comment by rbruhn** [comment]
If you need me to do something, let me know.

> The API will return a 404 if the requesting user doesn't have the correct access privileges vs saying unauthorized (we chose to do this based on github API).

I believe this issue started when workflows started having their own project id. Previously, all Biospex workflows had the project id 1558. Since NfN switched to each workflow being a project, Michael has had to add the Biospex user to each workflow he creates.

**Comment by camallen** [comment]
Is https://www.zooniverse.org/projects/md68135/notes-from-nature-plants-of-arkansas https://www.zooniverse.org/lab/9275 the correct project? Biospex is a collab on that project.

Can you try using the python client instructions to access the download? I believe if you set the `PANOPTES_CLIENT_ID` and `PANOPTES_CLIENT_SECRET` as environment variables that cli tool will pick this up and use it. However if not you can use the biospex username / password and the `panoptes configure` cmd to setup the cli tool to connect to the API.

**Comment by rbruhn** [comment]
There are several projects Biospex is collab on. It's not just one project this issue has effected. It also occurs on the project id 1558 workflows we use to use. For example, workflow id 8673 under project id 1558.

I will try the Python thing. I'm not a Python programmer but will see what I can do.

**Comment by camallen** [comment]
> There are several projects Biospex is collab on. It's not just one project this issue has effected. It also occurs on the project id 1558 workflows we use to use. For example, workflow id 8673 under project id 1558.

Understood, i'm trying to pick up if there is an issue with client creds oauth flow token (can't really see one but it could be) or a straight up authorization issue via the API. 

> I will try the Python thing. I'm not a Python programmer but will see what I can do.

It's a command line tool so you can use it from bash etc, hence the suggestion.

**Comment by rbruhn** [comment]
Ok... so these were the results.

First tried using the API credentials. I added the enviro variables like this...
```
export PANOPTES_CLIENT_ID=ourid
export PANOPTES_CLIENT_SECRET=oursecret
```
Not sure if that is the correct way or not... then ran
```
 panoptes project download --generate 11705  11705.csv
```
Received error:
```
Traceback (most recent call last):
  File "/home/vagrant/.local/bin/panoptes", line 11, in <module>
    sys.exit(cli())
  File "/home/vagrant/.local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/vagrant/.local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/vagrant/.local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/vagrant/.local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/vagrant/.local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/vagrant/.local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/vagrant/.local/lib/python2.7/site-packages/panoptes_cli/commands/project.py", line 186, in download
    project = Project.find(project_id)
  File "/home/vagrant/.local/lib/python2.7/site-packages/panoptes_client/project.py", line 57, in find
    return cls.where(id=id, slug=slug).next()
  File "/home/vagrant/.local/lib/python2.7/site-packages/panoptes_client/panoptes.py", line 672, in where
    return cls.paginated_results(*cls.http_get(_id, params=kwargs))
  File "/home/vagrant/.local/lib/python2.7/site-packages/panoptes_client/panoptes.py", line 623, in http_get
    **kwargs
  File "/home/vagrant/.local/lib/python2.7/site-packages/panoptes_client/panoptes.py", line 320, in get
    retry=retry,
  File "/home/vagrant/.local/lib/python2.7/site-packages/panoptes_client/panoptes.py", line 281, in json_request
    json_response['errors']
panoptes_client.panoptes.PanoptesAPIException: Could not find project with id='11705'

```

I then used panoptes configure and added the user/pass we use to log into the data-exports dashboard. I ran the same command as above:
```
 $: panoptes project download --generate 11705  11705.csv

Traceback (most recent call last):
  File "/home/vagrant/.local/bin/panoptes", line 11, in <module>
    sys.exit(cli())
  File "/home/vagrant/.local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/vagrant/.local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/vagrant/.local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/vagrant/.local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/vagrant/.local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/vagrant/.local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/vagrant/.local/lib/python2.7/site-packages/panoptes_cli/commands/project.py", line 186, in download
    project = Project.find(project_id)
  File "/home/vagrant/.local/lib/python2.7/site-packages/panoptes_client/project.py", line 57, in find
    return cls.where(id=id, slug=slug).next()
  File "/home/vagrant/.local/lib/python2.7/site-packages/panoptes_client/panoptes.py", line 672, in where
    return cls.paginated_results(*cls.http_get(_id, params=kwargs))
  File "/home/vagrant/.local/lib/python2.7/site-packages/panoptes_client/panoptes.py", line 623, in http_get
    **kwargs
  File "/home/vagrant/.local/lib/python2.7/site-packages/panoptes_client/panoptes.py", line 320, in get
    retry=retry,
  File "/home/vagrant/.local/lib/python2.7/site-packages/panoptes_client/panoptes.py", line 281, in json_request
    json_response['errors']
panoptes_client.panoptes.PanoptesAPIException: Could not find project with id='11705'

```

**Comment by camallen** [comment]
What is the OAuth application CLIENT_ID? (no need for the secret)

> I then used panoptes configure and added the user/pass we use to log into the data-exports dashboard. I ran the same command as above:

And just checking that it's the user with login `biospex`

**Comment by rbruhn** [comment]
CLIENT_ID=0fb75d7490ffe9050e12d3b75d943e544fec08cf34cc47051dd61e35863f5bd0

Yes, the user "biospex" we use to log into https://www.zooniverse.org/lab/1558/data-exports or other data-exports.

**Comment by rbruhn** [comment]
The first one worked using the "panoptes configure" option. I tried clearing the user/pass in the configure by using "space" and now I can't access the configure options. Gives me an error. How do I clear the configure so I can test the OAuth credentials?

```
Traceback (most recent call last):
  File "/home/vagrant/.local/bin/panoptes", line 11, in <module>
    sys.exit(cli())
  File "/home/vagrant/.local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/vagrant/.local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/vagrant/.local/lib/python2.7/site-packages/click/core.py", line 1063, in invoke
    Command.invoke(self, ctx)
  File "/home/vagrant/.local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/vagrant/.local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/vagrant/.local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/vagrant/.local/lib/python2.7/site-packages/panoptes_cli/scripts/panoptes.py", line 47, in cli
    admin=admin,
  File "/home/vagrant/.local/lib/python2.7/site-packages/panoptes_client/panoptes.py", line 108, in connect
    cls._local.panoptes_client = cls(*args, **kwargs)
  File "/home/vagrant/.local/lib/python2.7/site-packages/panoptes_client/panoptes.py", line 140, in __init__
    self.login()
  File "/home/vagrant/.local/lib/python2.7/site-packages/panoptes_client/panoptes.py", line 501, in login
    response.json().get('error', 'Login failed')
panoptes_client.panoptes.PanoptesAPIException: Invalid email or password.

```

**Comment by rbruhn** [comment]
The OAuth credentials seem to work as well.
So I guess the next question would be why it doesn't work when calling via Postman or our website.

**Comment by camallen** [comment]
So if the OAuth credentials are working correctly via our python client then it must be a malformed request for the authentication in your code. What does the Authorization header on your GET HTTP requests look like? Are they being set correctly with the token from the oauth client credentials flow? I think that's the place to look here. 

Postman i've had varying success using, last time i got it working and documented at https://zooniverse.github.io/Panoptes/#example-using-postman. However the interface has apparently changed though i'd be interested to know if you can get it working.

**Comment by rbruhn** [comment]
The way I use to do it with Postman and our code:
I set the auth url and POST the client_id and client_secret. I receive the access_token in the response. That is saved in the Bearer Token. 
In the GET request for classifications, I use Bearer Token in the Authorization, the content and accept headers have the appropriate api and json info.

**Comment by rbruhn** [comment]
I did a debug on the panoptes client. I set the Postman urls to the same that are used in the panoptes client. So everything works up until "GET /api/workflows/11705/classifications_export"

```
vagrant@homestead:~/.panoptes$ PANOPTES_DEBUG=true panoptes workflow download-classifications 11705 11705.csv
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.zooniverse.org:443
DEBUG:urllib3.connectionpool:https://www.zooniverse.org:443 "POST /oauth/token HTTP/1.1" 200 944
DEBUG:redo:attempt 1/5
DEBUG:urllib3.connectionpool:https://www.zooniverse.org:443 "GET /api/workflows/11705 HTTP/1.1" 200 None
DEBUG:redo:attempt 1/5
DEBUG:urllib3.connectionpool:https://www.zooniverse.org:443 "GET /api/workflows/11705/classifications_export HTTP/1.1" 200 1499
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): zooniverse-static.s3.amazonaws.com:443
---connects to amazon and downloads the file.
```

**Comment by camallen** [comment]
Hi @rbruhn so for clarity, the current state of play is that you can use the panoptes python client and get access to the files? However you cannot using postman or your custom php code?

**Comment by rbruhn** [comment]
Yes, that is correct. Remember too, my code and Postman has been working for a couple years now. It wasn't until recently that it stopped.

**Comment by camallen** [comment]
Can you export the postman scripts (removing any access tokens etc) and send to contact@zooniverse.org or post here is you are happy with them being public?

I'd really like to debug the API calls, it is strange that postman and your php code stopped working. I can't think of any API changes that could impact on these data flows but it is a simple explanation for the issue.

**Comment by rbruhn** [comment]
Not sure how to export them, but it allowed me to create a link to share
https://www.getpostman.com/collections/a2065b8582089a762c51
