### ISSUE TITLE
Removing a subject from a set deletes the subject

### ISSUE THREAD

**Issue by adammcmaster** [zooniverse/Panoptes#3181]
```
$ cat subject-ids.txt 
25395350
$ docker-compose run dev2 subject-set add-subjects 15180 -f subject-ids.txt 
$ docker-compose run dev2 subject-set remove-subjects 15180 -f subject-ids.txt 
$ docker-compose run dev2 subject-set add-subjects 15180 -f subject-ids.txt 
...
panoptes_client.panoptes.PanoptesAPIException: Couldn't find linked subjects for current user
$ docker-compose run dev2 subject ls 25395350
panoptes_client.panoptes.PanoptesAPIException: Could not find subject with id='25395350'
```

**Comment by adammcmaster** [comment]
The subject in question was also a member of another subject set the whole time.

**Comment by adammcmaster** [comment]
It should only run the cleanup worker if the subject isn't linked to any more sets. Otherwise you're deleting subjects when the user might not be expecting it.

**Comment by camallen** [comment]
hmm - what about multiple concurrent(ish) incoming requests to unlink? Perhaps better to schedule cleanup at a latter date and handle the multi set check in the cleanup worker.
