### ISSUE TITLE
Copy linked workflow resources when linking (copying) a workflow to a project

### ISSUE THREAD

**Issue by camallen** [zooniverse/panoptes#3192]
Copying (linking) a workflow to a project should also copy any existing required resources (workflow translation, tutorials & their translations) for the workflow. 

A use case is the lab app copying workflows in/between projects or the education API. They can use this end point to simplify the client code and get a full working copy of the workflow and associated resources.

**Comment by lcjohnso** [comment]
Related issue: for project copying = https://github.com/zooniverse/panoptes/issues/3126

**Comment by lcjohnso** [comment]
Related: JS code used to create new translation resource -- see here: https://github.com/zooniverse/pandora/blob/2b16ecbb1e4357bc08109f4b3c093f838b973c1c/src/ducks/resource.js#L101-L136

This code could serve as a model for implementing similar functionality for project copying use case.

**Comment by camallen** [comment]
this was mostly implemented in #3626 - we now have full workflow and translation cloning support. We don't currently copy the workflow tutorial but can revisit if needed.
