### ISSUE TITLE
Docker compose libjemalloc1

### ISSUE THREAD

**Issue by chen3e** [zooniverse/Panoptes#3197]
When cloning this repository and setting up docker, I run into an issue with `sudo docker-compose build`. The command errors out with

`E: Unable to locate package libjemalloc1
ERROR: Service 'panoptes' failed to build: The command '/bin/sh -c apt-get update && apt-get -y upgrade &&     apt-get install --no-install-recommends -y     git     curl     supervisor     libpq-dev     postgresql-client-9.4     tmpreaper     libjemalloc1     &&     apt-get clean' returned a non-zero code: 100`

After some extensive Googling I was able to finish building the container by replacing `libjemalloc1 \` in Dockerfile.dev with `libjemalloc2 \`. I'm not sure exactly what's going on beneath the hood, as I'm not familiar with this particular package, but thought I'd let you know that the repository as is might present similar docker issues for people trying to clone in the future.

**Comment by camallen** [comment]
Hi @chen3e thanks for reporting this, i believe this is an issue with using a different version of the underlying ruby docker image and the debian version that this is built on. 

https://github.com/zooniverse/Panoptes/blob/328966df94398b2932d67e30af4422a18726f07f/Dockerfile#L1
https://github.com/zooniverse/Panoptes/blob/328966df94398b2932d67e30af4422a18726f07f/Dockerfile.dev#L1

It looks like default ruby image is using debian buster (not stretch) and this debian version upgraded the jemalloc package to v2 (https://packages.debian.org/buster/libjemalloc2). 

Noting that we explicitly want to run with the v1 version of this allocator in production systems after testing and introduced in #3088. My understanding is that the v2 debian package (really jemalloc v5.1.0) doesn't provide the necessary memory savings we tested and use v1 (jemalloc 3.6.0) for.

This blog post has good info, https://www.joyfulbikeshedding.com/blog/2019-03-29-the-status-of-ruby-memory-trimming-and-how-you-can-help-with-testing.html

> Using jemalloc as Ruby's default is a bit problematic. There was a heated discussion in the Ruby bug tracker about this, but in the end no decision was made. The main issue raised is the fact that memory usage only reduces when using jemalloc 3; memory usage is still high when using jemalloc 5. Nobody knows why, so that makes the choice of defaulting to jemalloc very dodgy.

Now with all that info, i think we can approach this issue with 2 solutions:
1. Remove jemalloc from the dev template and use the default allocator in ruby
0. Lock the develoment docker file to the same as we use in production

The solution here really depends on our and your use case, ideally we'd like to keep out development and production systems in sync so we have reproducible environments for testing. However I can see value in the use of default ruby setup for development work and simplifying the docker build.

Can you please let me know your use case? Specifically are you evaluating / playing around with this repo or are you using the development dockerfile for deployment?

**Comment by chen3e** [comment]
I was simply curious about the repository- there's no need for you to go out of your way to change your development container just to accommodate me. I just wanted to bring this to your attention, in case there was anything you felt you needed to do. Cheers!

**Comment by camallen** [comment]
Thanks for the report @chen3e, it's greatly appreciated
