### ISSUE TITLE
New media adaptor for Azure

### ISSUE THREAD

**Issue by zwolf** [zooniverse/panoptes#3201]
The migration to Azure requires a new media adaptor to upload/serve files from Azure instead of AWS. This will touch primarily subject uploading and serving presigned URLs for private resources and exports.

**Comment by camallen** [comment]
Ideally we would use rails ActiveStorage to handle this for us. We chose to do this in Tove to avoid writing custom adapters, https://github.com/zooniverse/tove/blob/b0488ff77993a8013c3295132619e93c5c0b3537/README.md#data-exports unser section `Talking with Azure Blob Storage`

https://github.com/zooniverse/tove/blob/2a010321e0f9f4e8529778b3e23f8d24851d787f/app/models/transcription.rb#L22

However this would require us to get onto rails 5 by finishing work in #3128 - this is needed longer term as we're on unsupported version 4.2 now, https://guides.rubyonrails.org/maintenance_policy.html#security-issues
