### ISSUE TITLE
Port to Kubernetes

### ISSUE THREAD

**Issue by zwolf** [zooniverse/panoptes#3202]
Panoptes should run in our Kubernetes cluster. This is no small issue, but I'm keeping it simple here to have something to keep track of the requirement over the course of the migration. This issue can and should be expanded with details on what this will require specifically.

**Comment by zwolf** [comment]
Progress: https://github.com/zooniverse/Panoptes/pull/3287

**Comment by adammcmaster** [comment]
I'm closing this in favour of tracking progress with the cards in the project in the Ops repo.
