### ISSUE TITLE
Clean up pending specs

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#322]
There are still pending specs to do with Omniauth behaviour when invalid / non-unique user recrods are created.

![pending_specs](https://cloud.githubusercontent.com/assets/295329/5265963/83fe697a-7a3e-11e4-8ed6-b33664791c4a.jpg)

**Comment by edpaget** [comment]
@brian-c are we still planning to have the Facebook/Google login working by launch?

**Comment by brian-c** [comment]
Will check with @chrislintott to see if this is critical, but I assume it's not worth complicating what's already working.

**Comment by chrislintott** [comment]
Would be nice, but not critical path.

**Comment by edpaget** [comment]
Cool moving to the future

**Comment by marten** [comment]
Wow, have we really had those pending specs for a year now? I'm moving this to the next sprint, but I'm fine if we just decide to toss out the specs instead of doing the work.

**Comment by camallen** [comment]
pretty sure we have similar functionality prompted in the UI via [here](https://github.com/zooniverse/Panoptes/blob/8ca5e8b606c7b2179c9f20de2a25998c40435f63/app/serializers/user_serializer.rb#L34), so it'd be nice to finally wire this up and get it done.

**Comment by zwolf** [comment]
This is now implemented.
