### ISSUE TITLE
Allow subjects to be unretired

### ISSUE THREAD

**Issue by lcjohnso** [zooniverse/panoptes#3226]
From time to time it is desirable to unretire subjects from a workflow.  Typically, this is required when a retirement rule in Caesar is misconfigured, or when a project team wishes to revise a workflow's retirement limit.

Unretirement of a subject on a workflow consists of setting `retired_at` and `retirement_reason` back to `NULL` on the `subject_workflow_counts` table.  Currently this is accomplished via the Rails console or via direct SQL commands (yikes!).  It would be helpful to add an API endpoint to execute these unretirements given a workflow ID and either a subject ID or a subject set ID.

See [this Slack thread](https://zooniverse.slack.com/archives/C0DTP3L2K/p1576252503007800?thread_ts=1576190314.179700&cid=C0DTP3L2K) for more context.

**Comment by camallen** [comment]
I'd be up for pairing on this one - @nciemniak this might be a good first issue for you on the API. Thoughts?

**Comment by lcjohnso** [comment]
@camallen @adammcmaster @nciemniak -- After discussion with @zwolf during Ops Party on 18 Dec 2019, here are some notes and ideas.

Proposed solution would be to provide unretire functionality via the Python Client.  The goal here is to provide a solution that does not require Rails console access (dangerous level of access, even for internal team) but does not require front-end UI tool building (e.g., via Project Builder interface or admin interface).  Client fulfills both of these criteria.  We also discussed whether feature should be admin-only or open, and concluded we might as well allow owners access to the function too.

For this solution, back end work on Panoptes is still required to open up an API update route to subject_workflow_counts (table name) / subject_workflow_status (model name) entries.

Relevant Links:
Route = https://github.com/zooniverse/Panoptes/blob/88fc3c291a0eaeefcefb7dc7dcab8d1aa680b352/config/routes.rb#L141

Model = https://github.com/zooniverse/Panoptes/blob/master/app/models/subject_workflow_status.rb

If this solution is acceptable, I'll issue it up on the [Python Client repo](https://github.com/zooniverse/panoptes-python-client).

**Comment by adammcmaster** [comment]
That sounds fine to me. It should be straightforward to add that to the Client once it's in the API.

[Retiring subjects is already supported](https://github.com/zooniverse/panoptes-python-client/blob/master/panoptes_client/workflow.py#L55). My suggestion would be to support a `DELETE` request to the `retired_subjects` endpoint

**Comment by camallen** [comment]
I don't think switching to a HTTP delete verb will work well as DELETE requests may not support a payload body, https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/DELETE and https://tools.ietf.org/html/rfc7231#section-4.3.5
```
A payload within a DELETE request message has no defined semantics; 
sending a payload body on a DELETE request might cause some existing implementations to reject the request.
```
Also as we do not have a `WorkflowRetiredSubject` resource that we reference directly via an ID then we would have to pass the relevant subject ids via URL path (singluar retirement) or using query params (supports batches with list e.g. `?subject_ids=1,2,3,4`)

Taking the above into consideration it may be simpler and more intuitive to add a similar POST request to `unretire` a subject for a known workflow, e.g. 
` POST /api/workflows/1/unretire_subject` with a payload body of `subject_ids={1,2,3,4}`

**Comment by camallen** [comment]
Possibly use the code in https://gist.github.com/camallen/44972b25a3359b649f5338d23fb203d2 as a template for this work

**Comment by rogerhutchings** [comment]
This would be super handy for 1715 Labs stuff too (cc @tingard)

**Comment by tingard** [comment]
(I would like to 👍 this)

**Comment by lcjohnso** [comment]
One specific part of this feature request: in addition to passing a `subject_ids` payload, I'd also like to support passing `subject_set_ids` too.  As seen in Cam's script code linked above, most of the time we are looking to unretire all or some subject sets linked to a workflow.  A `subject_set`-based option would be **very** helpful!
