### ISSUE TITLE
workflow version entry in project builder data export is always 1

### ISSUE THREAD

**Issue by simensta** [zooniverse/Panoptes#3246]
In a workflow export from the Data Export tab in the Project Builder, the workflow version entry is always 1. I noticed this when I tried to merge a workflow export with a classification export on the workflow version fields.

To replicate, see project with ID 1506.

workflow_id | display_name | version | first_task |  tasks |minor_version
-- | -- | -- | -- | -- | --
2345 | Vascular Plant Transcription 2.0 | 1 | T1 | {"T1":{"help":"T1... | 1
2345 | Vascular Plant Transcription 2.0 | 1 | T1 | {"T1":{"help":"T1... | 2

**Comment by camallen** [comment]
I'm seeing workflow versions up to 1- 47 for workflow_id = 2345

workflow_id | display_name | version
-- | -- | --
2345 | Vascular Plant Transcription 2.0 | 47
2345 | Vascular Plant Transcription 2.0 | 47

**Comment by camallen** [comment]
closing for now - please reopen if you need.
