### ISSUE TITLE
How does sidekiq start in K8s env?

### ISSUE THREAD

**Issue by camallen** [zooniverse/panoptes#3314]
It appears that docker will use the default supervisor config in k8s, hence we will only have the puma app running, https://github.com/zooniverse/Panoptes/blob/5cbaf621f99799880112e7304e9b4016ff78343d/supervisord.conf

I suggest that we reconfigure how the app boots and is deployed in k8s
1. remove the dependency on supervisor
0. start the puma app by default via dockerfile CMD syntax
0. Add a deployment config for sidekiq, https://github.com/zooniverse/caesar/blob/e86609e8a7b1111f54b6283875f3cd49be8de8f7/kubernetes/deployment-staging.tmpl#L194
0. modify how docker-compose starts the dev env, add a sidekiq container instead of booting multiple processes in one container.

**Comment by camallen** [comment]
> I'd prefer not to reconfigure it to remove sidekiq at this stage.

I'm not sure what this means, sidekiq isn't being removed via the described issue.

As it stands, this deploy will only run the web app, nothing else and the staging system will be in a broken state.

**Comment by camallen** [comment]
and to clarify - that's fine that we focus on the migration, however we need to migrate a working system to test cloud cut over, so it'll have to happen at some point.

**Comment by adammcmaster** [comment]
Sorry that should have said supervisor, not sidekiq. I'd prefer to remove supervisor in a separate change after the migration.

**Comment by camallen** [comment]
> Sorry that should have said supervisor, not sidekiq. I'd prefer to remove supervisor in a separate change after the migration.

Yep - ok, i'll defer to y'all on timing.
