### ISSUE TITLE
Add user field for NASA email communication

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/panoptes#3401]
Mentioning @lcjohnso. Related to https://github.com/zooniverse/Panoptes-Front-End/pull/5747.

Add user field for NASA email communication preference, similar to `beta_email_communication`.
Maybe `nasa_email_communication`?

For NASA email list.

**Comment by zwolf** [comment]
Is the default false?

**Comment by lcjohnso** [comment]
@zwolf Yes, default is `false` -- this will be an opt-in email list.

**Comment by zwolf** [comment]
Do you want the option to subscribe to these to show up on the user registration page? What should the text be next to the box?

I assume that this should be included wherever `beta_email_communication` is, right?

**Comment by lcjohnso** [comment]
@mcbouslog implemented the tick box for signup via email settings page here: https://github.com/zooniverse/Panoptes-Front-End/pull/5747

We do not need to include option to sign-up at time of registration -- only allowing sign-up via email settings page is OK.

**Comment by zwolf** [comment]
Resolved by https://github.com/zooniverse/panoptes/pull/3421
