### ISSUE TITLE
Add completeness counts to subject sets

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/panoptes#3450]
For Engaging Crowds, we'd like to display subject set completeness when giving volunteers a choice of subject sets to work on for a particular workflow. It would be useful to have completeness, or number of completed subjects, recorded per subject set, if that's possible.

Here's a design for the project home page, showing how completeness will be listed for each subject set.
![Screenshot of the project home page, showing a list of workflow subject sets with a percentage completeness for each one.](https://user-images.githubusercontent.com/59547/98942925-a8eb4100-24e6-11eb-91f0-3a3af970491e.png)

**Comment by eatyourgreens** [comment]
One possible complication here: a subject set can be linked to multiple workflows, and will have different completeness counts for each workflow that uses it.

**Comment by eatyourgreens** [comment]
There's also conversation on https://github.com/zooniverse/front-end-monorepo/issues/1884, around how we'll want to list individual subjects from a set and show workflow status for each one, for the current user.

**Comment by camallen** [comment]
Linking https://github.com/zooniverse/front-end-monorepo/issues/1884#issuecomment-726006195

One naive approach could be to do this when doing the project completion counts on the hourly schedule? https://github.com/zooniverse/panoptes/blob/e4dcb068ad39bddd960423ef6e794f9917e940ca/app/workers/calculate_completeness_worker.rb

I'm not sure what kind of load the above would add to the system, it might be more prudent to modify the set counts on each retirement event? https://github.com/zooniverse/panoptes/blob/e4dcb068ad39bddd960423ef6e794f9917e940ca/app/workers/retirement_worker.rb#L12

Once those counts are on the SubjectSet resource we can serialize them via the API on the subject set resource.
