### ISSUE TITLE
Unexpected subject selection behaviour from grouped workflows with an invalid subject set

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/panoptes#3477]
While testing selection by subject set, in the classifier, I edited the page URL to pass an invalid subject set for the current workflow. The following API request was made, as expected. Here, workflow 15652 is a test project that Shaun set up but subject set 857 is an AnnoTate subject set.
https://www.zooniverse.org/api/subjects/queued?workflow_id=15652&subject_set_id=857&http_cache=true

I expected that the response would either be an empty array (there are no subjects for this workflow in that subject set) or an error (that subject set is not linked to this workflow.) Instead, I got back subjects from subject sets that are linked to workflow 15652.

Does subject selection always fall back to random selection from linked sets, even when a subject set is specified?

I'm going to label this as a bug because it could produce unwanted classifications in a transcription workflow.

**Comment by eatyourgreens** [comment]
See https://github.com/zooniverse/designator/issues/91

**Comment by camallen** [comment]
This is related to designator behaviour. 

>Does subject selection always fall back to random selection from linked sets, even when a subject set is specified?

Grouped selection in panoptes will filter to the set id in question and return an empty array if that set isn't linked to the workflow. 

https://github.com/zooniverse/panoptes/blob/5f7b8d24e5b5a1cccad9dbf32510c50ce6ef1bd0/lib/subjects/postgresql_selection.rb#L24-L32
