### ISSUE TITLE
subjects with incorrect classification numbers (issue with downloads?)

### ISSUE THREAD

**Issue by denslowm** [zooniverse/panoptes#3500]
We (Notes from Nature) think we have an issue with subjects "retiring" before they have met the subject retirement that has been specified. There also may be an issue with the subject downloads being generated correctly.

Take the following example.
https://www.zooniverse.org/lab/11689/workflows/15918
Retirement is set to 3

When I download the workflow classification export I see several subjects with < 3 classifications (listed below).

48701946 48702258 48703234 48703669 48701483 48701614 48701620 48701694 48701758 48701940 48701953 48702002 48702186 48702264 48702282 48702662 48702711 48702776 48702820 48702864
48702969 48702993 48703082 48703117 48703149 48703318 48703368 48703371 48703380 48703518 48703577 48703824 48703865 48703876 

Update:
After some back and forth this Jim, we discovered a few things. The workflow.classification_count is 6137. The download referenced above was from a week ago. I tried a new download today and it now has 6145 classifications, so regardless it seems like there is an issue with the download generation in the system. I estimate that this workflow "completed" and was auto-removed from the Project landing page around September 14th.

**Comment by camallen** [comment]
Looking at your export i see the following for some randomly sampled subject ids. 

|subject id| classification ids|
| :-: | :-: |
| 48701946 | [273292316, 273614598, 273620343] |
| 48702282 | [ 269567829, 273559615, 273604575 ] |
| 48703518 | [ 269014987, 273551452, 273604869 ] |
| 48703876 | [ 269588513, 273290668, 273602930, 275752797, 277836460 ]
| 48702711 | [268611079. 273509154, 273591518 ]

These look ok to me but i haven't inspected them all. Perhaps the export you had was out of date?

> I tried a new download today and it now has 6145 classifications, so regardless it seems like there is an issue with the download generation in the system. 

What kind of issue is there? It seems to be working ok but you had were referencing an old export so the data wasn't the most up to date.

You can inspect the most recent export and look for the `subject_data` column. the `retired_at` datetime attribute is included in there for each subject / classification.
E.g. for subject id 48702711 (so on each corresponding classification id row entry)
``` JSON
"48702711": {
    "retired": {
      "id": 68437990,
      "workflow_id": 15918,
      "classifications_count": 3,
      "created_at": "2020-08-04T20:19:03.693Z",
      "updated_at": "2020-09-14T09:12:20.476Z",
      "retired_at": "2020-09-14T09:12:20.444Z",
      "subject_id": 48702711,
      "retirement_reason": "classification_count"
    },
```

> I estimate that this workflow "completed" and was auto-removed from the Project landing page around September 14th.

The retired_at dates look like that's when data was being retired.

I'm going to close for now as i believe this is not an issue with the data. Feel free to leave follow up comments and I'll reopen if needed.

**Comment by denslowm** [comment]
This was just one example, so perhaps I have to dig up another. If we assume the workflow completed on 2020-09-14 then I'm unclear why a download from 2020-10-26 would have different classifications numbers from a download from 2020-11-02. There are also classifications being recorded as late as 2020-10-28 (and several post 2020-09-14). I know it is possible for users to access the workflow after it gets removed from the landing page, but this seems like way more than expected. 

Either the download from 2020-10-26 was generated before 2020-09-14 or there is some kind of lag in the system. I don't know a way to check when the 2020-10-26 was actually generated and I realize you likely need a reproducible example, so I'd like to keep this open while I go dig through another workflow.

**Comment by denslowm** [comment]
Here is another example. Workflow #16247

The workflow "completed" around 2020-10-05. I downloaded the data on 2020-10-24 and subject 49323153 has <3 classifications. It shows as retired after 2. The workflow should have a retirement of 3 and it seems improbable that someone would have changed that long enough to affect 1 subject in the whole set. 

I'm getting myself a little confused with a few different issues (e.g., data export download dates), but the primary issue here that we are trying to solve is that we are seeing workflows "complete" before subjects get the correct number of classifications.

**Comment by camallen** [comment]
> The workflow "completed" around 2020-10-05. I downloaded the data on 2020-10-24 and subject 49323153 has <3 classifications. It shows as retired after 2. The workflow should have a retirement of 3 

Indeed I can see that this subject has retired at 2 classifications. 

It's possible there is a bug in the retirement code** though that code has been quite stable and we haven't seen an early retirement like this in other projects. I would assume that this bug would have shown up on other projects before now as we often have folks questioning how retirement works (I've done a **lot** of data digging on this topic across our platform). That said I won't rule this out.

I can't see any Caesar configuration for this workflow which could handle more complex retirement. I assume it never had any?

> and it seems improbable that someone would have changed that long enough to affect 1 subject in the whole set.

It certainly could have been a very quick change and correct via the lab which caused this error. I wouldn't rule this out. Sadly we don't track the retirement config changes on the workflow so I can't see if this was a user generated change from 3 to 2 and back to 3 via the lab.

I filtered the classification export `subject_data` column on `"retired_at":"2020-09-15T` to see what else retired (and with what values) around the problematic ones. It looks like this early retirement has only impacted the subject `49323153`, which may support a lab user generated change and quick fix. I'm leaning towards this being the underlying issue tbh.

> I'm getting myself a little confused with a few different issues (e.g., data export download dates)

Please do generate a new export before doing any more data investigations though, it's important to have up to date exports and these are only (re)generated on request, not automatically. Thus don't assume the dowload date is the same as the generation date. 

> but the primary issue here that we are trying to solve is that we are seeing workflows "complete" before subjects get the correct number of classifications.

Understood, If you can provide more data that supports the early retirement bug, I'll investigate further and re-open this issue. 

** retirement code links
+ https://github.com/zooniverse/panoptes/blob/3fe89b90ae005460c3293456ce33b7b1a90c9878/app/workers/retirement_worker.rb#L9-L10
https://github.com/zooniverse/panoptes/blob/3fe89b90ae005460c3293456ce33b7b1a90c9878/app/models/subject_workflow_status.rb#L31-L43
+ https://github.com/zooniverse/panoptes/blob/3fe89b90ae005460c3293456ce33b7b1a90c9878/lib/retirement_schemes/classification_count.rb#L11-L12

**Comment by nciemniak** [comment]
Ive taken a look at subject id `49323153`, you're right that it has been set to retired but only has a classification count of 2:
```
  "retired":{
  "id":69791539,
  "created_at":"2020-09-14T16:16:35.461Z",
  "retired_at":"2020-09-15T18:38:02.492Z",
  "subject_id":49323153,
  "updated_at":"2020-09-15T18:38:02.546Z",
  "workflow_id":16247,
  "retirement_reason":"classification_count",
  "classifications_count":2
}
``` 
For reference, the API call to get this information is https://panoptes.zooniverse.org/api/subjects/49323153
@camallen any thoughts on what would have caused this?

**Comment by lcjohnso** [comment]
There are now a total of 5 subjects across 3 workflows that show this same behavior.  It is very rare (5 out of 32k) but appears to have occurred a few times.  See subjects: 49323153, 50494904, 50495177, 50495430, 50715191
