### ISSUE TITLE
Data Model Description link in Readme goes to empty page

### ISSUE THREAD

**Issue by parejkoj** [zooniverse/panoptes#3504]
The README.md for the project says to check out the "Data Model Description", with a link to this page on the wiki: https://github.com/zooniverse/Panoptes/wiki/DataModel but that pages does not exist on the wiki. It looks like that was added to the readme ~7 years ago: did the wiki get revamped since then and was that page deleted?

**Comment by camallen** [comment]
@parejkoj thanks for bringing this to our attention those readme link are out of date, i've removed them now.
