### ISSUE TITLE
Classifications not in data export

### ISSUE THREAD

**Issue by denslowm** [zooniverse/panoptes#3516]
We have a workflow (https://www.zooniverse.org/lab/12335/workflows/16579) that completed on 2020-11-22.
The workflow classification export appears to only contains data up until 2020-10-27. The stats show 3,532 / 3,532 subjects retired and the workflow was auto-removed from the project landing page. 

I don't understand why there is only classification data up until 2020-10-27. As an additional test, I classified and submitted a subject (marked as "FINISHED!") in the workflow myself on 2020-11-25 and generated a new export 24 hours later. My classification isn't recorded.

Can someone help me understand what might be going on?

**Comment by denslowm** [comment]
An update on this.  I regenerated a download today and all the data seems to now be there including my test classification. 

I believe this confirms that there is a significant lag in data getting written to the outputs, but I am concerned about what might be causing it. Could it be something related to the workflow or just an issue in the system?

**Comment by camallen** [comment]
We've had some issues with our export systems running out of disk space recently which would have impacted the generated data. 

I've manually fixed this issue and have this programmatic fix in to ensure we don't run into this in the future, https://github.com/zooniverse/panoptes/pull/3519/files

I'm glad you've got your data out.
