### ISSUE TITLE
SubjectGroup selection bug - 422 error, "PG::UniqueViolation" on "key" values

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/panoptes#3550]
## API bug

When attempting to GET data from `/api/subjects/grouped`, for staging Workflow 3412 and Subject Set 4827, I'd receive a **422 Error** with the error message: `PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_subject_groups_on_key"`

Related: #3530 - the initial addition of the SubjectGroup API end points

### Testing

Setup
- Project: [Survos Survey 2020 (staging)](https://master.pfe-preview.zooniverse.org/lab/1900)
- Workflow: [3412](https://master.pfe-preview.zooniverse.org/lab/1900/workflows/3412) - workflow.configuration set up to use the SubjectGroupViewer and the Survos API. Whitelisted to use the Survos API.
- Subject Set: Subject Set 4827, which has 300 Subjects, each having 1 image. _(This is the Subject Set I'm using for "actual" Survos Group Subject data. My assumption here is that how the Survos project will organise their data)_

Action:
- pinged https://panoptes-staging.zooniverse.org/api/subjects/grouped?workflow_id=3412&num_rows=5&num_columns=5 via Postman

Expected:
- A pseudo-Subject that consists of 25 images. Resource looks the same as any other Subject, as the Front End is concerned.

Result:
- a 422 error. Please see https://zooniverse.slack.com/archives/G010RKVH28Z/p1610382071032700 for the full error message, since I'm not sure it's good to post those deets out here.

### Status

Medium priority bug, since this is required for the Survos project to work.

Tagging @camallen

**Comment by camallen** [comment]
This was fixed in #3554 - closing for now. Please re-open / comment and i'll re-open this issue.

**Comment by shaunanoordin** [comment]
Just wanted to confirm that 3554 fixes this issue, as tested on staging 👍
