### ISSUE TITLE
RFC: Websockets rather than polling for workflow assignment

### ISSUE THREAD

**Issue by srallen** [zooniverse/panoptes#3591]
Right now, PFE polls Panoptes every N classifications to GET the user project preferences and check for an assigned workflow from the project. I'd like to explore whether we can use websockets instead for this. This is a generic issue placeholder for this idea, so feel free to comment on feasibility and/or move it to a more appropriate repo (maybe Sugar?) if applicable.

**Comment by camallen** [comment]
All the websocket infrastructure for message passing to clients are already in place via the Sugar notifications system and aligned message handling code in PFE (via sugar-client and [this example PR](https://github.com/zooniverse/Panoptes-Front-End/pull/4744/files)). We've successfully used this websocket paradigm for sending intervention messages to display to the user in PFE.

I think a general system to support live in classifiying workflow assigment would work like this:
1. user is classifying on a project submitting classifications from the UI
2. UI system in PFE (FEM?) has the sugar client installed and configured to listen to the user channel events incoming from notifications (sugar) system.
3. internal system** decides to send the user a message and sends the relevant message to the notifications (sugar) system
4. sugar system correctly sends the message to the client
5. PFE / FEM client code handles in the incoming message and modifies the UI to implement the workflow assignment UX

I don't think any work is needed to support this as all the backend service components are in play. Some additions to Caesar may be needed if that's the 'decision' system that will would use for user workflow assignment metric evaluations.

We may need a way to track if a user want's to opt out of messaging broadly vs on a project (UserProjectPreference resource) but that's to be decided as the implementation firms up.

Also work on the caesar system may be needed to add these message actions and user metrics (using aggregation for caesar service) once it's decided that will be the 'decision' system in this data pipeline.

** Assuming for the moment we use caesar to derive some user metrics on when to assign a user to a different workflow. Once that threshold is reached a message is sent from say caesar (using rule actions) to the notifications system to notify the relevant user. For similar message proxy system see https://github.com/zooniverse/interventions-gateway#post-messages

**Comment by eatyourgreens** [comment]
Here’s the PFE notifications client, if it’s useful. It’s a store that listens for intervention messages, then fires off actions based on `message.event_type`. https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/redux/ducks/interventions.js

**Comment by eatyourgreens** [comment]
There’s one other piece that I forgot. When the store initialises, the sugar client starts listening for messages and fires off an action in the handler. I think that’s all that’s needed to get async messaging working. https://github.com/zooniverse/Panoptes-Front-End/blob/45399f3267f45fa1d67d5bcd162b4050ed11e5ac/app/redux/init-store.js

**Comment by srallen** [comment]
Thanks. I didn't need an explanation on how websockets work, just a confirmation of feasibility and whether or not work needed to be done prior to potential implementation.
