### ISSUE TITLE
Subjects endpoint returns duplicate subjects and misses others

### ISSUE THREAD

**Issue by tingard** [zooniverse/panoptes#3652]
Using the `/subjects` endpoint with the `subject_set_id` query param returns duplicate subjects, and doesn't return all subjects linked to the subject set.

## Example:
When trying to list subjects on set 97507 - I could try

```python
# Authenticate
client = panoptes_client.Panoptes.client()
# Setup an initial endpoint URL
next_url = f'/subjects?page_size=200&subject_set_id=97507 &sort=id'
subjects = []
while True:
    response, _ = client.json_request('GET', next_url)
    subjects.extend(response['subjects'])
    # Try and get the URL for the next page, exiting if none was returned
    next_url = response['meta']['subjects'].get('next_href')
    if not next_url:
        break
```

This returns 3,000 items (the number that *should* be present in the subject set), but only 2169 unique subjects.

Using `set_member_subjects` or querying by workflow ID seems to behave as expected.

Let me know if I can provide any more information!

**Comment by lcjohnso** [comment]
Closed by https://github.com/zooniverse/panoptes/pull/4359 -- we added ID sort by default for subjects in order to provide better consistency over paginated results.
