### ISSUE TITLE
where-is-spoony question

### ISSUE THREAD

**Issue by coderbm1** [zooniverse/panoptes#3808]
Go to
https://www.zooniverse.org/projects/hugo-ferreira/where-is-spoony/classify

Click on 'NEED SOME HELP...'

Screenshot
![obraz](https://user-images.githubusercontent.com/60202305/158815718-d26f366f-69b8-416c-aba9-cc85974ebe54.png)

How can I know is it spoonbill?

- Clicked button - more info needed

**Comment by zwolf** [comment]
Project-specific questions should be asked on the project's Talk page: https://www.zooniverse.org/projects/hugo-ferreira/where-is-spoony/talk/4214. If you're experiencing errors or there's a problem with the website, you can email contact@zooniverse.org for support.
