### ISSUE TITLE
science-scribbler-key2cat tutorial

### ISSUE THREAD

**Issue by coderbm1** [zooniverse/panoptes#3809]
It would be great to see a numbers of pages (not only clicks Next/Previous)

Go to https://www.zooniverse.org/projects/msbrhonclif/science-scribbler-key2cat/classify

Click to Tutorial and clicks Next, and so on so on

Screenshot
![obraz](https://user-images.githubusercontent.com/60202305/158818260-fdff3b9a-a6d4-43a2-979b-63199be60264.png)

**Comment by zwolf** [comment]
This appears to be a visual bug with the tutorial, either with our front end or the tutorial itself. You can raise this issue in the project's Talk page (https://www.zooniverse.org/projects/msbrhonclif/science-scribbler-key2cat/talk/4835) and the researchers and Zooniverse team will take a look.

You can also email contact@zooniverse.org directly for support. Thanks!
