### ISSUE TITLE
What's a User?

### ISSUE THREAD

**Issue by brian-c** [zooniverse/Panoptes#40]
Currently a user signs up with:

- Username
- Password
- Real name (for recognition in papers, etc.)
- "Send me beta announcements"

In #38 @edpaget suggested a separate key for URL. That gives us three "name" properties. Can we use the login for the URL, encoding what needs encoding when calling the API? URLs in the browser should render okay: [#/ß®ï@ñ-¢](#/ß®ï@ñ-¢).

**Comment by edpaget** [comment]
@parrish brought this up at Standup today. What kind of user logins will we allow? I'm for downcased and no whitespace, but otherwise anything goes. When a migrated user signs on, we just prompt them to change their login name, while leaving their display name set to their old user name.

**Comment by parrish** [comment]
I think a set of restricted characters is fine too.  At least `^` and `@` since we're using those in Talk.

**Comment by chrislintott** [comment]
Have we given up on shifting to allowing Facebook/Twitter/whatever logins? We’ve had that on our desirables list for a long while now.

**Comment by edpaget** [comment]
Nope already support Facebook and google+ logins. We don't have twitter at
the moment since there isn't a way to get email from that.
