### ISSUE TITLE
Rails 6 Upgrade Task: DEPRECATION WARNING: Content-Type header without modification (json_api_render, api_response)

### ISSUE THREAD

**Issue by yuenmichelle1** [zooniverse/panoptes#4096]
- [ ] ```DEPRECATION WARNING: Rails 6.1 will return Content-Type header without modification. If you want just the MIME type, please use `#media_type` instead. (called from block (2 levels) in <module:JSONApiRender> at /rails_app/app/controllers/concerns/json_api_render.rb:11)```

- [ ] ```DEPRECATION WARNING: Rails 6.1 will return Content-Type header without modification. If you want just the MIME type, please use `#media_type` instead. (called from block (2 levels) in <top (required)> at /rails_app/spec/support/api_response.rb:3)```

**Comment by yuenmichelle1** [comment]
I could be wrong on this but I take this deprecation warning as us not being able to set content-type header anymore. which looks like what we are doing in: 
https://github.com/zooniverse/panoptes/blob/27033fb31b550ea9c5db5806019792e19638ecf7/app/controllers/concerns/json_api_render.rb#L11

@zwolf  @camallen  @lcjohnso

**Comment by camallen** [comment]
that content type should only be set for the API routes so removing it from the application controller makes sense to me. 

that api vnd content type should be set correctly on incoming requests and validated here, https://github.com/zooniverse/panoptes/blob/27033fb31b550ea9c5db5806019792e19638ecf7/app/controllers/api/api_controller.rb#L11

**Comment by yuenmichelle1** [comment]
I believe #4135 closes this issue.
