### ISSUE TITLE
Investigate Doorkeeper monkey patches after upgrading

### ISSUE THREAD

**Issue by edpaget** [zooniverse/Panoptes#411]
Updating to 1.4.1 solved the security issue, but 2.0.0 seems to take care of some of the monkey patching I'm doing, by allowing application scopes to be restricted.

**Comment by marten** [comment]
We did the update, but I haven't looked at those monkey patches. Keeping this issue open as a reminder about those.

**Comment by marten** [comment]
Can't immediately see a feature that would make the patches redundant.
