### ISSUE TITLE
Restrict SVG uploads

### ISSUE THREAD

**Issue by zwolf** [zooniverse/panoptes#4146]
Uploading `.svg` files (content type `svg+xml`) should be restricted due to possible insecurities inherent in the format. Panoptes never directly reads the files, only facilitates the uploads to blob storage, and so it cannot sanitize them directly. Uploads with this content type should therefore be restricted, either to admin users only or (more likely) to projects that have a new experimental flag allowed. 

The latter can be accomplished with a new Medium validation that, if the content_type is restricted, checks project configuration (via the linked_type/id, an additional db query) for the flag and returns invalid if it is not present. Reflecting on `ApiUser.admin?` is a little trickier since the locations are built in the model, so that would require diving into the create_params in the SubjectsController prior to the `super` call.

**Comment by eatyourgreens** [comment]
A strict Content Security Policy on `panoptes-uploads.zooniverse.org` would work too.

**Comment by lcjohnso** [comment]
Closing as CSP strategy was adopted, negating need for stronger or broader upload restrictions.

cc: @zwolf
