### ISSUE TITLE
API  always startes at Page 1 when asking for subjects

### ISSUE THREAD

**Issue by njsgastro** [zooniverse/panoptes#4230]
When Pulling subjects using subject_sets ( having 1131 pages at 40 records per page)  thru the API  the result always seems to start at page 1.  Setting the page in the call (&page=500) to indicate that it should be sending the results for page 500 and beyond doesn't seem to work.  If I read it correctly the API doc seems to indicate that page 1 is default and one can pass some other value to start where you left off in the event there was an interruption in the retrieval .  IS this possible?

Thanks
Nor

**Comment by yuenmichelle1** [comment]
Hi @njsgastro, 

Current dev team is having an issue replicating this behavior. We should note that we have made improvements to that particular API endpoint See:  https://github.com/zooniverse/panoptes/pull/4359 to ensure more consistent paginated results. 

If you are still facing issues, please let us know with steps to replicate and we can reopen this issue.

Thanks!
