### ISSUE TITLE
Front-end tryout - Edit project

### ISSUE THREAD

**Issue by rcheng3** [zooniverse/Panoptes#426]
I had created a project via the new front-end build. However, I have some questions regarding the "edit" project function. Thanks!
1) There are three boxes I can edit (general & science case). How about subjects & workflow? How can I edit them?
2) For the workflow, I changed "type": "single" to "type": "multiple" = the selection changed from radio button to check-box. How about "drawing"? can I draw boxes? when I changed to "drawing" it gave me radio button again. What other "type" are available?
3) How can I put content in the interface under "Status" and "Team"?

**Comment by edpaget** [comment]
Checkout the [zooniverse/Panoptes-Front-End](https://github.com/zooniverse/Panoptes-Front-End) for questions about the front end. I'll ping @brian-c for help on this too.

**Comment by edpaget** [comment]
We're still getting documentation together, but he's some more info about Workflow task options https://github.com/zooniverse/Panoptes/issues/401#issuecomment-66874291

**Comment by rcheng3** [comment]
Thanks, I am playing with the "type": "drawing". Thanks for the documentation.

**Comment by brian-c** [comment]
1) Editing subjects and workflows is not implemented yet. This is coming soon.

2) See Ed's link. There'll be a proper workflow-editor interface for this in the future.

3) "Status" and "team" content will be generated automatically.

**Comment by camallen** [comment]
Seems to be a Panoptes Front End issue to me.
