### ISSUE TITLE
How is masking handled?

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes#429]
We're going to have masks for the images we show volunteers (like Penguin Watch has). Each mask will be used by many images (one mask per site). How would I do this with the API?

**Comment by edpaget** [comment]
Sorry, I'm unfamiliar with the masks in Penguin Watch. Do you mind posting a screenshot of what you're talking about?

**Comment by brian-c** [comment]
She's referring to the grayed-out, non-classifyable regions on the subject images:

![screen shot 2015-01-09 at 4 08 20 pm](https://cloud.githubusercontent.com/assets/464389/5682694/d0e9978e-9819-11e4-86ac-7a57d20e1a6c.png)

I don't think this will be a 1.0 feature. Would graying out the areas on the images themselves be enough?

**Comment by mkosmala** [comment]
I think @chrislintott mentioned masking would be available in 1.0, but that was a while ago when we talked about it (Sept). I can gray out parts of our images in pre-processing, but it means the whole image won't be viewable in Talk, like the it is in Penguin Watch. (And it's a pain-in-the-neck data-management-wise, because we'll have to keep copies of all our images -- masked and unmasked -- but doable.)

**Comment by edpaget** [comment]
I think we'd handle this on the backend by putting a "masking_coordinates" field in the Subject's metadata that would be an array of points that the mask would be drawn over. It'd be up the client application to support actually drawing the mask.

**Comment by mkosmala** [comment]
I actually already have masks for all my images (as images). I just need a way to upload a mask (backend), associate the mask with a subject (backend), and display the image with the mask over it to users (frontend).

**Comment by camallen** [comment]
@mkosmala - I'm pretty sure we said that masking wouldn't be available in 1.0 of Panoptes Front End. As @edpaget mentioned, you can include the mask coords in the subject metadata hash, it'll be up to the front end client to use this information to apply a mask though. 

@brian-c , would a setup like this work in the meantime: Create 2 images (1 masked, the other without) and upload both as a single subject (much like the 3 image subject in Serengeti). The different front ends (talk/PFE) can then select which image to display.

**Comment by camallen** [comment]
Closing now as I don't this this is a general PFE use case. The API supports subject metadata should support mask coords and multi image subjects (1 mask, 1 image), etc.
