### ISSUE TITLE
Email notification for email address change should be sent to old address

### ISSUE THREAD

**Issue by lcjohnso** [zooniverse/panoptes#4351]
**Current Behavior:** From a different thread regarding account verification (https://github.com/zooniverse/Panoptes-Front-End/pull/7117#issuecomment-2178003143): upon change of email address, it appears that the _new address_ receives an email notification about the change, rather than the _old address_.

**Desired Behavior:** When a change occurs to an account's email address, a notification is sent to the user's _old email address_ and the _new email address_.

Seems like this might be a bug in the callback and/or the mailer code?

**Comment by lcjohnso** [comment]
@eatyourgreens See above -- I've issued up your observation about notification emails here on Panoptes.

**Comment by eatyourgreens** [comment]
Thanks! I wasn't sure if it was serious enough to warrant a security issue, but it seemed dodgy.

**Comment by lcjohnso** [comment]
Addressed by #4374
