### ISSUE TITLE
A copied workflow with survey task does not show images linked to survey task

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/panoptes#4364]
**Summary:** The survey task uses workflow_attached_images, but it appears the workflow copier does not duplicate those images when copying a workflow. This results in a working task & workflow (references to URLs from original workflow remain, can be accessed by the task), but the user cannot edit the images and the task editor interface does not work as expected.

## Expected behavior
- copy workflow with survey task
- go to new workflow, survey task, "Images" tab of survey task editor
- see list of images per task object `images` property

## Current behavior
- do not see list of images per task object `images` property
- because images are not linked to new workflow resource
- to volunteer new survey task loads as expected, because urls in task object `images` property exist (as long as original workflow exists?)
- but project collaborator can't see/delete images in survey task editor "Images" tab

## Steps to replicate
- https://master.pfe-preview.zooniverse.org/lab/1634/workflows/3817?env=staging

## Additional information
- Linked Talk Post: https://www.zooniverse.org/talk/18/3378978
- Possible PFE-based solution (but since API is already responsible for copying, best to make change to Panoptes): when copying a workflow, could link attached images I think [here](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/pages/lab/actions/workflow.js#L23) with `.update({ links.attached_images: [workflowData.links.attached_images.ids] })` as per [PJC link docs](https://github.com/zooniverse/panoptes-javascript-client/tree/main/lib/json-api-client#working-with-links), or something along those lines

**Comment by lcjohnso** [comment]
@mcbouslog -- Issue is transferred to Panoptes, and yes seems related to original copier PR. I'll note that we've also recently adjusted what gets duplicated or not for project copier, so perhaps @Tooyosi can take a look at this issue.
