### ISSUE TITLE
Change automatic email notifications for project status changes

### ISSUE THREAD

**Issue by lcjohnso** [zooniverse/panoptes#4366]
## Current Behavior
When project transitions to launch approved, an automatic email notification is sent to the project team and relevant Zoo emails. These emails are confusing (e.g., stating your request is being reviewed vs. the project just went live) and not necessary (plenty of notification already via current project review + launch process).

## Desired Behavior
Halt all project status email notifications **EXCEPT** the initial notification acknowledging project has applied for beta review.

**Comment by Tooyosi** [comment]
Some feedback on this issue, the `ProjectRequestEmailWorker` is triggered on the after_update callback of the Projects model, within the `send_notifications` function. Essentially what is happening here is it checks if the project has just been beta_requested or launch_requested and calls the Worker and Mailer with the appropriate request type(beta/launch) which is passed to the mail template.

I tried reproducing the usecase of mails sending when launch_approved is changed but was unable to. Checking through the code, i can't find a pointer to where the mail is triggered upon approval. 

Opened a pr to keep the emails on beta_requested alone here: https://github.com/zooniverse/panoptes/pull/4373

**Comment by lcjohnso** [comment]
On closer examination: I confirm that the unwanted notification email is in response to "launch_requested" change to true -- example: see [this notification](https://zooniverse.slack.com/archives/C08JEPZA6/p1719584884796629) in Slack. The confusion from my side was due to the fact that launch_requested & launch_approved are toggled together, leading to my imprecise assignment of what change was leading to the notification.

Conclusion: This issue is a request to **disable the email notification for launch_requested**.

**Comment by lcjohnso** [comment]
Closed by #4373
