### ISSUE TITLE
412 Precondition failed

### ISSUE THREAD

**Issue by brian-c** [zooniverse/Panoptes#437]
On pantoptes-staging:

I tried to PUT /api/workflows/44 with the header `If-Unmodified-Since: Wed, 17 Dec 2014 15:55:24 GMT`, copied directly from the `Last-Modified` header, but I got a `412 Precondition Failed` anyway.

If I add one second to the time (Wed, 17 Dec 2014 15:55:25 GMT), I get a 500 with `Content-Type: text/html; charset=utf-8`, even though I specified `Accept: application/vnd.api+json; version=1`.

**Comment by edpaget** [comment]
Closed by d971cc632cc707d922575341bdcf1a2f6e0ca536
