### ISSUE TITLE
Lost

### ISSUE THREAD

**Issue by alianos-** [zooniverse/Panoptes#438]
Hello people,
I am trying to set up Panoptes for a project in UoP (I assume some of you know that already, I just took over from Coleman).

I have managed to set up panoptes using dockers. I am now in a stage where I am trying to use JS to communicate from the UI. I believe I am doing the whole thing architecturally wrong, but that's an issue for another time. Where I got stuck is in authentication.

So the way I tackled this so far with is with ajax requests. I tried to translate from the python script so there are three calls one after the other.

1. Just call the sign-in form, extract the csrf token. That seems to work fine.
``` js
function getSignInFormPromise() {
    return $.ajax({
        type: 'GET',
        url: host + '/users/sign_in',
        contentType: 'text/html'
    });
}
```

2. Attempt to log in and aquire a session. The response from that is a JSON object
`{login:"/users/sign_in", facebook:"/users/auth/facebook", gplus: "/users/auth/gplus"}` Is that what its supposed to happen? 

``` js
function getSessionPromise(userName, password, csrfToken) {
    return $.ajax({
        type: 'GET',
        url: host + '/users/sign_in',
        headers: {accept: "application/json", "content-type": "application/json"},
        data: JSON.stringify({
            "user": {
                "login": userName,
                "password": password},
            "authenticity_token": csrfToken
        })
    });
}
```

3. Finally I am trying to get the token, but instead I face a 401 error. As for the client ID to interact with the API i got from the installation step 6. After a lot of trial and error I tried step 6 again, got a new token, restarted panoptes and used the new client id. No changes noted.

`Status:401`
`Headers:Cache-Control: no-store Pragma: no-cache Content-Type: application/json; charset=utf-8`
`{"error":"invalid_resource_owner", 
"error_description":"The provided resource owner credentials are not valid, or resource owner cannot be found"}
`

``` js
function getBearerTokenPromise(appClientID) {
    return $.ajax({
        type: 'POST',
        url: host + '/oauth/token',
        headers: {accept: "application/json", "content-type": "application/json"},
        data: JSON.stringify({
            "grant_type": "password",
            "client_id": appClientID
        })
    });
}
```

Any ideas?

**Comment by edpaget** [comment]
You're comment looks like it has disappeared. I agree we need better authentication documentation. I'll add a note to write that. In the meantime, I'll try to supply some sample JS code for authenticating against Panoptes, shortly.

**Comment by alianos-** [comment]
Hi, sorry for the disapearing comment. I somehow posted it early (I think I hit enter while outside the editor).

**Comment by edpaget** [comment]
Thanks, you can wrap code in your comments with a ``` on the line above and the line below, so it ends up looking like this

```
function() { console.log("Hello World");
```

**Comment by edpaget** [comment]
@alianos your second AJAX request should be a POST. `GET /users/sign_in` returns a a list of possible authorization endpoints.

**Comment by camallen** [comment]
Beat me to it @edpaget. Also the accept should be `Accept: application/vnd.api+json; version=1`

**Comment by edpaget** [comment]
I don't think that matters for the authorization routes right?

**Comment by camallen** [comment]
Ah my bad, that's only for the API end point and not for auth ones.

**Comment by alianos-** [comment]
Hm. I did try that in one of my brute force trials! I end up with 422 error in the second ajax
`ActionController::InvalidAuthenticityToken in SessionsController#create `

My params are
``` js
{"user":
    {"login":"zooniverse_admin",
    "password":"password"},
"authenticity_token":"nQgcqPt/yoM1koAseDxm4nMIRey/tAiciL3WytP7/Ck="}
```

That certainly is the csrf token from the previous request though. Problems with sessions or cookies maybe?

**Comment by camallen** [comment]
Yeah that sounds like the session and the CSRF token aren't aligning. I.e the session isn't being stored in the cookie or the cookie isn't persisting between requests. 

Have a look at the Panoptes Front End auth code [here](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/api/auth.coffee).

**Comment by alianos-** [comment]
So here is what I think happens. My ajax requests don't seem to contain cookies, and it turns out that cross domain calls cannot contain any cookies to protect privacy.

**Comment by camallen** [comment]
@alianos- what domains are the front end / backend running on? I assume you're running a local version of panoptes via fig/docker (perhaps on a mac?) and you're front end code is being served from web server on the same domain? If so you won't have to worry about cross domain calls.

If however you're running the backend via fig/docker and boot2docker on a VM IP and your JS code is being served via localhost then you'll have to modify your setup to run both your JS and backend code on the same domain.

**Comment by alianos-** [comment]
Both servers are running on ubuntu on different ports. Panoptes on :3000 and the UI at :8383, but it still counts as cross domain request (and btw the protocol counts as well). Still moving everything to the same server would not be a proper solution, I need to figure this out.

**Comment by alianos-** [comment]
OK lets see what we learned so far.

a) When you try to make a Cross Domain request, don't have the other domain open in another tab, it messes up your session.
b) CORS requests do not respect the "set-cookie" header. If you want them to do that, you need to set `xhrFields: withCredentials: true`, even if you are not sending any cookies and all you want to do is to read the html. As a result for this to work, all requests need that header set.

So in the end, it worked. Off to the next challenge :) Thanks for the help!

**Comment by camallen** [comment]
@alianos- great! 

I should have pointed out that in dev mode all CORS origins are allowed for all resources (not just the API), https://github.com/zooniverse/Panoptes/blob/5d27b845846c712d385b9639437ff64e4d13343b/config/environments/development.rb#L41.

If you run the panoptes server in production / staging env you'll have to modify the CORS origins and / or the resources (api vs *) that are allowed via CORS.
