### ISSUE TITLE
Guidelines for image sizing

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes#442]
I need some guidelines about the best size image to upload for Panoptes projects. I know that with Snapshot Serengeti, our images are shrunk in pre-processing to make front-end load time faster. Our leaf project images are even bigger than Snapshot Serengeti images, so I imagine I should shrink them. But by how much? I want to optimize both load time and volunteer-viewed image resolution.

**Comment by edpaget** [comment]
Pinging @chrissnyder and @brian-c as they may have a better idea about this than me. Panoptes doesn't have any limits built in.

**Comment by brian-c** [comment]
We should probably have some limit, even if it's not enforced on the back end. Is 1MB per image a reasonable max?

**Comment by chrissnyder** [comment]
If the image is being displayed "as-is" within the interface, then there's little value in uploading anything greater than ~1500px wide, as it will just be shrunk down when viewed within the interface for most people.

1MB/image seems fine as a first-pass validation. Should probably also check file type, as I can see somebody trying to upload a folder of bmp, tif, whatever.

**Comment by mkosmala** [comment]
Great, that's the guideline I was looking for: ~1500px wide. Thanks!

**Comment by mkosmala** [comment]
Sorry for closing. I guess this is now "check file type" for v0.0.6.

**Comment by camallen** [comment]
@edpaget - any thoughts about restricting the subject mime types [here]
(https://github.com/zooniverse/Panoptes/blob/5d27b845846c712d385b9639437ff64e4d13343b/app/controllers/api/v1/subjects_controller.rb#L62)?

Also it looks like a 500 will occur if client uploads an unknown mime type.

**Comment by twhyntie** [comment]
Apologies for a potentially naive comment, but I've used the **Paperclip** gem to automatically process images into different sizes for different uses server-side:

<https://github.com/thoughtbot/paperclip>

(It's also probably a second-order consideration, and would introduce more dependencies, but it's worked well for me. It also handles the file types too.)
