### ISSUE TITLE
Arbitrary image uploads

### ISSUE THREAD

**Issue by brian-c** [zooniverse/Panoptes#443]
Users and projects will need avatars, and projects will need custom background images. There are also other place we might want to allow people to upload images (answer icons, help text, etc.)

I think we should have a way to upload arbitrary images for these cases. Could we have something like a /images endpoint, where posting something like `{"images": {"src": "image/jpeg"}}` returns a signed S3 URL like we do with subjects?

**Comment by edpaget** [comment]
@camallen so what I'd like to do for this #497 and #425 is to create a new `/media` resource that accepts a POST request that looks something like this:

```json
{
  "media": {
      "types": ["video/mpg", "video/webp"],
      "links": {
         "user": "1", //or
         "user_group": "2", //or
         "project": "3", //or
         "subject": "4" //or
      }
   }
}
```

It then returns a response with a link

```json
{
  "media": [{
      "id": "1",
      "types": ["video/mpg", "video/webp"],
      "storage_locations": ["s3url for mpg", "s3url for webp"],
      "links": {
         "subject": "1"
      }
   }]
}
```

The actual contents of storage locations would vary depending on the configured storage engine. 

Finally to actually use the media resource you'd get a subject resource back:

```json
{
   "subjects": [{
      "id": "1",
      "links": {
         "location": {
              "href": "/media/1"
              "type": "media",
              "id": "1",
              "content_types": ["video/mpg", "video/webp"]
          }
       }
    }]
}
```

And the front end could then make a request `GET /media/1 Accept: video/mpg; video/webp` to retrieve the media. 

Responses would look similar for other resources that can have attached media. 

To solve #481 would could restrict the allowed media types by their linked resource. For example users can only have `image/jpeg`, `image/gif`, or `image/png` media linked to them.

**Comment by camallen** [comment]
Hey @edpaget. Yeah I like this, it's a nice abstraction around shared media and links to subjects and projects (and future use cases). 

A couple of questions: 
  
1. In #497 would we have has_one relations for for `background_image` and `avatar` that are both `media` instances and just include these relations when serialising the project? We'd probably want to restrict the numbers of media objects a project can upload too (subjects included i guess).

2. Would an external subject location be required? #491 showed a simple use case to just have the subject location URL's be specified via subjects. This could work via the `media` model as well though.

3. Do you think we should include the "subject -> media" location link when serialising subjects? That would save the extra query to `GET /media/1 Accept: ...`

4. Re #481, I was thinking more valid MIME types only. Short term we'd want to limit types that can be presented to what the front end can handle. Long term we'll probably want to free this up (to valid types) and restrict file sizes (thinking s3 costs for us).

Thoughts?

**Comment by brian-c** [comment]
I've got some minor formatting requests that'll make these easier to deal with on my end. No worries if they're not possible, it looks like this is on the right track.

As an example, here's how I'd want to set a project's avatar.

To create the image:

POST /media

```
{
  "media": {
    "src": {
      "image/jpeg": null
    },
    "links": {
      "parent": {
        "type": "projects",
        "id": "p"
      }
    }
  }
}
```

Response:

```
{
  "media": {
    "id": "m",
    "src": {
      "image/jpeg": "Signed S3 URL to PUT to"
    },
    "links": {
      "parent": {
        "type": "projects",
        "id": "p"
      }
    }
  }
}
```

(Then upload the image.)

And then to update the project's avatar:

PUT /projects/p

```
{
  "projects": {
    "links": {
      "avatar": {
        "type": "media",
        "id": "m"
      }
    }
  }
}
```

GET /projects/p?include=avatar

```
{
  "linked": {
    "media": [{
      "id": "m",
      "src": {
        "image/jpeg": "Normal S3 URL"
      },
      "links": {
        "parent": {
          "type": "projects",
          "id": "p"
        }
      }
    }]
  },

  "projects": [{
    "id": "p",
    "links": {
      "avatar": {
        "type": "media",
        "id": "m"
      }
    }
  }]
}
```

**Comment by alianos-** [comment]
Hi Both,
Just clarify. As I said on #491 we do not need links at all. We just need to retrieve the coordinates, and then there is a whole different procedures with login and a different API to retrieve the right images from a different server. We do not have a persistent URL.

Also for my other project the whole crowdsourcing part was plain text questions that required some human intelligence to be answered, so it was not involved with any images at all in the first place. (think mTurk). We would just need to store plain text.

**Comment by edpaget** [comment]
@alianos- I think what we'd do for your use case is the allow you to specify your own links in the media POST request like 

POST /media

```json
{
  "media": {
    "src": {
      "image/jpeg": "https://example.com/your_self_hosted_media.jpg"
    },
    "links": {
      "parent": {
        "type": "projects",
        "id": "p"
      }
    }
  }
}
``` 

Although I'm not sure if we would support projects with those kind of links the main Panoptes web interface due to security concerns, but that wouldn't be a problem for your use case.

**Comment by alianos-** [comment]
Well you could but to what end? I do not need links so I'd just leave the field empty.

**Comment by camallen** [comment]
It's a use case that's outside our scope. @edpaget @alianos- uses the metadata subject coords to retreive images from a WMS server. In this instance you'd just have subjects without media and use your metadata to derive your client presentation view.
