### ISSUE TITLE
Sign out response in firefox

### ISSUE THREAD

**Issue by aweiksnar** [zooniverse/Panoptes#447]
When signing out of in firefox, on the post req to /users/sign_out, I noticed that a console error of `no element found` gets thrown from the 404 page

Apparently it's more of a firefox bug (tickets [here](https://bugzilla.mozilla.org/show_bug.cgi?id=884693) and [here](https://bugzilla.mozilla.org/show_bug.cgi?id=521301)). I saw it [came up in jquery's bug tracker too](http://bugs.jquery.com/ticket/13654#comment:14), and wanted to check if it's worth changing the response over or not. It doesn't have an effect on site functionality, and I've only seen it in firefox.

**Comment by edpaget** [comment]
I think the /users/sign_out expects DELETE instead of POST, which should work correctly.

**Comment by brian-c** [comment]
We're sending a POST with `X-HTTP-Method-Override: DELETE` to work around PhantomJS not sending content with DELETE requests. If this is a Firefox bug and doesn't actually break anything I think we should ignore it.
