### ISSUE TITLE
302 Found response and a JS odyssey

### ISSUE THREAD

**Issue by alianos-** [zooniverse/Panoptes#448]
Hi, here I am again already!

So as I said I did manage to login. Three chained ajax requests, the first of which gets the sign_in page and extracts the csrf token. If I try to log in twice in a row though, the sign_in page requests fails with a 302 found error. Now as you know browsers are supposed to handle such requests trasparently so I have no control over it.

That wouldn't be much of a problem, but aparently the request to sign_out also needs a csrf token which I need to get from the sign_in page (?!). Since JS is not allowed access to the session variable, I don't have much to go with. 

Any ideas?

Thanks

**Comment by edpaget** [comment]
@alianos- Are you intending to run Panoptes standalone for this project? Or do you just want a custom front-end to our future deployment of Panoptes? If it's the later we, allow OAuth2 authorization for third-party applications that is significantly easier to implement than the username/password authorization. 

I'll try to swing around an answer your actual question in a bit. I'm just curious.

**Comment by alianos-** [comment]
I am not really sure of what options I have! What do you mean "your deployment of Panoptes"? You will run your own server where people can host their own projects? 

I believe the approach taken here (i.e. for this project), is to set up our own server. One of the partners has written the public UI which I am now trying to connect to Panoptes. At the same time we are working on a management UI (to add projects, workflows etc).

**Comment by edpaget** [comment]
Sorry that wasn't super clear. 

When Panoptes is finished enough to deploy and make publically available, we will provide a way for third-parts to integrate their websites with Panoptes, so users can log into your project with their Zooniverse credentials and your site can retrieve subjects and send classifications on their behalf.

**Comment by alianos-** [comment]
That sounds awesome mate. When you say "intergrate their websites with Panoptes" I assume you mean with a central server running somewhere (which you also call Panoptes), and not the platform itself, right? Sounds like a pro idea.

By the way you just sparked a question I had for some time now. When we finish with UI/Panoptes connection, we plan to launch the site. Would you say that Panoptes is ready for that?

**Comment by edpaget** [comment]
No at the moment it's not ready to go. It should be ready by the end of February.

By "integrate", I mean we'd provide a way for users to log into your site and for you to store your subjects and classifications. Basically your site would have a "Login with Zooniverse" button that would direct your users to page where they can authorize your application (much like when you use "Login with Facebook" or "Login with Twitter"), and your application will get a token you can use to make requests as that user against our server's API. 

That authorization method is much easier to implement than the one that requires a username and password since it's the one specifically designed for non-Zooniverse projects.

**Comment by edpaget** [comment]
As for your original question. I think you just need to get a CSRF token to do the sign_out? I think you can use the one that's included on the main page for the site. If you request "/" there should be a meta tag with the CSRF token on the page.

**Comment by alianos-** [comment]
Oh. Well yes that makes much more sense. To be honest I was counting for that since there is OAuth in the package but I had no info to go on with. Typically users are allowed to do both however, register locally, or log in with another account. So I think getting it to work is not a waste of time.

As for you answer I though of that and I will try it asap, but it doesn't actually solve the problem, since then I will not able to log back in, right?

**Comment by edpaget** [comment]
Nope you should still be able to log in. The 302 response only happens because you are already signed in.

**Comment by alianos-** [comment]
Worked like a charm. Thanks. I'll post the scripts once things settle down a bit.
