### ISSUE TITLE
Post to /api/classifications errors

### ISSUE THREAD

**Issue by brian-c** [zooniverse/Panoptes#449]
With this data, "found unpermitted parameters: subject":

```
{
  "classifications":{
    "links":{
      "project":"73",
      "workflow":"44",
      "subject":"365314"
    },
    "metadata":{
      "started_at":"2015-01-26T11:37:54.805Z",
      "user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2270.0 Safari/537.36",
      "user_language":"en",
      "workflow_version":"446.353",
      "finished_at":"2015-01-26T11:37:58.991Z"
    },
    "annotations":[
      {
        "present":false
      }
    ],
    "complete":true
  }
}
```

**Comment by camallen** [comment]
Brian, try `set_member_subject` instead of subject, https://github.com/zooniverse/Panoptes/blob/5d27b845846c712d385b9639437ff64e4d13343b/spec/controllers/api/v1/classifications_controller_spec.rb#L29

I see the docs are out of date.

**Comment by brian-c** [comment]
Thanks. But now I get "found unpermitted parameters: complete".

Also, I'm not entirely clear what a set member subject is. According to the docs the set member subject represents the relationship between a subject and its subject set, but why is that exposed to the API?

**Comment by camallen** [comment]
It should be 'completed'.

Subjects are independent of a project in panoptes to enable sharing / re-use. They are now linked to a project via the subject_set_member (via subject_set).

**Comment by camallen** [comment]
This seems inconsistent to what you're getting back form the subjects selection end point though (just subjects without the set_member_subject id).

What does a request to the `/subjects` end point in your app look like?

**Comment by brian-c** [comment]
Getting /subjects responds with this:

![screen shot 2015-01-26 at 12 19 02 pm](https://cloud.githubusercontent.com/assets/464389/5899606/9a648b9e-a555-11e4-9e1e-cc91135eacb4.png)

**Comment by camallen** [comment]
And the request i assume just includes the `workflow_id`? Are you also using the `sort` param for Cellect?

**Comment by brian-c** [comment]
My request for subjects to classify is `/subjects?project_id=73&workflow_id=44&sort=cellect`, which returns something similar. I did have cellect disabled, but turning it back on didn't change anything.

**Comment by brian-c** [comment]
What should I be looking for? A `subject_member_set` ID in `links`?

**Comment by camallen** [comment]
Just make it work at the moment. I'm digging into what `Cellect` and `/Subjects` return specifically. Will have more info soon.

**Comment by edpaget** [comment]
The `/subjects` route doesn't return the SetMemberSubject id. We should change classifications to use the plain subject_id and figure out what set_member_subject was classified based on the workflow.

**Comment by camallen** [comment]
Since a subject can belong to many subject sets and thus many workflows I'm not sure we can reconstruct the sms (set_member_subject) id from just the workflow and the subject ID. I think we need to add the smd_id to the `subjects` response if a sort param is set.

**Comment by edpaget** [comment]
I think we should prevent a user from being a shown a subject twice as part of a single workflow even if it belongs to multiple subjectsets that are assigned to workflow since past experience has taught us that users hate when that happens. We should just set all the set member subjects that have the just classified subject and are a part of the current workflow as seen for the user.

**Comment by edpaget** [comment]
```ruby
SetMemberSubjects.joins(:subject_set).where(subject: subject, subject_sets: {workflow: workflow})
```

Would give us all the representations of a particular subject within a workflow, which would then be added to the user seen subjects.

**Comment by camallen** [comment]
Is there any use case where we'd need a subject to be seen in different workflows?

**Comment by camallen** [comment]
I meant different subject sets above but you're right there is no value repeating the same set of tasks for the workflow for a user. I wasn't thinking about the use case properly.

**Comment by twhyntie** [comment]
@camallen 

Yes please - we'd love to have a "standard" subject set that our users could design and edit their workflows for if possible, to avoid uploading the same subject sets again and again. See [here](https://github.com/twhyntie/Panoptes/wiki/Designing-a-classification-scheme-for-a-new-dataset-on-a-local-VM) for our example [CERN@school](http://cernatschool.web.cern.ch) use case.

Cheers, @twhyntie

**Comment by camallen** [comment]
@edpaget - I'm not 100% sure just submitting the subject to the classification fits well into the schema, especially for queued subjects (`UserSubjectQueue` as they are particular for a set_member_subject_id). 

I'm leaning towards just returning the `set_member_subject_id` in the subject response with a `sort` param that is required when submitting a classification. Thoughts?

**Comment by edpaget** [comment]
Just using the subject_id makes things much more simple for client implementors (why do they need to care about SMSs as Brian said?). I also think this is going to be a huge pain to implement with RestPack. 

I'm not sure why UserSubjectQueues couldn't be handled in the same manner as the UserSeenSubjects.

**Comment by edpaget** [comment]
@brian-c just realized there's also the "complete" issue. The field is actually "completed" I'll update the docs to reflect that.
