### ISSUE TITLE
Will anyone ever need to see task keys or annotation answer values?

### ISSUE THREAD

**Issue by brian-c** [zooniverse/Panoptes#450]
While designing the workflow editor last week I decided to simplify it by not letting the user define their own machine-readable task keys or answer values. Task keys are random and answer values are just the index of the answer in its list.

So instead of

```coffee
# Tasks
{
  is_cool: {
    type: 'single'
    answers: [
      {value: 'y', label: 'Yes'}
      {value: 'n', label: 'No'}
    ]
  }
}

# Classification
{
  annotations: [
    {task: 'is_cool': answer: 'y'}
  ]
}
```

You'd have

```coffee
# Tasks
{
  asdfgh: {
    type: 'single'
    answers: [
      {label: 'Yes'}
      {label: 'No'}
    ]
  }
}

# Classification
{
  annotations: [
    {task: 'asdfgh', answer: 0}
  ]
}
```

The goal is to make editing workflows and tasks as simple as possible. As long as we don't need to make sense of the classification _without its workflow_, there shouldn't be a problem. Does this matter? Does anybody care what a classification looks like out of context?

**Comment by twhyntie** [comment]
Hi @brian-c ,

My only thoughts would be (if I've got the right end of the stick):

* Would this make accessing the answers via the API more cumbersome or tricky if there are image-based answers or very descriptive labels? `y` and `n` would be useful for scripts.
* Would keeping the `value` also allow the `label` to be changed more easily if user feedback indicated a badly-phrased label? Or would such a change require a new migration anyway?

Cheers, @twhyntie

**Comment by edpaget** [comment]
I don't see a problem with this. Let's cc @aliburchard and @ggdhines in case they have an opinion.

**Comment by aliburchard** [comment]
I'm not actually sure I understand, but I'm pretty sure this is okay.

**Comment by edpaget** [comment]
Cool I make sure you can send classifications in that form. Quick question though in your #460 you use `value` instead of `answer` are you settled on one or the other?

**Comment by brian-c** [comment]
Sorry, yes, I settled on each annotation having a `task` and a `value`, regardless of type.
