### ISSUE TITLE
Include owner with project responses

### ISSUE THREAD

**Issue by brian-c** [zooniverse/Panoptes#453]
I can't think of an instance where we're showing a project without its owner's name and a link to its profile. Can we get `owner` added to the project include-ables list?

Currently `:owner is not a valid include for Project` when I try to get `/projects/73?include=owner`.

Possibly related to #451.

**Comment by edpaget** [comment]
Does it work if you do "owners". I did some work on this, but Restpack is weird about pluralization.

**Comment by brian-c** [comment]
There ya go. Thanks.

**Comment by brian-c** [comment]
Actually, it returns with the user in an `owners` key, so I have no way of picking it apart as a user. Should it come back under a `users` key, since its link from the project is `type: 'users'`?

**Comment by edpaget** [comment]
I don't think there's a good way to do that. I can return a type key inside the owner response?

**Comment by brian-c** [comment]
Yeah, that'll work.
