### ISSUE TITLE
Projects need a "public" state

### ISSUE THREAD

**Issue by brian-c** [zooniverse/Panoptes#455]
@aliburchard, correct me if I'm wrong: I believe last time it was discussed we landed on "play -> private -> public -> promoted".

I don't think there are any fields on the project to store this state.

How about two fields, "live" and "public"; both default to false. You could in theory have public non-live projects, we just won't query for these.

Promoted projects could just be a list we maintain manually at first. I don't think that's a property of the project itself.

**Comment by edpaget** [comment]
We already have a `private` field on projects user groups and collections. What does `live` affect exactly?

**Comment by brian-c** [comment]
`live` would lock your workflows, so changing them requires a conscious decision to separate your data.

Didn't know about `private`. Just tried it, here's what I got putting `{"projects":{"private":true}}` to /projects/73:

```
{"errors":[{"message":"[\"The property '#/' contains additional properties [\\\"private\\\"] outside of the schema when none are allowed in schema c2c343d1-2878-5065-9851-a2a569c91c1f#\"]"}]}
```

That error is broke; `errors[0].message looks like it got double-serialized. I'll make another issue for that.

**Comment by edpaget** [comment]
My bad the private field is introduced in #418

**Comment by aliburchard** [comment]
Hey guys - 
Alrighty, I think what we agreed on (see https://docs.google.com/document/d/1EQ6hm-wsE6dhmA1G67uqenq8c8VxMf_brcjFSyTXSYo/edit) is that the first stage is "playground" where a project is still being built and tinkered with, but classifications need to be viewable (to inform improved workflow design). These classifications can be wiped when a project moves to the next stage.

At this point, a project can go into one of two stages. They can 1) launch into a small project without needing any checks from the Zooniverse. I believe we called this "science mode" for lack of a better term. In this mode, the project is indeed "live" and classifications will be recorded and consensus run. Or 2) they can proceed down the path of a full-on Zooniverse project which would involve a proper beta test, input from the community, and eventually a public launch. 

I think that the "science mode" projects are what we are envisioning for our small classroom or research team projects that need an interface for a small group to process data. They can also decide to move to a full from this "science mode." 

I realise that's a bit roundabout, but hopefully the sketch and doc help flesh it out?

![screen shot 2015-01-28 at 09 02 16](https://cloud.githubusercontent.com/assets/6217406/5934848/6b476ad4-a6cc-11e4-962d-0a60bc47aafd.png)

**Comment by twhyntie** [comment]
Hi @aliburchard ,

"Playground" and "Science Mode" are exactly what we need for the CERN@school use cases - thanks!

+1 for the classifications need to be viewable, too :-)

Cheers, @twhyntie
