### ISSUE TITLE
Some errors are double-serialized

### ISSUE THREAD

**Issue by brian-c** [zooniverse/Panoptes#456]
Just tried putting {"projects":{"private":true}} to /projects/73 (#455) and got this in return:

```
{"errors":[{"message":"[\"The property '#/' contains additional properties [\\\"private\\\"] outside of the schema when none are allowed in schema c2c343d1-2878-5065-9851-a2a569c91c1f#\"]"}]}
```

Notice errors[0].message is a JSON string representation of an array of a string. I've seen this before but didn't make a note. Totally minor, and I'm regexing to interpret error messages anyway, but it's probably not quite right somewhere.

**Comment by camallen** [comment]
Linked to #520 

This happens via invalid json payloads that don't pass validation on the json schema format. I'll include a fix in the PR that closes this.
