### ISSUE TITLE
Track invalid emails for existing users

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#462]
Ensure we don't get blacklisted for spam again and track which existing users have invalid / spam emails.

**Comment by camallen** [comment]
Linked to #483 migrate this field on sign in via zoo home. Set it on create as all emails should be a valid format until we know otherwise. This will create a data consistency issue as zoo home will update via bounces but panoptes will only update when a user logs in.

**Comment by edpaget** [comment]
Are we going to be sending emails through Panoptes during stargazing? Since all the users will just be created in Zoo-Home perhaps we should just use that and punt this until after we do the real migration?

**Comment by camallen** [comment]
Zoo home will be the authoritative source. I was more interested in adding the field for future use. Punt it to a later milestone as its not needed for stargazing.
