### ISSUE TITLE
IE needs a P3P header for CORS

### ISSUE THREAD

**Issue by brian-c** [zooniverse/Panoptes#469]
IE won't do third-party cookies without a P3P header in the response.

https://msdn.microsoft.com/en-us/library/ie/ms537341%28v=vs.85%29.aspx

Here's a gem to do it automatically: https://github.com/carrot/p3p

**Comment by camallen** [comment]
If i get this setup locally on my server do you have a client to test it?

**Comment by brian-c** [comment]
Yep, let me know.

**Comment by camallen** [comment]
I've done and tested (with a browser) this, just need to spec it now.
