### ISSUE TITLE
Why do we include classifications in the serialized user response?

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#471]
Firstly why do we include the classification sets of a user on their index route?

Also it seems Restpack is querying the includes even when not actually using them. This will be pretty slow for basic index routes on users (especially as classifications come in).

https://github.com/zooniverse/Panoptes/blob/671ba191fb30193de8104b442a009714990f7a61/app/serializers/user_serializer.rb#L4

Index route (no include params) result set:
![screen shot 2015-01-30 at 22 37 01](https://cloud.githubusercontent.com/assets/295329/5984692/8ac0d17e-a8d0-11e4-82a5-f179e4c4990e.png)

Test Log DB queries:
![screen shot 2015-01-30 at 22 36 24](https://cloud.githubusercontent.com/assets/295329/5984688/7b1b2878-a8d0-11e4-8349-4adb5c892895.png)

**Comment by edpaget** [comment]
In order to include include the top_level link to the classifications in restpack you have to include them as a whole. We should override this behaviour or replace restpack.

**Comment by camallen** [comment]
What's the use case for having the top level classification links on the serialised user response?

**Comment by edpaget** [comment]
Because the responses need to have thr url link to all their related
models. That's how clients figure out how to navigate the api. Overriding
restpack to just have the url link and not the list of ids is pretty easy.
I think I do it in another one of the serializers.

**Comment by camallen** [comment]
Right so it's just ensuring a valid hypermedia API. I'll look into why RP is querying the associations even when not serialising them via the optional include param.
