### ISSUE TITLE
Extra property 'private' in project creation

### ISSUE THREAD

**Issue by alianos-** [zooniverse/Panoptes#476]
Hola,
When I try to create a project I get an error that I have an extra property "private". Removing the property the calls goes through fine. I assume apiary needs updating?

For reference

Apiary, create new project
```
var body = {
    'projects': {
        'name': 'galaxy_zoo',
        'description': 'A doubleplus good project',
        'primary_language': 'en-us',
        'private': true,
        'links': {
            'workflows': ['1', '2']
            'owner': {
                'id': 10,
                'type': 'user_groups'
            }
        }
    }
}
```

The response
```
{
    "readyState": 4,
    "responseText": "{\"errors\":[{\"message\":\"[\\\"The property '#/' contains additional properties [\\\\\\\"private\\\\\\\"] outside of the schema when none are allowed in schema 67d5f871-fee6-590a-b681-4f28729f6e3a#\\\"]\"}]}",
    "responseJSON": {
        "errors": [
            {
                "message": "[\"The property '#/' contains additional properties [\\\"private\\\"] outside of the schema when none are allowed in schema 67d5f871-fee6-590a-b681-4f28729f6e3a#\"]"
            }
        ]
    },
    "status": 422,
    "statusText": "Unprocessable Entity"
}
```

**Comment by camallen** [comment]
The API docs are for the latest version of the code. You should get the latest from the repo and restart the server. 

There are breaking changes in the latest code though (data model changes that we didn't add migrations for). You should just recreate the database from scratch (rake db:migrate:reset but changes here too, see docs) and reseed the admin user and client application. 

Once you've got the latest code and db schema recreated try the client code again to see if you can reproduce the issues.

**Comment by alianos-** [comment]
Solved in the new version indeed! Thanks
