### ISSUE TITLE
rake configure error

### ISSUE THREAD

**Issue by alianos-** [zooniverse/Panoptes#477]
@camallen thanks for the answers in the other issues. I'll let you know what happened once I test them but right now I am doing a fresh installation of panoptes.

I am stuck in the first line tbh. I read a bit what rake does but it didn't help me debug much. I found the configure.rake file but I don't think I can replicate all it does by hand. Any ideas?

Does it matter where I run rake from maybe? Tried a series of folders to no avail.

```
ubuntu@ubuntu:/opt/panoptes/lib/tasks$ rake configure
(in /opt/panoptes)
rake aborted!
cannot load such file -- bundler/setup
/opt/panoptes/config/boot.rb:4:in `<top (required)>'
/opt/panoptes/config/application.rb:1:in `<top (required)>'
/opt/panoptes/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)
```

**Comment by camallen** [comment]
Sounds like you need to install the bundler gem to run rake. The first few commands run outside of docker so you'll need ruby and bundler installed on your system / user install. 

I recommend rvm and specific gemsets if your running different ruby apps / envs on your server.

**Comment by alianos-** [comment]
I realize you might have better things to do, but I'll need your help again. You see I am new in ruby and I have to google everything that comes up to understand what it does (i.e. rake, gem, bundler, rvm).

So I got bundler, then I tried `rake configure` and I get this 
```
Could not find json-1.8.2 in any of the sources
Run `bundle install` to install missing gems.
```

Then I run `bundle install` and I get this
```
Fetching source index from https://rubygems.org/
Using rake 10.4.2
Using i18n 0.7.0

Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

        /usr/bin/ruby1.9.1 extconf.rb 
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- mkmf (LoadError)
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from extconf.rb:1:in `<main>'


Gem files will remain installed in /tmp/bundler20150201-5591-n2nrxm/json-1.8.2/gems/json-1.8.2 for inspection.
Results logged to /tmp/bundler20150201-5591-n2nrxm/json-1.8.2/gems/json-1.8.2/ext/json/ext/generator/gem_make.out
An error occurred while installing json (1.8.2), and Bundler cannot continue.
Make sure that `gem install json -v '1.8.2'` succeeds before bundling.
```

Then I tried `sudo gem install json -v '1.8.2'` but I get this
```
Building native extensions.  This could take a while...
ERROR:  Error installing json:
	ERROR: Failed to build gem native extension.

        /usr/bin/ruby1.9.1 extconf.rb
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- mkmf (LoadError)
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from extconf.rb:1:in `<main>'


Gem files will remain installed in /var/lib/gems/1.9.1/gems/json-1.8.2 for inspection.
Results logged to /var/lib/gems/1.9.1/gems/json-1.8.2/ext/json/ext/generator/gem_make.out
```

**Comment by alianos-** [comment]
nvm I might got that one myself, I saw the full extent of the errors now that i posted them here.

**Comment by alianos-** [comment]
OK so I've just been through this marathon of problem solving. I got `bundler`, did `rake configure`, asked for a `bundle install`, then I had to figure out all the libraries and dependencies missing until that completed successfully (hooray \o/ )

Then. Fail. I am going to bed.
```
Use `bundle show [gemname]` to see where a bundled gem is installed.
ubuntu@ubuntu:/opt/panoptes$ rake configure
rake aborted!
/var/lib/gems/1.9.1/gems/fig_rake-0.9.2/lib/fig_rake/rails.rb:27: unknown type of %string
    %i(console server dbconsole runner).each do |method|
       ^
/var/lib/gems/1.9.1/gems/fig_rake-0.9.2/lib/fig_rake/rails.rb:27: syntax error, unexpected $end, expecting keyword_end
    %i(console server dbconsole runner).each do |method|
       ^
/opt/panoptes/config/boot.rb:5:in `require'
/opt/panoptes/config/boot.rb:5:in `<top (required)>'
/opt/panoptes/config/application.rb:1:in `<top (required)>'
/opt/panoptes/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)
```

**Comment by camallen** [comment]
Hey @alianos- sounds like you're running an old version of ruby, what version are you using? In our [requirements](https://github.com/zooniverse/Panoptes#requirements) docs we specify you need to run newer versions of ruby / jruby.

This [wiki page](https://github.com/zooniverse/Panoptes/wiki/Local-installation-on-an-Ubuntu-VM) has information about getting the system setup for running on Ubuntu but this doesn't leverage the fig / docker containers. It does specify getting started with ruby [here](https://github.com/zooniverse/Panoptes/wiki/Local-installation-on-an-Ubuntu-VM#software) though

**Comment by alianos-** [comment]
Ubuntu people have issues with Ruby people -> https://bugs.launchpad.net/ubuntu/+source/ruby2.0/+bug/1310292

Anyhow, I solved it through rvm. So first step of the installation guide, done :)

I'll post my notes for future reference when I manage to finish the installation. Thanks for the help.

**Comment by camallen** [comment]
@alianos- Great! All docs appreciated.
