### ISSUE TITLE
422 Unprocessesable entry

### ISSUE THREAD

**Issue by alianos-** [zooniverse/Panoptes#479]
Hi,
Hopefully last step before I can login and use the API again. I've set up the latest version of panoptes. I am not sure if the populating the DB worked however. I am getting this when I try to acquire a token
```
HTTP/1.1 422 Unprocessable Entity
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Type: text/html
Cache-Control: no-cache
X-Request-Id: 54d22407-7c27-4e1d-94f2-edb949010ec4
X-Runtime: 0.092000
Access-Control-Allow-Origin: http://localhost:8383
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS, PATCH
Access-Control-Expose-Headers: Last-Modified
Access-Control-Max-Age: 1728000
Access-Control-Allow-Credentials: true
Vary: Origin
Transfer-Encoding: chunked
```

I tried running the db populating script again (to get a new client_id) but I am getting errors. Should it overwrite everything, or is it normal to fail? Also, how can I find the client_id?

**Comment by camallen** [comment]
It'll fail as the user already exists most likely. Reset your DB schema and data (if you don't care about data) and reseed the app user and client (you'll have to update the backed app id OR use the new one in your front end code).
 
Ensure you turn on fig step 3 https://github.com/zooniverse/Panoptes#usage

Then run rake db:migrate:reset to rebuild the db.

Then run step 5 in https://github.com/zooniverse/Panoptes#usage

**Comment by alianos-** [comment]
Worked. I probably had the client_id wrong.
