### ISSUE TITLE
Addition to the docs - adding mysql as a requirement

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/Panoptes#480]
On OSX, `bundle install` will fail if you don't already have MySQL installed. It might be worth adding a Requirements section to the README for pre-install requirements

**Comment by edpaget** [comment]
@camallen I don't think we're using the zooniverse_user import rake task I wrote. Should we just go ahead and remove it and the mysql dependency?

**Comment by camallen** [comment]
Alas i wish we could. The plan for stargazing is to use this to sync with zoo home.

**Comment by camallen** [comment]
@rogerhutchings are you going to add the doc updates? It's be super sweet taking into account this issue too https://github.com/zooniverse/Panoptes/issues/477

**Comment by rogerhutchings** [comment]
Yeah, I was going to - I'll have a look at this one as well.
