### ISSUE TITLE
Integrate logins and signups with zoo home

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#483]
Ensure logins and signups are not isolated in Panoptes and are usable across the zooniverse.

**Comment by edpaget** [comment]
So the way I think would work best for handling this is having the Panoptes database replace Zooniverse Home as the authoritative database for usernames/passwords across the the zooniverse. 

Here's a list of things we'll need to do to handle the change:
* [ ] Point Ouroboros's `ZooniverseUser` model at the Panoptes database
* [ ] Connect Zooniverse-Home to Panoptes for authenticating users
* [ ] Connect the CAS Server to the Panoptes database for authenticating users
* [ ] Make sure all three of the above use the same password updating scheme as Panoptes
* [ ] Write a script to migrate users into Panoptes

**Comment by camallen** [comment]
Long term i totally agree but I'm not sure we should have the CAS / Ouroboros logins working on panoptes for stargazing.

In my mind stargazing is a one off and would be a first attempt at using panoptes to run a project. We'd then iterate on the lessons learned and afterwards, deploy the first version of a real panoptes. The first real panoptes deploy would have some downtime to migrate all users and move auth to the panoptes DB, linking CAS login and ouroboros. 

For stargazing, I think we should just implement a `zooniverse_user` like solution (as per ourobros) to read from the zoo home DB user accounts and scale the zoo home DB to handle the load. This was we can leave existing ouroboros / CAS login auth mechanisms in place and just worry about stargazing work.

Thoughts @chrislintott @astopy ?

**Comment by edpaget** [comment]
i think we're going to have problems hacking Devise to work with the `ZooniverseUser` solution. Also I thought we'd continue to run the Panoptes database even if the actual rails app is no longer accessible, so Zoo-Home, Ouroboros, the CAS server could still access the two columns they need to do login.

**Comment by edpaget** [comment]
I think the biggest problem with doing the migration now will be setting up the CAS server to do bcrypt for passwords.

**Comment by camallen** [comment]
I've got a few concerns switching over to panoptes so close when it's untested and we've got a lot of work todo for stargazing. What are your main concerns re hacking devise? 

I thought we would modify the `sessions_controller` (almost the same as Ouroboros's `login_controller`) to check authentication via zoonverse user and if it's valid then migrate the user account and sign them in via devise's sign in. This way the user account is synced for all projects and not isolated in Panoptes (until we migrate away from CAS). 

Signups would be similar (`registrations_controller`), try and create a Zooniverse user and if valid sign them in to a panoptes session. Let me know what you think.

**Comment by chrislintott** [comment]
Just to chip in - I strongly agree with Cam that we shouldn’t be doing much before Stargazing. I’m worried about breaking other projects and distracting ourselves; my vote is for modifying the controller as described above.

Then first priority after Stargazing is to do the migration properly.

**Comment by edpaget** [comment]
@camallen my main concern is that we'd have to two copies of every user record. How to do we handle changes to those records? Do we need to propagate edits in Ouroboros or Zoo-Home to Panoptes? Or visa versa? If a user resets their password on Galaxy Zoo after doing stargazing, do we need to add code to Zoo-Home to copy their new password over to Panoptes?

Both ways of doing this are untested. Doing the migration is the simpler way to handle login, which should make it easier to test. We'd can also aim to have all the changes deployed a week ahead of Stargazing, so we'd have plenty of time to make sure the implementation will work for our needs.

**Comment by parrish** [comment]
Perhaps this is a different issue, but it looks like Panoptes has abandoned the notion of a separate display name and login.  Credited name, display name, and login are all distinct in usage.

What's the motivation for making such a large breaking change?

**Comment by edpaget** [comment]
@parrish Credited name still exists. @brian-c thought login names would be hidden entirely and I didn't think it made any sense to still have a login name if it would never show up in the interface. [See here](https://github.com/zooniverse/Panoptes/issues/544#issuecomment-75062414)

As far as I can tell you can't even set the old Zoo-Home display name option anywhere (if you look at https://www.zooniverse.org/account/settings).

**Comment by camallen** [comment]
@edpaget - the way zooniverse_user works in Ouroboros is the zooniverse home db is the canononical record, all authentication happens via this record and a local copy is created in Ouroboros. 

If we setup panoptes to do this then a panoptes user would be a local cache / proxy for the zoo home user and any changes to a zoo home user account (via ouroboros / zoo home, etc) would propogate across the zooniverse. 

In panoptes on each login we authenticate via the zoo home user model and if needed merge new details to panoptes to update the local version and sign the user in. On registration we try and create a new user in zoo home and if successful copy the record over to panoptes and sign them in. 

Am i missing something? Have you checked out the [ouroboros login controller](https://github.com/zooniverse/Ouroboros/blob/b66b4e9623f4414a436b2fd538af4752de466054/app/controllers/login_controller.rb#L90)?

**Comment by parrish** [comment]
Okay, I see where you're coming from, so I'll revisit the original intent of the different fields.

Login: Canonical, unique user id.  This is what a user logins with and is @-mentioned by
Display name: Public name.  My login is parrish and my public name is Michael.  If anything gets dropped it's this one.
Credited name: What a user wants to have their name published as.  Previously real name

I don't particularly care what we call them, but using "display_name" for login is downright confusing.

Again, we still need a canonical user id and a public facing (non-unique) name.  Just let me know those fields are going to be called and I'll change the code that depends on them.

**Comment by edpaget** [comment]
@parrish I don't care what it's called either. If you and @brian-c concur on a different name to use, I'll change it to that. The login for using `display_name` is that every model that has a uses `display_name` as the field for the publically displayable name.

**Comment by edpaget** [comment]
@camallen no the problem I was proposing doesn't appear to be an issue the more I think about it. I was wondering about the case where someone logins into Panoptes, resets their password using Zooniverse Home, and then logs into Panoptes again. That's not a problem since we'd be checking against Zoo Home on every login.

If you are so strongly opposed to just doing the migration, I'll go ahead and code to use Zooniverse Home. I just don't see why people think it will be difficult to do. I went ahead did a demonstration port of ZooniverseUser in Ouroboros earlier today as a demonstration. It was really easy and would only require adding a few additional fields to Panoptes's User table: https://github.com/edpaget/Ouroboros/blob/panoptes-login/app/models/zooniverse_user.rb

**Comment by brian-c** [comment]
I don't care what the keys are. `display_name` looks weird as a login, but it's consistent with everything else, so: whatever.

Last time this came up we agreed that users are identified across the site by one name, the same one they sign in with. Their `credited_name` is optional and non-unique and not how people'll be primarily identified.

If we're going to change key names, please do it after Stargazing?

**Comment by camallen** [comment]
Re `display_name` - this thread just keeps going, I think we should just leave all this as is and change the setup after stargazing if that's what we decide to do.

**Comment by camallen** [comment]
Re migrating vs zoo_home auth: @edpaget the only issue I have is that we're combining a set of work that is outside the scope of just running stargazing. I.e. we would be updating login.zooniverse.org (CAS) to run a new hashing algorithm on top of panoptes, ensure zooniverse home updates panoptes user account, migrate ouroboros's authoritative user account to panoptes and then migrate all users to panoptes. All that is just to make sure login works for all our old projects. 

We'd then have to make sure that all legacy / ouroboros projects then still work as expected (user preferences, others?). Also @astopy's bounce email system runs off zoo home so we'd have to migrate that. Finally any other dependencies I can't think off right now would still have to work.

Doing all this work and finishing off stargazing and then ensuring stargazing doesn't affect all our existing projects is too much in a short time span for my mind. I think we should schedule this set of work after stargazing finishes and we have got a solid set of information about panoptes load profiles and how to scale out authentication to the wider zooniverse (hopefully turning of CAS for a start and just rolling ouroboros onto panoptes), hopefully old projects can just be shut down when this happens.

Hopefully I've outlined some valid concerns re migrating authoritative user accounts to panoptes and I'm not just being paranoid. Let me know what you think Ed.

**Comment by edpaget** [comment]
@camallen I've been working on just doing it your way, by connecting to Zoo-Home. I'm most of the way through. My two remaining issues are managing a test schema in a separate database for the Zoo-Home table, and doing the sessions controller login as a Warden strategy, to make sure it works right with Devise.

**Comment by camallen** [comment]
Re diff database, what about a sqllite db / table? Let me know if I can help.

**Comment by edpaget** [comment]
Yup was just to figure out how to setup the schema for a separate connection. It's all worked out now.
