### ISSUE TITLE
Automate subject activation

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#486]
Worker script to activate subjects below when they fall below an active number

**Comment by edpaget** [comment]
I thought the idea with Cellect was that we don't need to limit the number of active subjects?

**Comment by camallen** [comment]
Do we have any stats on server numbers, concurrent users and subject set sizes? If we can hold a large priority set for 4-10k concurrent users we could be good for stargazing. 

What about long term with lots of projects? db connection limits might be a scaling issue if we need lots of cellect servers and api and sidekiq nodes.

**Comment by camallen** [comment]
Depends on the outcome of #504

**Comment by camallen** [comment]
Cellect is going to handle large enough subject sets and we can manually do this if needed. We will revisit this for full scale panoptes (many projects) if needed in the future.
