### ISSUE TITLE
Panoptes installation guide for Ubuntu 14.04

### ISSUE THREAD

**Issue by alianos-** [zooniverse/Panoptes#489]
## 1. Install Docker ##
Original guide  https://docs.docker.com/installation/ubuntulinux/

`curl -sSL https://get.docker.com/ubuntu/ | sudo sh`

## 2. Install Fig ##
Original guide http://www.fig.sh/install.html

Onliner `curl -L https://github.com/docker/fig/releases/download/1.0.1/fig-`uname -s`-`uname -m` > /tmp/fig; sudo mv /tmp/fig /usr/local/bin/fig; chmod +x /usr/local/bin/fig`

Run `fig --version` to see if it worked.

## 3. Prepare ruby ##
3.1. Get the right ruby

Try `ruby -v` to see what ruby you have.

It is likely you don't have ruby 2. So you need to get it, alas, package manager won't help you (long story, but use rvm so you can get the version we need). Useful resource http://stackoverflow.com/questions/26595620/how-to-install-ruby-2-1-4-on-ubuntu-14-04 

Panoptes currently needs 2.1.5

```
sudo apt-get update
sudo apt-get install build-essential make curl
\curl -L https://get.rvm.io | bash -s stable
source ~/.bash_profile
rvm install ruby-2.1.5
```
Then check ruby versions installed and in use
```
rvm list
rvm use --default ruby-2.1.5
```

( Ruby is installed in $HOME/.rvm/rubies )

3.2. Put ruby in 2 mode (asked at the panoptes installation guide)
`export JRUBY_OPTS=--2.0`

3.3. Then get ruby dev
`sudo apt-get install ruby-dev`

3.4. Then, get bundler
`sudo gem install bundler`

## 4. Install Panoptes ##

Original guide https://github.com/zooniverse/Panoptes

4.1. Download, move, extract, all at once
`cd /tmp; wget  https://github.com/zooniverse/Panoptes/archive/master.zip; unzip master.zip; sudo mv Panoptes-master/ /opt/panoptes; cd /opt/panoptes`

4.2. Configure things automatically using 'rake' (you can install 'rake' from the package manager)

But before you do that! If you are in a fresh ubuntu installation, you will probably eventually run into some problems. You might want to read ahead and solve them proactively.

The order of things is

`rake configure`

This will tell you to `bundle install`, which will give you the following problems (one by one, in each consecutive run, which is why it is good to install the dependencies on beforehand)

If you get an error with 'nokogiri', solve it by `sudo apt-get install liblzma-dev zlib1g-dev`. 
If you get an error with 'mysql2', solve it by `sudo apt-get install libmysqlclient-dev` (or for other linux distributions http://stackoverflow.com/a/4304489)
If you get an error with 'pg_config' solve it by `sudo apt-get install libpq-dev` (http://stackoverflow.com/a/10792110)
If you get an error with 'therubyracer' solve it by `sudo apt-get install g++`

I am assuming different installations might get different problems, so solve on a per-case basis. The issue always seems to be some dependency. Keep running `bundle install` until everything downloads and installs.

Once you manage to finish successfully, rerun `rake configure`. Good luck.

4.3. add the user we run panoptes as, in the 'docker' group.

This is so you can see the docker deamon running.

`sudo gpasswd -a ${USER} docker; sudo service docker restart`

Then either do a `newgrp docker` or log out/in to activate the changes to groups.

4.4. Add folder that is missing from the /opt/panoptes installation directory. (might be fixed in future versions) `mkdir -p tmp/pids`

4.5. Up we go
Run `fig up`
If something fails try again. Eventually you will end up with panoptes running \o/

4.6. Build the DB
a) Now if for some reason you need ubuntu with a GUI, you'll have some issues with ruby and rvm and you will need to set things up for every terminal session. Here is a solution https://rvm.io/integration/gnome-terminal

OR

b) If you run with no GUI you should be fine. Just a reminder, bash has tabs and you can switch between them with Alt+F1, Alt+F2 etc.

Either way open a new terminal session with properly set ruby and go

`export FIG_RAKE=on`
`rake db:create db:migrate`

4.7. Seed the DB

Now when this step is done, your client_id will be printed in your screen. You will need to make a copy of it. 

a) If you have a GUI (or you are happy to retype it as you see it), then just do
`rails runner db/fig_dev_seed_data/fig_dev_seed_data.rb`

OR

b) Direct the output to a file. This means you won't see what is happening, so let me guide you.
`rails runner db/fig_dev_seed_data/fig_dev_seed_data.rb > client_id.txt`
Wait for 15 seconds. Is something happening? No, it's not! Good. Type in the password for your administration user. Then wait a second and type it again. Then after a few more the script should finish. `cat client_id.txt` to see what you just did. (PS. you can always open a new terminal, and use 'cat' to see where the script is currently at, then switch terminal and continue, and so on).

If something got messed up, reset the DB and try again.

## 5. Use & reuse ##
Thats that. Stop panoptes with `ctrl+C`, rerun with `fig up`. 

You will need the IP of your machine, panoptes uses port 3000.

If you want to reset the installation just reset the DB
`export FIG_RAKE=on`
`rake db:migrate:reset`
Then step 4.7. to reseed the db.

**Comment by alianos-** [comment]
Hi people. So here is what I have come up with. It's for a fresh ubuntu installation. I am not sure where would be right place to put it, so I just posted it here.

If someone can read through it, maybe there are things you can put in the official documentation (like the user that needs to be in the dockergroup for example). I am just googling everything as I go but I am pretty much clueless about fig/docker/ruby/gems/rvm/bundler and probably a few more of the tech used, so someone check it out and make sure I aint doing something awfully stupid.

**Comment by camallen** [comment]
@alianos- thanks for the contribution. There are definitely some dependency issues that we haven't documented. I also think some of these steps can be streamlined via normal ruby / rails server installation. 

We'll look through and use this as a template for adding getting started documentation for an Ubuntu install using fig + docker.

**Comment by camallen** [comment]
Just leave this open for now so we can get to it when we have time.

**Comment by edpaget** [comment]
I think this is well covered in our readme now.
