### ISSUE TITLE
Add version scheme to Panoptes once we reach a stable release

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#490]
I like Semantic Versioning personally but open to ideas, especially any that ensure we don't forget to bump release versions.

**Comment by edpaget** [comment]
How would the versioning information be used?

**Comment by camallen** [comment]
Possibly via a publicly accessible static file on the api nodes? See the link i just added.

**Comment by astopy** [comment]
+1 for semantic versioning.

**Comment by edpaget** [comment]
Sorry @camallen I meant what would it be used for?

**Comment by camallen** [comment]
1. Master should always be deployed.
2. Staging can have non-merged features in 'pre-release' on the staging site.

If we want to patch a bug then we'd patch and deploy master (and the version number x.x.N). I agree we'll need version numbers for formalising the release cycle (especially for 3rd parties) but we're not at 1.0 yet and probably won't be till after stargazing.
