### ISSUE TITLE
ensure classification is persisted before queuing to background worker

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#503]
Classification lifecycle queues the classification by id before persisting to the db.
 - [x] Ensure the workfer doesn't fail and retry for days look at reducing retry limits - 3?
 - [x] Hook into create classifcation event via yield block and queue the classification ID after successful save

**Comment by edpaget** [comment]
@camallen with regards to number two. Why wouldn't we just do a `classification.persisted?` instead?

**Comment by camallen** [comment]
Hey @edpaget the lifecycle is created and queued in the build block of the controller [here](https://github.com/zooniverse/Panoptes/blob/master/app/controllers/api/v1/classifications_controller.rb#L57). It won't have an ID till it's persisted and we pass that ID into sidekiq when we queue the job.

I was thinking roughly a yeild [here](https://github.com/zooniverse/Panoptes/blob/b554b6042ee886f1a809fd22d4d31692537b15b4/lib/json_api_controller/creatable_resource.rb#L11)
```RUBY
def create
  resources = resource_class.transaction(requires_new: true) do
  begin
    Array.wrap(create_params).map do |ps|
      resource = build_resource_for_create(ps)
      resource.save!
      yield resource if block_given?
      resource
    end
  end
end
```
Used [here](https://github.com/zooniverse/Panoptes/blob/b554b6042ee886f1a809fd22d4d31692537b15b4/lib/json_api_controller/classifications_controller.rb)
``` RUBY

def create
  super { |classification| lifecycle(:update, classification) }
end
```
Am i missing something?
