### ISSUE TITLE
super minor typo on the apiary

### ISSUE THREAD

**Issue by alianos-** [zooniverse/Panoptes#506]
I am not trying to be annoying, really! I just noticed it and figured to let you know.

At http://docs.panoptes.apiary.io/#reference/subject-set/subjectset/retrieve-a-single-subject-set 

The response text reads  `"set_member_subject_cound": 100,` (which is see fixed in the actual response from my server).

**Comment by alianos-** [comment]
Also, at the http://docs.panoptes.apiary.io/#reference/classification/classification-collection/create-a-classification the following comments.

1.
>Create a classification by providing a JSON-API formatted object that must include annotations and a links hash with **a set_member_subject**, a project, and a workflow.

Which if I am not mistaken should be **the subjects**

2.
 >Optionally may include the **complete** field, which will be set to true by default.

Which apart from the complete**d**, could also use an explanation for what it does. (Does this imply that I can save incomplete classifications for example, so the user can later continue where he left it?).

**Comment by camallen** [comment]
Feel free to fix the docs and issue a pull request. Google hit hub and contributing via a pull request. 

Completed is indeed for temporarily storing incomplete classifications. Cross device as well!

**Comment by alianos-** [comment]
Erm sure, but how? If I get it right I need to fork the project, do my changes, then issue a pull request. But where are the docs?

**Comment by camallen** [comment]
https://github.com/zooniverse/Panoptes/blob/master/apiary.apib

**Comment by camallen** [comment]
Closed by #510

**Comment by alianos-** [comment]
I am assuming you fixed them yourself. Sorry I didn't do it promptly, I have no git experience so it takes a while to understand how things work.

**Comment by camallen** [comment]
No worries, just trying to encourage you. Any contribution back from the community is great. Hopefully we can leverage your JS code as API examples when your they are stable and your happy with them.

**Comment by alianos-** [comment]
Sure thing. Actually I just installed git and managed to fork and clone to the server. So for training I will make the effort to spell check the documentation. The documentation you just updated could also use some clarification, so I can do that as well if you clarify it.

We are talking for http://docs.panoptes.apiary.io/#reference/classification/classification-collection/create-a-classification


1.
>and a links hash containing a subjects hash, a project and workflow ids. 

a) Does this mean a lot of ids so I update the code with a workflow id hash instead of a single id
b) It is a typo and should be "workflow id" and not "id**s**"
c) Neither

for reference 
```
'links': {
      'subjects': [
        '11'
      ],
      'workflow': '81',
      'project': '2'
    }
```


2.
>Create a classification by providing a JSON-API formatted object that must include metadata. The metadata hash must contain the keys specified below.

There is no below. Does this mean **all** the keys we see in the code are mandatory?
```
'metadata': {
      'started_at': '2014-08-24T22:20:21Z',
      'finished_at': '2014-08-24T22:24:31Z',
      'user_agent': 'cURL',
      'user_language': 'es_MX',
      'workflow_version': '11.12'
    },
```

**Comment by camallen** [comment]
Re 1), it could be clearer and it's both, a workflow id and a project id. 
Again any doc PR's that you reword would be appreciated, as a consumer of the API docs your opinions is valued!

Re 2), below mean the classification example in the docs. On apiary it's formatted to display in another panel, in the docs it's below. Feel free to PR this change too!
