### ISSUE TITLE
Allow arbitrary params nesting in classifications

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#508]
Linked to #505 - Hash answers of annotation keys are not currently permitted. 

``` RUBY
{ classifications: {
    annotations: [
       { 
          "2003": { 
            "water": "70",
            "forest": "30" 
          } 
    ]
  }
}
```
Remove strong params and use json schema OR manually whitelst the nested params.

**Comment by edpaget** [comment]
Are we just planning to allow anything in the classification hash? I think we need to validate the annotations format for classifications to make sure malformed annotations that won't be read by the aggregation program are not accepted.

**Comment by edpaget** [comment]
Yeah I'm updating it to use JSON Schema so more types can be accepted as part of the annotation, but all annotations should always be of the form 

```json
"annotations": [
   {
      "task": "workflow-task-name",
      "value": ["something", "anything"]
   }
}
```
