### ISSUE TITLE
Top-level links for classifications

### ISSUE THREAD

**Issue by brian-c** [zooniverse/Panoptes#512]
Here's a weird question: What's a reasonable way for me to get the top-level links of the `classifications` type? Since the client creates classifications, but generally never retrieves any, there's no obvious opportunity to get this until I save one. But when passing around a client-created classification in the client it'd be nice to be able to get linked things instead of passing them along too.

I could make a request for /classifications?this_matches=nothing to get back an empty list with the top-level `links` key, but that seems hacky (and is currently not allowed anyway).

As for the links themselves, it appears `workflow` isn't in there. Subjects are referred to by `set_member_subjects`; are we still exposing that?

**Comment by camallen** [comment]
Conforming to the idea of HATEOS the only way is to get a representation of the resouce. You could request only one classification via `/api/classifications?page_size=1`and then harvest the links. As you said you can get the resource after a valid create. A more hacky solution you could create a fake, incomplete classification and then delete it after, that should have the top level links on it.

Classifications store the `set_member_subjects to link them to the project / workflow. The `set_member_subject` links between the `subject_set` and the `subject`. 

What's the use case for passing a client-created, non-persisted classification around?

**Comment by brian-c** [comment]
GET /api/classifications is only allowed when logged in. I'm fine with this solution otherwise.

I get what set_member_subjects is, but I thought we agreed (can't find the issue now) it was a back-end implementation detail that wouldn't be exposed to the client. The classification doesn't care what subject_set its subject is a member of. Docs need updating if that's not the case.

In the client, a classification is _created_ by the project's Classify page and then passed into a more generic Classifier component to do all the work. Given any classification resource, the Classifier should be able to find the other resources (workflow and subject) it needs to build the classification interface.

**Comment by camallen** [comment]
`set_member_subject` is an implementation detail. We should probably revisit the classification representation. Originally the classification representation was for use in aggregation, however that use case requires the project, workflow, subject set and subject links. I'll confirm with Greg what he needs.

**Comment by edpaget** [comment]
We could add a `subject_ids` field to the Classification model and not accept set_member_subjects in the response. We would have to change the UserSeenSubject model to use subject_ids instead of set_member_subject ids and revisit our Cellect adapter unless we wanted to take the extra database hit to retrieve the SetMemberSubject ids after a classification.

**Comment by camallen** [comment]
Why don't we store all the required info on save and just serialize the representation as is, I.e. take the db hits in the background workers instead of when serializing. 

I don't think we have to change the data model but just what the serialised resource looks like.

**Comment by camallen** [comment]
@ggdhines - what information do you need for aggregation in a representation of classification data?  Ed's work in #519 will provide the `subject ids`, `raw annotations`, `workflow id` and `project id`. Do you need more?

**Comment by camallen** [comment]
@ggdhines speak now or forever hold your peace.

**Comment by ggdhines** [comment]
Yup - that sounds good.

**Comment by camallen** [comment]
I think we've got this sorted, re-open if you've got concerns.
