### ISSUE TITLE
Allow fig to run off latest docker image

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#514]
Allow production use of panoptes via fig that leverages the pre built docker images instead of the dev version that requires an image rebuild when gem dependencies change.

**Comment by edpaget** [comment]
Maybe we should change https://github.com/zooniverse/devoptes into that?

**Comment by camallen** [comment]
Yeah I think that's a nice place to host a stable release. We should probably figure out if it will run properly in production mode with the default configs we have setup as we don't want users deploying sites against a dev mode server. 

FYI - Fig now does allow you to specify the fig.yml file you want to run off so we could make wrapper scripts to do this in panoptes.

**Comment by marten** [comment]
I'm going to close this, if someone needs it we can build it but let's not have this in our issue tracker until then.

**Comment by camallen** [comment]
docker-compose has superseded this anyway, one can just specify the image instead of a build.
