### ISSUE TITLE
Research hot restarts with puma

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#515]
Research reloading new code without stopping the web server (can we do this?):

https://github.com/puma/puma/issues/210
https://github.com/puma/puma#restart

Also if we restart sidekiq as well do we leak file descriptors unless we setup the sidekiq config in the `on_restart` blocks? https://github.com/puma/puma#cleanup-code

**Comment by astopy** [comment]
I was experimenting with this on Friday, and couldn’t get it to work properly. Sending SIGUSR2  caused it to just crash entirely (it raised SIGABRT), and SIGUSR1 seems to make it restart cleanly but it doesn’t serve requests while it’s doing so (which means the server is basically dead for a few minutes).

I’m still trying to think of a way around it.

**Comment by camallen** [comment]
http://deployingjruby.blogspot.co.uk/2012/05/zero-downtime-deploys-with-jruby.html

**Comment by camallen** [comment]
Looks like docker will kill the container when the process quits. We'd need something like supervisor to ensure the process and container stays alive.

**Comment by astopy** [comment]
I did try this with supervisor, but even that’s not good enough because jruby is so damn slow at starting. My current plan is to not bother trying to update the live EC2 instances, but to bring up new instances and pull the new code to them before putting them behind the load balancer and killing the old ones.

**Comment by camallen** [comment]
Ha - damn you JRuby and your slow startup times.

**Comment by camallen** [comment]
I've tested MRI hot restart in cellect_panoptes, https://github.com/zooniverse/cellect_panoptes/pull/12. It works really well and can be used to manage memory as well.

**Comment by camallen** [comment]
Startup times are too slow in Jruby to avoid autoscaling probably killing the nodes when they are rebooting. Hot code deploys will be by launching new production api with new code.
