### ISSUE TITLE
Ensure valid link ids when creating /updating a classification

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#520]
https://app.honeybadger.io/fault/40595/38ff4b85f727959b6137f80c0e20910f

Looks like the links allow strings that may not be castable to model id's. This causes a 500 error from the PG adapter.

@edpaget - i don't think we can enforce this in the schema but probably should do a sanity check on before_create / update when extracting params. Thoughts?

See "RAW_POST_DATA" in the error:
``` JSON
{"classifications":
  {"annotations":[{"task":"draw","value":[]}],
   "metadata":{
     "started_at":"2015-02-07T15:52:16.821Z",
     "user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2295.0 Safari/537.36",
     "user_language":"en"},
   "links":{
     "workflow":"MOCK_WORKFLOW_FOR_CLASSIFIER",
     "subjects":["MOCK_SUBJECT_FOR_CLASSIFIER"],
     "project":"18"}
   }
}
```

**Comment by edpaget** [comment]
We can handle this with the schema, since you can include a regex for string types. So we'd just need to have a "[0-9]*" in them. I'll add to the schema generation for ActiveCerealizers.

**Comment by edpaget** [comment]
http://json-schema.org/example2.html

**Comment by camallen** [comment]
Sweet - i should read the docs!

**Comment by edpaget** [comment]
I don't its included in my dsl, but it's in Michael's
