### ISSUE TITLE
Matching users to their classifications

### ISSUE THREAD

**Issue by ggdhines** [zooniverse/Panoptes#521]
This seems to be a recurring issue with Ouroboros - I don't know if is has been addressed in Panoptes (apologies if it has) but I wanted to note it.
In the current Mongodb database for each of projects there are two tables (technically collections in the Mongo terminology) called project_classifications and project_users. For each classification, if the user is logged in, that classification record (stored in project_classifications) contains a field called "user_name". You can use this field to then look up the user in the project_users table where each user instance also has a field called "user_name" (or just "user"). In the users instance there is also a "classification_count" field.
My understanding is that if classification_count equals 10 (for example), then I should be able to find 10 classifications in that projects classification table from that user. That user may have other classifications from when they weren't logged in (and I don't care about those) but those 10 classifications should exist.
Unfortunately, this is not always the case. I have found regular instances in both Snapshot Serengeti and Penguin Watch (haven't checked others) where a user is listed in the user table and with a classification_count (sometimes in the 100s) but I can't find those classifications.
In the current state this really limits how useful the user table is.

**Comment by edpaget** [comment]
Yes I think this is an issue with how the counts are denormalized in MongoDB in Ouroboros. We save each classification with a user_id (if it exists) and a user_ip address. We'll denormalize the counts in a background workers, but they shouldn't be considered 100% reliable, since the transaction to update the counts can fail, and are mostly for displaying to the user. 

Beyond an identifier for a user (which will always be accurate or the classification itself won't be saved), what else do you need from the users table?

**Comment by ggdhines** [comment]
I can't speak for every possibility - I only encountered this issue for the first time yesterday which was because of the specific analysis I was doing. So it is possible that in the future, I come across something new. But it would just be really nice if, for example, when a user's classification count says 25, I can find those 25 classifications.

**Comment by camallen** [comment]
Panoptes will link the logged in user when submitting a classification on the classification model. The user model has a count of submitted classifications that "should" be in sync with the classification models.

Ideally I think doing some spark processing to group the classifications via users (when set) is the best way to go.

I'm going to close this now but feel free to open back up if there's more we should discuss.
