### ISSUE TITLE
External URLs (blog, social) for a project(/user/group/subject?)

### ISSUE THREAD

**Issue by brian-c** [zooniverse/Panoptes#524]
We should have a way to associate external URLs with a resource (zooniverse/Panoptes-Front-End#91). Projects for sure (blog, Facebook, Twitter, etc.), and probably users and groups, but maybe subjects too, for links to some external data source? I don't think we need to be super descriptive with them, just a list. The client can be responsible for identifying the service and picking an icon for recognized ones.

I'm thinking:

```
{
  "projects": {
    "urls": [
      "https://github.com/brian-c",
      "https://twitter.com/__brian_c__"
    ]
  }
}
```

**Comment by edpaget** [comment]
Does this need to be in place for Stargazing?

**Comment by brian-c** [comment]
Nope.

**Comment by vrooje** [comment]
Just a comment: in addition to enabling icons displayed on projects, I think this is really important for our eventual goal of giving clients a measure of the health of their project in a way that encompasses their engagement as well as their project's popularity (i.e. what I talked about at the Zoo team meeting). If they provide external links and we have a way of measuring that activity (e.g. counting blog posts and comments), we can have a much better sense of how they're doing.
