### ISSUE TITLE
Listing Classifications returns each classification twice

### ISSUE THREAD

**Issue by alianos-** [zooniverse/Panoptes#532]
What the title says.

Request
```
GET /api/classifications?project_id=1&for=projects HTTP/1.1
[...]
```

Response
``` js
{
    "classifications": [
        {
            "id": "4",
            "annotations": [
                {
                    "task": "2003",
                    "value": {
                        "water": "70",
                        "forest": "30"
                    }
                },
                {
                    "task": "2015",
                    "value": {
                        "water": "80",
                        "forest": "20"
                    }
                },
                {
                    "task": "other",
                    "value": {
                        "bridgeLoss": "true"
                    }
                }
            ],
            "created_at": "2015-02-13T21:38:06.370Z",
            "links": {
                "project": "1",
                "user": "1",
                "set_member_subjects": [
                    "1"
                ]
            }
        },
        {
            "id": "5",
            "annotations": [
                {
                    "task": "2003",
                    "value": {
                        "water": "70",
                        "forest": "30"
                    }
                },
                {
                    "task": "2015",
                    "value": {
                        "water": "80",
                        "forest": "20"
                    }
                },
                {
                    "task": "other",
                    "value": {
                        "bridgeLoss": "true"
                    }
                }
            ],
            "created_at": "2015-02-13T21:52:40.428Z",
            "links": {
                "project": "1",
                "user": "1",
                "set_member_subjects": [
                    "1"
                ]
            }
        },
        {
            "id": "4",
            "annotations": [
                {
                    "task": "2003",
                    "value": {
                        "water": "70",
                        "forest": "30"
                    }
                },
                {
                    "task": "2015",
                    "value": {
                        "water": "80",
                        "forest": "20"
                    }
                },
                {
                    "task": "other",
                    "value": {
                        "bridgeLoss": "true"
                    }
                }
            ],
            "created_at": "2015-02-13T21:38:06.370Z",
            "links": {
                "project": "1",
                "user": "1",
                "set_member_subjects": [
                    "1"
                ]
            }
        },
        {
            "id": "5",
            "annotations": [
                {
                    "task": "2003",
                    "value": {
                        "water": "70",
                        "forest": "30"
                    }
                },
                {
                    "task": "2015",
                    "value": {
                        "water": "80",
                        "forest": "20"
                    }
                },
                {
                    "task": "other",
                    "value": {
                        "bridgeLoss": "true"
                    }
                }
            ],
            "created_at": "2015-02-13T21:52:40.428Z",
            "links": {
                "project": "1",
                "user": "1",
                "set_member_subjects": [
                    "1"
                ]
            }
        }
    ],
    "links": {
        "classifications.project": {
            "href": "/projects/{classifications.project}",
            "type": "projects"
        },
        "classifications.user": {
            "href": "/users/{classifications.user}",
            "type": "users"
        },
        "classifications.user_group": {
            "href": "/user_groups/{classifications.user_group}",
            "type": "user_groups"
        },
        "classifications.set_member_subjects": {
            "type": "set_member_subjects",
            "href": "/set_member_subjects/{classifications.set_member_subjects}"
        }
    },
    "meta": {
        "classifications": {
            "page": 1,
            "page_size": 20,
            "count": 4,
            "include": [],
            "page_count": 1,
            "previous_page": null,
            "next_page": null,
            "first_href": "/classifications?project_id=1",
            "previous_href": null,
            "next_href": null,
            "last_href": "/classifications?project_id=1"
        }
    }
}
```

**Comment by edpaget** [comment]
This is bug because I use UNION ALL in the SQL query, project owners who classify in their own projects will see double classifications. I think we may want to change how classifications are retrieved if only for speed of retrieval.

I was thinking we could add a param to the route like `/classifications?for=user`, which could also be `/classifications?for=projects` or `/classifications?for=groups`, but I don't really like it because it doesn't seem super discoverable via JSON API. Thoughts @camallen

**Comment by alianos-** [comment]
Why don't you just remove the `ALL`? If I recall correctly all it does in comparison to just `UNION` is allow duplicates isn't it?

Also I think the `for` parameter can be omitted, since you can get this information implicitly by the `subject_id`, `group_id` or `user_id` (i.e. if any of these parameters exist in the request, what I wanted is the `classifications` with that constraint).

As a note so we don't forget, at the current state, when I get lets say, a user, the link to classifications is missing the `for` parameter.

example
```
"users.classifications": {
            "href": "/classifications?user_id={users.id}",    <----- The 'for' is missing
            "type": "classifications"
        },
```

Finally, don't we also need a way to retrieve all the classifications for a specific subject?

**Comment by camallen** [comment]
@alianos- A union query has to remove duplicates and is a slower for large union sets. We will have this problem if we have successful projects that have lots of classifications. Our current use case for the classifications table is pretty much a dumb store for long term storage. Our plan is to use  supporting services to harvest classificaitons, e.g. read replica DB for long running queries and external DB's such as cassandra for processing. Your desired use case makes sense in the context of smaller volumes of classifications. Once you get into large volumes and table scans (indexes won't save us) then the API probably won't cut it.

@edpaget - I think you're right, it's analogous to inverse nested routes (that we're not using), e.g. `/projects/id/classifications`, `/users/id/classifications?project_id=X`, etc so we'd need a query param to specify the relationship context. Using an overloaded route with a context param for hypermedia discovery in the context of our serializers just made me weep just a little. Personally the nested routes make sense to me.

Finally the bug, we could just restrict actor classifications to projects they don't own / collaborate on? Not sure what the query profile would be like and perhaps a union would be faster. https://github.com/zooniverse/Panoptes/blob/a0e22a7068b14c3a0c32f063c09d82b8718379ac/app/models/classification.rb#L25

```ruby
when :show, :index
  actor_project_scope = Project.scope_for(:update, actor)
  actor_classifications = actor.classifications
                                              .where
                                              .not(id: actor_project_scope.pluck(&:id))
  query = joins(:project).merge(actor_project_scope)
    .union_all(joins(:user_group).merge(actor.user_groups))
    .union_all(actor_classifications)
```

**Comment by alianos-** [comment]
well not that I mind all that much so long as there is a way to retrieve classifications, but if the API is only to be used for retrieving smaller numbers (i.e. all the classifications for a single subject, or for a single user), then it should not be much of an issue to have slower queries.

**Comment by camallen** [comment]
We need to do some real world benchmarking with actual data to determine union vs selective query as proposed above, especially with large union sets with duplicates between them. I don't think we'll do this until we really need to.

Re slower queries, API nodes tied up serving long running processes (not even taking into account browser timeouts) can't serve new requests. Under high load you'll need more api nodes (processes / threads) or notice a slow down in the app. Again benchmarking real time queries will allow some decisions to be made about this. E.g. if classification queries take 1 minute / single user then you might decide this is tolerable. But what if all incoming processes were tied up, you'd have to wait 1 minute for your client app to start responding (probably not acceptable). It's really up to what you deem is acceptable. I know that we wont find that acceptable so we need to determine other ways to search our classification data.

**Comment by alianos-** [comment]
Agreed on that. But my point is that if the API is not to retrieve large volumes of classifications then the time will be negligible. How many classifications will a subject have, 10? 30? 50? Negligible numbers in an already rare operation. And then there is paging as well which can reduce big numbers to small numbers. Just my 2 cents.

PS. We aim for alpha testing at the end of the month so I can give you some numbers if you want.

**Comment by camallen** [comment]
Yeah it really depends on how much data you have in the table. Large row counts will be table scans (maybe index but depends on the query optimizer) so we still pay a query cost on this. Again hard numbers will direct this. Numbers are most welcome! Ideally at large row count volumes (which is where we plan to get too).

Paging using limit offset (by default what we use) slows down the further into a collection you go and there is a problem with large row counts, see https://github.com/zooniverse/Panoptes/issues/136.

**Comment by edpaget** [comment]
@camallen we could just create new routes for retrieving classifications that would scope them differently. A `/recents` for getting the current user's recently classified subjects; an analogous `/group_recents` for getting a user groups recent items; and use `/classifications` just for project owners to get the full classification object.

We probably don't want users retrieving their classifications with annotations anyway.

**Comment by camallen** [comment]
Yeah that sounds good,  nice one @edpaget.

**Comment by edpaget** [comment]
@brian-c does that sound okay to you, separating recently seen subjects from the actual classifications resource?

**Comment by brian-c** [comment]
That sounds fine. It'll be linked as `user.links.recents: {href: '/recents?user_id={users.id}'}` or something? Can a user still get their actual classifications for a subject?

**Comment by brian-c** [comment]
Never mind, just read your comment again.
