### ISSUE TITLE
Putting subjects links on a new subject_set: "Precondition failed"

### ISSUE THREAD

**Issue by brian-c** [zooniverse/Panoptes#534]
This is an old bug, but I don't think there was ever an issue for it.

As it exists now, the project-creation wizard thing calls with after creating a workflow and some subjects:

`PUT` `/api/subject_sets/1` `{"subject_sets":{"links":{"subjects":["1","2","3"]}}}`

It usually (but not always) fails with a `412 Precondition Failed` despite the usual `Last-Modified` as `If-Unmodified-Since` header passing thing.

I don't exactly remember, but I think @camallen said it was a race condition somewhere. Or maybe it was a rounding error.

**Comment by camallen** [comment]
Yeah - i thought there may have been a issue where a relation assignment (relation autosave via has_one) updating the original model via a :touch relation attribute on/after/around_save. I'm still not sold on this though.

**Comment by edpaget** [comment]
I'm working on this and some of the other precondition issues in one branch. So I can do a test case for it I just had a couple questions @brian-c 

* Do you just do it with Subject sets?
* Is it right after you create the subject set?
