### ISSUE TITLE
Where to set the required number of classifications

### ISSUE THREAD

**Issue by alianos-** [zooniverse/Panoptes#537]
Normally in crowdsourcing projects, a lot of people complete the same task on the same subject. e.g. we ask 50 people if a galaxy is flat or round.

I cannot find where to set the amount of people required to complete each workflow/task, should it not be a parameter of the workflow? Also, since I cannot get all the classifications related to a specific subject, how do I know when the subject will be complete?

**Comment by camallen** [comment]
It's being added here, https://github.com/zooniverse/Panoptes/pull/536. This should be ready today sometime.

Note: this work relies on background worker processes to update the classification counts asynchronously external to the api web requests. This setup relies on sidekiq + redis (as a persistent storage engine) between processes. Admin users can access a UI component at `http://panoptes-url/sidekiq`. Everything should just work and is configurable via the sidekiq.yml file (with defaults from sidekiq.yml.hudson).

**Comment by alianos-** [comment]
Thanks. So it is configurable as a server parameter? Not per subject (or at least per workflow). 

If that is the case you should give it a second thought as this is very restrictive. It is my experience that different tasks require different number, and my research shows that you can fluctuate the number per subject and increase accuracy. 

Also what will happen if midproject I decide the results I am getting are not good enough and I need to bump up the number. Will the old subjects restart?

**Comment by camallen** [comment]
It is an API configurable setting via the subject_set. I.e. each set of subjects for a workflow can have a set number of classifications before it retires.

Each workflow will have 1-N subject_sets, you can set the retirement for this workflow via the each subject_sets. This should be flexible enough for different tasks (workflows) across subjects. 

Re bumping, nope you would have to reactivate the subjects via `set_member_subjects` via http://docs.panoptes.apiary.io/#reference/setmembersubject/setmembersubject/edit-a-setmembersubject. Ideally this should be captured before launching a project. We're getting closer to ideas about this (see [here](https://github.com/zooniverse/Panoptes/issues/455)) but it'll be an iterative process. In my opinion you can run a beta / first attempt with a large retirement number to oversample and then do some analysis to optimize the retirement numbers.

**Comment by aliburchard** [comment]
Yep, I think one of the key goals of the beta is to figure out what the retirement rules should be. You put in a relatively small number of subjects with no retirement (or something crazy like 100 users), and then can do a bootstrapping analysis to see when accuracy levels off.

That being said, I suspect that it will absolutely be an iterative process. For example, say you need 5 people to get 90% accuracy and 10 people to get 95% accuracy. You might initially launch with a retirement rule of 10 people, but if you don't get enough volunteers, and it looks like it will take years to complete, you might decide to accept a lower level of accuracy and drop the retirement rules.
