### ISSUE TITLE
Filter owner name by display_name

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#544]
Linked to https://github.com/zooniverse/Panoptes-Front-End/pull/105

The owner filter should check against display_name: 
https://github.com/zooniverse/Panoptes/blob/634a981d7e517bcda271c8c975e205a8a9a09be2/app/controllers/concerns/filter_by_owner.rb#L10

**Comment by edpaget** [comment]
I just starting to work on this, but I wanted to double check that this was what we really wanted to do. The `display_name` field is not unique between users and groups. The `login` field of the user and the `name` field of the group are kept unique between both types of models. 

My impression was the `login` and `name` fields would be used for filtering projects and collections by group or user, and the `display_name` field was a way for the user to customize the way their name showed up in Talk or on their profile.

**Comment by brian-c** [comment]
It's so weird that we keep getting hung up on this.

`login` is really an implementation detail in the auth system. We shouldn't show this to anybody.

A user's and a project's `display_name` is the name people see. If it's not unique it should be.

I didn't think we were going Twitter-style "You can say you're whoever you want" names. I don't think we should. Nobody benefits from non-unique names.

**Comment by camallen** [comment]
So a user can't change their login but can change their display name. 

The identity group (created with a user) has the name field set to the downcased and underscored version of the login on create [here](https://github.com/zooniverse/Panoptes/blob/451a2735ef71e2c43a22ab5da3154c3bd153fe56/app/models/user.rb#L123) so may not be 100% consistent with the actual login name (devise downcases but doesn't replace whitespace).

What if we just synced the display_name to the identity group when a user updates it? A user currently has a uniq validation / index on the display_name field. I assume we could do a similary uniq case validation think on the group?

**Comment by edpaget** [comment]
We should just use the `login` and `name` fields, and just remove the `display_name` one (or visa versa). If we weren't going have a customizable field, why have the two separate fields? 

I though we were restricting character set of `login` and `name` to make it easier to use to implement @-mentioning of users in [Talk](https://github.com/zooniverse/Panoptes/issues/40#issuecomment-70112054), but then still allowing users to customize how their name appears because people do all sorts of characters in their usernames now. The display_names are still unique between all users, just not between users and groups. 

If we don't need to do that, or just only want 1 kind of name for a user, we should remove the fields we're not using.

**Comment by brian-c** [comment]
I would expose one unique `name` for a user/group. If it's easy, make it changeable, with a warning on the front end that any links to their projects will break. Lots of services don't let you change your name, people are okay with that. Restrict characters on new accounts. Old ones with spaces just won't work as @-mentions until they change them (if we allow that, if not they can contact us).

**Comment by edpaget** [comment]
Great I'll drop the display_name bit then. That's probably nicer for users anyway.

**Comment by camallen** [comment]
So does this mean my display name will be my login?

**Comment by edpaget** [comment]
Yes. I think so.

**Comment by chrislintott** [comment]
Sorry to open this one up again, but we need to retain the concept of a publishable name - a name that people are happy to have put on papers, publications and so on. It need not be displayed anywhere - indeed, it is explicitly not the display_name - but the option to include it is needed upon sign up. 

Chris

**Comment by edpaget** [comment]
@chrislintott that exists as `credited_name`
