### ISSUE TITLE
Is there a way to create a user using the API

### ISSUE THREAD

**Issue by alianos-** [zooniverse/Panoptes#546]
The API has no documentation for registering a new user. Is there a way to do that from my own interface?

**Comment by edpaget** [comment]
You can post to `/users/registrations` to create a user. You have to do the same CSRF stuff you do with login. OAuth applications using the API aren't allowed to create users, which is why its not documented and why you there isn't a normal route for it.

**Comment by bruggsy** [comment]
Two questions: 
1. Are OAuth applications still not allowed for this?
2. What is the format of the payload? Based off of the source, currently passing as 
<pre><code>payload = {'authenticity_token':token,
           'user':{
        'login':'aksldfjklasjdflkasjdflkasjdf',
        'email': 'junk@galskdjlkasdjflkasjdlkfjasdlkfjasdlkfj.com',
        'password': 'iamamazing!!',
        'credited_name':'test',
        'global_email_communication':False,
        'beta_email_communitcation':False,
        'project_email_communication':False,
        'project_id':292
	}
           }
</code></pre>

and submitting a request as <pre><code>requests.post("https://www.zooniverse.org/users",headers=header_get,data=json.dumps(payload)) </code></pre>
 Getting a 500 error returned.

**Comment by camallen** [comment]
your payload is invalid, remove the authenticity_token and change it to be like 
`{ 'users': {  data here... } }`

I'm pretty sure you'll also need to submit a CSRF token that you can harvest from response headers / HTML. 

If you request  `GET /users/sign_in` you will get the CSRF token for your session in the header [here](https://github.com/zooniverse/Panoptes/blob/255ae7c5a0c52916f98c778031b39af59b4bfdb8/app/controllers/sessions_controller.rb#L4) (you'll need cookies working on these req's to track your session).

HTML form you can do that like [here](https://github.com/mkosmala/PanoptesScripts/blob/f5ee484aa4b2bbb7bc7bdc5fab97c8806416875f/panoptesPythonAPI.py#L36), there are some python examples in that repo.

**Comment by bruggsy** [comment]
Thanks for the info: the proper form (with spelling typos fixed as well) is 
<code><pre>
payload = { 'user':{
        'login':'login_name',
        'email': 'example@email.com',
        'password': 'password',
        'credited_name':'test',
        'global_email_communication':False,
        'beta_email_communication':False,
        'project_email_communication':False,
        'project_id':292
        }
           }
</pre></code>

And a request post as before. No need either a CRSF token or an OAuth token in the header.

**Comment by marten** [comment]
Cleaning up some older issues. This one seems to be solved so I'm going to close it. Let me know if I'm wrong.
