### ISSUE TITLE
Expose ETag header

### ISSUE THREAD

**Issue by brian-c** [zooniverse/Panoptes#551]
Please add "ETag" to `Access-Control-Expose-Headers`.

Related to #550.

**Comment by camallen** [comment]
yeah i was just researching this. I assume we're replacing last-modified with etag? I can't see last-modified in the response headers

**Comment by brian-c** [comment]
That's fine. I've got the client set up to use either, depending on what's present.

**Comment by camallen** [comment]
OK - pretty sure we've switched from last modified to etag only now due to the problems with preconditions.
