### ISSUE TITLE
project_roles not available unless logged in

### ISSUE THREAD

**Issue by brian-c** [zooniverse/Panoptes#555]
Looks like this should have been fixed by d2b0300ab6c3c3bb1cfbef9e62f27d1eb3fc1d23, but I still get a 401 with "You must be logged in to access this resource."

**Comment by camallen** [comment]
The index route is working for me, `https://panoptes-staging.zooniverse.org/api/project_roles`. 

The show resource route still requires a login `https://panoptes-staging.zooniverse.org/api/project_roles/1`.

**Comment by edpaget** [comment]
Are there any differences between what the show and index routes return? We should just expose both without a login if there isn't.

**Comment by camallen** [comment]
I don't think so.

The original issue asked for project_roles for a project so i exposed the index route with the `project_id` filter param `/project_roles/?project_id=X`.
