### ISSUE TITLE
Per-project count of classifiers

### ISSUE THREAD

**Issue by brian-c** [zooniverse/Panoptes#567]
We'll need a way to get a count of how many users have classified on a project.

It'd be cool to get a count of unique users along with how many of those are not logged in ("guests"?).

**Comment by camallen** [comment]
Getting into the sloan project territory - #142.

I could get a pretty basic per project counter model up and running.
Counts:
- [ ] Classification
- [ ] Classifying user logged in
- [ ] Classifying users not logged in
