### ISSUE TITLE
Return subjects even when all seen / retired

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#571]
Linked to #565 

When cellect returns and empty set for a user(?) / workflow then return some data to keep the classification interface working.

1. When all subjects for a workflow have been seen by a user (i.e. cellect returns and empty set) select a random sample (preserving limit) and mark as `already_seen: true` on the response.

2. When all subjects have been retired for a project select a random sample (preserve limit) and mark as `retired: true`

**Comment by edpaget** [comment]
How do you want to do the random selection? Add an optional to support those kind of selections in Cellect?

**Comment by camallen** [comment]
Not 100% but for 1. i was thinking about testing the cellect return results (empty []) and then selecting into subjects randomly.

For 2. we could check the project completeness status and then select some subjects.

**Comment by edpaget** [comment]
Cool this sounds like it could be solved in conjunction with #424 then. If you get a chance can you share any code you had from when you were working on a postgres based selection scheme? I started a branch to work on that few months ago, but ran into problems figuring out how to do the random selection efficiently.

**Comment by camallen** [comment]
https://github.com/camallen/naive_subject_selector - Not sure how useful it will be as this was exploratory and I used a custom schema with SQL queries. 

The [schema](https://github.com/camallen/naive_subject_selector/blob/master/db/schema.rb) might be the best place to start to see how i was tracking USS for a subject using array indexes.

Then the scripts to concurrently classify / select, https://github.com/camallen/naive_subject_selector/tree/master/script

**Comment by camallen** [comment]
@edpaget are you working on this?

**Comment by edpaget** [comment]
I started on this trying to solve it with #424, but I couldn't find a satisfying solution to it. I was going to pick it up after finishing login stuff, but if you've got time definitely have a crack at it.

**Comment by camallen** [comment]
yeah - i'll start on it.

**Comment by camallen** [comment]
Hey - I didn't get a chance to start this. Can you work on this one and i'll finish the load testing scripts?

**Comment by edpaget** [comment]
Yup was working on it yesterday before the login kerfluffle.

On Tue, Mar 10, 2015 at 9:25 AM, Campbell Allen <notifications@github.com>
wrote:

> Hey - I didn't get a chance to start this. Can you work on this one and
> i'll finish the load testing scripts?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zooniverse/Panoptes/issues/571#issuecomment-78063628>.
>



-- 
Ed Paget

**Comment by camallen** [comment]
sweet

**Comment by brian-c** [comment]
Is this working? I've definitely classified all the subjects in my project, but I haven't seen any come through marked `already_seen`.

**Comment by edpaget** [comment]
No I think it was broken when I redid the Cellect to Queuing stuff.
