### ISSUE TITLE
JSON Parse Error

### ISSUE THREAD

**Issue by astopy** [zooniverse/Panoptes#572]
The following seems to be a result of #564. I'm not sure what JSON it's referring to...

    => Notice: server is listening on all interfaces (0.0.0.0). Consider using 127.0.0.1 (--binding option)
    => Ctrl-C to shutdown server
    log4j:WARN No appenders could be found for logger (org.apache.zookeeper.ZooKeeper).
    log4j:WARN Please initialize the log4j system properly.
    Exiting
    JSON::ParserError: A JSON text must at least contain two octets!
                              initialize at json/ext/Parser.java:175
                                     new at json/ext/Parser.java:151
                                   parse at /usr/local/lib/ruby/gems/shared/gems/json-1.8.2-java/lib/json/common.rb:155
                               send_ping at /usr/local/lib/ruby/gems/shared/gems/honeybadger-2.0.6/lib/honeybadger/config.rb:309
                                    ping at /usr/local/lib/ruby/gems/shared/gems/honeybadger-2.0.6/lib/honeybadger/config.rb:246
                                   start at /usr/local/lib/ruby/gems/shared/gems/honeybadger-2.0.6/lib/honeybadger/agent.rb:69
                                   start at /usr/local/lib/ruby/gems/shared/gems/honeybadger-2.0.6/lib/honeybadger.rb:30
                                 Railtie at /usr/local/lib/ruby/gems/shared/gems/honeybadger-2.0.6/lib/honeybadger/init/rails.rb:14
                           instance_exec at org/jruby/RubyBasicObject.java:1562
                                     run at /usr/local/lib/ruby/gems/shared/gems/railties-4.1.9/lib/rails/initializable.rb:30
                        run_initializers at /usr/local/lib/ruby/gems/shared/gems/railties-4.1.9/lib/rails/initializable.rb:55
                              tsort_each at /usr/local/lib/ruby/1.9/tsort.rb:150
       each_strongly_connected_component at /usr/local/lib/ruby/1.9/tsort.rb:183
    each_strongly_connected_component_from at /usr/local/lib/ruby/1.9/tsort.rb:219
       each_strongly_connected_component at /usr/local/lib/ruby/1.9/tsort.rb:182
                                    each at org/jruby/RubyArray.java:1613
       each_strongly_connected_component at /usr/local/lib/ruby/1.9/tsort.rb:180
                              tsort_each at /usr/local/lib/ruby/1.9/tsort.rb:148
                        run_initializers at /usr/local/lib/ruby/gems/shared/gems/railties-4.1.9/lib/rails/initializable.rb:54
                             initialize! at /usr/local/lib/ruby/gems/shared/gems/railties-4.1.9/lib/rails/application.rb:300
                                  (root) at /rails_app/config/environment.rb:5
                                 require at org/jruby/RubyKernel.java:1071
                                 require at /usr/local/lib/ruby/gems/shared/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247
                         load_dependency at /usr/local/lib/ruby/gems/shared/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:232
                                 require at /usr/local/lib/ruby/gems/shared/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247
                                  (root) at /rails_app/config.ru:1
                           instance_eval at org/jruby/RubyBasicObject.java:1533
                         new_from_string at /rails_app/config.ru:3
                              initialize at /usr/local/lib/ruby/gems/shared/gems/rack-1.5.2/lib/rack/builder.rb:55
                                    eval at org/jruby/RubyKernel.java:1107
                         new_from_string at /rails_app/config.ru:0
                         new_from_string at /usr/local/lib/ruby/gems/shared/gems/rack-1.5.2/lib/rack/builder.rb:49
                              parse_file at /usr/local/lib/ruby/gems/shared/gems/rack-1.5.2/lib/rack/builder.rb:40
       build_app_and_options_from_config at /usr/local/lib/ruby/gems/shared/gems/rack-1.5.2/lib/rack/server.rb:277
                                     app at /usr/local/lib/ruby/gems/shared/gems/rack-1.5.2/lib/rack/server.rb:199
                                     app at /usr/local/lib/ruby/gems/shared/gems/railties-4.1.9/lib/rails/commands/server.rb:50
                             wrapped_app at /usr/local/lib/ruby/gems/shared/gems/rack-1.5.2/lib/rack/server.rb:314
                                   start at /usr/local/lib/ruby/gems/shared/gems/rack-1.5.2/lib/rack/server.rb:250
                                   start at /usr/local/lib/ruby/gems/shared/gems/railties-4.1.9/lib/rails/commands/server.rb:69
                                     tap at org/jruby/RubyKernel.java:1886
                                  server at /usr/local/lib/ruby/gems/shared/gems/railties-4.1.9/lib/rails/commands/commands_tasks.rb:81
                                    call at org/jruby/RubyMethod.java:124
                                  server at /usr/local/lib/ruby/gems/shared/gems/railties-4.1.9/lib/rails/commands/commands_tasks.rb:76
                                  server at /usr/local/lib/ruby/gems/shared/gems/fig_rake-0.9.2/lib/fig_rake/rails.rb:34
                            run_command! at /usr/local/lib/ruby/gems/shared/gems/railties-4.1.9/lib/rails/commands/commands_tasks.rb:40
                                 require at org/jruby/RubyKernel.java:1071
                                  (root) at bin/rails:8
    D, [2015-02-23T15:06:33.018000 #6] DEBUG -- : Terminating 103 actors...

**Comment by camallen** [comment]
Which node is this? API for panoptes? Can it ping out?

**Comment by astopy** [comment]
It’s running on ec2-52-1-37-59.compute-1.amazonaws.com <http://ec2-52-1-37-59.compute-1.amazonaws.com/>

**Comment by camallen** [comment]
Seems to be a JRuby thing. It works under MRI on my dev docker image. I'm trying out a new version of JRuby 1.7.19.
