### ISSUE TITLE
fix jruby 1.7* compressed http responses 

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#575]
JRuby HTTP compressed responses have empty bodies, attempt to get the jruby 1.7 series patched as per:
https://github.com/jruby/jruby/issues/1216#issuecomment-71573125
https://github.com/jruby/jruby/commit/89ef3e9f691c2c5d6a56ab775225526b3b309206

**Comment by marten** [comment]
This seems irrelevant at the moment with JRuby 9k being released. Closing.
