### ISSUE TITLE
Project FAQ content

### ISSUE THREAD

**Issue by brian-c** [zooniverse/Panoptes#583]
Like #582 and #525, a project field for FAQ content.

**Comment by edpaget** [comment]
Do these need to be in place for Stargazing?

**Comment by brian-c** [comment]
A place for results and FAQ would be there ideally. I'm not sure we'll have education content. We can work around it if it's tough (I assumed it was just adding a field somewhere).

**Comment by edpaget** [comment]
Yeah I just want to the figure out the priority of these, it shouldn't be too hard to get added. Is this just a markdown field?

**Comment by brian-c** [comment]
Yessir. Thanks.
