### ISSUE TITLE
Can no longer filter for projects

### ISSUE THREAD

**Issue by brian-c** [zooniverse/Panoptes#584]
My project exists in the set returned by `/api/projects`, but no longer returns with a query: `/api/projects?owner=brian-testing&display_name=Supernovae`.

Maybe related to all the display_name stuff, @edpaget?

**Comment by camallen** [comment]
yeah i saw that too, i'm investigating now.

**Comment by edpaget** [comment]
I don't think we moved migrated login names to dipslay_name, maybe that record had a different name?

**Comment by edpaget** [comment]
Cool figured this one out. It is just a database migration issue and not a logic one. The "identity_group" used to only assign a name and not a display_name for that group. I'll migrate the data current in the staging db to be correct.
