### ISSUE TITLE
Firebase custom auth token

### ISSUE THREAD

**Issue by brian-c** [zooniverse/Panoptes#587]
https://www.firebase.com/docs/web/guide/login/custom.html

It'd be good to have this is sooner than later, since I basically have no idea what I'm doing.

Ideally, the user could get a `firebase_auth_token` property, but I can just make another authenticated request for one if that's easier.

@camallen has my Firebase secret, or just ask.

**Comment by camallen** [comment]
This is stargazing specific i might add.
