### ISSUE TITLE
Docker: Could not find form_data-0.1.0 in any of the sources

### ISSUE THREAD

**Issue by astopy** [zooniverse/Panoptes#601]
---> 785ff3048b3e
    Step 8 : RUN bundle install
    Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
    installing your bundle as root will break this application for all non-root
    users on this machine.
    Fetching source index from https://rubygems.org/
    Fetching git://github.com/edpaget/active_record_union.git
    Could not find form_data-0.1.0 in any of the sources

**Comment by camallen** [comment]
Cellect depends on this but they yanked the gem (so annoying). I'm working on a solution.

**Comment by camallen** [comment]
So they yanked the [form_data gem](https://rubygems.org/gems/form_data/versions/0.1.0) and renamed it to [HTTP-form_data](https://rubygems.org/gems/http-form_data). They [haven't updated](https://github.com/httprb/http.rb/blob/c4e62139668e08116c9d4744caa6daf0291ceb5b/CHANGES.md#unreleased) the HTTP gem to use the new dependency though (yay!) which cellect uses in the server and client.

We will have to bump cellect's dependency when the new HTTP-form_data dependency is included in HTTP gem.
