### ISSUE TITLE
Allow access from stargazing2015.zooniverse.org

### ISSUE THREAD

**Issue by brian-c** [zooniverse/Panoptes#605]
To panoptes.zooniverse.org

**Comment by camallen** [comment]
are you talking about cors? It should just work as they are sub-domains.

**Comment by brian-c** [comment]
I think it's still technically a different origin.

http://stargazing2015.zooniverse.org/ is deployed, give it a shot, maybe I'm doing something wrong.

**Comment by camallen** [comment]
I'm not getting any cors errors in the logs. In my understanding browsers will only stop Cors requests if they domain is different so our API routes are exposed to all origins (as they should be) but logons, etc should only be allowed via *.zooniverse.org domains for the time being.

The production DB is completely blank, no client app for logons, no data, nothing. I think we need to set some of this up and test again.

**Comment by camallen** [comment]
Are you seeing the Options preflight in your browser?

**Comment by brian-c** [comment]
It fails for auth-related stuff. If there's no app I'll just hold off.

The options preflight for a `projects` resource is fine, but it's still CORS.

**Comment by camallen** [comment]
I think this is related to the missing client app data, user accounts. Can this wait till we've sorted #483? Once that's finished you should be able to use your zoonivese account to login.

**Comment by brian-c** [comment]
Cool, that'll be fine. Thanks.
