### ISSUE TITLE
Language translation

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes#610]
Feel free to tag this with "enhancement", but just wondering if site language translation support is on the horizon or if it's a long way off.

**Comment by edpaget** [comment]
Translation support already exists for projects. I'm not sure about the state of translations in the main interface. A project owner can mark a user with the 'translator' tag and they can then create translations of project and worklfow content see in apiary: 

http://docs.panoptes.apiary.io/#reference/projectcontents
http://docs.panoptes.apiary.io/#reference/workflowcontents
