### ISSUE TITLE
Migrate Zooniverse User Table to Panoptes

### ISSUE THREAD

**Issue by edpaget** [zooniverse/Panoptes#615]
So the way I think would work best for handling this is having the Panoptes database replace Zooniverse Home as the authoritative database for usernames/passwords across the the zooniverse. 

Here's a list of things we'll need to do to handle the change:
* [x] Point Ouroboros's `ZooniverseUser` model at the Panoptes database
* [x] Connect the CAS Server to the Panoptes database for authenticating users
* [x] Write a script to migrate users into Panoptes
* [x] Write a script to migrate email subscriptions
* [x] Write a script to migrate classification counts

**Comment by mrniaboc** [comment]
For what it's worth, here are the things I use the Zoo Home DB for at the moment:

- Building email lists for newsletters
- Generating lists of names for author pages
- Updating/maintaining the publications page
- The Zooniverse advent calendar
- Updating Zoo Home (obvs)

**Comment by edpaget** [comment]
This is all good then. We just have to do the migration from ZooHome.

**Comment by vrooje** [comment]
Does this mean the migration hasn't taken place yet? Am thinking ahead to the possible World Bank/Nepal project on Panoptes, which we'd want to email out to the volunteers and let them use their logins.

**Comment by edpaget** [comment]
No we're planning to do it the week before the launch

**Comment by camallen** [comment]
@edpaget are you working on this?

**Comment by edpaget** [comment]
Yes I was planning to find a time next week were we could tolerate some downtime (or at least frozen account creation/password resets) while the migration happened'

**Comment by camallen** [comment]
So have you written the email / count scripts? Also what's the plan with migrating classification counts, where will they live in Panoptes?

**Comment by edpaget** [comment]
Nope. I only added them recently when I realized we'd need them. I'm going to add a classifications_count field the user project preferences model that users per-project classification counts will be saved at.

**Comment by camallen** [comment]
Mind if I take a crack at them? Just been delving into the subscription table to figure out why new project counts weren't showing up on zoo home.

**Comment by edpaget** [comment]
For sure. Do you want to add stuff to denormalize user-per-project classification counts too then?

**Comment by camallen** [comment]
Do you mean add a `classifications_count` and `panoptes_project` field in `UserProjectPreferences`?

**Comment by edpaget** [comment]
I don't know what the second field would be for...

**Comment by camallen** [comment]
Marker to say it's a legacy project outside of panoptes, prob should be inverted if that's the case. Perhaps just legacy|migrated_project?
