### ISSUE TITLE
Scheduler to run the aggregation code

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#621]
We need an scheduled app to launch @ggdhines aggregation code for stargazing. We need one of these long term for panoptes as well. 

I was thinking we could adopt a similar model to Ouroboros with the whenever gem and the jobs model to distribute the job across api nodes and ensure only 1 node runs the job at a time. BUT then i was thinking we probably want to have an internal API node(s) not serving requests via the public ELB that we can use for the aggregation / subject importer code as well. If this is just 1 API node then we could install cron and whenever gem to luanch jobs (possibly via sidekiq).

https://github.com/javan/whenever
https://github.com/mperham/sidekiq/wiki/Scheduled-Jobs#recurring-jobs

**Comment by camallen** [comment]
Alternatively we could just setup Greg's aggregation code to run on an Ec2 instance under docker that a cronjob fires up on a scheduled interval.

**Comment by ggdhines** [comment]
I don't understanding the one node /multi node issue - I'm happy with whatever. I had been planning on talking to Adam about setting up some docker stuff for Stargazing but if long term another approach would be better then we could do with it.

**Comment by camallen** [comment]
Lets just get gregs code running via docker on an ec2 instance that has a schedule installed on startup.

**Comment by edpaget** [comment]
Looks like this was taken care of via https://github.com/zooniverse/aggregation/commit/3c6c8bc5222890f2b5939a99ea198bcb5ecb5aa4
