### ISSUE TITLE
Monitor everything for stargazing

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#627]
If we aren't monitoring it how will we fix it? @astopy thoughts?

Setup monitoring for:
- [X] panotpes API
- [x] DB - how? VIA RDS monitoring
- [x] Cellect - new relic and manual instrumentation as a rack app?
- [x] Zookeeper - docker stats perhaps?
- [x] Redis - docker stats perhaps?
- [x] Kafka - docker stats perhaps? Should we just turn kafka off?

**Comment by edpaget** [comment]
Don't we get DB monitoring through RDS?

**Comment by camallen** [comment]
Probably i just added it in for comments.

**Comment by astopy** [comment]
At the least we can monitor most things with cloudwatch, at least to keep
track of CPU, etc. (it doesn't monitor memory out of the box, but
apparently there are ways to report memory usage to it).

**Comment by camallen** [comment]
@edpaget @astopy - should we just turn off kafka for stargazing? we're not using it yet.

**Comment by edpaget** [comment]
If it's not a big deal to keep it on I'd like to just to compute some stats
reading from it.

**Comment by camallen** [comment]
all good, let's just leave it on.

**Comment by camallen** [comment]
Monitor via cloudwatch and dockerstats if we need more visiblity.
