### ISSUE TITLE
Project resource's "owner" link's href missing leading slash

### ISSUE THREAD

**Issue by brian-c** [zooniverse/Panoptes#633]
`"owner": {"href": "users/3",...` should be `"owner": {"href": "/users/3",...`

Minor; super easy to work around this.

**Comment by edpaget** [comment]
Closed by #635

**Comment by brian-c** [comment]
This seems to have not stuck somehow.

**Comment by camallen** [comment]
Looks good to me in a project response from the staging api. can you confirm?

```json
"owner": {
  "id": "146",
  "type": "users",
  "href": "/users/146"
}
```

**Comment by brian-c** [comment]
GET /api/project_roles?project_id=76 from panoptes-staging.zooniverse.org

```json
"project_roles": [
  {
    "id": "83",
    "roles": [
      "owner"
    ],
    "links": {
      "user_group": "142",
      "project": "76",
      "owner": {
        "id": "146",
        "type": "users",
        "href": "users/146"
      }
    }
  }
],
```

You can see this request show up on the Science page.

Not a huge deal, we can hide the roles for this one.

**Comment by camallen** [comment]
Ah i was looking at projects. not project roles.

**Comment by edpaget** [comment]
That link should probably just be called user and the user_group id shouldn't be returned at all. I'll make that change separately, post-stargazing.
