### ISSUE TITLE
Sidekiq thread / db counts should match

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#637]
Looks like this was caused from 25 sidekiq threads and 16 db connections
https://app.honeybadger.io/fault/40595/23272b557f27a3d0bc3eaef0b5929f3b
https://github.com/mperham/sidekiq/issues/43

Need to keep these in sync so each sidekiq gets more DB connections (how many do we get with RDS size) OR we reduce to 16 to match puma threads and the DB connections.

**Comment by astopy** [comment]
You can query the connection limit in Postgres with “SHOW max_connections;” — the current limit is 296, so if we keep it at 16 we can have 18 sidekiq instances at the current RDS size.

**Comment by camallen** [comment]
So the API nodes and Sidekiq currently exist together

1 API node = 16 threads & 16 DB connections
1 Sidekiq Node = 25 threads & 16 DB connections (this issue is all about making these equal)
= 32 DB connections per Panoptes Staging EC2 Instance

Dont' forget that Cellect also connects to the panoptes DB as well (it is running MRI ruby with Puma so depending on the blocking IO / connection pooling it may get to it's max thread / db count). My benchmarking showed under heavy load we will probably want 500 concurrent users / cellect node, so 10 Cellect nodes for 5000 concurrent users, it all depends on user timing profiles though and this number may vary with thread counts up to 64 threads/connections not 16 per node.

1 Cellect Node = 16 DB connections max (via database.yml in panotpes)
10 X 16 = 160DB connections for the Cellect cluster (subject to variation on the thread counts we need to service the number of concurrent requests - there is a lot of HTTP in Cellect)

So let's leave 6 connections spare (perhaps we'll need to connect to the DB manually or via a launched ec2 instance)

So for stargazing with that RDS DB size we look like this:
290 - 160 = 130 / 32 = ~4 API nodes available to serve 5-10K concurrent users.

Based on some simple staging benchmarks last night where 100 concurrent users  (~300rpm) on the staging API node this will just not work, requests will take way too long to service and people will leave. So we'll need more API nodes and a larger DB with greater connection limits

These are probably pretty close, http://pagesofinterest.net/blog/2014/05/amazon-rds-instance-connection-limits/. We will need to pre-scale panoptes DB's and zoo home DB's as well.

We need to be able to handle that initial peak load so we need the API nodes to be more performant. I'm looking into N+1 queries today and other optimisation (via newrelic) and how we can bump puma threads / DB connections for the API nodes to almost saturate the CPU / Mem of the API nodes. 

Happy to discuss this further and i've got a load testing script to simulate non-logged in workflows if you want it.

**Comment by astopy** [comment]
OK, I’m going to scale staging up to a m3.large now so we can load test against that.

**Comment by camallen** [comment]
I've updated the sidekiq config to match the DB connection counts in production and staging (16 in both).
