### ISSUE TITLE
Panoptes when sellecting via cellect, fail over to PG?

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#650]
Should we detect when cellect is broken and fail over to PG selection? 

This error was due to no cellect server registered in ZK: https://app.honeybadger.io/fault/40595/d5dd2966d7d0e9c530776ccadd52a8f1

**Comment by edpaget** [comment]
You and @brian-c have a different fallback right?

**Comment by brian-c** [comment]
I'm checking if Firebase's `/$host/projects/$projectID/override-subject-selection/skip-cellect` is `true`

**Comment by camallen** [comment]
yeah - but this will 500 on the server, we could catch the error and gracefully send a message.

**Comment by edpaget** [comment]
Great I'll catch that then return 503 Service Unavailable unless another code makes more sense.

**Comment by camallen** [comment]
sounds fine.
