### ISSUE TITLE
making aggregations more efficient

### ISSUE THREAD

**Issue by ggdhines** [zooniverse/Panoptes#655]
I would like to have a time stamp associated with classification such that I can say "give me all the classifications since March 16th at noon". I don't care about the time being exactly right but I need it to be fixed. Cam was concerned about there being a chance that created_at and updated_at could be changed.

**Comment by camallen** [comment]
I think we can just add an index to the `created_at` field here so @ggdhines can retreive the set since he last processed.

**Comment by ggdhines** [comment]
Would be fine with me.

**Comment by camallen** [comment]
Ah - Greg is accessing the read replica DB directly from code via PG drivers so there are no changes to the API. 

Seems we cant' add an index to the read-replica only:
**Creation of Indexes on Read Replica 	Currently not supported**
http://aws.amazon.com/rds/faqs/

I assume indexes are propogated to the read-replicas from master, as it's a *read* replica.
