### ISSUE TITLE
how to deal with a change in the workflow

### ISSUE THREAD

**Issue by ggdhines** [zooniverse/Panoptes#667]
So Grant decided with Stargazing that he wanted to change what 0 and 1 meant -  the Stargazing annotations correspond to descending a binary tree and originally 1 meant going right and 0 left (based on the aggregation algorithm in the paper - sorry forget the name of the paper but the one we're using as the basis for the analysis in Stargazing). Grant changed it so that 1 now means going left and 0 right. 

As a result, we now have some classifications with incompatible annotations (just in the staging environment DB - so this should be just fine for production as long as Grant doesn't change his mind back). This brings up two issues (again we are fine for Stargazing, these are issues for the long term).

First, how do I know that the workflow has changed? Each workflow is identified as workflow_id= X where X is made up of two numbers, the over all workflow id and the version. So if I use the DB to retrieve all classifications with the condition "workflow_id=X" I should be specifying both the overall workflow id and the version number. So this should prevent me from ever getting incompatible annotations in the first place. In my code I am using the condition "WHERE workflow_id=X" - so something is not right. 

Second how do we deal with changed workflows? Ideally all of the changes should be made before a project is released to the public. But there could be exceptions to this and even changes during the "private" stage could be a bit of a problem - for example, if you changed the workflow half way through the private/beta stage and then want to do some analysis at the end to see if the project would work, you could wind up having some incompatible annotations which would mess up the analysis. 

In theory, you could use the json description of two workflows to figure out how to compare one to the other. I really don't like this approach - this could be very difficult to implement and really messy. I would prefer that workflow versions act kind of like inheritance. For example, if you have version A and then move to version B, any annotations done during version A should still make sense under version B. For example, with our tree example, you could add on extra nodes but once you choose 0=left, you are stuck with that choice. Not sure would we would impose this. Just something that needs to be discussed.

**Comment by brian-c** [comment]
Explanation for why tasks' values are identified by index in #450. My main argument against a per-value identifier is that there's no practical way to tell when a value has moved position or a typo has been corrected or the meaning of the answer has totally changed.

**Comment by ggdhines** [comment]
Sorry Brian - not sure why that is relevant.

**Comment by brian-c** [comment]
If each answer had an ID you wouldn't have to depend on its index. Just a note for future discussion.

**Comment by edpaget** [comment]
@ggdhines the way it handled right now is through the `workflow_version` field that's returned from the workflow resource. We keep track of all changes to workflows and workflow content strings (along with the user that made the changes), and then generate the version number as "version_of_tasks.version_of_strings_for_the_given_language". This number is included in the `metadata` section of a classification.

I really don't think we should worry to much about how to reconcile versions if they change. I think we're going to have to messaging in the UI to discourage people from making too many changes to their workflows after their project goes into production. If people ignore those, they pretty much do it at their own risk.

**Comment by ggdhines** [comment]
Thanks Brian and Ed - makes sense now.
I agree with telling people not to make too many changes - we just need to make sure that we tell people what the possible effects of the changes could be. Ideally would want it to be as robust as possible - wouldn't want someone to accidentally change something and then have a bunch of classifications we can't deal with.

**Comment by edpaget** [comment]
Yeah I think they'll have to click a big button that says, "I'm cool with breaking my project" in order to make changes.
