### ISSUE TITLE
Make sure we are capturing emails correctly

### ISSUE THREAD

**Issue by mrniaboc** [zooniverse/Panoptes#668]
We want to be capturing the email addresses of new users in a way that means they are opted-in to our newsletters, as we do just now.

**Comment by camallen** [comment]
On registration we should be setting the subscriptions in zoo home based on the variable supplied by the front-end (https://github.com/zooniverse/Panoptes-Front-End/issues/145).

**Comment by camallen** [comment]
I'm not working on this at the moment, worst case we'll merge the new signups into zoo home subscriptions after the event.

**Comment by camallen** [comment]
- [ ] Migrate new stargazing sign up email preferences back to zoo home

**Comment by camallen** [comment]
What are the plans for the production database and reboot of panoptes? I'm starting to think we should just leave all the infrastructure in place and migrate users into panoptes and shut down zoo home.

**Comment by edpaget** [comment]
I agree that we should go ahead and do the migration. #615 has a checklist that needs to be accomplished first.

**Comment by edpaget** [comment]
This is same as #615 and #748 unless there's something else that should be done
