### ISSUE TITLE
update_links is slow

### ISSUE THREAD

**Issue by edpaget** [zooniverse/Panoptes#672]
When updating a has_many it issues an UPDATE for every child model. That's not smart @edpaget.

**Comment by edpaget** [comment]
This is wrong. It's slow because we're creating a bunch of rows at once. I don't think there's a good way to handle this in default rails. We could use a gem to handle bulk inserts like https://github.com/zdennis/activerecord-import. Thoughts @camallen?

**Comment by camallen** [comment]
@edpaget i'm happy to use this bulk import gem. Looks like it may have jruby support but might not be tested.

**Comment by camallen** [comment]
@edpaget are you happy to see how this goes in the API nodes and we'll look to implement a solution in the next iteration? Also i think the Bug label could be enhancement too.

**Comment by edpaget** [comment]
Yeah I'm fine punting this until later. I'm not super sure how to solve it.
