### ISSUE TITLE
Index workflow version metadata

### ISSUE THREAD

**Issue by ggdhines** [zooniverse/Panoptes#680]
Long term request - could we maybe make workflow version a field in the classification table? That way it can be really easy to read in classifications from only the most recent version?

**Comment by camallen** [comment]
The classification workflow version is currently stored in the metadata object. We can either add an index to this field or extract it to it's own column completely.

I'm in favour of just indexing the metadata object path at the moment, here's a good read on json vs jsonb indexes for postgres: http://nandovieira.com/using-postgresql-and-jsonb-with-ruby-on-rails

**Comment by ggdhines** [comment]
According to this webpage (the first I found regarding the subject) http://schinckel.net/2014/05/25/querying-json-in-postgres/, I can use something like metadata @> '{"workflow_version": 3.2}' but that requires metadata to be of type jsonb which I don't know if it is different than just type json. (The current type of metadata). For right now, I'll just stick with downloading the metadata field as part of the query.

**Comment by camallen** [comment]
You should be able to do something like `SELECT * FROM classificaitons WHERE metadata->>'workflow_version' = '3.2';`

I don't think we can use the containment operator without a jsonb column type.

**Comment by edpaget** [comment]
After we finish with #703

**Comment by edpaget** [comment]
@camallen we can create this index now, but it would require changing our schema dump format to SQL. Is that cool with you?

**Comment by camallen** [comment]
I can't see anything on jsonb index and changing the schema dump format. I do like the ruby format (readablity).

**Comment by edpaget** [comment]
So I don't want to the GIN index the entire classifications metadata table. I'd like to create an expression index on `metadata->>'workflow_versions`, and you can only create that index with SQL in Rails. Otherwise we could make the required metadata fields normal columns on the models.

**Comment by camallen** [comment]
Sounds like the workflow_version is becoming a real model attribute, what do you think about extracting it to it's own column?

**Comment by edpaget** [comment]
I agree I think we should do that.
