### ISSUE TITLE
Logging in no longer works - what changed?

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes#684]
After two months of working on front-end stuff, I'm back to working on back-end stuff. My script to log in to Panoptes no longer works.

My script is here:
https://github.com/mkosmala/PanoptesScripts/blob/master/panoptesPythonAPI.py

Log-in dies in method 'get_bearer_token' in the try statement on line 46 with the message:
```
In get_bearer_token, stage 2:
The server couldn't fulfill the request.
Error code:  401
Error response body:  {"error":"You need to sign in or sign up before continuing."}
```

What's changed?

**Comment by edpaget** [comment]
@mkosmala stargazing live is happening today. Panoptes has been temporarily reconfigured to log in through the old Zooniverse Home database.

**Comment by mkosmala** [comment]
Oh right! Okay, I'll wait until next week. Thanks, @edpaget

**Comment by mkosmala** [comment]
@edpaget . It's next week. Can we put Panoptes back to its old configuration?!

**Comment by camallen** [comment]
@mkosmala - you should be able to log in with your zooniverse credentials. If you can log into zoo home then you can log into Panoptes.

Are you trying the staging site?

**Comment by edpaget** [comment]
@camallen I think @mkosmala has a login specifically for the project she was working on. I'm deploying staging without the Zoo-Home connection now.

**Comment by camallen** [comment]
No problems, we still need the production site up for another day at least.

**Comment by mkosmala** [comment]
@camallen I can log in via the frontend, but not with my script (that is from a couple months ago). See my first entry in this issue.

**Comment by edpaget** [comment]
Yup. It should just be a matter of having a zoo_home_#{environment} connection declared or not in the database.yml file.

**Comment by mkosmala** [comment]
Oh, and yes on the staging site.

**Comment by edpaget** [comment]
Also @mkosmala it really may be worth running Panoptes locally, to not be hampered by us monkeying around.

**Comment by mkosmala** [comment]
How hard is that to set up?

**Comment by edpaget** [comment]
You can run it on a PC see: https://github.com/zooniverse/Panoptes#installation 

It shouldn't be hard and we appreciate any feedback about getting a local environment configured.

**Comment by mkosmala** [comment]
Okay, I'll have a go. I'm sure I'll have more questions, though. :smiley:

**Comment by edpaget** [comment]
@mkosmala try logging into staging again it should be setup now.

**Comment by mkosmala** [comment]
Hmm. Nope. Same problem.

**Comment by edpaget** [comment]
What's the user name?

**Comment by mkosmala** [comment]
'mkosmala'

**Comment by edpaget** [comment]
Try either using the same password you use for that username on zooniverse.org (it looks like that password may have been imported) or reseting your password. https://panoptes-staging.zooniverse.org/users/password/new

**Comment by mkosmala** [comment]
Yes, it's a password issue. But something is weird.

I sign out and then reset my password. Resetting my password automatically logs me in. I then log out, but cannot log back in again -- I get a wrong password error. I did the whole thing twice just to make sure that's what is actually happening. All of this through the simple GUI.

**Comment by edpaget** [comment]
Just made a small change you trying logging in now?

**Comment by edpaget** [comment]
Also are you on our hipchat? It might be easier to handle support stuff like this and #698 through there. I'll send you an invite if you're not.

**Comment by mkosmala** [comment]
Nope. Not on hipchat.

**Comment by mkosmala** [comment]
Okay, I can now log in and out with the GUI just fine. 

But my script still dies the same way.
