### ISSUE TITLE
Slow retirement workers when talking to cellect

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#693]
`CellectClient.remove_subject` is taking 360ms in the retirement worker. This was after deploying #692 so there is a problem with http requests to cellect.

Cellect on the other hand doesn't report any problems, but may not be as it may not actually receive / service these requests to report on them.

**Comment by edpaget** [comment]
Do you think this is due to it working as a broadcast? Have to send a request to each Cellect client?

**Comment by camallen** [comment]
Yeah - that makes sense. It's not a big deal for me how long they take.

**Comment by edpaget** [comment]
Yeah there might not be a way for us to handle that. It could just take a while to communicate with each server. Maybe it we had real threading the requests could at least be concurrent.

**Comment by camallen** [comment]
We should revisit running sidekiq under jruby and removing that process from the Panoptes docker container. Linked to #695

**Comment by camallen** [comment]
Looks like we can use celluloid futures for concurrent http requests, https://github.com/httprb/http.rb/wiki/Parallel-requests-with-Celluloid%3A%3AIO

**Comment by camallen** [comment]
not an issue unless we revert to cellect.
