### ISSUE TITLE
Denormalize Recent Subjects to new table

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#696]
https://github.com/zooniverse/Panoptes/blob/master/app/controllers/concerns/recents.rb#L12

Looks like we are using it somewhere. Perhaps we can store these in a FIFO queue type data structure?

**Comment by edpaget** [comment]
I can't find any info about whether ANY works with GIST indexes, but using that could also be an option. 

Otherwise I agree with denormalizing recents maybe related to #292

**Comment by camallen** [comment]
@edpaget just wondering how you're going to achieve this? I had an idea about appending a per project set of recent classification IDs on the user project preferences model that gets built in the background like a FIFO queue. We could extract these ID's for a simple scope like `Classification.where(id: [recent_ids])`. Thoughts?

**Comment by edpaget** [comment]
I was literally just gong to make it its own table. That just related classification_id to a subject_id. You'd be able to filter it by project and workflow

**Comment by camallen** [comment]
So the recents will really just be a full history?

**Comment by edpaget** [comment]
I think it has to be. I'd like to find a way to handle this without having to use a full table, but I'm not sure how.

**Comment by camallen** [comment]
Sounds fine, i was thinking more along the lines of a [capped collection](http://docs.mongodb.org/manual/core/capped-collections/). 

Would this table be a more natural place to store a user's project : workflow classification counts?

**Comment by edpaget** [comment]
I don't think so, the table is just going to be primary_key, classification_id, subject_id
