### ISSUE TITLE
Installing Panoptes locally

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes#698]
The Panoptes installation instructions say that I need Docker and Fig. The Fig webpage says Fig is deprecated. If I install Docker, will Fig be installed automatically?

**Comment by edpaget** [comment]
No you have to install fig separately from Docker. We're working up updating to docker-compose the replacement for fig.

**Comment by mkosmala** [comment]
Ugh. There's no Windows version of Fig. So I just tried installing the Fig python package (which is the only other alternative). And PIP reports that it installed correctly, but a simple 'fig --version' fails. This stuff is always crap on PCs... <sigh>

**Comment by mkosmala** [comment]
Giving up installation on my PC. Will try to do it remotely on my linux work machine...

**Comment by camallen** [comment]
Yay windows!

Docker-compose is/should be backwards compatable with fig so you if you want you can try that before giving up on windows (but i won't blame you if you want to).

**Comment by mkosmala** [comment]
Okay, I've got Docker and Fig installed on Ubuntu. Now ~~stupid~~ naive question:
What Panoptes files do I need to download, and where should I put them, before I continue with the instructions under "Usage" in the Panoptes README?

**Comment by camallen** [comment]
Just follow the points under usage. Please let us know where they don't work / can be clearer.

**Comment by camallen** [comment]
Oh - you need to checkout / clone the source code then follow the usage instructions.

**Comment by mkosmala** [comment]
Right, thanks. Never done it on Ubuntu before, but that was super easy. 

OK. Now I'm at "Create and run the application containers by running fig up" but I don't have a Docker daemon running. Need to figure out how to do that. (And you might want to add that to the instructions.)

**Comment by mkosmala** [comment]
I'm stuck. Docker thinks its daemon is running in the standard location. 'fig up' can't find it.

**Comment by mkosmala** [comment]
Finished doing this with @edpaget on HipChat. Ed is updating the docs to reflect the issues I ran into in the process. But was ultimately successful.
