### ISSUE TITLE
Password Resets should update the hash_func column

### ISSUE THREAD

**Issue by edpaget** [zooniverse/Panoptes#700]
Reseting a password through the HTML page doesn't update the hash_func for a user to bcrypt. It should.

**Comment by edpaget** [comment]
That PR didn't seem to fix the issue in actuality

**Comment by camallen** [comment]
can we just run a rake task to update all users to bcrypt now that zoo home is removed?

**Comment by edpaget** [comment]
No a user has to login first before we can upgrade their hash to bcrypt since we don't know their plaintext password.

**Comment by camallen** [comment]
got it.

**Comment by edpaget** [comment]
This is working now
