### ISSUE TITLE
Update JSON columns to JSONB

### ISSUE THREAD

**Issue by edpaget** [zooniverse/Panoptes#703]
Add a requirement on Postgresql 9.4.

**Comment by camallen** [comment]
Perhaps we may need JSON types, do we need to preserve the ordering of json object keys say for workflow tasks?

http://www.postgresql.org/docs/9.4/static/datatype-json.html

> There are two JSON data types: json and jsonb. They accept almost identical sets of values as input. The major practical difference is one of efficiency. The json data type stores an exact copy of the input text, which processing functions must reparse on each execution; while jsonb data is stored in a decomposed binary format that makes it slightly slower to input due to added conversion overhead, but significantly faster to process, since no reparsing is needed. jsonb also supports indexing, which can be a significant advantage.

>Because the json type stores an exact copy of the input text, it will preserve semantically-insignificant white space between tokens, as well as the order of keys within JSON objects. Also, if a JSON object within the value contains the same key more than once, all the key/value pairs are kept. (The processing functions consider the last value as the operative one.) By contrast, jsonb does not preserve white space, does not preserve the order of object keys, and does not keep duplicate object keys. If duplicate keys are specified in the input, only the last value is kept.

**Comment by edpaget** [comment]
I don't think so. @brian-c do you know?

**Comment by brian-c** [comment]
Nope, JavaScript objects don't guarantee key order so I don't rely on it.

**Comment by camallen** [comment]
Jsob it is then.

**Comment by astopy** [comment]
There’s no quick way to upgrade the exiting RDS instances. We’ll need to create new ones and then dump/restore (we can’t even use snapshots apparently, so it’ll be a case of using pg_dump and pg_restrore). We’ll want to upgrade staging first and make sure everything’s OK before doing production.

How soon do we want this?

**Comment by camallen** [comment]
Not terribly pressing but something to we will want to do before relaunching panoptes.

**Comment by camallen** [comment]
@brian-c if we're using these json fields for storing text for display, will losing whitespace formatting make a difference?

>Because the json type stores an exact copy of the input text, it will preserve semantically-insignificant white space between tokens, as well as the order of keys within JSON objects. Also, if a JSON object within the value contains the same key more than once, all the key/value pairs are kept. (The processing functions consider the last value as the operative one.) By contrast, jsonb does not preserve white space, does not preserve the order of object keys, and does not keep duplicate object keys. If duplicate keys are specified in the input, only the last value is kept.

>In general, most applications should prefer to store JSON data as jsonb, unless there are quite specialized needs, such as legacy assumptions about ordering of object keys.

>PostgreSQL allows only one character set encoding per database. It is therefore not possible for the JSON types to conform rigidly to the JSON specification unless the database encoding is UTF8. Attempts to directly include characters that cannot be represented in the database encoding will fail; conversely, characters that can be represented in the database encoding but not in UTF8 will be allowed.

>RFC 7159 permits JSON strings to contain Unicode escape sequences denoted by \uXXXX. In the input function for the json type, Unicode escapes are allowed regardless of the database encoding, and are checked only for syntactic correctness (that is, that four hex digits follow \u). However, the input function for jsonb is stricter: it disallows Unicode escapes for non-ASCII characters (those above U+007F) unless the database encoding is UTF8. The jsonb type also rejects \u0000 (because that cannot be represented in PostgreSQL's text type), and it insists that any use of Unicode surrogate pairs to designate characters outside the Unicode Basic Multilingual Plane be correct. Valid Unicode escapes are converted to the equivalent ASCII or UTF8 character for storage; this includes folding surrogate pairs into a single character.

**Comment by brian-c** [comment]
I don't interpret that as losing whitespace within string values, just whitespace in the json formatting itself. Shouldn't be a problem.

**Comment by camallen** [comment]
You're right - json values don't lose whitespace, that just applies to the overall document structure itself. 

I thought this was a useful read on json indexes paying particular attention to the `jsonb_path_ops` index type: https://blog.compose.io/is-postgresql-your-next-json-database/.
