### ISSUE TITLE
Can I get the subjects in a subject set?

### ISSUE THREAD

**Issue by brian-c** [zooniverse/Panoptes#705]
There doesn't seem to be any way to list the subjects in a subject set. Could something like `/subjects?subject_set_id=316` work, or is this not available by design?

**Comment by camallen** [comment]
That won't work. There's no relation between subject and subject_set directly. What you need todo is use the `set_member_subject` resource and the `subject_set_id` link should get you the list of subjects (in the response) for the Subject members of the set, `/set_member_subjects?subject_set_id=316`

**Comment by edpaget** [comment]
You should also be able to do `/set_member_subjects?subject_set_id=456&inclue=subject` but its not working through curl for me, so I'll investigate later.

**Comment by edpaget** [comment]
I think this is related to #711.

**Comment by edpaget** [comment]
Hey this just failed because retrieving subjects in production is ludicrously slow, but I think you'll want to do `GET /set_member_subjects?subject_set=3&include=subject` to get subject in a subject set.
