### ISSUE TITLE
Cached resource responses

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#706]
Resources like project don't include the sum counters when determining the Etag cache key. These resources then return 304 when they should be returning 200 with the updated data representation.

I can think of `project`, @brian-c what other resources were exhibiting this behaviour?

**Comment by brian-c** [comment]
Projects are the only ones I ran into. If I see any more I'll report them here.

**Comment by edpaget** [comment]
Maybe we should just remove the Conditional Get support? I think this is going to be a thorny issue to sort out without the ability to generate ETags from the serializer.

**Comment by camallen** [comment]
Happy to remove this.

**Comment by edpaget** [comment]
Cool I'm going to remove this today then.

**Comment by MvGulik** [comment]
Aha, so that's why my "If-None-Match" GET's keep returning data instead of a 304.
Bummer.
