### ISSUE TITLE
How do I retrieve all Subjects for a Project?

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes#711]
I'm trying to troubleshoot my Subjects not being assigned to SubjectSets properly. But since the Subjects are not properly assigned at creation, I lose their IDs. Once I've lost their IDs, the only way to retrieve them from a Project is to specify a Workflow or a SubjectSet to which they belong (according to the documentation). But I have lots of 'floating' Subjects that are only assigned to a Project and not a SubjectSet or a Workflow. How do I find them?

**Comment by edpaget** [comment]
This is definitely a bug `GET /subjects?project_id=1` should work, but doesn't for me.

**Comment by edpaget** [comment]
Hmm doing `GET /subjects?project_id=210` on staging works for me know. I think there's still a query performance problem when the subject table is large as on production though.
