### ISSUE TITLE
Getting all projects ignores 'per_page'

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes#712]
I'm trying to get all my projects in one go and so have set per_page=50. But I still only get back 20 projects at a time.

**Comment by camallen** [comment]
https://github.com/RestPack/restpack_serializer#paging
You want `page_size` instead. Where did you get per_page, the docs?

**Comment by mkosmala** [comment]
Yes, the docs. Project Collection --> List All Projects.
FWIW, the docs are consistent in that it's "per_page" when requesting objects from all the Collection objects. Should it be "page_size" for all of them, instead?

Either way, mark this issue 'documentation'. (I don't have permission to.)
