### ISSUE TITLE
Need help linking SubjectSet to Workflow

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes#713]
According to the documentation, the recommended way to add a SubjectSet to a Workflow is "Update Subject Set Links" within Workflows. 

I am POSTing:
```
https://panoptes-staging.zooniverse.org/api/workflows/253/links/subject_set
```
with content
```
{
      "subject_sets": [ 490 ]
}
```
And I get back an error 422.

**Comment by camallen** [comment]
can you try and stringify the 490, `["490"]`

Also the body of the error response (422) will have details about the specific error.

**Comment by mkosmala** [comment]
Ok. I did stringify last week without success. I'll get more error info in a moment...

**Comment by mkosmala** [comment]
Okay, debugging info in detail:
```
URL: https://panoptes-staging.zooniverse.org/api/workflows/349/links/subject_set

Payload:
        {
            "subject_sets": [ "613" ]
        }

Status code: 422
"The change you wanted was rejected (422)
Maybe you tried to change something you didn't have access to."
```

Any chance that it's a plural thing? The URL uses "subject_set" (singular), but the payload uses "subject_sets" (plural).

**Comment by camallen** [comment]
I just checked, it's meant to be `/api/workflows/349/links/subject_sets`

**Comment by mkosmala** [comment]
Sweet. That's it. I guess, mark this issue "documentation" then.

**Comment by camallen** [comment]
If you have time, you can fork the repo and fix the docs when you find problems.

**Comment by camallen** [comment]
Similar to #506

**Comment by mkosmala** [comment]
Yup. "If I have time" being the key. I was supposed to have a project up for alpha testing last week...
