### ISSUE TITLE
Retirement rules not saved

### ISSUE THREAD

**Issue by brian-c** [zooniverse/Panoptes#715]
PUT `{"subject_sets":{"retirement":{"criteria":"classification_count","options":{"count":25}}}}` to /api/subject_sets/250 responds with a 200, but the `retirement` key is not present.

**Comment by camallen** [comment]
Yeah, I've seen this we need to add a `will_change` to the controller.

**Comment by edpaget** [comment]
I think it's just that it isn't included in the serializer.
