### ISSUE TITLE
Is UserGroup required to add collaborators?

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes#716]
I have a Project that I own. 
I want to add a collaborator. 
I am doing this:
```
POST: https://panoptes-staging.zooniverse.org/api/project_roles

Payload:
        {
            "project_roles": {
                "roles": ["collaborator"],
                "links": {
                    "project": "190",
                    "user": "6"
                }
            }
        }
```
And I get an Error 400 with message:
```
Validation failed: User group can't be blank
```
I'm a bit confused because I thought there were two ways to have multiple people running a project:
1) create a user-owned project and then add collaborators to the project (as I'm attempting to do); or
2) create a user group (with multiple people in it) and then create a project that is owned by that group.

It is true that my project does not have a user group. But I thought I didn't need one. Help?

**Comment by camallen** [comment]
Sounds like a bug. 

It's an internal implementation detail that you really don't have to worry about, we're all users have their own "Identity" Group for access control.

**Comment by edpaget** [comment]
@mkosmala it looks like User 6 was deleted at some point. You can't assign roles to a deleted user. The error response should be better though.

**Comment by mkosmala** [comment]
I got the same response on a newly created user, too.

**Comment by edpaget** [comment]
What's the id of the new user?

**Comment by mkosmala** [comment]
Shoot. I was working on that yesterday. Let me recreate it and I'll get you the relevant ID.

**Comment by mkosmala** [comment]
User is 9:
```
POST: https://panoptes-staging.zooniverse.org/api/project_roles

Payload: 
        {
            "project_roles": {
                "roles": ["collaborator"],
                "links": {
                    "project": "193",
                    "user": "9"
                }
            }
        }
```
Response:
```
Status code: 400
Response text: {"errors":[{"message":"Validation failed: User group can't be blank"}]}
```

**Comment by edpaget** [comment]
When I run `curl -H "Accept: application/vnd.api+json; version=1" https://panoptes-staging.zooniverse.org/api/users/9` I get `{"errors":[{"message":"Could not find user with id='9'"}]}` which means that use has probably also be deleted.

**Comment by mkosmala** [comment]
But I do a lookup by username to get the ID. So the user has to exist for it to return that ID.
And Cam said yesterday that 6 was his ID, which is why I used it first.

**Comment by mkosmala** [comment]
Oh wait, but I'm getting '9' for two different usernames. Let me double-check my code...

**Comment by edpaget** [comment]
Ah, that's on the production server, when you do a `GET https://panoptes.zooniverse.org/api/users/6` you get Cam's record back. The two servers no longer share a database since there's actual data on production now

**Comment by edpaget** [comment]
Cam is 27 on staging.

**Comment by mkosmala** [comment]
Ok, let me hardcode 27.

**Comment by mkosmala** [comment]
Okay, adding '27' as collaborator worked. And yep, '9' is deleted.

The problem is in my get_userid_from_username() method in my script. I wrote it a long time ago and maybe the API has changed. I do 
```
GET https://panoptes-staging.zooniverse.org/api/users?login=imaginaryfriend
```
But this returns all users. Is there a way for me to specify a user by name now?

**Comment by edpaget** [comment]
Use `display_name` instead of `login`.

I've also just added a Pull Request to give a "No User with id: 6 exists" error when it can't find the user or the user is disabled.

**Comment by mkosmala** [comment]
Perfect. Everything works. 

Related, if I keep adding the same user again and again as a collaborator, multiple (duplicate) Project Roles are created. Might want to do error checking to make sure the project-role-user combo doesn't already exist?
