### ISSUE TITLE
Values for ProjectRole - documentation needed

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes#717]
What are the valid values for ProjectRoles and what permissions do they each have?
I can see that I am an 'owner' and I see that 'collaborator' exists. Others?

**Comment by camallen** [comment]
It's in code [here](https://github.com/zooniverse/Panoptes/blob/2f676979e29786f0b9d9aec252cd5d4cec9c150c/app/models/project.rb#L28) but we need to add it to the docs.
