### ISSUE TITLE
Project attributes not set on Project creation (but ProjectContents attributes are)

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes#718]
When I create a project and specify the 'education_content','faq', 'introduction', 'results', and 'science_case', these continue to be listed as null when I retrieve the project itself. The 'display_name' and the 'description' get changed to the values I listed.

However, all these values ARE properly set in the associated ProjectContents. 

So why do these fields even exist at the Project level? Wouldn't it make more sense to just have a single 'introduction' (and 'education_content', 'faq', etc.), instead of one in the Project object (which isn't being updated) and one in the ProjectContents (which is being updated)?

**Comment by edpaget** [comment]
How are you retrieving the project resource? Are you doing a `GET /projects?display_name=SomeProject`? 

 If you're doing that this is expected behaviour, but it should probably be changed.

**Comment by mkosmala** [comment]
Yep, that's what I'm doing.

**Comment by edpaget** [comment]
Great, I'll a fix for this later today.
