### ISSUE TITLE
Workflow attributes - documentation needed

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes#719]
What do these Workflow attributes mean?
'grouped'
'pairwise'
'prioritized'

**Comment by camallen** [comment]
Is this a documentation question? I thought we went over this?

**Comment by mkosmala** [comment]
You mentioned these and pointed me to the code. But what exactly does 'prioritized' mean, for example? Does it just signal to the front-end that this workflow should be done first? 'Pairwise' means that two subjects will be returned at a time? And still not clear on 'grouped'...

**Comment by camallen** [comment]
Think of these terms in relations to your `subject_sets`. 

'Priority' uses a float value to create an ordered list. 
A 'Pairwise' set get two subjects at once.
A 'Grouped' allows a workflow to have many groups and be able to select from a specific group. If you have many subjec sets for a worklow and you don't set "Grouped" you will get a random selection of a subject set and thus subject.

**Comment by mkosmala** [comment]
Okay makes sense so far. What if I have three Workflows with ordered priority levels 1, 2, 3. Does that mean all the subjects in Workflow 1 need to be retired before moving to Workflow 2? Or is it more complicated than that?

**Comment by camallen** [comment]
Workflows don't have a priority value per se, just that they are order their subjects with priorities. You would want to ensure the end user (front end) selects the first workflow until all the data is done. Then cascade down the workflows. 

What's your actual use case for this? Just doing different tasks but you've prioritised certain task sets over others?

**Comment by mkosmala** [comment]
I don't need to use these. Just making sure I understood them, so that I know that I don't need to use them.

**Comment by camallen** [comment]
So our use case it to allocate sets of tasks to subjects. The front end doesn't have to select from a workflow you dont want it to but i'm not sure if we offer that by default. Just don't set it up if you don't want people using it.

**Comment by edpaget** [comment]
This is already documented [here](http://docs.panoptes.apiary.io/#reference/workflows)

```
Three parameters: grouped, prioritized, and pairwise configure how Cellect chooses subjects for classification. They are all false by default, which will give a random selection of subjects from all subject_sets that are part of a workflow. grouped enables selecting subjects from a specific subject set. prioritized ensures that users will see subjects in a predetermined order. pairwise will select two subjects at a time for classification.
```

Although I think beyond just API documentation, we need docs for how Panoptes as a system works.
