### ISSUE TITLE
Types should be predictable.

### ISSUE THREAD

**Issue by brian-c** [zooniverse/Panoptes#720]
A project's "introduction" value is `null` until it's manually defined. An introduction is a string. It should never be anything else. It should never be `null`.

This is an easy to fix in the client, but I don't think that's the right place to do it. Let me know if I'm wrong.

cc: zooniverse/Panoptes-Front-End#170

**Comment by camallen** [comment]
So you want missing data values to be represented as empty based on their types? I think strings kind of make sense here, `introduction: ""` but what about numbers `count: 0`?

**Comment by brian-c** [comment]
Yup, that'd be ideal.

**Comment by camallen** [comment]
I'm thinking with my logic hat that missing (null) is different to the blank / empty values of a type and there is a semantic difference here.

**Comment by camallen** [comment]
Specifically showing that a value isn't set by returning a null value versus an actual value that may be allowed to be blank based on type.

**Comment by brian-c** [comment]
The client generally doesn't care if a value has been set by a human or not. Maybe this is just a matter of defining sensible default values.

Does something like `classifications_count` not start at 0?

**Comment by camallen** [comment]
Our summary counters will most likely default to 0 (i'd have to double check) but some other integer fields may not be set. 

I'm just wondering if this is better dealt with client side on object initialisation (but you don't have type information) traded-off against a possible API use case that requires knowledge of set / unset field values. I'm leaning towards implementing what the client requires and setting blank values in the serialized responses, @edpaget thoughts?

**Comment by edpaget** [comment]
I'm fine with setting blank values if that's easier for brian to deal with.

**Comment by camallen** [comment]
Started to handle this in #921, https://github.com/camallen/Panoptes/commit/bfbf32dd912e081ae6b23a76248c4789814bd203

**Comment by edpaget** [comment]
I think that'll work fine for now, but we'll probably end up having to reflect on the database column or declare types in the serializer in order to handle the full spectrum of potentially null-able values.
