### ISSUE TITLE
Duplicate Subjset Sets for multiple Workflows

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes#721]
I have a Subject Set that I want to assign to two Workflows. In the docs for "Update subject set links" under "Workflow", it says it "Creates a copy of the subject set if it belongs do a different *project*." And under "Create a Workflow", it says "A SubjectSet that already belongs to another *workflow* will be duplicated when it is linked."

If I assign Subject Set A to Workflow X and then re-assign Subject Set A to Workflow Y, it removes the link between Subject Set A and Workflow X. (Rather than duplicating the Subject Set.) Is this expected behavior?

If I assign Subject Set A to Workflow X and then create Workflow Y with Subject Set A assigned, then the back-end will duplicate Subject Set A so that a copy is assigned to each of Workflow X and Workflow Y. Is that right? (I haven't tried this; it's my interpretation of the docs.)

Why duplicate Subject Sets on Workflow creation but not on assignment to Workflows?

I'm wondering because I am assigning Subject Sets to Workflows after they already exist. So I will have to manually duplicate my Subject Set to assign it to two Workflows. No big deal, but I want to make sure I'm understanding the API correctly.

**Comment by edpaget** [comment]
A SubjectSet can only be associated with a single Workflow because we need to keep track of classification counts on the model that associates subjects with subject_sets for handling retirement. 

@camallen there are a couple ways we could make this better:
1. Allow a subject set be assigned to multiple workflows, then have set_member_subjects track classifications counts across all workflows it's part of
2. Always duplicate a subject_set when it has workflow_id set

**Comment by mkosmala** [comment]
Yep, I get the one-to-many relationship and why it's needed. I think your first option to Cam could be messy. I'd keep the one-to-many relationship. Just wondering who (front-end, back-end) is responsible for duplicating subject sets when an author wants to use the same one for multiple workflows.

**Comment by edpaget** [comment]
The backend should be.

**Comment by edpaget** [comment]
It should be doing that for subject sets outside of the project, but I'm not sure if that's setup for subject sets already inside the project.

**Comment by mkosmala** [comment]
It doesn't currently duplicate from workflow to the next within a project.

**Comment by camallen** [comment]
Hmm - i can't find where we clone the subject sets if they belong to an external project. Also is there any support for re-linking the subjects from the cloned subject_set?

 @edpaget can you provide links to the code where these bits happen, it's probably just me being blind.

**Comment by edpaget** [comment]
It happens [here](https://github.com/zooniverse/Panoptes/blob/93cc0d1649694893f6c61ae3b34630604188694c/app/controllers/api/v1/projects_controller.rb#L65-L73).

**Comment by camallen** [comment]
How does that override on `projects` apply when updating a workflow? Normally it'll use the base method [here](https://github.com/zooniverse/Panoptes/blob/93cc0d1649694893f6c61ae3b34630604188694c/lib/json_api_controller/relation_manager.rb#L41) won't it?
