### ISSUE TITLE
Random cellection?

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes#728]
Are subjects randomly cellected right now? It seems like I always get the subjects in the same order...

**Comment by edpaget** [comment]
They should be.

**Comment by mkosmala** [comment]
Okay, I'll be more systematic to see if it's random or not and report back. (Hard to really know if it's random with just 5 subjects...)

**Comment by camallen** [comment]
The default page size is 10 set [here](https://github.com/zooniverse/Panoptes/blob/master/lib/subject_selector.rb#L50), you can override the param to be less than your subject set size to test the randomness of the selection.

**Comment by edpaget** [comment]
Seems like this ended up working?

**Comment by mkosmala** [comment]
Seems random. Although, the subjects are always presented in the same order, I think. So if I have 20 subjects and the first draw is A, B, D, E, ... and the second draw is A, B, C, G, ..., I'll always see A first, then B. So with 10 or fewer subjects (and the default page size) you always get the same subjects in the same order. I don't think there's anything wrong with this -- especially when subject sets are expected to be in the hundreds or thousands or more.

**Comment by edpaget** [comment]
Ah I think this is an issue of RestPack sorting by id. This actually will be a problem

**Comment by camallen** [comment]
Does RPS really sort by ID by default? https://github.com/RestPack/restpack_serializer#sorting

I think this is the find by ID [here](https://github.com/zooniverse/Panoptes/blob/ef069001492b964a82bbcd7a3f1700618f4436e4/lib/subject_selector.rb#L31) doesn't preserve the order of records in the ids array.
