### ISSUE TITLE
Do not duplicate user roles for a resource

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#730]
Linked to #716 - Ensure roles are appended to the array instead of creating new roles instances.

Add `user_group_id` uniqness validation scoped to `resource_id` and `resource_type` for `access_control_list` model.

**Comment by edpaget** [comment]
Should it append to the roles on a POST request where the ACL already exists or return an error?

**Comment by camallen** [comment]
Ha - Good question! I think we should just return an error saying the role already exists and they should update the role via PUT.

**Comment by edpaget** [comment]
This could be fixed along with #704
