### ISSUE TITLE
Fetching and displaying aggregation results

### ISSUE THREAD

**Issue by chrissnyder** [zooniverse/Panoptes#735]
I apologize if this has been discussed elsewhere.

Is there any docs (or just thought given) to how https://github.com/zooniverse/aggregation will feed results back to the front-end? I see the endpoints for aggregations, but don't know what a real response would look like. I'm thinking about this in the context of the built-in aggregation display tools for the front-end (basically Milkbot).

**Comment by aliburchard** [comment]
@chrissnyder I'm not aware of this discussion having happened elsewhere. 

My impression (@ggdhines please correct me if I'm wrong) is that we'll be able to return the raw classifications and some per-task aggregations by launch in some sort of a csv format, but I'm not aware of visualizations/display tools in the works for launch.

I'm also not sure if anything's been done on an interface for project builders to select/vary aggregation parameters or request the classifications ( @brian-c?). Maybe that would be a good starting point?

**Comment by ggdhines** [comment]
Yeah Brian and I have talked about the visualization tools needed for the long term but nothing will be ready for launch

**Comment by aliburchard** [comment]
@ggdhines visualization tools aside, what sort of aggregated data will be available for projects at launch?

**Comment by ggdhines** [comment]
@aliburchard - I will aim to have majority voting implemented. This will involve combining Cassandra, Spark and my code - I don't know how trivial that will be. I probably have a fair bit to learn. Ask me in a week and I can give you a better idea of things

**Comment by marten** [comment]
We've had aggregation resources in Panoptes for a while now. So long in fact that we're already phasing them out, since Caesar can be queried directly.
