### ISSUE TITLE
Un-linking a subject set from a workflow deletes the subject set

### ISSUE THREAD

**Issue by brian-c** [zooniverse/Panoptes#738]
After DELETE https://panoptes-staging.zooniverse.org/api/workflows/608/links/subject_sets/1142
GET https://panoptes-staging.zooniverse.org/api/subject_sets/1142 returns a 404.

**Comment by camallen** [comment]
Indeed - looks like we're deleting the linked resource [here](https://github.com/zooniverse/Panoptes/blob/ef069001492b964a82bbcd7a3f1700618f4436e4/lib/json_api_controller/relation_manager.rb#L27) instead of just removing the link.

**Comment by camallen** [comment]
Also reported here https://github.com/zooniverse/Panoptes-Front-End/issues/227

**Comment by edpaget** [comment]
Yup will patch that method too.
