### ISSUE TITLE
Support for Snapshot Serengeti and Chicago WW type interface

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes#742]
@camallen @aliburchard @chrislintott I've heard that a classifying interface like that used in Snapshot Serengeti and Chicago Wildlife Watch is in the works for Panoptes. What's the timeline look like that for that? I ask because I just got a query from someone who has camera trap images and wants to talk to me about how to do something like Snapshot Serengeti. I know Panoptes is expected to go public in May; will this include an animal-classifying interface? Or is that further down the line? (If so, how far?)

**Comment by edpaget** [comment]
Isn't it just a multiple-choice question with a bunch of possible answers?

**Comment by chrislintott** [comment]
Best guess (if you want to do more than just a decision tree), late summer. 

Chris

**Comment by mkosmala** [comment]
@chrislintott Thanks!
