### ISSUE TITLE
I'd really like free hand drawing as a tool. :) 

### ISSUE THREAD

**Issue by karenlmasters** [zooniverse/Panoptes#744]
Pretty please. I want to draw spiral arms onto galaxies. :)

**Comment by karenlmasters** [comment]
Although what I really want is a line which doesn't have to be straight… It *could* be done with the polygon.

**Comment by camallen** [comment]
Hi @karenlmasters, this panoptes repo is for the backend api. the drawing tools are part of the panoptes front end (https://github.com/zooniverse/Panoptes-Front-End/). I suggest you recreate this issue over there to get more focused opinions.  

Finally i think there may have even been something coded the other day for use similar uses in transcription projects.

**Comment by karenlmasters** [comment]
Awesome. Thanks for the clarification. :)

**Comment by camallen** [comment]
No problems.
