### ISSUE TITLE
User identities in data dumps

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes#745]
@chrislintott @mrniaboc Darren...? (What's his GitHub handle?): 
In the data dumps (and in derived data sets) that science teams get from running their projects, will user names be shown explicitly? Or will they be anonymized? I know user names have been shared with science teams historically, but is it a good thing to do for Panoptes, where anyone could create a project? 

(I don't care much either way. Just doing some fun fun fun IRB paperwork...)

**Comment by edpaget** [comment]
Usernames will not be included in datadump. You'll get some kind of hash of the user's id or ip address.
