### ISSUE TITLE
Keep JISCMail in sync

### ISSUE THREAD

**Issue by astopy** [zooniverse/Panoptes#748]
We need to propagate subscriptions/unsubscriptions to JISCMail by emailing their listserv.

**Comment by edpaget** [comment]
What do we need to do subscribe and unsubscribe people? What do the address and commands for that look like?

**Comment by astopy** [comment]
To subscribe users (the first if we’re not including their names):

quiet add zooniverse <email> * PW=<password>
quiet add zooniverse <email> <user’s name> PW=<password>

To unsubscribe users:

quiet del zooniverse <email> PW=<password>

These need to go to listserv@jiscmail.ac.uk <mailto:listserv@jiscmail.ac.uk> and they need to be addressed from a recognised email address (no-reply@zooniverse.org <mailto:no-reply@zooniverse.org> will work I think, or we can set up a new one specifically for this). The password is the admin password associated with whatever address we send the commands from.
