### ISSUE TITLE
Move /api/events.json when zoo home is rebuilt

### ISSUE THREAD

**Issue by astopy** [zooniverse/Panoptes#750]
Currently Ouroboros hits this under zooniverse.org.

**Comment by edpaget** [comment]
Why not just shut this down and generate the classification counts from the Kafka stream? I'm pretty sure that's what the end point is doing.

**Comment by camallen** [comment]
I think @edpaget is right it's generating subscription events and keeping counts by the look.

**Comment by edpaget** [comment]
So I think this endpoint is doing a little more and is used by other applications like Old Weather, so we're definitely going to need to figure out how to handle this. I'd really prefer not to add anything to panoptes to do though.

**Comment by camallen** [comment]
@edpaget can you elaborate on the functionality?
