### ISSUE TITLE
Out of band subject logged in user subject queue builds

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#752]
We need to ensure a timely way to build a queue for a user when requesting a subject for a workflow in-band. Previously we relied on the project's workflow resource being loaded ahead of time and paid the cost to build the queue then so there is data when they request subjects.

Since a user queue has never been built can we assume that they haven't seen **any** subjects for this workflow? If so we could just return the first X and then build the queue but taking into account what we've just sent them.

@edpaget Thoughts?

**Comment by edpaget** [comment]
We should just copy over the non-logged in user queue for a user if they don't have a queue and request a random subject.

**Comment by edpaget** [comment]
We should also generate the non-logged in queue when a Subject set is added to a workflow.

**Comment by camallen** [comment]
Copying the non-logged in user queue sounds good, as long as it already exists. I agree that it should be created whenever data is added to a worfklow.
