### ISSUE TITLE
How do I pass Markdown via JSON for non-trivial cases?

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes#753]
I am trying to create a project with actual content for the introduction, science case, etc. I can do so successfully when the content is a trivial short string. But if I want anything more complex, I get an error. Sending my request content through a JSON validator, I find that the JSON is invalid. For example:

```
{
    "projects": {
        "display_name": "Season Spotter Test9",
        "description": "description nothing here",
        "introduction": "trivial introduction",
        "science_case": "Overview
--------
Welcome to Season Spotter! We use modern technology to bring the ancient art of tracking the seasonal changes in plants, shrubs, and trees into the 21st century. We have mounted hundreds of cameras around North America (and beyond) to record the timing of leafing out, flowering, seed making, and leaf drop across many types of ecosystems. While we can use automated algorithms to identify some of the vegetation changes in the photographs, we need your eyes and brain to figure out the changes that are harder to spot. The timing of these seasonal changes tells us about how variation in weather and climate affect plant, shrub, and trees species. Ultimately, we hope to produce forecasts of the timing of these seasonal changes. These forecasts will be useful for a wide range of purposes, including in agriculture, conservation, tourism, and public health.",
        "education_content": "useful for education",
        "faq": "frequently asked questions",
        "result": "no results yet",
        "primary_language": "en-us",
        "private": false
    }
}
```
The JSON validator says it doesn't like that there is a newline after "Overview". But I need a newline in order to put that line of dashes that indicates the above line should be styled as a heading. 

Alternatively, it also doesn't like me beginning the first line with a hash (which the Markdown docs say I can do instead of the line of dashes to get a heading format).
```
{
     "projects": {
          "display_name": "Season Spotter Test8",
          "description": "# Keep an eye on changing seasons! 
## By spotting seasonal changes in forests, shrublands, and grasslands, you can help study the impacts of our changing climate.",
          "introduction": "introduction nothing here",
          "education_content": "useful for education",
          "faq": "frequently asked questions",
          "result": "no results yet",
          "primary_language": "en-us",
          "private": false
     }
}
```
Is there some trick to encoding Markdown in JSON so that I can pass it on to the Panoptes project creator?

**Comment by edpaget** [comment]
You'll need to escape your newlines. Use a '\n' where you'd insert a line break in your strings. 

Alternatively, Python will do this for you. Instead of building your JSON as a string and sending the string, build it as a Python Dict then call `json.dumps(your_dictionary)` and send the result of that. Python will take care of making sure everything is properly escaped legal JSON.

**Comment by mkosmala** [comment]
Thanks, Ed.
