### ISSUE TITLE
Including Incomplete Classifications in Data-Dump?

### ISSUE THREAD

**Issue by csalexwilliams** [zooniverse/Panoptes#756]
Hi there -- 
I've been tasked with porting the Ancient Lives application (http://www.ancientlives.org/) from Juggernaut to Panoptes. One of the primary functions of the current Ancient Lives application is the "Lightbox" view (http://www.ancientlives.org/lightbox/), a page similar to that of the standard Profile view that most Zooniverse projects have. Unlike the Profile view, clicking on a subject image in the Lightbox view allows a user to return to the classification view to continue making classifications on the respective subject. 

Earlier, @brian-c informed me that each classification is labeled as either 'incomplete' or 'complete and that users should be able to return to classifications that are incomplete. In Ancient Lives, the Lightbox allows users to return to any subject to keep providing classification information. In order to enable such functionality in Panoptes, it sounds like all user classifications would have to be indefinitely set to incomplete.

Two Questions:
1. Lightbox allows a user to load the classification with a specific subject. Is it possible to load a specific subject using Panoptes's API?

2. Brian's primary concern with setting all classifications to incomplete is that our data-dumps would be empty as only "complete" classifications are included in the data-dumps. Is there an option or parameter that can allow data dumps to include incomplete classifications? (I'm open to alternative approaches too.)

Thanks so much for your help and answers!

**Comment by camallen** [comment]
Hi @csalexwilliams, incomplete classification was built to save a users work temporarily so they can pick it up again (possibly across devices). Classifications with incomplete are not processed fully in the backend and don't contribute to subject retirement and counts, etc. 

What you could do is use a users' recent collection ([details here](https://github.com/zooniverse/Panoptes/blob/4a5318659165ab1450238b5b9bd595d1f2de25b1/app/controllers/concerns/recents.rb#L8)) to get a list of work that user has completed.

That way the user could still submit classifications for subjects but still find the subjects via the recents list. @edpaget i know we don't have a decent index solution for a classification's `subject_ids`. Any complaints about using this technique. Alternative solutions welcome.

**Comment by csalexwilliams** [comment]
@camallen Thanks so much for the quick reply.

I like your solution. I just want to clarify two things:
1. Using the Panoptes API, is it possible to query for a specific subject by some subject ID? Although this seems like it would be a necessity, I can't remember seeing this in the Zooniverse API for Ouroboros. 

2. Provided we're able to load in a subject that a user has classified, can you foresee any problems with Panoptes handling additional classifications? i.e. Overwriting past classifications. (Upon loading a new subject in Ancient Lives, I would need to check for and retrieve any pre-existing Classification objects for the subject / user combination and ensure that they're appended appropriately.)

**Comment by edpaget** [comment]
1) Yes you can always retrieve a subject by doing `GET /api/subjects/{subject_id}` You may run into problems at the moment doing that because I need to optimize the query that checks for a user's access rights.

2) No each classification is independent of others, as long as you do a `POST /api/classifications` you should be fine.

**Comment by edpaget** [comment]
Sorry, I think I misunderstood on point 2, do you want to append onto old classifications?

**Comment by csalexwilliams** [comment]
@edpaget Thanks for the reply. No worries on the query time. I'm still putting together a roadmap for the development of the application. Simply clarifying what is and is not possible with Panoptes. :-) 

In response to your last post - Yes. In the current live version of Ancient Lives, a user's past classifications for a subject (e.g. a letter classification) are loaded with the subject. After the loading has completed, the user has the option to add additional letter classifications to the subject or delete pre-existing classifications. 

Is Panoptes's Classification class similar to Ouroboros's (or the Zooniverse API's) Classification class? (I've already used the Classification class in the Zooniverse API.)

**Comment by camallen** [comment]
@csalexwilliams You can add new classifications for a subject, however you can only delete incomplete classifications a user has saved as per [here](https://github.com/zooniverse/Panoptes/blob/4a5318659165ab1450238b5b9bd595d1f2de25b1/app/models/classification.rb#L33). Normal classifications are write once, read many times. I guess the interface could allow multiple classifications for a subject fragment.  

Classification API is pretty similar, some differences. The code is [here](https://github.com/zooniverse/Panoptes/blob/master/app/controllers/api/v1/classifications_controller.rb#L5) where `resource_actions :default` resolves to [this](https://github.com/zooniverse/Panoptes/blob/4a5318659165ab1450238b5b9bd595d1f2de25b1/lib/json_api_controller.rb#L13)

**Comment by csalexwilliams** [comment]
@camallen Thanks for the link to the Classification API reference.

Based on the "write once, read many" principle, I assume it is not possible to toggle a user's prior classifications for a subject from "complete" to "incomplete" after a subject and the prior classifications have been retrieved and loaded in the Classification view? (One alternative could be copying the contents of the existing Classification object into a new Classification object?)

An even more important question: Can you delete a Classification via the Panoptes API? 

If so, I think the smoothest approach might be:
1. Retrieve existing Classification that's stored in Panoptes and copy contents to new Classification(or toggle "Incomplete" on retrieved Classification).
2. Delete the Classification that's stored in Panoptes.
3. User adds to / deletes from / modifies Classification.
4. Store new Classification object in Panoptes.

This ensures that we'll have only a user can have only one classification for a subject. Thoughts?

As always, thanks for working with me on figuring this out.

**Comment by csalexwilliams** [comment]
Oops -- I realized I got ahead of myself.
Let's just focus on the toggling of a Classification from "Complete" to "Incomplete". Is that possible?

**Comment by camallen** [comment]
No you won't be able to delete a classification. You can only update / delete a classification if it's incomplete. 

Why not just have multiple classifications per subjects, i.e. I come along and transcribe fragment "A", then do fragment "B". Later on I come back and see i've submitted A & B bu I'm not sure about the intermediates so I skip to "Y", "Z" and submit them. there's no problem submitting multiple "partial" classifications for the whole subject. In fact our new beta transcription projects are using multiple classifications (line fragments) per subject and just caching them locally before submitting en masse.

It will change the way your have to do some aggregation work. I.e. you'll have to reduce the set of all classifications for a subject, possibly using classification metadata (pixel coords for the fragment) to combine them as per their location on the text. @rogerhutchings is using a similar technique in the [transcribe](https://github.com/zooniverse/transcribe/) project to transcribe lines of text.

**Comment by camallen** [comment]
Just to be clear, you won't be able to go from `complete` to `incomplete`, the update is one way only.

**Comment by csalexwilliams** [comment]
@camallen Thanks. That's what I needed to hear. Identifying duplicate information is already implemented as a safety measure in our pipeline, so no worries there. 

Thanks again for helping me out!
