### ISSUE TITLE
handle stale resource errors

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#758]
https://app.honeybadger.io/projects/40595/faults/12475380

don't 500 but return a 409 and an useful error message.

**Comment by edpaget** [comment]
That shouldn't cause a 500 since it's happening in a worker. I wonder what state ended up being stale in that model.

**Comment by edpaget** [comment]
This should already be handled in the request/response cycle too https://github.com/zooniverse/Panoptes/blob/master/spec/requests/v1/api_locking_spec.rb

**Comment by camallen** [comment]
my bad - should have read the stack trace.
