### ISSUE TITLE
Can't filter subject_sets by workflow_id

### ISSUE THREAD

**Issue by brian-c** [zooniverse/Panoptes#764]
`/subject_sets?workflow_id=898` seems to returns a set of 106 (total) workflows.

**Comment by edpaget** [comment]
Similarly needs to be able to filter subjects by collection id.

**Comment by camallen** [comment]
So I had a quick look and this filtering looks constrained by RestpackSerializer [here](https://github.com/RestPack/restpack_serializer/blob/b1f3cb62de1af8cca11870aec4fbac5da6d901c1/lib/restpack_serializer/serializable/filterable.rb#L18). I think we'd need to extend RP (again) to handle the `has_and_belongs_to_many` association filtering, doable just not a quick fix.

**Comment by edpaget** [comment]
We can handle it similarly to this https://github.com/zooniverse/Panoptes/blob/master/app/controllers/concerns/filter_by_owner.rb so we don't have to dig around in RP.
