### ISSUE TITLE
How can we fetch all a user's projects?

### ISSUE THREAD

**Issue by brian-c** [zooniverse/Panoptes#765]
`/projects?owner=brian-testing` comes up blank, I'd guess because `/projects` excludes unapproved and beta projects. But `/projects?owner=brian-testing&approved=false` also comes back blank (bug?). And since I actually want any projects the user owns regardless of state, can I maybe query something like `?approved=*&beta=*`?

**Comment by edpaget** [comment]
I think the false/true issue is because approved is null for everything in the database before I made that change. We'll need to migrate existing projects to approved false. 

@camallen, @brian-c I'd like your thoughts, but I think if you're listing a project by owner name and/or display name it should just not scope to approved or beta at all.

**Comment by camallen** [comment]
I think the `/projects` index route should return only the approved projects. 
`/projects?beta=true` should return the approved beta projects. 
Index routes filtering on owner should return all the projects for that specific user and any filtering the use wants to add should be applied, e.g. `/projects?owner=brian-testing&beta=true&approved=false` should return that users unapproved beta projects.

**Comment by brian-c** [comment]
Wouldn't it make more sense for `/projects` to return all projects, beta, unapproved, whatever, and then use query params to filter that list down to what's useful in each situation?

Main projects index would get `/projects?approved=true&beta=false`

Beta index would get `/projects?approved=true&beta=true`

Lab index would get `/projects?owner=brian-testing` because approval/beta-ness doesn't matter.

**Comment by camallen** [comment]
Should `approved` and `beta` default to false when creating a project if they haven't been set?

https://github.com/zooniverse/Panoptes/blob/177d735a31406db18a854712cc60550fc6d0fecc/db/schema.rb#L185

**Comment by brian-c** [comment]
Yeah, any reason everything shouldn't have a sensible default value?

**Comment by camallen** [comment]
No - just wondering if yesterday's PR had an explicit reason for leaving without a default.

**Comment by mkosmala** [comment]
Question about betas. So approved=true and beta=true means the project is on a Zooniverse-approved list of beta projects. What does approved=false and beta=true mean? (if anything)

**Comment by camallen** [comment]
The user has set their project to `beta` but it hasn't been approved by the zooniverse.

**Comment by mkosmala** [comment]
So if a user sets a project to beta=true, then it ends up in a queue of projects that Zooniverse should look at. But until Zooniverse looks at it and sets approve=true, then the project doesn't show up anywhere special. Can it collect classifications with beta=true and approved=false?

**Comment by camallen** [comment]
@mkosmala yeah that's the plan, not sure exactly how this will play out in the UX. 

Classifications will be collected at all times. We version the workflow changes and link this version number to the classification to understand the what the questions (tasks) were performed at classification time. 

#766 adds a project live field to specify that the project is running. It'll promp the UX to warn the user that it's live and you shouldn't change it. Our aim is to use the workflow version numbers to determine what data is included in the aggregation engine. 

If you're taking a dump of the raw data then this information would be included and it's up to the science team member to understand the state of workflows they wan't to include in analysis.

**Comment by brian-c** [comment]
Another reason `/projects` should return an unfiltered list and query params would filter it: `#/projects/owner_name/project_name` needs to be able to query by owner and project name, regardless of private/beta/approved state.

**Comment by edpaget** [comment]
@brian-c I wanted it to just default to what would on the project page, but I will change it so it doesn't filter by approved or beta by default and instead just lets you set those manually.
