### ISSUE TITLE
reset password form and emails

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#768]
- [ ] Update the routes from `/users/password/new` to something like `/passwords/reset`.
- [ ] Update the email content to use the existing copy and ensure the links use the correctly URL's [here](https://github.com/zooniverse/Panoptes/blob/177d735a31406db18a854712cc60550fc6d0fecc/config/environments/production.rb#L69).
- [ ] Skin the form better perhaps like the original

![image](https://cloud.githubusercontent.com/assets/295329/7412715/8198a8b6-ef3d-11e4-8a15-af8bbb052492.png)

**Comment by edpaget** [comment]
I'm pretty sure we support reseting through a JSON call. Shouldn't this just live in the front end?

**Comment by camallen** [comment]
Yeah probably. Depending on the Nginx config HTML requests to the api server can get to those forms. If users can we should probably skin them properly.

**Comment by edpaget** [comment]
This is done now
