### ISSUE TITLE
Can't create project with approved=false

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes#769]
When I try to create a project with "approved": false, I get a 422 error message saying:
```Only Admins may Approve Projects```

**Comment by mkosmala** [comment]
I'm sure this is related to #765

**Comment by camallen** [comment]
Only admin's can modify this field. I'll add a default value to those fields so you won't have to set them. PR to follow.

**Comment by mkosmala** [comment]
Sounds good.
