### ISSUE TITLE
Hook up facebook and GPlus logins via the front end

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#770]
Finish off this implementation, Facebook hooks up ok. Gplus isn't working:

![image](https://cloud.githubusercontent.com/assets/295329/7413240/d8212574-ef41-11e4-9f9d-2ba03a84f840.png)

**Comment by edpaget** [comment]
Hmm this was working at one point. I wonder if google changed stuff?

**Comment by edpaget** [comment]
Re #322 we're not going to have 3rd party logins for the soft launch.

**Comment by zwolf** [comment]
This has been implemented.
