### ISSUE TITLE
Hard limits for normal users?

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#774]
Should we enforce limiting the number of projects a normal user can spin up? Also how many subjects and subject sets can they create for a project?

**Comment by mkosmala** [comment]
:notes: la la la la la :notes:

**Comment by camallen** [comment]
@mkosmala you are not a "normal" user and I mean that in a good way.

**Comment by vrooje** [comment]
I feel like this is a good idea but perhaps the limit should be relatively high, as new but motivated users will be testing stuff a lot. Maybe not as much as @mkosmala :)

**Comment by edpaget** [comment]
Yeah I think we could just restrict the total amount of subject they can upload. The real cost is storing subjects for classification. Having a bunch of projects isn't a lot to deal with.

**Comment by chrislintott** [comment]
Agreed with @edpaget. Suggest for now that anyone wanting to upload more than, say, 10000 subjects should talk to us.

**Comment by edpaget** [comment]
We can keep track of who uploaded subjects and have a a subject limit field and a subject count field on their user model, and just return `403 Forbidden` when they exceed their subject limit. Would that be fine for the launch?

**Comment by camallen** [comment]
@aliburchard what are your thoughts on a reasonable number of subjects to run a beta and how many the subject uploader can handle in the first instance. 

We can make this limit number configurable without changing code too.

**Comment by aliburchard** [comment]
I have mixed feelings about a "reasonable number." First, I think that with the current subject uploader, where you have to manually select all the subjects, just won't work for something like 10,000 images.  At least from the user's perspective  -- I would worry about accidentally missing a file when I selected them to upload. (And without being able to see a list of the files that were actually uploaded, I'd have no way of figuring out which I'd missed.)

I think the limits depend a bit on what we're expecting in terms of private projects vs. zoo-approved projects. A small limit, say, 1,000 images, would be plenty for folks to build a project, test it, revise it, run a beta, and then request launch -- if we approve, then we can up the limit number. 

I realize we want to decrease the number of projects we want to manually review, but we'll have to review for beta and launch, and I suspect that projects progressing to zoo home will have more images than can be processed through the current uploader anyway.

**Comment by twhyntie** [comment]
@camallen @aliburchard I agree - 1,000 subjects per project sounds good. I'd upload in subject sets of 100 and now multiple selection in the File Dialog is working I'd just hit Ctrl-A and hope :-)

That's also a maximum of 10 projects per user, which again sounds reasonable for people starting out.

**Comment by vrooje** [comment]
I haven't yet uploaded more than about 650 at a time but that worked fine -
I can try 1,000 next time. I think that's a good limit for a beta
especially given typical beta response rates.
>
>
Q: How does someone move out of the "normal user" category?

**Comment by camallen** [comment]
> Q: How does someone move out of the "normal user" category?

Writing your own code to interact with the API is one way, i'm sure there are others.

**Comment by mkosmala** [comment]
I'm in agreement. We're using between 300 and 400 subjects for our beta. 
1,000 seems reasonable for images. But what about sound clips or videos (or other)? Should those have a different limit?

**Comment by edpaget** [comment]
I think ideally we'd eventually change the limit to be storage size based. So you could have xGB of subjects before needing to talk to us or something, but we also don't really support video or audio at the moment.
