### ISSUE TITLE
Can you append to an existing subject set? 

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes#777]
We have a lot of use-cases where folks are going to want to add subjects into an existing project. From the project-builder's perspective, much of the time these would be considered part of the same "subject set." For example, let's say they collect field data every day, and upload it daily.

Can people update or append to existing subject sets? Or are these considered "new subject sets"? 

@camallen @edpaget

**Comment by camallen** [comment]
The API supports appending subjects to a subject set. You could also can create new subject sets and add subjects.

Have you tried appending via the front end? I'm pretty certain adding new data to an existing subject set just appends.

**Comment by vrooje** [comment]
So far that seems to be how it's working on the Nepal project I'm creating
- I'm uploading ~2K subjects in batches of about 400 and the subject counts
seem correct after each batch (though I am not sure I know how to check for
duplicates etc).

**Comment by camallen** [comment]
Total counts at the end should tell you if data got duplicated. Failing that we'd have to check the subject metadata image paths to ensure they are uniq / match what you uploaded.

**Comment by aliburchard** [comment]
Aha, got it. I didn't realize from the front-end instructions I could **add** to an existing subject set. I'll have a go.

@vrooje are you uploading a new manifest as well? or did you upload a single manifest first and are slowly dragging and dropping new batches of files into the drop area? (I've got some weird disconnects displaying on the drop area that I'll raise in a separate issue.)

@camallen do we have any plans to implement those sorts of checks? (Or can we make plans to allow those sorts of checks?)

**Comment by camallen** [comment]
@aliburchard can you please open an issue about this?
