### ISSUE TITLE
subject uploader doesn't match uploaded files

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes#778]
![screen shot 2015-05-01 at 11 47 19](https://cloud.githubusercontent.com/assets/6217406/7429364/f1a84a02-eff7-11e4-9401-d616c2fc4e8b.png)

The drop area says I've got 0 manifests and 2 files selected, though note that nothing is actively selected for upload. Also, I actually have uploaded 1 manifest and 4 files at this point. Not sure if this is @camallen or @brian-c

**Comment by camallen** [comment]
this is a front end issue with the subject uploader. can you please move to the front end repo?
