### ISSUE TITLE
RetirementWorker stale object errors

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#782]
Multiple retirement workers are being kicked off i think [here](https://github.com/zooniverse/Panoptes/blob/4a5318659165ab1450238b5b9bd595d1f2de25b1/app/workers/classification_count_worker.rb#L8) and are touching the `set_member_subejct` objects all at once. I think we should just put an incrementing delay on each one to offset their execution [ala here](https://github.com/mperham/sidekiq/wiki/Delayed-extensions#activerecord).

![stale_worker_failure](https://cloud.githubusercontent.com/assets/295329/7431528/4be8d878-f017-11e4-8d53-c7cf53f64317.jpg)

**Comment by edpaget** [comment]
I think we can make the retirement update ignore locks. If we make the update statement something like `UPDATE set_member_subjects SET retired_workflows = array_append(set_member_subjects.retired_workflows, #{id to retire} WHERE set_member_subjects.id = #{whatever}` that would work without needing to lock the workflow.
