### ISSUE TITLE
Seeing the same subjects multiple times while classifying

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes#790]
I (and several other users) have been seeing duplicate subjects popping up again and again. Initially I thought this was just because I was refreshing my browser, but it has persisted even when I'm not.

Typically I will see ~10 different subjects, and the 11th subject is actually the first subject again, and I classify the whole sequence again up to 20, when I may start a new set of 10 or I may start seeing a third round. (I don't think it's always 10, but I'm not sure.) The net effect is that getting through a subject set takes twice the effort it should... so this is a pretty big deal.

I last duplicated this bug about 15 minutes ago.

**Comment by edpaget** [comment]
This is actually related to #787
