### ISSUE TITLE
csv export needs to include owner-/collaborator-supplied metadata

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes#791]
csv exports are working and I'm getting hourly updates right now, which is great.

However, the export doesn't contain any information that allows me to link the subject ids from Panoptes back to the information I originally uploaded in the manifest, such as the image name(s), so I don't know what classifications go to which subject in a meaningful way for me to make sense of my results.

**Comment by camallen** [comment]
closed by #792
