### ISSUE TITLE
Can't create multiple unnamed projects

### ISSUE THREAD

**Issue by chrislintott** [zooniverse/Panoptes#797]
If I have a project which I don't bother to rename, then I can't create a new project. Can we change this?

**Comment by edpaget** [comment]
I can't duplicate this Chris. When I create a project in the Lab, it gives it a default name like "Untitled project 2015-05-04T20:43:02.001Z" if I create another project the time stamp at the end is updated so the project has a different name and can save. Are you deleting the default name and leaving it empty or was this a recent change @brian-c?

**Comment by brian-c** [comment]
Yeah, this workaround has been in for a while. @chrislintott what URL are you on? Might be an old version deployed somewhere.

**Comment by camallen** [comment]
I can't reproduce, pretty sure this is fixed.
