### ISSUE TITLE
Beta test imminent

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes#807]
@mrniaboc @camallen @edpaget @brian-c @aliburchard @chrislintott 
We're about ready to run a beta test of Season Spotter. But I know you all are going full out to get Panoptes back and front ends finished. We would need stable back and front ends for our beta test. Is that doable?

**Comment by mkosmala** [comment]
Bueller?... Bueller?...

**Comment by camallen** [comment]
@mkosmala How long is this beta going to run for? Also which project (of your many) is going to beta?

**Comment by mkosmala** [comment]
@camallen A week? Two? @mrniaboc, you have a lot more experience running betas than I do. How long does it generally take to get enough feedback for a science team to decide they're getting useful data and that users can use the site okay?

We're running two projects (billed as one) to get around the limitations of the landing page. The two will be almost identical to these:
http://demo.zooniverse.org/panoptes-front-end/#/projects/mkosmala/Season%20Spotter%20BASIC%20Beta1
http://demo.zooniverse.org/panoptes-front-end/#/projects/mkosmala/Season%20Spotter%20DETAILS%20Beta1

Except, I have a few tweaks to make to adjust to the most recent changes in the back-end and front-end. (Like 'description' no longer being Markdown... [grumble]). So I'll likely build new projects -- as soon as I know things aren't going to change much.

**Comment by camallen** [comment]
Out of interest, why are you creating new projects and not updating the existing ones? Have you tried http://demo.zooniverse.org/panoptes-front-end/#/lab ?

**Comment by mkosmala** [comment]
It's a good point. For these minor things, I can probably just use the lab. (It was down last week when I needed to make some changes, so I just used the back-end API.) On the other hand, a new project gets rid of all my ~~goofing around~~ testing classifications...

**Comment by camallen** [comment]
So changes to workflows modifies the workflow_version that is attached to the classificaiton. You can use this (in the dump) to determine which classifications you want to aggregate over. So no real need to create new projects.

**Comment by mkosmala** [comment]
But what if I like my workflow and just want to alter other stuff? I could make non-material changes to the workflows (add white space?) to set them to new versions, I suppose. But I've got 10 of them to do. Would take less of my time to run my "create Season Spotter project" script.

**Comment by camallen** [comment]
FYI - Workflow version has 2 keys, `"Major.Minor"`. Content changes modify the minor version number, task changes modify the major. It's the major version number you are looking at mostly as different task sets need to be understood to know how the combine in classifications.

**Comment by mkosmala** [comment]
Good to know. Thanks.

Also, I just did all my minor revisions via the lab. (It was super fast. Thanks.) So we'll probably use the two links above for the actual beta test. I'll just filter classifications by date to get rid of any before the beta official starts.
