### ISSUE TITLE
Select subjects for a group (subject_set)

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#810]
I've setup stargazing to select subjects for group 15: https://stargazing2015.zooniverse.org/#/projects/zooniverse/Snapshot%20Supernova/classify
`Error: subject_set_id parameter missing for grouped workflow`

Seems we require `group_id` [here](https://github.com/zooniverse/Panoptes/blob/a669aaa8f5288d54d2f54c8ff4416e6825424e53/lib/subject_selector.rb#L31) but all queries use the `subject_set_id` param [here](https://github.com/zooniverse/Panoptes/blob/a669aaa8f5288d54d2f54c8ff4416e6825424e53/lib/subject_selector.rb#L47)

**Comment by edpaget** [comment]
Ah my bad I think that was the param cellect used.
