### ISSUE TITLE
maximum number of subjects per classification?

### ISSUE THREAD

**Issue by ggdhines** [zooniverse/Panoptes#816]
@edpaget - we currently represent the subjects associated with a classification as a list. This means that we can have an arbitrary number of subjects, but in practice we will only have 1 or maybe 2. (Think Solar Storm Watch is the only project that currently has 2 - and we haven't developed support for that type of project in Panoptes.) Things would be easier for me if we limited the number to at most 2. Does this seem reasonable? Are there any projects down the road where we might want to support more?

**Comment by edpaget** [comment]
We're not even going to support Pairwise projects at launch, so I think we can say that there won't be classifications with more than two subjects for the time being.
