### ISSUE TITLE
Remove all zoo home configs / tests after migration

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#819]
Get rid of a suite of test infrastructure / code that isn't need after users are migrated from zoo home.

**Comment by edpaget** [comment]
This is going need to stay around longer.

**Comment by camallen** [comment]
@edpaget, @astopy wants to consolidate the zoo home db..what's the reasoning for keeping the connections in panoptes around?

**Comment by edpaget** [comment]
Previously there were some users whose records had not migrated properly. I've since narrowed that down to about 400 records that I couldn't migrate, which could be dumped and consulted as necessary. 

We also need to keep it around to migrate counts and subscriptions though right?

**Comment by camallen** [comment]
Yeah - subscriptions is the only thing left i could think of.

**Comment by marten** [comment]
@camallen I think this is done right?

**Comment by camallen** [comment]
yeah - looks like you got it in #1542
