### ISSUE TITLE
Improve error message when no subject set exists for a workflow

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#821]
currently returns `Error: No queue defined for user. Building one now, please try again.`

Detect when a subject queue fails to build / doesn't exist [here](https://github.com/zooniverse/Panoptes/blob/master/lib/subject_selector.rb#L18) and raise a more informative error message

**Comment by edpaget** [comment]
@camallen - @brian-c and I talked and he's going to instead listen for this error message and then reload the subjects route, so it won't be shown to users.
