### ISSUE TITLE
Change subject set for a workflow

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes#822]
This might be addressed by #787, but I'm not sure. I had my primary workflow linked to a small set of test subjects for building. I then created a new, fuller, subject set. When I tried to link to the new subject set, I got a "param missing" error. I then deleted the small (original) subject set, and tried to link the workflow to the new set. The box doesn't appear ticked, but it seems to have worked...

**Comment by edpaget** [comment]
@brian-c is this an issue with the way the links are being displayed?

**Comment by brian-c** [comment]
Might be. I'll dig into this and report back.

**Comment by brian-c** [comment]
Looks like something might actually be up.

- Created a new workflow and two new subject sets.

- Added link to first subject set, that worked fine.

- Added link to second subject set, worked fine, but the next request for the workflow's subject sets did not include it in the list.

- Tried linking the second subject set again, responds with an error ("Workflow is already used" or something).

- Created a third subject set.

- Added a link to the third subject set, worked fine. Next request for workflow's subject sets now correctly responds with all three.

- Delete link to third subject set, works fine, but next request for the workflow's subject sets still responds with all three (should only be the first two).

**Comment by camallen** [comment]
Sounds like a caching issue on those resources, similar to projects and their linked resources. @brian-c were those requests reported as 304's? Test in chrome if you can as firefox ignores the etag if-none combo and instead listens to what the server actually says.

**Comment by brian-c** [comment]
Oooh, yeah, you're absolutely right @camallen. Should have caught that.

**Comment by camallen** [comment]
How are you accessing the resources, we'll need to add a cache key override as per #825 to get this working properly.

**Comment by brian-c** [comment]
I'm comparing `/api/subject_sets?project_id=318` (a project's "subject_sets" link) with `/api/subject_sets?workflow_id=1048` (a workflow's "subject_sets" link).

**Comment by edpaget** [comment]
Is something that could be solved with your cache associations module @camallen ?

**Comment by camallen** [comment]
Yep, I think including the associated workflows in the subject_set cache key will modify the etag properly. But we may need an extra key / field on the workflow model that changes when the subject links change as well.

**Comment by camallen** [comment]
@brian-c I think this was fixed by #840, can you check it out?

**Comment by brian-c** [comment]
Seems to be working fine now.

**Comment by edpaget** [comment]
:fireworks:
