### ISSUE TITLE
update mailer config url's

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#823]
update mailer configs for the different prod & staging envs.  e.g. [here](https://github.com/zooniverse/Panoptes/blob/master/config/environments/production.rb#L69)

**Comment by camallen** [comment]
@edpaget your redirect should take care of this. Do you think we should update these links anyway for text based emails?

**Comment by edpaget** [comment]
Not really we'll probably still want to change them when we actually do that cut over anyway.

**Comment by camallen** [comment]
@edpaget did you mean to close this?
