### ISSUE TITLE
non-logged in user in same session can keep repeat classifying subjects already classified

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes#830]
testing out [P4:Terrains](http://demo.zooniverse.org/panoptes-front-end/#/projects/mschwamb/Planet%20Four:%20Terrains/classify)  - there are only 6 images in the set and I can keep repeat classifying them on firefox with no stop. If I'm logged in it brings up the no-more subjects data message. Same issue occurs on Chrome.

**Comment by mschwamb** [comment]
checked at a different ip address. Same result.

**Comment by edpaget** [comment]
This is intended behaviour. We don't track subjects logged out users have seen.

**Comment by camallen** [comment]
@mschwamb you might want to make an issue in the front-end to warn the user when they've already classified this subject for that session.

**Comment by chrislintott** [comment]
@camallen But we are recording classifications, right? It's just that they're not repeated.

**Comment by brian-c** [comment]
Signed-in users will get a warning when #571 is fixed and zooniverse/Panoptes-Front-End#135 is merged.

**Comment by camallen** [comment]
All classifications are recorded. 

Brian, does the front end skip subjects that have already been seen in a session? Non logged in users may have this problem with small data sets and slow moving projects that don't retire quickly. 

Also are we prompting to sign up / log in after x classifications?

**Comment by brian-c** [comment]
The front end doesn't skip any subjects. I could put the same warning as logged-in users get though. Is there any incentive to register in knowing when you've seen repeats?

I've got a PR open for prompting (zooniverse/Panoptes-Front-End#264). I'll ping @chrissnyder to merge it.

**Comment by camallen** [comment]
@brian-c I thought all our front ends kept a list of project subjects that have been seen for a session to avoid people accidentally seeing duplicates (and getting upset that we've wasted their time).

Check out [this project](http://demo.zooniverse.org/panoptes-front-end/#/projects/klmasters_panoptes/VOLCROWE/classify) for an example, it only has 6 subjects so a non-logged in user will just loop through these without any warning.
