### ISSUE TITLE
only queue subjects for workflows that still exist

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#831]
Ensure we are only queueing subjects for workflows that still exist.

![sidekiq_missing_workflow_for_queue](https://cloud.githubusercontent.com/assets/295329/7589530/06c1a87c-f8bb-11e4-9fac-2038f9050061.png)

**Comment by edpaget** [comment]
@camallen I'm not sure what we should be doing about this other than putting a limit on retries for the queue worker. If a user deletes the workflow between the time the queue action is started and when sidekiq process the queue action, it's going to fail.

**Comment by camallen** [comment]
Can't we just test the queue exists in the worker and if not then return instead of raising an error?

**Comment by camallen** [comment]
Sorry, test if the workflow exists.

**Comment by edpaget** [comment]
Ah sure that makes sense
