### ISSUE TITLE
Can't unlink workflow from subject set

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes#839]
When I tried to uncheck a subject set from my "Marking2" workflow in http://demo.zooniverse.org/panoptes-front-end/#/projects/aliburchard/WhaleTails, I get this error: 
message:"Couldn't find SubjectSet with 'id'=1959 [WHERE "subject_sets_workflows"."workflow_id" = ?]"

**Comment by camallen** [comment]
make the error message more informative and not expose SQL details.

**Comment by edpaget** [comment]
I also think this is caching bug somewhere. @aweiksnar was seeing something similar yesterday

**Comment by edpaget** [comment]
@aliburchard I think @camallen's most recent deploy fixed this. Can you try and see if you're still having the issue?

**Comment by aliburchard** [comment]
Hmm, I'm still struggling. The tick boxes now reflect being checked and un-checked (yay @brian-c) but I can't seem to link to a subject set. I even tried deleting all the old ones and uploading a new one and still no luck. I get a "param missing" error when I try to link to the subject set, and then have no subjects to classify. This is after a hard reload.
![screen shot 2015-05-15 at 12 30 49](https://cloud.githubusercontent.com/assets/6217406/7651958/503b715a-fafe-11e4-91f7-d42087c81a0e.png)
![screen shot 2015-05-15 at 12 30 17](https://cloud.githubusercontent.com/assets/6217406/7651959/503f61d4-fafe-11e4-9f08-2514e2e0f219.png)

**Comment by edpaget** [comment]
@aliburchard @brian-c I think that error is just caused by the save button becoming active again when you link subject sets (even though it saves that automatically and separately)

**Comment by brian-c** [comment]
Yeah, both these issues are my bad. I'll get them sorted today.
