### ISSUE TITLE
Welcome email for new users

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#841]
Do we want to have a welcome email for new signups ready? 

If so this should be in a background worker for sending.

**Comment by chrissnyder** [comment]
Assigning this to @DarrenMcRoy and @heathv.

For reference, the current one looks like http://i.imgur.com/plNdQDG.png. So we can't do much worse.

**Comment by DarrenMcRoy** [comment]
I can go ahead and write up some content for this, and then give it to @heathv to make it look pretty.

Will have something by the end of today or first thing Monday.

**Comment by heathv** [comment]
Adding it to the list.

**Comment by edpaget** [comment]
Can you guys also look at #768 too?

**Comment by camallen** [comment]
I've started working on this [here](https://github.com/camallen/Panoptes/tree/welcome_email). @mrniaboc you might want to checkout the email content.

**Comment by DarrenMcRoy** [comment]
Hey @camallen -- sorry, confused, was going to work on this today (got delayed by other content).

Is there any actual content yet, or is this just the dev side of things to make whatever content we write appear?

**Comment by camallen** [comment]
Just the tech side, no copy / layout yet.

**Comment by DarrenMcRoy** [comment]
Cool. Thanks! Will really try to have that drafted by end of today.

**Comment by DarrenMcRoy** [comment]
First draft:

https://docs.google.com/a/zooniverse.org/document/d/1fu97oc0MLGBk_F8UcykOUz75yaO1oITbUgKV2rwc0gc/edit?usp=sharing

Thoughts?

**Comment by DarrenMcRoy** [comment]
I think this mailer content is ready to go?

**Comment by camallen** [comment]
closed via #1025
