### ISSUE TITLE
Add attached_images to projects

### ISSUE THREAD

**Issue by edpaget** [zooniverse/Panoptes#848]
Create a media endpoint for attaching images to projects for help text. We should probably limit the number of images would 20 or so sound reasonable?

**Comment by aliburchard** [comment]
20 seems like plenty for a help/faq (though if this includes logos of project collaborators maybe not so much...) On the off-chance people have more, can we manually increase this limit for them? (I doubt this would happen much.)

**Comment by vrooje** [comment]
I could see people going over that pretty fast if they try to build a
spotter's guide. Then again if the limit is number of images, not total
disk space used etc., they could just make a big image mosaic and then it
counts as 1...

**Comment by edpaget** [comment]
Yeah I might just leave this uncapped for now, then if it becomes a problem we can talk to people.

**Comment by mkosmala** [comment]
FWIW, we use ~40 images for help.
