### ISSUE TITLE
events queue consumer

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#854]
Not really a panoptes task but one that needs to happen on zoo home switch to ensure the zoo home events queue consumer still runs and posts to `zooniverse.org/api/events` to enable legacy projects to update activity counts.
- [ ] change zoo home supervisord config to only run the rails runner queue consumer task

**Comment by edpaget** [comment]
Cool I'll need to add a redirect from that url to panoptes.zooniverse.org/api/events for now too.

**Comment by edpaget** [comment]
Is it just a matter of adding this to the supervisord config?

**Comment by camallen** [comment]
Yeah, changing the zoo home docker/supervisord.conf#L12 start script to just run the queue and not the rails app

**Comment by edpaget** [comment]
Close via https://github.com/zooniverse/Zooniverse-Home/pull/53
