### ISSUE TITLE
Subjects `already_seen` field changes depending on how its accessed

### ISSUE THREAD

**Issue by brian-c** [zooniverse/Panoptes#857]
It looks like when I get a subject back through `/subjects?project_id=231&workflow_id=622&sort=cellect`, its `already_seen` property is accurate, but through `/subjects?collection_id=10&id=11937` (and `/subjects/11937`) It's always `false`.

Can we only include the attribute when we're sure of its accuracy?

Might apply to `retired`, too, but I haven't checked.

**Comment by camallen** [comment]
That information via the `sort=cellect` is correct. Looks like a bug in the serializer.

**Comment by edpaget** [comment]
I don't think it should be included at unless the conditional attributes in RestPack aren't working https://github.com/zooniverse/Panoptes/blob/master/app/serializers/subject_serializer.rb#L8-L9

**Comment by camallen** [comment]
yeah - i've got a PR coming through.
