### ISSUE TITLE
unsubscribe email end point with token auth

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#865]
Replicate behaviour from here: https://www.zooniverse.org/unsubscribe for use in links in emails from the zooniverse. 

When a user clicks a link in an email we send them it will unsubscribe the user from all project email lists and set their user global & project email communication preferences to false.

We need to add a per-user token to embed into the link that will authenticate the user request.

**Comment by brian-c** [comment]
On the front end, I have project newsletter subscriptions set up as either true or false. Should this actually be true, false, or null, null meaning "whatever global is set to"?

**Comment by edpaget** [comment]
They will automatically be set as true or false the first time a user classifies on a project, depending on their global preference.

**Comment by brian-c** [comment]
Sounds good, thanks.

**Comment by DarrenMcRoy** [comment]
Strongly recommend including a note to the effect of:

We're sorry to lose you, but if you would like to stop receiving newsletters from us please enter your account email address below. Please note that this will result in removing *all* newsletters from the Zooniverse and Zooniverse projects. If you would like to manage individual newsletters, or if you ever change your mind after unsubscribing, you can change the settings for your account on your profile settings page.

**Comment by camallen** [comment]
Just to clarify this will replicate the unsubscription behaviour via the backend. There is no intention of providing a form (like now) where the user has to put their email address into and click unsubscribe. 

Instead the plan is to have a link with a unique per user token in the email that they click and will automatically unsubscribe them from all emails in the backend. 

Instead this wording should be where the link exists in the copy text but we should make subscribing and unsubscribing as easy as possible.

**Comment by vrooje** [comment]
Completely agree on making it as easy as possible to unsubscribe; I get why it makes sense to ask users to put in the email address they want to unsubscribe, but as an end user that can be a little annoying (and people sometimes don't remember what email they signed up with years ago and are now forwarding to their current email).
