### ISSUE TITLE
Ensure that Panoptes calculates classification duration and session number for each user classification. 

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes#866]
@vrooje @ggdhines and I have all needed to do analysis on user sessions when looking at user classification behaviour. The best way to do this is to record a classification duration for each classification (that is, the time between the end of user's previous classification and the end of this one). Each time the classification duration is greater than one hour, that indicates the start of a new session (this is accepted in papers etc as a standard approach for identifying sessions). This metric is so useful that it would be good to have this generated automatically after a classification is stored.

I discussed with @camallen and he had 3 ideas:
1) the aggregation engine could have a worker which listens for the classification update then calculates the classification duration and session ID and adds this metadata to the classification.
2) the "current session number" for each user could be stored in Kafka, and updated each time 1 hour has elapsed since the last classification.
3) Cam had another idea, I'll invite him to add it here.

Notes:
Even though the classifications may come in non-sequentially, you should be able to reliably get the order of classifications for a user after the fact by using the incremental key
The current Panoptes model has start time and finish time - however the classification duration is more than this, as it has to take into account the previous classification as well.

Having this metric automatically in place for all projects will be hugely useful in future experimental work or user behavioural analysis.

**Comment by camallen** [comment]
So this seems like a place where a stream of classifications from Kafka could be used to determine which user sessions classifications belong to.

> 1) the aggregation engine could have a worker which listens for the classification update then calculates the classification duration and session ID and adds this metadata to the classification.

I.e. a batch process that runs over the set of classifications to create these session identifiers and duration. It would then append these fields to the classification or store them in another table with the list of associated classification ID's. Sessions would be static so this process would only need to be run on new data coming in.

> 2) the "current session number" for each user could be stored in Kafka, and updated each time 1 hour has elapsed since the last classification.

So I thought we could have a storm / spark streaming process listening to the stream of classifications that would create / use a per user : project session ID that expires / increments after a set timeout (e.g. the 1 hour mentioned above). It could attach this session id, start and end times on the classification or store the details in a separate table. Duration of the session could be calculated by inspecting the classification session groups.

> 3) Cam had another idea, I'll invite him to add it here.

Specifically adopting the idea from point 2 above but for an existing Ouroboros project (snapshot serenget) that can run in @edpaget's storm topology.

**Comment by vrooje** [comment]
Would we want to run this for a user's sessions in individual projects, or count people who switch projects without ever taking a break as the same session? Would it be hard to do both?

**Comment by camallen** [comment]
@parrish can we use the notifications system presence system to construct / retrieve a session identifier that can be appended to the classification?

**Comment by camallen** [comment]
sounds like we should just use a client side session identifier from PFE for this.

**Comment by vrooje** [comment]
Just noting somewhere for future reference: @willettk and I have been chatting about how classification duration (time it takes to do 1 classification) might be used to identify bots, by comparing each user's typical classification duration against the overall distribution and identifying outliers.
