### ISSUE TITLE
updating DB schema

### ISSUE THREAD

**Issue by ggdhines** [zooniverse/Panoptes#869]
@edpaget or @camallen - can we update the postgres schema for classifications so that subject_ids becomes subject_id (just one value) and add an index back on? Not sure when we are aiming to put Cassandra in but Chris L. wants some simple analysis ready so it seems that using postgres for the time being would be useful.

**Comment by camallen** [comment]
Not sure we want to do this by default but there are a few ways we could enable this use case as well as paired subject classification later on (array's vs sparse second subject_id column).

I thought the plan was to get Cassandra working with custom python code?

**Comment by ggdhines** [comment]
Discussed with Cam - understand things better, going to just go with Cassandra
