### ISSUE TITLE
Deactivating a user should not deactivate it's identity group

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#870]
[From here](https://github.com/zooniverse/Panoptes/blob/ba78dc5f1aebde339274612275c206ef399f6ce1/app/controllers/api/v1/users_controller.rb#L62) we should have a scope / method to return all the non-identity memberships to deactivate.

**Comment by edpaget** [comment]
Why wouldn't we want to the deactivate that too?

**Comment by camallen** [comment]
We need to keep it active or we modify our search scopes like you're slug migration uses.

**Comment by edpaget** [comment]
Ah yeah we should make that migration on looks at active stuff.

**Comment by camallen** [comment]
Using modified finder scopes to avoid this issue. Will need to take care in future with user migrations failing the identity group validations.
