### ISSUE TITLE
Associating subject set with workflow appears to work, but doesn't

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes#882]
I've got subject set 8 loaded (382 subjects) and workflow 3 written for preview site [project 3](http://preview.zooniverse.org/panoptes/#/lab/3) (which I'm happy to add anyone to who wants it; it's still a private project), but when I try to classify in the project I get the message "Error: No subjects available for workflow 3". 

I've tried waiting >1 hour (nope) and un-ticking and re-ticking the subject set box in the workflow editor (nope). I don't get any additional errors in the console when I do this.

My console has errors, e.g. related to Zooniverse/Panoptes-front-end#409 (which I suspect I probably should have posted here instead; sorry) and Zooniverse/Panoptes-front-end#412, but nothing that is obviously related to this:

![screen shot 2015-05-26 at 14 13 41](https://cloud.githubusercontent.com/assets/2357126/7813313/b53c59c8-03b1-11e5-95b1-0879018fbe63.jpg)

**Comment by edpaget** [comment]
I'm pretty sure this, zooniverse/Panoptes-Front-End#402 and zooniverse/Panoptes-Front-End#393 are all caused by the same problem, in that workers updating the queues are getting stuck. Still trying to figure out what's causing that to happen.

**Comment by karenlmasters** [comment]
I'm seeing this behaviour this evening. Should it have been fixed? I haven't waited that long yet….

**Comment by edpaget** [comment]
Yes this should be fixed. What project are you having problems with?

**Comment by karenlmasters** [comment]
I just started a new one called "MaNGA Quality Control Inspection" (which is intended to remain private).

**Comment by karenlmasters** [comment]
So it was working this morning (and Cam is now a collaborator), but I just tried to change the subject set (to trial having multiple images per subject) and that has not worked.

**Comment by camallen** [comment]
I just checked the subject queues and they are correct for the Test 4 images subject set (1 subject). this looks like some other behaviour with changing subject sets (authentication?).

@karenlmasters what subject set did you try and change it to? I'll try on my end to reproduce the issue.

**Comment by karenlmasters** [comment]
Looks like it was a reload issue with my browser.

**Comment by edpaget** [comment]
Seems like it's the subject caching the Front-End does then.
