### ISSUE TITLE
Project's attached_images don't keep metadata

### ISSUE THREAD

**Issue by brian-c** [zooniverse/Panoptes#889]
POSTed fine with `{"media":{"content_type":"image/jpeg","metadata":{"filename":"pac-man-logo1.jpg"}}}`, but `metadata` doesn't come back with the response.

**Comment by camallen** [comment]
Data is being stored, it's just not serialized in the response. Update attributes [here](https://github.com/zooniverse/Panoptes/blob/master/app/serializers/medium_serializer.rb#L4) to include the metadata.
