### ISSUE TITLE
Poorly-formed POSTs to /users never respond, kill the server?

### ISSUE THREAD

**Issue by brian-c** [zooniverse/Panoptes#897]
I've been using POST /users with only a "display_name" or "email" field (no "password") to test to see if a username or email address is available before creating a new account.

At some point (not sure when) this seems to have slowed way way down, sometimes just timing out after a minute.

And I'm _pretty_ sure if I do it enough the whole back end dies for a few minutes. I can't even load /commit_id.txt right now.

**Comment by edpaget** [comment]
Looks like the slug validation on the identity group and the display_name case insensitive validations can run really slow. Some testing from local machine have them at 1.5s each.
