### ISSUE TITLE
Cannot send project_id with registration

### ISSUE THREAD

**Issue by brian-c** [zooniverse/Panoptes#903]
POST to /users with `{authenticity_token: '...', user: {project_id: '231', display_name: '...', password: '...', email: '...'}}` returns a 500.

Without a `project_id` it's fine.

For zooniverse/Panoptes-Front-End#372.

**Comment by camallen** [comment]
Pretty sure I was working on this with the welcome email

**Comment by camallen** [comment]
Linked to #841

**Comment by camallen** [comment]
closed by https://github.com/zooniverse/Panoptes/pull/917
