### ISSUE TITLE
Downloading classification data

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes#904]
I saw that #611 closed a little while ago. What's the scoop on getting classification data out? I'd like to see the results of the Season Spotter beta...

**Comment by brian-c** [comment]
There should be a "Request data export" button on the lab/project details page now. It'll send you an email with a link to the classifications.

**Comment by mkosmala** [comment]
Perhaps this was implemented after the stand-alone Season Spotter beta got put up? I don't have that option available at:
http://demo.zooniverse.org/seasons/#/lab/403

(But I do see it on my projects on panoptes-staging.)

**Comment by camallen** [comment]
Yeah that button http://demo.zooniverse.org/seasons/#/lab/403 will work, it's the same backend generating it for you.

**Comment by mkosmala** [comment]
@camallen The thing is I don't HAVE that button on http://demo.zooniverse.org/seasons/#/lab/403. The button is not there.

**Comment by camallen** [comment]
Sorry, i thought *(But I do see it on my projects on panoptes-staging.)* meant you did.

**Comment by camallen** [comment]
Can't you just access it via http://demo.zooniverse.org/panoptes-front-end/#/lab/403?

**Comment by mkosmala** [comment]
Not sure. Are these the same on the backend?
http://demo.zooniverse.org/seasons/#/lab/403
http://demo.zooniverse.org/panoptes-front-end/#/lab/403

**Comment by camallen** [comment]
Yep.

**Comment by mkosmala** [comment]
Oh. Right. Okay, then yes, I can just do that. Thanks!

**Comment by mkosmala** [comment]
Um, when I press the button and retrieve the data via email, I have 4 classifications -- all from 5/1 or 5/6. Likely these are testing classifications that I made, as we didn't launch the beta until 5/14. Where are all the beta testing classifications?! I hope this is a retrieval bug and not a storage bug. @camallen can you easily check how many classifications are associated with project 403?

**Comment by edpaget** [comment]
There are only 4 classifications for that version of your Project.

**Comment by edpaget** [comment]
Project 405 and 406 are the ones that have all the classifications.

**Comment by mkosmala** [comment]
Sorry everyone, @edpaget 's totally right.
