### ISSUE TITLE
Can't copy one workflow's subject_set into another workflow

### ISSUE THREAD

**Issue by brian-c** [zooniverse/Panoptes#907]
Related to zooniverse/Panoptes-Front-End#387:

I want to copy a subject set from one workflow to another one.

Posting `{subject_sets: ["1166"]}` (just using 1166 for dev right now) to `/api/workflows/1147/links/subject_sets` results in a 422: `{"errors":[{"message":"Couldn't find linked subject_sets for current user"}]}`.

That's my subject set (that shouldn't matter) and my workflow and my project, but the subject set belongs to a different project.

Bug or misunderstanding on my part?

**Comment by edpaget** [comment]
You have to link the subject set the project first to import it at the moment. That's just where the copying is triggered. We can also do it when you link to the workflow.

**Comment by camallen** [comment]
@brian-c I'm going to implement what the docs say's it does on the workflow.
