### ISSUE TITLE
Empty metadata in subjects

### ISSUE THREAD

**Issue by aweiksnar** [zooniverse/Panoptes#908]
I noticed it's possible for an empty key-value pair to be stored in the metadata of a subject (example: stringify the response of subject `3993`). I don't think it's a major issue (could be handled on frontend), but wanted to ask if it's worth addressing or might bring up unexpected weirdness in the future

**Comment by edpaget** [comment]
Ah do you mean you're able to submit a subject with metadata that just an empty string?

**Comment by aweiksnar** [comment]
I haven't tested it when submitting a new subject (I can if it'd be helpful), but was classifying that particular subject and saw that the metadata in the UI looked funky, since I think the interface iterates over all the fields and prints them, and then noticed that it was storing an empty key/val

**Comment by edpaget** [comment]
Ah word. I'll look into that.

**Comment by marten** [comment]
This empty pair no longer exists in subject 3993. Assuming fixed.
