### ISSUE TITLE
Fuzzy Searching for Usernames

### ISSUE THREAD

**Issue by edpaget** [zooniverse/Panoptes#919]
It'd be nice to support fuzzy matching user names to support easier searching for @-mentions, collaborators and people to receive data emails. 

The similarity function in postgresql and a trigram index is probably the best way to go about this.

**Comment by edpaget** [comment]
Actually this is more urgent since I think I'm using the wrong sort of index anyway.

**Comment by camallen** [comment]
Are we using left anchored matches? If so it looks like we can use a like operator and a btree index.

**Comment by edpaget** [comment]
We need them to be case-insentive and 'ILIKE' only works with a btree index is the left anchored portion is only made of characters without cases like digits and punctuation. See the [doc](http://www.postgresql.org/docs/9.2/static/indexes-types.html) I think the third or fourth paragraph.

**Comment by camallen** [comment]
Can we use left anchored `LIKE` on the `identity_group#name` field? We downcase that from the `display_name` before `user_group` validation.

**Comment by camallen** [comment]
Also wanted to say I don't really mind what the implementation of this is, just thinking through the options.
