### ISSUE TITLE
Add 'is retired' field to classification output

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes#920]
The classification output should have a boolean field that says whether or not that subject has been retired. I imagine this might turn into a string at some point for a retirement reason, as is done for Snapshot Serengeti. But since Panoptes just supports one type of retirement right now (correct?), then a boolean is fine for now.

**Comment by aliburchard** [comment]
I like this. We've noticed on Snapshot Serengeti that sometimes there are a few images that never seem to have been retired, even though the season is "complete." This would help sleuth out weirdnesses.

**Comment by mkosmala** [comment]
It's actually essential, not just nice. I need to know whether to expect more classifications on any given subject, or whether I have them all.
