### ISSUE TITLE
Subject drag and drop of images/metadata unresponsive

### ISSUE THREAD

**Issue by AdrianEvans** [zooniverse/Panoptes#931]
Just created an account and a new project and can't seem to upload images and metadata to a subject. Perhaps I'm doing it wrong. It just doesn't do anything at all (the cursor does change to the state usually associated with the location being an acceptable spot to drop files).

csv content is:

file,area,location
DSC03210_01.jpg,1,1
DSC03210_02.jpg,1,2
DSC03210_03.jpg,1,3
DSC03210_04.jpg,1,4
DSC03210_05.jpg,1,5
DSC03210_06.jpg,1,6
DSC03210_07.jpg,1,7
DSC03210_08.jpg,1,8

and here are the first two pictures
![dsc03210_01](https://cloud.githubusercontent.com/assets/10448680/7965189/cea4962e-0a13-11e5-8a7e-26f2aa593653.jpg)
![dsc03210_02](https://cloud.githubusercontent.com/assets/10448680/7965190/ceabbb5c-0a13-11e5-9b42-97f2916ad240.jpg)

**Comment by camallen** [comment]
@aliburchard thoughts?

**Comment by brian-c** [comment]
@AdrianEvans Whats OS and browser are you on?

**Comment by AdrianEvans** [comment]
win 8.1 and up-to-date chrome - error reproduced in explorer 11 too

**Comment by aliburchard** [comment]
No idea, though I know there were issues with windows hiding csv extensions.

**Comment by edpaget** [comment]
Closing in favor of #479 since it seems like its an OS compatibility issue with the front end.
