### ISSUE TITLE
Add workflow name to classifications export

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes#935]
All we have right now to identify which workflow was done for a given classification is the workflow number. So currently have to manually compile a table of workflow numbers to workflow names, so I know which workflow each classification is associated with. You will make science teams MUCH happier if you could just provide the workflow name in the classifications export somewhere.

**Comment by mkosmala** [comment]
Actually, this is even worse than I thought. The workflow number does not appear in the project builder. (@brian-c, should it?) So as a "normal" project builder I have no way to associate the exported classifications with their workflows.

**Comment by edpaget** [comment]
You can use the API until we have a chance to provide a solution. `curl -H "Accept: application/vnd.api+json; version=1" "https://panoptes.zooniverse.org/api/workflow/{your id number}" will return your project's workflow details (unless it's private then you'll also need to set the Authorization header).
