### ISSUE TITLE
Tracking not-logged-in users in classifications export

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes#937]
Please add a session tag of some sort to the classifications export, so we can follow the not-logged-in users through a session, at least.

**Comment by camallen** [comment]
This should already be working with the not-logged-in, their user ip and the classification timestamps. @mkosmala are you talking something like this, https://github.com/zooniverse/Panoptes/issues/866?

**Comment by mkosmala** [comment]
@camallen Yes, exactly. So is the session-izing going to be a post-hoc aggregation function? And will something like a session ID be included in the raw exports?

**Comment by camallen** [comment]
yeah - either a batch job or part of our streaming infrastructure when we get it running. I think we'll include the session id in the export as it's useful for science teams.

You should have all the information you need to construct sessions right now (for both logged in and not logged in). Username + ip + user_agent + classification timestamps, etc.

**Comment by mkosmala** [comment]
@camallen Okay, thanks.

**Comment by camallen** [comment]
Closing this in favour of #866
