### ISSUE TITLE
Accessing Panoptes API from non zooniverse.org domains?

### ISSUE THREAD

**Issue by chrissnyder** [zooniverse/Panoptes#952]
I assume I need an application ID scoped to a specific domain(s)?

**Comment by camallen** [comment]
Yep, we can add another first party application with the correct scopes if needed as per [here](https://github.com/zooniverse/Panoptes/blob/a737d7a0755eb843f03dfd2972f47307509d840b/db/fig_dev_seed_data/fig_dev_seed_data.rb#L49)

Also will need to allow cors to the non-api routes as per [here](https://github.com/zooniverse/Panoptes/blob/a737d7a0755eb843f03dfd2972f47307509d840b/config/environments/production.rb#L95)

**Comment by chrissnyder** [comment]
Sweet, looks easy. One clarification, for a first-party app that isn't on zooniverse.org, would reusing the same app ID and just adding a CORS rule work? Or would it make more sense to create a new app per site?

**Comment by camallen** [comment]
We could but then it would be harder revoke a specific applications access so we'd want to have one per app. I'd be more in favour of using uniq applications for our custom projects but wouldn't be upset with one for custom builds and just modifying the CORS rules.
