### ISSUE TITLE
gold standard data dump

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes#971]
Can we create a data dump that just returns classifications made by experts in "gold mode"?

I think this will be critical for researchers trying to test and improve on aggregation approaches.

**Comment by edpaget** [comment]
Don't we already include this information in the normal classification dump?

**Comment by camallen** [comment]
Yep we do but science teams will most probably want dumps of just the gold standard data.

**Comment by edpaget** [comment]
Still this would be another feature to main, and a further complication of the API for little benefit. I mean this is literally just sorting by a column in Excel. If someone is doing aggregation analysis they are 100% capable of deriving that data without our help.

**Comment by camallen** [comment]
Fair call on their expertise, will re-open if the feature is directly requested.
