### ISSUE TITLE
Label tools in data export

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes#979]
Looking at the raw classifications, drawing tool markings are just associated with "tool 1", "tool 2" etc. I don't know how the tool number maps to the tool label in the workflow. Can we report the tool label instead of the tool number?

**Comment by camallen** [comment]
Moving to soft launch as this is needed for data analysis.

**Comment by aliburchard** [comment]
Yup. Science teams trying to aggregate over raw classification data need to be able to easily link the classifications to tasks and tools. I suspect @ggdhines might also want these labels as well for outputting human-readable aggregated data.

**Comment by twhyntie** [comment]
:+1:

**Comment by marten** [comment]
If someone can give me a pointer as to where in panoptes these exports are made (or is it just the ClassificationSerializer that's used for this?) I'm happy to have a go at adding the labels.

**Comment by camallen** [comment]
@marten [here](https://github.com/zooniverse/Panoptes/blob/64596a83f4457210ec03dd6f94e06784d794af67/lib/formatter/csv/classification.rb#L56) you'd need to extract the annotations and replace the tool name based on the relevant workflow's `workflow_content` for the task. You may want to eager load the workflow contents as well ala [here](https://github.com/zooniverse/Panoptes/blob/64596a83f4457210ec03dd6f94e06784d794af67/app/workers/classifications_dump_worker.rb#L29) to avoid any N+1 query.

**Comment by marten** [comment]
Can I just use the label from the first available workflow_content or do you want me to find the one matching a specific language?

**Comment by edpaget** [comment]
The workflow should have a 'primary_language' field on it. It seems safe to me to just serialize that language.

**Comment by marten** [comment]
@aliburchard In my pull request I'm simply adding an additional field "tool_label", and not overriding the existing "tool" field which has the number in it. I assume that's fine for your purposes (and that this was not broken behaviour vs. how it used to be)?

**Comment by aliburchard** [comment]
@marten that's perfect, thanks -- this will make the raw data dumps so much easier to read. Realized two things that may or may not have been done:
1) Can we also export the "task" label as well? 
2) Can tool and task labels be stripped of punctuation? The punctuation within the labels can cause a number of problems when trying to read this as a csv (which I suspect most people will still be working in)

**Comment by marten** [comment]
1) We could, it'll probably increase the size of the CSVs somewhat, as it gets a bit repetitive. It wouldn't be hard to do, but I wonder why the task identifier (eg. "vegetationtype") isn't sufficiently identifying. @camallen @edpaget can I get a yay or nay here?

2) Any comma's (which I suspect is the issue, not things like periods and question marks) should cause the column value to be wrapped in quotes automatically. But you're right that not all software deals with this very well by default. I could strip all comma's, or replace them with something. Is there a chance for newlines in labels, those usually cause the same havoc?

**Comment by twhyntie** [comment]
@marten 

1) I don't think Front End users can specify the task identifier via the workflow builder. There seems to be an automatic numbering system that is based on the order the questions are added - and it's pretty tricky to decode in the CSV. But yes, having the label in each classification is going to bloat the CSV file. Longer term, could some sort of key file be generated from the workflow?

2) There are commas all over the place in the CSV output, which is manageable but bit of a pain (and sort of defies the point of a CSV file). The double quotes sort of helps (I'm using a Python script using `split` - I'm sure there are more elegant ways of doing it) but an alternative might be to dump a Tab Separated Value (TSV) file instead.

**Comment by marten** [comment]
@twhyntie If you're using python, you probably just want to use the built-in CSV module which is about as simple as `split`, just use `csv.reader(opened_file)` instead of reading lines and splitting them yourself:

```python
import csv
with open("/tmp/foo.csv", "rb") as f:
  print list(csv.reader(f))

# ==> [['1', 'foo', 'foo,bar', 'quux\nbaz']]
```

**Comment by twhyntie** [comment]
@marten Ha! Yes, that would indeed be "more elegant" :-)

**Comment by aliburchard** [comment]
@marten - to second @twhyntie, I think the report uses an automatically generated number and no "identifier." I suspect the 'vegetation type' text identifier is from Margaret's season-spotter, which was created directly via API.

**Comment by marten** [comment]
@aliburchard Ah, okay that's the thing with just starting out: not knowing all the details about the contents of the database. That was just the first project to pop up while searching for an example case :). I'm in favour of adding those task labels then, at the very least until we can have a key file to accompany the CSVs.

**Comment by camallen** [comment]
I think we can expect people working with raw data will have enough skills to get the code working. we can look at providing example code (as per above) to help them out.

@marten have a look at the example kitty zoo project's classifications / workflows for a project built with the front end.

@aliburchard I assume you want the task label and answer labels as well? This is getting into bloat territory as it'll just be repeating sets of data.  For reference, in the past we've used custom scripts to extract the annotations to their own csv columns and avoid this kind of bloat but that's not really what we want for panoptes. 

I think the best solution is to provide a separate lookup file outlining the workflow contents that can be joined to the labels in the annotations in code. Both of these files should be included in a zip file for download. Again some examples to help researchers will need to be provided, code samples / docs from the community are welcome!

@marten slight highjack, any chance you can convert this code [here](https://github.com/zooniverse/Panoptes/blob/9678a88dcd397d3d4b8a86920befb474fdf58e95/app/workers/classifications_dump_worker.rb#L14) to use ruby temp files instead of just normal files to build the dump archive? I failed in a previous iteration to get this working properly (check your tmp dir after testing).

**Comment by twhyntie** [comment]
@camallen :+1: for the zip file solution :-)

**Comment by marten** [comment]
@camallen Shall I just switch gears and build that zip file and let's say an example of how to deal with it in Python? Given the annotations are JSON, I'll assume the lookup file can be JSON too. Maybe we can reuse `Export::JSON::Project` for that?

**Comment by camallen** [comment]
yeah sounds good, re-use what you like. For reference that project export was for moving a project between databases via json dumps.

**Comment by aliburchard** [comment]
A "lookup file" that can be separately attached is a major improvement, but I'd like to argue for spending some effort creating readable csv dumps for the raw classifications in the near future.

Until we get aggregations working for *all* projects, the raw data dumps are all that researchers have to look at. They would benefit enormously from immediately understandable dumps of raw data -- which includes enough of the human text labels for tasks and tools, as well as some more parsing of the "annotations" field. The couple of science teams I'm working with currently can't make much sense of the raw data as it is currently. 

Specifically, what I'd like to see is:
1) Some subset of the task and tool label text, in addition to the computer generated task/tool numbers. This text could be say the first 10-20 characters of the labels, stripped of punctuation.
2) Some sort of splitting of the annotations. Right now, all the answers that we want to look at are in some sorted of nested list in a single "column" produced by the automatic JSON to CSV exporter. I'd vote for lengthening the format to *one row per user per task per subject*, though appreciate that increases file size if we are adding label text.

**Comment by marten** [comment]
We had a bit of discussion on Hangouts and Slack where @ggdhines and @aliburchard started with the suggestion hinted to above, of splitting up what currently are single rows per classification into multiple rows to handle the list of tasks and the list of drawn points / multiple choice items inside the JSON in a more CSV-ish manner.

Going over the Panoptes codebase, it seems it currently is able to get away with storing/returning project workflows and classifications as black boxes, and having the frontend deal with the different types of tasks and the structure of the classification annotations that come out of them. That means that Panoptes currently doesn't care what tasks are defined.

If we want to break classifications up into multiple rows and specific columns, that will mean introducing coupling with the specifics inside workflows and tasks (in fact PR #1008 already does this by special casing "drawing" tasks). The implication there is that when the frontend adds a new type of task, the backend needs to also be updated to handle that or annotations of that type won't be exported correctly. This is the upside of the raw export we currently do, although in practice that only means offloading that coupling to the researcher that then wants to actually use the data...

As so often happens, the actual implementation of either adding labels to the JSON or even the breaking up of rows is something that could be added relatively quickly. Deciding whether or not that's the best course of action is much harder... :wink:

**Comment by camallen** [comment]
Just to revisit the original issue here, the request was to replace annotation lables in json with the actual strings for human consumption. I think we should just go forward and implement something that fixes this issue. I favour the seperate join file to create fast easy exports. @marten i'll leave it up to you to come up with something.

We can come up with a better solution that is in line with the aggregation engine's requirements as it has to understand workflows and tools too.

Finally, I agree we should support researchers but that can be a slippery slope as well. Perhaps code examples and offering help (where we can) is best here.
