### ISSUE TITLE
Add priority selection strategy for transcription projects

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#983]
Transcription projects will want to flow in order from a starting point to a finishing point, e.g. page 1, 2, 3....End. We need to add the functionality to build the selection queue in order from the priority field [here](https://github.com/zooniverse/Panoptes/blob/70f2453db5edd31f4e8f0fb8af0f59d620f332b3/lib/postgresql_selection.rb#L35). 

Also the Tate transcription project we'll also need to support grouped and prioritized as individual volumes will be a subject set.

**Comment by rogerhutchings** [comment]
cc @VVH

**Comment by camallen** [comment]
For reference, we need to implement grouped and prioritized [here](https://github.com/zooniverse/Panoptes/blob/dc255329cd19f3ebdfaf6771f8dc4b4540e91efc/lib/postgresql_selection.rb#L36).

**Comment by eatyourgreens** [comment]
Wellcome is going to need this too. The health reports are volumes that can be grouped by London borough or year.

**Comment by camallen** [comment]
Just noting we'll need this for beta launch for tate project by the 10th August.
