### ISSUE TITLE
Reject a request to create a new workflow if a project is live and approved

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#984]
LInked to https://github.com/zooniverse/Panoptes-Front-End/issues/274#issuecomment-112741781

If a project is live and has been approved for beta/launch by the zooniverse and a team member tries to add a new workflow it should reject the request. Modifying a live project should only be allowed under certain conditions and in consultation with the zooniverse team.

**Comment by camallen** [comment]
@edpaget should we disable modification to existing workflows as well? Ala, https://github.com/zooniverse/Panoptes-Front-End/pull/751

**Comment by vrooje** [comment]
Will modifications to the Help text of an existing workflow will be allowed?

**Comment by camallen** [comment]
@vrooje we could allow certain updates and reject others like add a task, etc. What should be allowed?

**Comment by vrooje** [comment]
As long as modifying help text is still tracked with a 0.x change in workflow, I think it should be fine to modify that. I think adding main text or tasks, or changing the order of tasks, should require confirmation/permission. 

Am tagging @chrislintott as he may have a different opinion on the potential impact of changing help text mid-project.

**Comment by aliburchard** [comment]
I agree with @vrooje on this. While making changes to the help-text mid project might improve volunteer accuracy, I feel like those impacts would be relatively minor.

**Comment by twhyntie** [comment]
:+1: agree with @vrooje and @aliburchard - if you can track the minor version in the workflow, you could even evaluate the impact of the changes if you wanted :-)

**Comment by camallen** [comment]
Working on this now.

**Comment by vrooje** [comment]
Oops -- now that I see it's coming together -- I think the ability to change the subject sets associated with the workflow should also be allowed.

**Comment by camallen** [comment]
A live workflow is locked for editing. Data can be added to a subject set. 

@vrooje can you please open a new issue for editing a live workflow?

**Comment by camallen** [comment]
closed by #1022
