### ISSUE TITLE
Get retired subject counts by subject set

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/Panoptes#986]
As discussed with @camallen, I'd like to show progress counts by subject set (in my case, e.g. pages of a book)

**Comment by camallen** [comment]
add counts of the subject sets retired set_member_subject workflows to the subject set representation

**Comment by edpaget** [comment]
I can't think of a good way to do this without introducing another resource for the relationships between subject sets and workflows.

**Comment by camallen** [comment]
Can this be an optional field on the subject_set serializer that runs a query to count the linked `subject_sets -> set_member_subjects -> retired subject_workflow_counts` for any worfklow that a subject set belongs to?

**Comment by edpaget** [comment]
I feel like that's a less optimal solution, than having a /subjects_workflows route that would return that as part of it's request. You'd have not way to discover what param to set.

**Comment by camallen** [comment]
true true. so would the /subjects_worfklows end point look like /subject?worfklow_id=X ?

**Comment by edpaget** [comment]
Ah my bad. It would be /subject_sets_workflows like the model that does the join between. Alternatively, we could include the counts in the workflow response?

**Comment by camallen** [comment]
I like the `/subject_sets_workflows` resource, so we'd add a `retired_count` & possibly a `total_count` on that resource serialiser?

**Comment by camallen** [comment]
@rogerhutchings i think this is a nice to have but i won't have it ready for the beta today. you ok if i punt this till the front end functionality is ready? Is it already?

**Comment by rogerhutchings** [comment]
Not yet, so no big deal

**Comment by marten** [comment]
Just chiming in, a bit late, but I don't particularly like exposing join tables as resources in the API. Could we not return this as a hash on the workflow resource (`retired_counts_by_set: {set_1: 32, set_4: 2320}`) ?

**Comment by edpaget** [comment]
yeah since working on revising the api, I agree with that position @marten.

**Comment by marten** [comment]
@rogerhutchings do you still need this? I could start work on it if you do, but since it's been a while I wanted to double check that it's still relevant.

**Comment by rogerhutchings** [comment]
Yes please @marten, it's still relevant to AnnoTate and Old Weather
