### ISSUE TITLE
sending transcriptions/classifications/markings directly to Cassandra

### ISSUE THREAD

**Issue by ggdhines** [zooniverse/Panoptes#987]
@rogerhutchings and @VVH would like to run a beta of annoTate starting July 1st. I'd like to be able to read in the transcriptions directly from Cassandra. @camallen thinks this is doable

**Comment by camallen** [comment]
reopening since #1315 removed them temporarily. I'm wondering if this is similar to the docker panoptes errors we were experiencing?

**Comment by marten** [comment]
Closing since we're now focussing on writing daily dumps and computing using a Hadoop cluster long-term.
