### ISSUE TITLE
Project guide and team_members should store markdown

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes#995]
Related to https://github.com/zooniverse/Panoptes-Front-End/issues/568 and https://github.com/simoneduca/planet-four/issues/9

Avoid having to create custom pages and let the project teams decide on the content to display.

Once done, add an issue to the front end to use these fields in the project builder and on the project landing page.

**Comment by edpaget** [comment]
See #852. I think it makes more sense to allow a totally flexible set of pages to exist. The Project Builder only needs to have a wizard for creating the pages we think projects should by default.

**Comment by camallen** [comment]
Yeah #852 seems a better general solution for this. In the meantime project owners can use the fields they have available.
