### ISSUE TITLE
Cassandra speed issues

### ISSUE THREAD

**Issue by ggdhines** [zooniverse/Panoptes#997]
I've created a cassandra table with
CREATE TABLE classifications( project_id int, user_id int, workflow_id int, created_at timestamp,annotations text,  updated_at timestamp, user_group_id int, user_ip inet,  completed boolean, gold_standard boolean, subject_id int, workflow_version float,metadata text, PRIMARY KEY(project_id,subject_id,workflow_id,created_at) ) WITH CLUSTERING ORDER BY (subject_id ASC, workflow_id ASC,created_at ASC);")
I then query with the command:
select user_id,annotations from classifications where project_id = 3 and subject_id = 458744 and workflow_id = 3
it takes a less than a second to retrieve the result but add it up over many subject and it takes a while. Even with just 380ish subjects this is taking a while - with 5000 or 10000 (or more) subjects this would be completely inefficient. @edpaget any suggestions?

**Comment by camallen** [comment]
@ggdhines can you try and run the cassandra version of an sql explain on the query to make sure the index is being used and post back what that looks like.

**Comment by ggdhines** [comment]
so I think this is a problem with using the Python interface for Cassandra. Everytime I call the interface there is a delay while Python sets things up. I've implemented a batch/concurrent query which reduces the number of actually Python calls I need to make. Probably need to play around with some params to optimize stuff but this seems like a good approach.
